syntax = "proto2";

option cc_enable_arenas = true;
package nio.ad.messages;
import "common/perf/sensor_ts_header.proto";

import "common/map_engine/sd_hd_info.proto";


message GlobalSdRoutes {
  reserved 2, 6, 8, 10, 12, 15, 16, 17, 18, 19, 20, 22;

  optional int32 route_match_state = 1; // 0:未进入导航状态, 1:已进入导航状态
  optional uint64 current_hd_link_id = 3; // 当前hd_link_id
  optional uint64 current_sd_link_id = 4; // 当前sd_link_id

  optional uint64 last_match_time_ns = 5; // 最近一次重新计算匹配的时间，单位为ns
  repeated SdLinkInfo sd_link_info_list = 7; // sd发起请求时传入的link info列表
  repeated HdLinkSegment hd_link_segments = 9; // hd_link_segments 表示九宫格内路线的前进方向上的每段连续的hd路段

  optional bytes extended_info = 11; // 方便紧急情况下不被ccb给block的扩展

  optional uint64 current_sd_link_index = 13; // 当前SDlink 在SDRoute的索引, 来自DC的透传消息
  optional uint64 current_hd_link_index = 14; // 根据current_sd_link_index计算的在HDroute上的当前hdlink的索引，只是用于解决重复路问题， 不能用于定位，由于精度问题可能会不准确

  repeated uint64 filtered_match_hd_links = 21; // 匹配结果中由于白名单或黑名单被过滤掉的link有序排列

  optional uint64 timestamp = 536870905; // ptp timestamp, nanosecond，used for data bundle readin 
  optional uint64 publish_ptp_ts = 536870907; // publish ptp timestamp, uint in nanosec
  optional string publisher_id = 536870909; // uuid of the publisher
  optional uint64 counter = 536870910;         // message counter
  optional uint64 publish_ts = 536870911;    // publish timestamp,uint in nanosec;
}

