// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/map_engine/hd_poi.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_common_2fmap_5fengine_2fhd_5fpoi_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_common_2fmap_5fengine_2fhd_5fpoi_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3018000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3018001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "common/map_engine/map_geometry.pb.h"
#include "common/map_engine/hd_link_info.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_common_2fmap_5fengine_2fhd_5fpoi_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_common_2fmap_5fengine_2fhd_5fpoi_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_common_2fmap_5fengine_2fhd_5fpoi_2eproto;
namespace nio {
namespace ad {
namespace messages {
class HdPoi;
struct HdPoiDefaultTypeInternal;
extern HdPoiDefaultTypeInternal _HdPoi_default_instance_;
}  // namespace messages
}  // namespace ad
}  // namespace nio
PROTOBUF_NAMESPACE_OPEN
template<> ::nio::ad::messages::HdPoi* Arena::CreateMaybeMessage<::nio::ad::messages::HdPoi>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace nio {
namespace ad {
namespace messages {

// ===================================================================

class HdPoi final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nio.ad.messages.HdPoi) */ {
 public:
  inline HdPoi() : HdPoi(nullptr) {}
  ~HdPoi() override;
  explicit constexpr HdPoi(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HdPoi(const HdPoi& from);
  HdPoi(HdPoi&& from) noexcept
    : HdPoi() {
    *this = ::std::move(from);
  }

  inline HdPoi& operator=(const HdPoi& from) {
    CopyFrom(from);
    return *this;
  }
  inline HdPoi& operator=(HdPoi&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HdPoi& default_instance() {
    return *internal_default_instance();
  }
  static inline const HdPoi* internal_default_instance() {
    return reinterpret_cast<const HdPoi*>(
               &_HdPoi_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(HdPoi& a, HdPoi& b) {
    a.Swap(&b);
  }
  inline void Swap(HdPoi* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HdPoi* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline HdPoi* New() const final {
    return new HdPoi();
  }

  HdPoi* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<HdPoi>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HdPoi& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const HdPoi& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HdPoi* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nio.ad.messages.HdPoi";
  }
  protected:
  explicit HdPoi(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLinkIdsFieldNumber = 6,
    kLinkFeaturePointsFieldNumber = 7,
    kUuidFieldNumber = 2,
    kPoiInfoFieldNumber = 4,
    kPointFieldNumber = 5,
    kIdFieldNumber = 1,
    kTypeFieldNumber = 3,
  };
  // repeated uint64 link_ids = 6;
  int link_ids_size() const;
  private:
  int _internal_link_ids_size() const;
  public:
  void clear_link_ids();
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_link_ids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
      _internal_link_ids() const;
  void _internal_add_link_ids(::PROTOBUF_NAMESPACE_ID::uint64 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
      _internal_mutable_link_ids();
  public:
  ::PROTOBUF_NAMESPACE_ID::uint64 link_ids(int index) const;
  void set_link_ids(int index, ::PROTOBUF_NAMESPACE_ID::uint64 value);
  void add_link_ids(::PROTOBUF_NAMESPACE_ID::uint64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
      link_ids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
      mutable_link_ids();

  // repeated .nio.ad.messages.LinkFeaturePoint link_feature_points = 7;
  int link_feature_points_size() const;
  private:
  int _internal_link_feature_points_size() const;
  public:
  void clear_link_feature_points();
  ::nio::ad::messages::LinkFeaturePoint* mutable_link_feature_points(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::LinkFeaturePoint >*
      mutable_link_feature_points();
  private:
  const ::nio::ad::messages::LinkFeaturePoint& _internal_link_feature_points(int index) const;
  ::nio::ad::messages::LinkFeaturePoint* _internal_add_link_feature_points();
  public:
  const ::nio::ad::messages::LinkFeaturePoint& link_feature_points(int index) const;
  ::nio::ad::messages::LinkFeaturePoint* add_link_feature_points();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::LinkFeaturePoint >&
      link_feature_points() const;

  // optional string uuid = 2;
  bool has_uuid() const;
  private:
  bool _internal_has_uuid() const;
  public:
  void clear_uuid();
  const std::string& uuid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_uuid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_uuid();
  PROTOBUF_MUST_USE_RESULT std::string* release_uuid();
  void set_allocated_uuid(std::string* uuid);
  private:
  const std::string& _internal_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(const std::string& value);
  std::string* _internal_mutable_uuid();
  public:

  // optional string poi_info = 4;
  bool has_poi_info() const;
  private:
  bool _internal_has_poi_info() const;
  public:
  void clear_poi_info();
  const std::string& poi_info() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_poi_info(ArgT0&& arg0, ArgT... args);
  std::string* mutable_poi_info();
  PROTOBUF_MUST_USE_RESULT std::string* release_poi_info();
  void set_allocated_poi_info(std::string* poi_info);
  private:
  const std::string& _internal_poi_info() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_poi_info(const std::string& value);
  std::string* _internal_mutable_poi_info();
  public:

  // optional .nio.ad.messages.MapPoint point = 5;
  bool has_point() const;
  private:
  bool _internal_has_point() const;
  public:
  void clear_point();
  const ::nio::ad::messages::MapPoint& point() const;
  PROTOBUF_MUST_USE_RESULT ::nio::ad::messages::MapPoint* release_point();
  ::nio::ad::messages::MapPoint* mutable_point();
  void set_allocated_point(::nio::ad::messages::MapPoint* point);
  private:
  const ::nio::ad::messages::MapPoint& _internal_point() const;
  ::nio::ad::messages::MapPoint* _internal_mutable_point();
  public:
  void unsafe_arena_set_allocated_point(
      ::nio::ad::messages::MapPoint* point);
  ::nio::ad::messages::MapPoint* unsafe_arena_release_point();

  // optional uint64 id = 1;
  bool has_id() const;
  private:
  bool _internal_has_id() const;
  public:
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint32 type = 3;
  bool has_type() const;
  private:
  bool _internal_has_type() const;
  public:
  void clear_type();
  ::PROTOBUF_NAMESPACE_ID::uint32 type() const;
  void set_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_type() const;
  void _internal_set_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:nio.ad.messages.HdPoi)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 > link_ids_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::LinkFeaturePoint > link_feature_points_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uuid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr poi_info_;
  ::nio::ad::messages::MapPoint* point_;
  ::PROTOBUF_NAMESPACE_ID::uint64 id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 type_;
  friend struct ::TableStruct_common_2fmap_5fengine_2fhd_5fpoi_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HdPoi

// optional uint64 id = 1;
inline bool HdPoi::_internal_has_id() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool HdPoi::has_id() const {
  return _internal_has_id();
}
inline void HdPoi::clear_id() {
  id_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 HdPoi::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 HdPoi::id() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.HdPoi.id)
  return _internal_id();
}
inline void HdPoi::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000008u;
  id_ = value;
}
inline void HdPoi::set_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.HdPoi.id)
}

// optional string uuid = 2;
inline bool HdPoi::_internal_has_uuid() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool HdPoi::has_uuid() const {
  return _internal_has_uuid();
}
inline void HdPoi::clear_uuid() {
  uuid_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& HdPoi::uuid() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.HdPoi.uuid)
  return _internal_uuid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HdPoi::set_uuid(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nio.ad.messages.HdPoi.uuid)
}
inline std::string* HdPoi::mutable_uuid() {
  std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.HdPoi.uuid)
  return _s;
}
inline const std::string& HdPoi::_internal_uuid() const {
  return uuid_.Get();
}
inline void HdPoi::_internal_set_uuid(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* HdPoi::_internal_mutable_uuid() {
  _has_bits_[0] |= 0x00000001u;
  return uuid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* HdPoi::release_uuid() {
  // @@protoc_insertion_point(field_release:nio.ad.messages.HdPoi.uuid)
  if (!_internal_has_uuid()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return uuid_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void HdPoi::set_allocated_uuid(std::string* uuid) {
  if (uuid != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  uuid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), uuid,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:nio.ad.messages.HdPoi.uuid)
}

// optional uint32 type = 3;
inline bool HdPoi::_internal_has_type() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool HdPoi::has_type() const {
  return _internal_has_type();
}
inline void HdPoi::clear_type() {
  type_ = 0u;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HdPoi::_internal_type() const {
  return type_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 HdPoi::type() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.HdPoi.type)
  return _internal_type();
}
inline void HdPoi::_internal_set_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000010u;
  type_ = value;
}
inline void HdPoi::set_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.HdPoi.type)
}

// optional string poi_info = 4;
inline bool HdPoi::_internal_has_poi_info() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool HdPoi::has_poi_info() const {
  return _internal_has_poi_info();
}
inline void HdPoi::clear_poi_info() {
  poi_info_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& HdPoi::poi_info() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.HdPoi.poi_info)
  return _internal_poi_info();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HdPoi::set_poi_info(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 poi_info_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nio.ad.messages.HdPoi.poi_info)
}
inline std::string* HdPoi::mutable_poi_info() {
  std::string* _s = _internal_mutable_poi_info();
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.HdPoi.poi_info)
  return _s;
}
inline const std::string& HdPoi::_internal_poi_info() const {
  return poi_info_.Get();
}
inline void HdPoi::_internal_set_poi_info(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  poi_info_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* HdPoi::_internal_mutable_poi_info() {
  _has_bits_[0] |= 0x00000002u;
  return poi_info_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* HdPoi::release_poi_info() {
  // @@protoc_insertion_point(field_release:nio.ad.messages.HdPoi.poi_info)
  if (!_internal_has_poi_info()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return poi_info_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void HdPoi::set_allocated_poi_info(std::string* poi_info) {
  if (poi_info != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  poi_info_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), poi_info,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:nio.ad.messages.HdPoi.poi_info)
}

// optional .nio.ad.messages.MapPoint point = 5;
inline bool HdPoi::_internal_has_point() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || point_ != nullptr);
  return value;
}
inline bool HdPoi::has_point() const {
  return _internal_has_point();
}
inline const ::nio::ad::messages::MapPoint& HdPoi::_internal_point() const {
  const ::nio::ad::messages::MapPoint* p = point_;
  return p != nullptr ? *p : reinterpret_cast<const ::nio::ad::messages::MapPoint&>(
      ::nio::ad::messages::_MapPoint_default_instance_);
}
inline const ::nio::ad::messages::MapPoint& HdPoi::point() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.HdPoi.point)
  return _internal_point();
}
inline void HdPoi::unsafe_arena_set_allocated_point(
    ::nio::ad::messages::MapPoint* point) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(point_);
  }
  point_ = point;
  if (point) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:nio.ad.messages.HdPoi.point)
}
inline ::nio::ad::messages::MapPoint* HdPoi::release_point() {
  _has_bits_[0] &= ~0x00000004u;
  ::nio::ad::messages::MapPoint* temp = point_;
  point_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::nio::ad::messages::MapPoint* HdPoi::unsafe_arena_release_point() {
  // @@protoc_insertion_point(field_release:nio.ad.messages.HdPoi.point)
  _has_bits_[0] &= ~0x00000004u;
  ::nio::ad::messages::MapPoint* temp = point_;
  point_ = nullptr;
  return temp;
}
inline ::nio::ad::messages::MapPoint* HdPoi::_internal_mutable_point() {
  _has_bits_[0] |= 0x00000004u;
  if (point_ == nullptr) {
    auto* p = CreateMaybeMessage<::nio::ad::messages::MapPoint>(GetArenaForAllocation());
    point_ = p;
  }
  return point_;
}
inline ::nio::ad::messages::MapPoint* HdPoi::mutable_point() {
  ::nio::ad::messages::MapPoint* _msg = _internal_mutable_point();
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.HdPoi.point)
  return _msg;
}
inline void HdPoi::set_allocated_point(::nio::ad::messages::MapPoint* point) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(point_);
  }
  if (point) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(point));
    if (message_arena != submessage_arena) {
      point = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, point, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  point_ = point;
  // @@protoc_insertion_point(field_set_allocated:nio.ad.messages.HdPoi.point)
}

// repeated uint64 link_ids = 6;
inline int HdPoi::_internal_link_ids_size() const {
  return link_ids_.size();
}
inline int HdPoi::link_ids_size() const {
  return _internal_link_ids_size();
}
inline void HdPoi::clear_link_ids() {
  link_ids_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 HdPoi::_internal_link_ids(int index) const {
  return link_ids_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 HdPoi::link_ids(int index) const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.HdPoi.link_ids)
  return _internal_link_ids(index);
}
inline void HdPoi::set_link_ids(int index, ::PROTOBUF_NAMESPACE_ID::uint64 value) {
  link_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.HdPoi.link_ids)
}
inline void HdPoi::_internal_add_link_ids(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  link_ids_.Add(value);
}
inline void HdPoi::add_link_ids(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_add_link_ids(value);
  // @@protoc_insertion_point(field_add:nio.ad.messages.HdPoi.link_ids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
HdPoi::_internal_link_ids() const {
  return link_ids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
HdPoi::link_ids() const {
  // @@protoc_insertion_point(field_list:nio.ad.messages.HdPoi.link_ids)
  return _internal_link_ids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
HdPoi::_internal_mutable_link_ids() {
  return &link_ids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
HdPoi::mutable_link_ids() {
  // @@protoc_insertion_point(field_mutable_list:nio.ad.messages.HdPoi.link_ids)
  return _internal_mutable_link_ids();
}

// repeated .nio.ad.messages.LinkFeaturePoint link_feature_points = 7;
inline int HdPoi::_internal_link_feature_points_size() const {
  return link_feature_points_.size();
}
inline int HdPoi::link_feature_points_size() const {
  return _internal_link_feature_points_size();
}
inline ::nio::ad::messages::LinkFeaturePoint* HdPoi::mutable_link_feature_points(int index) {
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.HdPoi.link_feature_points)
  return link_feature_points_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::LinkFeaturePoint >*
HdPoi::mutable_link_feature_points() {
  // @@protoc_insertion_point(field_mutable_list:nio.ad.messages.HdPoi.link_feature_points)
  return &link_feature_points_;
}
inline const ::nio::ad::messages::LinkFeaturePoint& HdPoi::_internal_link_feature_points(int index) const {
  return link_feature_points_.Get(index);
}
inline const ::nio::ad::messages::LinkFeaturePoint& HdPoi::link_feature_points(int index) const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.HdPoi.link_feature_points)
  return _internal_link_feature_points(index);
}
inline ::nio::ad::messages::LinkFeaturePoint* HdPoi::_internal_add_link_feature_points() {
  return link_feature_points_.Add();
}
inline ::nio::ad::messages::LinkFeaturePoint* HdPoi::add_link_feature_points() {
  ::nio::ad::messages::LinkFeaturePoint* _add = _internal_add_link_feature_points();
  // @@protoc_insertion_point(field_add:nio.ad.messages.HdPoi.link_feature_points)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::LinkFeaturePoint >&
HdPoi::link_feature_points() const {
  // @@protoc_insertion_point(field_list:nio.ad.messages.HdPoi.link_feature_points)
  return link_feature_points_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace ad
}  // namespace nio

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_common_2fmap_5fengine_2fhd_5fpoi_2eproto
