from typing import Dict, List


def set_lbs_message(group_name: str, req_id: str, result_code: str, msg: str) -> None: ...
def get_cdm_version() -> str: ...

class CdmCalVehInfo:
    def __init__(self) -> None: ...

class CDMEngine:
    def __init__(self) -> None: ...

    def init_engines(self,
                     rule_engine_conf_file: str,
                     inter_layer_engine_conf_file: str = "",
                     vdm_engine_conf_file: str = "",
                     vehicle_info: CdmCalVehInfo = CdmCalVehInfo(),
                     region: str = "CN") -> None: ...

    def get_required_topics(self) -> List[str]: ...

    def set_workdir(self, work_dir: str) -> None: ...

    def work_dir(self) -> str: ...

    def tag_result_dir(self) -> str: ...

    def reset_rule_engine(self, disable_basic_rule: bool = False) -> bool: ...

    def clear_rule_status(self) -> None: ...

    def list_rule_group_names(self) -> List[str]: ...

    def dump_tag_db(self, db_filename: str) -> None: ...

    def dump_rule_watch_data(self, filename: str = "rule_watch_data.json") -> bool: ...

    def process_pb_files(self, allfiles: Dict[str, str]) -> None: ...

    def on_process_message(self, topic: str, msg: str) -> None: ...

    def enable_co_mode(self,
                       co_name: str,
                       co_version: str,
                       proto_source_dir: str,
                       relative_proto_files: List[str]) -> None: ...

    def disable_co_mode(self, co_name: str, co_version: str) -> None: ...

    def get_co_mode_info(self) -> Dict[str, str]: ...

    def finalize(self) -> None: ...

    def dump_tag_inter_pb(self, pb_filename: str, human_readable: bool = False) -> None: ...
