syntax = "proto2";

option cc_enable_arenas = true;
package nio.ad.messages;
import "common/perception/vision_road_detection.proto";

message LaneLine_light {
    optional LaneLine.LDRole LD_Role = 1;
    optional LineProperty LD_First_Line = 2;
    // repeated SPoint LD_Points = 22;
}
message LaneDetection_light {
    optional float LD_Lane_Width = 1;//Width of the host lane
    optional bool LD_Crossing_Flag = 2; // The flag of  ego vehicle crosses the lane line
    repeated LaneLine_light line = 3;
}


message RoadDetection_light{
    optional LaneDetection_light laneline = 2;
    repeated StopLine stopline = 6; 
    optional uint64 timestamp = 536870905; // ptp timestamp, nanosecond，used for data bundle readin    
    optional uint64 publish_ptp_ts = 536870907; 
}