//用于adhmi输出MLM相关信号给到DC，MLM数据驱动，目前为2hz
syntax = "proto2";

option cc_enable_arenas = true;
package nio.ad.messages;
import "common/perf/sensor_ts_header.proto";
import "common/adhmi/adhmi_environment.proto";

message Hmi_PromptInfo{

    enum Hmi_Scenario_T{
        HMI_SCE_UNKNOWN = 0;
        ROAD_NORMAL = 1;
        ON_THE_BRIDGE = 2;
        UNDER_THE_BRIDGE = 3;
        OUTDOOR_PARKING_AREA = 4;
        INDOOR_PARKING_AREA = 5;
    }

    enum Hmi_Surface_T{
        HMI_SUR_UNKNOWN = 0;
        DRY = 1;
        WATER_ON_THE_GROUND = 2;
        SNOW_ON_THE_GROUND = 3;
        MUDDY_ON_THE_GROUND = 4;
    }

    enum Hmi_Weather_Type_T{
        HMI_WEA_T_UNKNOWN = 0;
        SUNNY = 1;
        RAINY = 2;
        FOGGY = 3;
        SNOWY = 4;
    }

    enum Hmi_Weather_Level_T{
        HMI_WEA_L_UNKNOWN = 0;
        LOW = 1;
        MIDDLE = 2;
        HIGH = 3;
    }

message Hmi_WeatherInfo{
    optional Hmi_Weather_Type_T hmi_weather_type = 1;
    optional Hmi_Weather_Level_T hmi_weather_level =2;
}


    optional Hmi_Scenario_T hmi_scenario = 1;
    optional Hmi_Surface_T hmi_surface = 2;
    optional Hmi_WeatherInfo hmi_weather_info = 3;
    
}

message Hmi_Mlm_AirInfo{
    enum Hmi_Air_T{
        HMI_MLM_AIR_UNKNOWN = 0;
        INTERNAL = 1;      //内循环
        EXTERNAL = 2;      //外循环
    }

    optional Hmi_Air_T hmi_air_type = 1;      // 空调内外循环 request
    optional uint32 hmi_air_reason = 2;       // 空调request原因 见SceneInfo.proto中 SceneInfo.proto
    optional string hmi_air_description =3;   // 空调request长文本
    repeated bytes hmi_air_image_buff = 4;    //dynamic_size * sizeof(uint16),图片二进制缓存
}

message Hmi_Mlm_ParkingInfo{
    optional uint32 hmi_parking_lot_type =1;            //停车场类型unknown/非停车场/地上停车场/地下停车场
    optional string hmi_floor_info = 2;                 //停车场楼层信息
    optional string hmi_area_info = 3;                  //停车场区号信息
    optional string hmi_parking_number = 4;             //停车场车位号
    repeated bytes hmi_parking_qr_code_buff =5;         // 停车场付费二维码信息 dynamic_size * sizeof(uint16)
    optional string hmi_parking_lot_description = 6;    //停车场长文本信息 
}

message Hmi_SurfaceInfo {
    optional uint32 hmi_surface_type = 1;               //路面附着状态信息 积水/积雪/正常
    optional uint32 hmi_surface_material_type = 2;      //路面材料信息
    optional uint32 hmi_surface_safety_level = 3;       //路沿附着情况安全等级
    optional uint32 hmi_driving_policy = 4;             //当前路面附着系数驾驶策略
    repeated Hmi_Vector3f hmi_slippery_area_point = 5;  //湿滑表面几何区域信息
    optional string hmi_surface_info = 6;               //地面附着情况与驾驶决策长文本描述
    repeated bytes hmi_surface_image_buff =7;           // 天气图片 dynamic_size * sizeof(uint16)
}

message Hmi_TrafficViolationInfo {
    optional bool hmi_traffic_violation = 1;  //是否违章
    optional uint32 hmi_traffic_violation_type = 2;  //违章类型信息 
    repeated bytes hmi_violation_attention_info = 3; //违章PV信息,图片信息
    optional string hmi_traffic_violation_description = 4;  //违章长文本信息
}

// VLN停车场标牌boundingbox类型
message Hmi_BoundingBoxType {
    optional uint32 x1 = 1;
    optional uint32 y1 = 2;
    optional uint32 x2 = 3;
    optional uint32 y2 = 4;
}

// VLN识别停车场标牌信息
message Hmi_VlnOcrInfo {
    repeated Hmi_BoundingBoxType ocr_box = 1;          // 热力区域外接矩形对角点
    repeated bytes front_camera_image_buff = 2;        // FW或FN相机影像截图 dynamic_size * sizeof(uint16)
    repeated string ocr_semantics = 3;                 // 标牌语义的文本描述
    optional string floor_area_info = 4;               // 车辆所处停车层和区域的文本描述 
    repeated string vln_guidance_info = 5;             // 基于标牌语义的解读描述
}

message Hmi_Mlm{
    reserved 999;                                                   //删除的字段

    optional Hmi_PromptInfo hmi_prompt_info = 1;
    optional Hmi_Mlm_AirInfo hmi_mlm_air_info = 2;
    optional Hmi_Mlm_ParkingInfo hmi_mil_parking_info = 3;
    optional Hmi_SurfaceInfo hmi_surface_info = 4;
    optional Hmi_TrafficViolationInfo hmi_traffic_violation_info = 5;
    optional Hmi_VlnOcrInfo hmi_vln_ocr_info = 6;

   
     
    optional string hmi_version = 1000 [default = "1.0.2"] ;         // proto version     
    optional string hmi_update_date = 1001 [default = "20250228"] ;  // proto updated date

    optional uint64 timestamp = 536870905; // ptp timestamp, nanosecond，used for data bundle readin    
    optional SensorTSHeader sensor_original_ts = 536870906;          // sensor original ts    
    optional string publisher_id = 536870909;                        // uuid of the publisher    
    optional uint64 publish_ptp_ts = 536870907;                      // publish ptp timestamp, uint in nanosec    
    optional uint64 counter = 536870910;                             // message counter    
    optional uint64 publish_ts = 536870911;                          // publish timestamp; unit : nanosecond
}