syntax = "proto2";

option cc_enable_arenas = true;

package nio.ad.messages;


message StatusPb {
  // Error codes enum for API's categorized by modules.
  enum ErrorCode {
    // No error, returns on success.
    OK = 0;

    // Control module error codes start from here.
    CONTROL_ERROR = 1000;
    CONTROL_INIT_ERROR = 1001;
    CONTROL_COMPUTE_ERROR = 1002;
    CONTROL_RECEIVED_CARSTATE_MSG_IS_NULL = 1003;
    CONTROL_RECEIVED_PATH_MSG_IS_NULL = 1004;
    CONTROL_RECEIVED_CARINFO_MSG_IS_NULL = 1005;
    CONTROL_RECEIVED_STATEMACHINE_MSG_IS_NULL = 1006;
    CONTROL_REVEIVED_CARSTATE_LOSSCOMM = 1007;
    CONTROL_REVEIVED_PATH_LOSSCOMM = 1008;
    CONTROL_REVEIVED_CARINFO_LOSSCOMM = 1009;
    CONTROL_REVEIVED_STATEMACHINE_LOSSCOMM = 1010;
    CONTROL_REVEIVED_PATH_HAS_NO_POSITION = 1011;
    CONTROL_REVEIVED_PATH_HAS_NO_ORIENTATION = 1012;
    CONTROL_REVEIVED_LOCALIZATION_CONFIDENCE_IS_INVALID = 1013;
    CONTROL_FIND_PATH_POINT_IS_INVALID = 1014;
    CONTROL_STATEMACHINE_IS_UNREADY = 1015;

    // parking controller(llc) error code
    PARKING_CONTROLLER_ERROR = 2000;
    PARKING_CONTROLLER_ERROR_PATH_EMPTY = 2001;
    PARKING_CONTROLLER_ERROR_PATH_POINT_TIME_MATCH_FAILED = 2002;
    PARKING_CONTROLLER_ERROR_NEAREST_PATH_POINT_MATCH_FAILED = 2003;
    PARKING_CONTROLLER_ERROR_FRONT_WHEEL_ANGLE_LOSS = 2004;
    PARKING_CONTROLLER_ERROR_ILLEAGL_GEAR_REQ = 2005;
    PARKING_CONTROLLER_ERROR_ILLEGAL_PATH_MODE = 2006;

    // trajectory controller error code
    TRAJECTORY_CONTROLLER_ERROR = 3000;
    TRAJECTORY_CONTROLLER_ERROR_PATH_EMPTY = 3001;
    TRAJECTORY_CONTROLLER_ERROR_POSITION_EMPTY = 3002;
    TRAJECTORY_CONTROLLER_ERROR_CARSTATE_TIME_LOSS = 3003;
    TRAJECTORY_CONTROLLER_ERROR_PATH_POINT_TIME_MATCH_FAILED = 3004;
    TRAJECTORY_CONTROLLER_ERROR_NEAREST_PATH_POINT_MATCH_FAILED = 3005;
    TRAJECTORY_CONTROLLER_ERROR_PATH_POINT_FRENET_TRANSFORM_FAILED = 3006;
    TRAJECTORY_CONTROLLER_ERROR_FIND_NEAREST_POINT_FAILED = 3007;
    TRAJECTORY_CONTROLLER_ERROR_FIND_CURRENT_S_FAILED = 3008;
    TRAJECTORY_CONTROLLER_ERROR_FIND_FUTRUE_MAX_SPEED_FAILED = 3009;
    TRAJECTORY_CONTROLLER_ERROR_CREEP_INPUT_PROCESS_FAILED = 3010;
    TRAJECTORY_CONTROLLER_ERROR_PATH_CREEP_INFO_EMPTY = 3011;
    TRAJECTORY_CONTROLLER_ERROR_CHASSIS_SPEED_EMPTY = 3012;
    TRAJECTORY_CONTROLLER_ERROR_FOLLOW_S_INVALID = 3013;
    TRAJECTORY_CONTROLLER_ERROR_UNWANTED_ACCELERATION = 3014;
    TRAJECTORY_CONTROLLER_ERROR_UNWANTED_DECELERATION = 3015;
    // LNG MPC
    TRAJECTORY_CONTROLLER_ERROR_LNGMPC_INVALID_NP = 3100;
    TRAJECTORY_CONTROLLER_ERROR_LNGMPC_INVALID_TS = 3101;
    TRAJECTORY_CONTROLLER_ERROR_LNGMPC_FIND_NEAREST_POINT_FAILED = 3102;
    TRAJECTORY_CONTROLLER_ERROR_LNGMPC_FIND_CURRENT_S_FAILED = 3103;
    TRAJECTORY_CONTROLLER_ERROR_LNGMPC_FIND_NEAREST_RELTIME_POINT_FAILED = 3104;
    TRAJECTORY_CONTROLLER_ERROR_LNGMPC_FIND_TARGET_POINT_FAILED = 3105;
    TRAJECTORY_CONTROLLER_ERROR_LNGMPC_INVALID_CARSTATE = 3106;
    TRAJECTORY_CONTROLLER_ERROR_LNGMPC_INVALID_PATH = 3107;
    TRAJECTORY_CONTROLLER_ERROR_LNGMPC_INVALID_REFMATRIX = 3108;
    TRAJECTORY_CONTROLLER_ERROR_LNGMPC_INVALID_DEBUGINFO = 3109;
    TRAJECTORY_CONTROLLER_ERROR_LNGMPC_SOLVER_INIT_FAILED = 3110;
    TRAJECTORY_CONTROLLER_ERROR_LNGMPC_SOLVER_COMPUTE_FAILED = 3111;
    TRAJECTORY_CONTROLLER_ERROR_LNGMPC_SOLUTION_NAN_FAILED = 3112;
    TRAJECTORY_CONTROLLER_ERROR_LNGMPC_REFERENCE_NAN_FAILED = 3113;
    // LAT MPC
    TRAJECTORY_CONTROLLER_ERROR_LATMPC_SOLVER_INIT_FAILED = 3200;
    TRAJECTORY_CONTROLLER_ERROR_LATMPC_SOLVER_COMPUTE_FAILED = 3201;
    TRAJECTORY_CONTROLLER_ERROR_LATMPC_MODEL_SIZE_MISMATCH = 3202;
    TRAJECTORY_CONTROLLER_ERROR_LATMPC_SOLVER_WEIGHT_MATRIX = 3203;
    TRAJECTORY_CONTROLLER_ERROR_LATMPC_SOLVER_UPDATE_BOUND = 3204;
    TRAJECTORY_CONTROLLER_ERROR_LATMPC_SOLVER_UPDATE_REF = 3205;
    TRAJECTORY_CONTROLLER_ERROR_LATMPC_SOLVER_UPDATE_TV_MATRIX = 3206;
    TRAJECTORY_CONTROLLER_ERROR_LATMPC_FIND_NEAREST_RELTIME_POINT_FAILED = 3207;
    TRAJECTORY_CONTROLLER_ERROR_LATMPC_FIND_TARGET_POINT_FAILED = 3208;
    TRAJECTORY_CONTROLLER_ERROR_LATMPC_LARGE_PREDICT_LATERAL_DISTANCE = 3209;
    TRAJECTORY_CONTROLLER_ERROR_LATMPC_REFERENCE_NAN_FAILED = 3210;
    TRAJECTORY_CONTROLLER_ERROR_LATMPC_LINEARIZE_MODEL_FAILED = 3211;

    // state space error code
    STATE_SPACE_MPC_DEBUG_FIND_CURRENT_S_FAILED = 4001;
    STATE_SPACE_MATRIX_FIND_LAST_NEAREST_POINT_IN_CURRENT_PATH_FAILED = 4002;
    STATE_SPACE_MATRIX_FIND_LAST_S_IN_CURRENT_PATH_FAILED = 4003;
    MATRIX_Q_SIZE_NOT_EQUAL_Q_SIZE = 4004;

    // Indicates an output has been exhausted.
    END_OF_OUTPUT = 14000;
  }
  optional ErrorCode error_code = 1 [default = OK];
  optional string msg = 2;
}