syntax = "proto2";

option cc_enable_arenas = true;

package nio.ad.messages;
import "common/pnc/geometry.proto";
import "common/pnc/hmi_state.proto";
import "common/pnc/planner_evaluation.proto";
import "common/pnc/refpath_debug.proto";
import "common/pnc/state_restore_enum_routing.proto";
import "common/pnc/lane_change_decision_debug.proto";
import "common/pnc/planner_debug.proto";

// string长度不允许超过50字节，长了截断
// repeated允许使用，最长为10，长了截断。不允许嵌套repeated。
// 通过infra审核，构建时自动化检查，publish前自动截断来保证以上规则实施

message DiagnoseReferenceLineDebug {
  optional bool is_reference_line_replaced = 10000;
  repeated Vector3d replaced_reference_line_points = 10001;
  repeated string fs_debug_txt = 10002;
  repeated Vector3d fs_path_points = 10003;
  optional FsPathDebug.FSState fs_state = 10004 [default = NOT_FS];
  optional int32 fs_scene = 10005 [default = 0];
  optional int32 fs_replan_type = 10006 [default = 0];
  optional int32 fs_replan_count = 10007 [default = 0];
}

message BPDecision {
  optional int32 obstacle_id = 1;
  optional double prob = 2;
}

message DiagnoseBPDebug {
  optional DiagnoseBPKeyObstacles bp_key_obstacle = 1;
  optional LaneChangeDeciderInfo lane_change_decider_info = 2;
  optional LaneChangeSafetyCheckInfo lane_change_safety_check_info = 3;
  repeated BPDecision bp_decisions = 4;
}

message DiagnoseBPKeyObstacles {
  repeated int32 yield_obs_ids = 1;
  repeated int32 cross_yield_obs_ids = 2;
  repeated int32 slot_yield_obs_ids = 3;
  repeated int32 vru_yield_obs_ids = 4;
  repeated int32 merge_yield_obs_ids = 5;
  repeated int32 merge_overtake_obs_ids = 6;
  repeated int32 risk_obs_ids = 7;
  repeated int32 slot_not_yield_obs_ids = 8;
  repeated int32 nudge_left_obs_ids = 12;
  repeated int32 nudge_right_obs_ids = 13;
  repeated int32 merge_front_nudge_obs_ids = 14;
  repeated int32 merge_back_nudge_obs_ids = 15;
  repeated int32 cross_not_yield_obs_ids = 16;
  repeated int32 cross_overtake_obs_ids = 17;
  repeated int32 cross_risk_obs_ids = 18;
  repeated int32 lane_change_cancel_obs_ids = 19;
  repeated int32 interference_yield_obs_ids = 20;
  repeated int32 interference_overtake_obs_ids = 21;
  repeated int32 interference_risk_obs_ids = 22;
  repeated int32 uni_yield_obs_ids = 23;
  repeated int32 uni_not_yield_obs_ids = 24;
  repeated int32 cross_yield_risk_obs_ids = 25;
  repeated int32 aeb_yield_obs_ids = 26;
}

enum DiagnoseFallbackType {
  DiagnosekLevel0 = 0;
  DiagnosekLevel1 = 1;
  DiagnosekLevel2 = 2;
  DiagnosekLevel3 = 3;
}

message DiagnosePlaningFallBackMsg {
  optional DiagnoseFallbackType speed_fall_back_type = 1;
  optional DiagnoseFallbackType path_fall_back_type = 2;
}

message DiagnoseMotionInput {
  optional double lon_diff = 1;
  optional FunctionRequest func_request = 2;
}

message DiagnoseSTSoftBndDebug {
  enum DiagnoseSTBoundaryType {
    NUDGE = 1;
    YIELD = 2;
    NOT_YIELD = 3;
    SLOT_YIELD = 4;
    SLOT_NOT_YIELD = 5;
    MERGE_YIELD = 6;
    MERGE_NOT_YIELD = 7;
    ALIGN_YIELD = 8;
    ALIGN_NOT_YIELD = 9;
    CROSS_YIELD = 10;
    CROSS_OVERTAKE = 11;
    VRU_YIELD = 12;
    LANE_CHANGE_HOLD_YIELD = 13
        [deprecated =
             true];  // deprecated lc hold type, using slot alignment instead
    INTERFERENCE_YIELD = 14;
    INTERFERENCE_RISK = 15;
    UNKNOWN = 16;
  }
  optional double bnd_position = 1;
  optional double bnd_velocity = 2;
  optional string obs_id = 3;
  optional double bnd_ttc = 4;
  optional double bnd_thw = 5;
  optional DiagnoseSTBoundaryType bnd_source_type = 6;
  optional double epsilon = 7 [default = 0.0];
  optional double weight = 8;
  optional double cl_thw = 9;
  optional double cl_ttc = 10;
  optional double cl_bnd_position = 11;
  optional double cl_ref_s = 12;
}

message DiagnoseHardBndDebug {
  optional double lb = 1;
  optional double ub = 2;
  optional string lb_obs_id = 3;
  optional string ub_obs_id = 4;
  optional double solution_distance_to_lb = 5;
  optional double solution_distance_to_ub = 6;
  optional DiagnoseSTSoftBndDebug.DiagnoseSTBoundaryType ub_source_type = 7;
  optional DiagnoseSTSoftBndDebug.DiagnoseSTBoundaryType lb_source_type = 8;
}

message DiagnoseSTConstraintPoint {
  optional double x = 1 [default = 0.0];
  optional uint64 index = 2;
  optional DiagnoseHardBndDebug hard_bound = 3;
  optional DiagnoseSTSoftBndDebug ub_follow_thw = 4;
  optional DiagnoseSTSoftBndDebug ub_follow_ttc = 5;
  optional DiagnoseSTSoftBndDebug ub_merge_thw = 6;
  optional DiagnoseSTSoftBndDebug ub_merge_ttc = 7;
  optional DiagnoseSTSoftBndDebug ub_slot_thw = 8;
  optional DiagnoseSTSoftBndDebug ub_slot_ttc = 9;
  optional DiagnoseSTSoftBndDebug ub_align_s = 10;
  optional DiagnoseSTSoftBndDebug ub_align_v = 11;
  optional DiagnoseSTSoftBndDebug ub_nudge_v = 12;
  optional DiagnoseSTSoftBndDebug lb_merge_s = 13;
  optional DiagnoseSTSoftBndDebug lb_slot_thw = 14;
  optional DiagnoseSTSoftBndDebug lb_slot_ttc = 15;
  optional DiagnoseSTSoftBndDebug lb_align_s = 16;
  optional DiagnoseSTSoftBndDebug lb_align_v = 17;
  optional DiagnoseSTSoftBndDebug ub_slot_s = 18;
  optional DiagnoseSTSoftBndDebug lb_slot_s = 19;
  optional DiagnoseSTSoftBndDebug ub_merge_s = 20;
}

message DiagnoseSpeedConstraintDebug {
  optional DiagnoseSTConstraintPoint index_0_point = 1 [deprecated = true];
  optional DiagnoseSTConstraintPoint index_1_point = 2;
  optional DiagnoseSTConstraintPoint index_10_point = 3;
  optional DiagnoseSTConstraintPoint index_25_point = 4;
  optional DiagnoseSTConstraintPoint index_35_point = 5;
  optional DiagnoseSTConstraintPoint index_5_point = 6;
}

message DiagnoseMotionDebug {
  optional DiagnosePlaningFallBackMsg fall_back_msg = 1;
  optional DiagnoseMotionInput motion_input = 2;
  optional DiagnoseSpeedConstraintDebug speed_constraint_debug = 3;
  optional DiagnoseSpeedLimit speed_limits_debug = 4;
}

message DiagnoseVTLine {
  optional DiagnoseVTPoint index_1_point = 1;
  optional DiagnoseVTPoint index_5_point = 2;
  optional DiagnoseVTPoint index_10_point = 3;
  optional DiagnoseVTPoint index_20_point = 4;
  optional DiagnoseVTPoint index_35_point = 5;
}

message DiagnoseVTPoint {
  optional double t = 1;
  optional double v = 2;
}

message DiagnoseRiskObsSpeedLimit {
  optional int32 obs_id = 1;
  optional double v = 2;
  optional double t = 3;
  optional string risk_type = 4;
  optional double s_start = 5;
  optional double s_end = 6;
  optional double min_dec = 7;
  optional double min_jerk = 8;
}

message DiagnoseRiskSceneSpeedLimit {
  enum DiagnoseRiskSceneSpeedLimitType {
    UNKNOWN = 0;
    LOCAL_MAP_TLD = 1;
    CUTIN_RISK_BRAKE = 2;
    SLOW_NEIGHBOR_TRAFFIC_SPEED = 3;
    OBSTACLE = 4;
    JUNCTION = 5;
    CROSSWALK = 6;
    RAMP_MERGE_IN = 7;
    OPENING = 8;
    NO_TRAFFIC_LIGHT_STOPLINE = 9;
    RELIEF_ENTRANCE = 10;
    CURB_PARKING = 11;
    OCCLUSION = 12;
    MERGE_BLIND_AREA = 13;
    NOT_IN_TARGET_LANE = 14;
    JUNCTION_SPLIT = 15;
    CROWDED_ROAD = 16;
    SCENE_FRONTAGE = 17;
    LOCAL_MAP_TURN = 18;
    HIGHWAY_MERGE_RIGHTMOST_SCENE = 19;
  }
  optional DiagnoseRiskSceneSpeedLimitType type = 1;
  optional double speed = 2 [default = 1000.0];
  optional double s_start = 3 [default = 0.0];
  optional double s_end = 4 [default = 200.0];
}

message DiagnoseRoadSceneSpeedLimit {
  optional string road_scene_speed_limit_type = 1;
  optional DiagnoseSRangeSpeedLimit speed_limit = 2;
}

message DiagnoseSRangeSpeedLimit {
  optional double speed = 1;
  optional double s_start = 2;
  optional double s_end = 3;
  optional double ratio = 4;
}

message DiagnoseSpeedLimit {
  optional DiagnoseVTLine origin_map_speed_limits = 1;
  optional DiagnoseVTLine kappa_speed_limits = 2;
  optional DiagnoseVTLine comfort_speed_limits = 3;
  repeated DiagnoseRiskObsSpeedLimit risk_obs_speed_limit = 5;
  repeated DiagnoseRiskSceneSpeedLimit risk_scene_speed_limit = 6;
  optional DiagnoseSRangeSpeedLimit service_area_speed_limit = 7;
  repeated DiagnoseRoadSceneSpeedLimit road_scene_speed_limit = 8;
}

message DiagnoseLastStack {
  repeated string stack = 1;
}

message DiagnosePlannerState {
  optional PlannerReturnCode planner_return_code = 1;
  optional string exception = 2;
  optional DiagnoseLastStack last_stack = 3;
  optional double cost_time = 4;
  optional double cost_time_99 = 5;
  optional double run_behavior_planner = 6;
  optional double run_motion_planner = 7;
  optional double run_attention_plan = 8;
  optional double planner_update = 9;
}

message DiagnosePspTaskScheduler {
  optional string psp_event_debug = 1;
  optional string pc_map_response_debug = 2;
  optional uint32 current_power_swap_station_type_debug = 3;
  optional bool has_reset_task_result = 4;
  optional routing.GlobalRoutingState global_routing_state = 5;
}

message DiagnoseHDMapModeDebug {
  optional uint32 hd_map_suppression_reason = 1 [default = 0];
}

message DiagnoseLocalMapModeDebug {
  optional uint32 local_map_suppression_reason = 1 [default = 0];
}

message DiagnoseMapManagerDebug {
  enum MapMode {
    INVALID = 0;
    HD_MAP = 1;
    LANE_MAP = 2;
  }
  optional MapMode map_mode = 1;
  optional DiagnoseHDMapModeDebug hd_map_mode_debug = 2;
  optional DiagnoseLocalMapModeDebug local_map_mode_debug = 3;
}

message ExplorationDiagnoseInfo {
  optional bool exploration_trigger = 1 [default = false];
  optional uint32 road_class_level = 2 [default = 0];
  optional uint32 check_low_road_class_failed_reason = 3;
  optional uint32 suppress_exploration_reason = 4;
  optional uint32 need_exploration_reason = 5;
  optional bool exploration_in_driving_space_success = 6 [default = false];
  optional bool high_road_class_trigger = 7 [default = false];
  optional bool has_reverse_space = 8;
}

message FollowVehicleDiagnoseInfo {
  optional bool follow_vehicle_trigger = 1 [default = false];
  optional uint32 need_follow_vehicle_reason = 2;
  optional uint32 suppress_follow_vehicle_reason = 3;
  optional uint32 follow_vehicle_failed_reason = 4;
}

message DiagnoseLocalMapDebug {
  optional DiagnoseMapManagerDebug map_manager_debug = 1;
  optional uint32 refline_generator_failed_reason = 2 [default = 0];
  optional uint32 refline_generator_failed_lane_id = 3 [default = 0];
  optional uint32 map_reconstruction_failed_reason = 4 [default = 0];
  optional ExplorationDiagnoseInfo exploration_debug = 5;
  optional FollowVehicleDiagnoseInfo follow_vehicle_debug = 6;
}
message DiagnoseTrafficLightJunctionDebug {
  optional uint32 junction_id = 1;
  optional uint32 color = 2;  // 1.red,2.yellow,3.green
  optional double countdown_time = 3;
  optional double yellow_color_time_tracker = 4;
  optional double blocked_tl_time_tracker = 5;
  optional double flash_yellow_color_time_tracker = 6;
  optional double flash_green_color_time_tracker = 7;
  optional double time_to_go = 8;
  optional double ego_to_stop_distance = 9;
  optional uint32 action_reason = 10;
  // 11.stop by np+ turn 12.stop by capability 13.stop by traffic light
  // event 14.stop by green countdown 15.stop by green flash 16.stop by yellow
  // light 17.stop by last frame stop 21.blocked go with leading vehicle 22.go
  // with yellow light 23.go with default unknown 24.go with extinct 25.unknown
  // go with leading vehicle 25.go with flash green
}
message DiagnoseTrafficLightDebug {
  optional uint64 dynamic_map_time_meas = 1;
  repeated DiagnoseTrafficLightJunctionDebug
      diagnose_traffic_light_junction_debug = 2;
}

message DiagnoseLocalRouteRewardDebug {
  optional uint64 route_hash_id = 1;
  // 0 means no junction
  optional uint64 junction_exit_lane_id = 2;
  optional double total_reward = 3;
  optional double efficiency_reward = 4;
  optional double heading_diff_reward = 5;
  optional double turn_length_reward = 6;
  optional double exit_priority_reward = 7;
  optional double obstacle_risk_reward = 8;
  optional double vehicle_flow_reward = 9;
  optional double constain_queue_area = 10;
  optional string risk_obstacle_ids = 11;
}

message DiagnoseLocalRouteDebug {
  repeated DiagnoseLocalRouteRewardDebug route_reward_debug = 1;
}

message MapReconstructionScenarioInfo {
  enum ScenarioType {
    JUNCTION = 0;
    EXTRA_WIDE_MERGE = 1;
  }
  optional uint64 id = 1;
  optional ScenarioType scenario_type = 2;
  optional string lane_ids = 3;
}

message MapReconstructionLaneInfo {
  enum ConstructionType {
    TOPO = 0;
    GEOMETRY = 1;
  }
  optional uint64 lane_id = 1;
  optional ConstructionType construction_type = 2;
}

message MapReconstructionDiagnoseDebug {
  repeated MapReconstructionScenarioInfo scenario_infos = 1;
  repeated MapReconstructionLaneInfo lane_infos = 2;
}

message PlannerDiagnose {
  optional uint64 planning_timestamp = 1;
  optional DiagnoseMotionDebug motion_debug = 2;
  optional DiagnoseBPDebug bp_debug = 3;
  optional DiagnosePlannerState planner_state = 4;
  optional DiagnosePspTaskScheduler psp_task_scheduler_debug = 5;
  optional DiagnoseLocalMapDebug local_map_debug = 6;
  optional DiagnoseLocalRouteDebug local_route_debug = 7;
  optional MapReconstructionDiagnoseDebug map_reconstruction_debug = 8;
  optional DiagnoseRefPathDebug refpath_debug = 9;
  optional DiagnoseReferenceLineDebug reference_line_debug = 10001;
  optional DiagnoseTrafficLightDebug traffic_light_debug = 10002;
}
