syntax = "proto2";

option cc_enable_arenas = true;

package nio.ad.messages;
import "common/perf/sensor_ts_header.proto";


message IntersectionThrough {
  optional uint64 time_pub =
      1;  // timestamp when the message is published. unit: ns
  optional int32 map_version = 2;  // inherited from map_engine
  optional uint64 intersection_enter_lane_id =
      3;  // enter lane id in crossing scenario
  optional uint64 intersection_exit_lane_id =
      4;  // exit lane id id in crossing scenario
}

message PlannerState {
  optional IntersectionThrough intersection_through = 1;
  optional uint64 frame_id = 2;
  optional int64 total_time_cost = 3;

  optional uint64 timestamp = 536870905;     // ptp time, nanosec, for cosine bundle timestamp  
  optional SensorTSHeader sensor_original_ts = 536870906;  // sensor original ts
  optional uint64 publish_ptp_ts =
      536870907;  // publish ptp timestamp, uint in nanosec
  optional string publisher_id = 536870909;  // uuid of the publisher
  optional uint64 counter = 536870910;       // message counter
  optional uint64 publish_ts =
      536870911;  // publish utc timestamp; unit : nanosecond
}
