syntax = "proto2";

option cc_enable_arenas = true;

package nio.ad.messages;

enum PlannerErrorCode {
  // No error, returns on success.
  PLANNER_OK = 0;

  // motion planning error code [1000-1999]
  MP_ERROR = 1000;
  MP_INIT_ERROR = 1001;
  MP_EXECUTE_ERROR = 1002;

  //  motion planning trajectory optimizer error code [1100-1199]
  TRAJECTORY_OPTIMIZER_ERROR = 1100;
  TRAJECTORY_OPTIMIZER_INIT_ERROR = 1101;
  TRAJECTORY_OPTIMIZER_EXECUTE_ERROR = 1102;
  TRAJECTORY_OPTIMIZER_UPDATE_REFERENCE_FAILED = 1103;
  TRAJECTORY_OPTIMIZER_UPDATE_STITCH_REFERENCE_FAILED = 1104;
  TRAJECTORY_OPTIMIZER_PATH_POST_CHECK_FAILED = 1105;
  TRAJECTORY_OPTIMIZER_UPDATE_INITIAL_STATE_FAILED = 1106;
  TRAJECTORY_OPTIMIZER_SOLVE_FAILED = 1107;
  TRAJECTORY_OPTIMIZER_FUSION_RESULT_EMPTY = 1108;
  TRAJECTORY_OPTIMIZER_EGO_TRAJ_SIZE_MISMATCH = 1109;
  TRAJECTORY_OPTIMIZER_UPDATE_FUSION_TRAJ_FAILED = 1110;
  TRAJECTORY_OPTIMIZER_FIND_TIME_MATCH_POINT_FAILED = 1111;
  TRAJECTORY_OPTIMIZER_UPDATE_BOUNDARY_FAILED = 1112;
  TRAJECTORY_OPTIMIZER_BOUNDARY_SIZE_MISMATCH = 1113;
  TRAJECTORY_OPTIMIZER_BOUNDARY_LINE_FIND_ERROR = 1114;
  TRAJECTORY_OPTIMIZER_PATH_HARD_BOUND_UNSAFE = 1115;
  TRAJECTORY_OPTIMIZER_PATH_LARGE_LATERAL_DISTANCE = 1116;
  TRAJECTORY_OPTIMIZER_OK = 1117;
  TRAJECTORY_OPTIMIZER_SKIPPED = 1118;
  TRAJECTORY_OPTIMIZER_BOUNDARY_LINE_SIZE_MISMATCH = 1119;
  TRAJECTORY_OPTIMIZER_NULLPTR_ERROR = 1120;
  TRAJECTORY_OPTIMIZER_NAN_DETECTED_ERROR = 1121;

  // motion planning cilqr path optimizer error code [1200-1299]
  CILQR_PATH_OPTIMIZER_SKIPPED = 1200;
  CILQR_PATH_OPTIMIZER_IN_EXPLORATION_LATERAL_ERROR = 1201;

  // motion planning piecewise jerk path optimizer error code [1300-1399]
  PIECEWISE_JERK_PATH_OPTIMIZER_SKIPPED = 1300;

  // path bounds decider error code [1400-1499]
  PATH_CORRIDORS_DECIDER_INIT_ERROR = 1400;
}

message PlannerStatusPb {
  optional PlannerErrorCode error_code = 1 [default = PLANNER_OK];
  optional string msg = 2;
}