syntax = "proto2";

option cc_enable_arenas = true;

package nio.ad.messages;

import "common/pnc/hmi_state.proto";
import "common/pnc/planner_debug.proto";
import "common/pnc/path.proto";

// 0830 nad state machine
enum DASMErrorCode {
  // No error, returns on success.
  DASMERROR_OK = 0;
  // 0830 debug info
  // fault info
  DASMERROR_ACTIVATION_PREVENTION = 1;
  DASMERROR_ATTENTION_DEMAND = 2;
  DASMERROR_TAKE_OVER_DEMAND = 3;
  DASMERROR_EAS_REQUEST = 4;
  DASMERROR_HARD_INHIBIT = 5;

  // lcc activation prevention reason
  DASMERROR_LCCACTPREV_REASON_BRAKE_APPLIED = 100;         // 驾驶员踩刹车
  DASMERROR_LCCACTPREV_REASON_VLC_CAPACITY_LIMITED = 101;  // 加速能力不足
  DASMERROR_LCCACTPREV_REASON_PARKING_ACTIVE = 102;        // 泊车功能使能
  DASMERROR_LCCACTPREV_REASON_VSC_ACTIVE = 103;  // 车辆稳定性控制使能
  DASMERROR_LCCACTPREV_REASON_MIRROR_ADJUST = 104;   // 后视镜未调节
  DASMERROR_LCCACTPREV_REASON_TRAILER_MODE = 105;    // 拖车模式
  DASMERROR_LCCACTPREV_REASON_AEB_ACTIVE = 106;      // AEB激活
  DASMERROR_LCCACTPREV_REASON_HANDS_OFF = 107;       // 驾驶员脱手
  DASMERROR_LCCACTPREV_REASON_STEER_OVERRIDE = 108;  // 方向盘override
  DASMERROR_LCCACTPREV_REASON_ELK_ACTIVE = 109;  // 自动紧急车道保持激活
  DASMERROR_LCCACTPREV_REASON_FAM_REQ_STANDBY = 110;  // FAM请求 da standby
  DASMERROR_LCCACTPREV_REASON_ESP_ACTPREV = 111;      // ESP故障
  DASMERROR_LCCACTPREV_REASON_VLC_ACTPREV = 112;      // VCU故障
  DASMERROR_LCCACTPREV_REASON_AEB_ACTPREV = 113;      // 前方碰撞预警
  DASMERROR_LCCACTPREV_REASON_DMS_OCCLUDED = 114;     // DMS摄像头遮挡
  DASMERROR_LCCACTPREV_REASON_LIDAR_ABNORMAL = 115;   // lidar异常
  DASMERROR_LCCACTPREV_REASON_NO_TAR_AT_STILL = 116;  // 无静止目标
  DASMERROR_LCCACTPREV_REASON_DA_ACTPREV = 117;  // 该区域DA是否允许激活
  DASMERROR_LCCACTPREV_REASON_EPSACI_ACTPREV = 118;  // EPS ACI接口不可用

  // Attention Demand Inhibit reason
  DASMERROR_AD_REASON_BRAKE_SYSTEM_RELATED = 200;  // Brake System 相关
  DASMERROR_AD_REASON_HOOD_OR_TRUNK_OPEN = 201;  // 引擎盖或后备箱状态打开>100ms
  DASMERROR_AD_REASON_DRIVER_DISTRACT_OR_DROWSE = 202;  // 驾驶员分心or疲劳
  DASMERROR_AD_REASON_OVER_SET_MAX_SPEED = 203;  // 表显速度超过SetMaxSpeed
  DASMERROR_AD_REASON_VEHICLE_STABILITY_FUNC_DISABLED =
      204;  // TCS/VDC/ARP/DTC功能不可用
  DASMERROR_AD_REASON_FCT_FIM_RELATED =
      205;  // BCM/SCM/DMS/雷达/BGM/HOD检测等故障
  DASMERROR_AD_REASON_DMS_HOD_STATUS_ERROR =
      206;  // HOD驾驶员脱手检测传感器故障
  DASMERROR_AD_REASON_DMS_HOD_FEEDBACK_TIMEOUT = 207;  // DMS的HOD实时反馈超时
  DASMERROR_AD_REASON_VLC_CAPACITY_LIMITED = 208;  // 纵向VLC加速能力受限
  DASMERROR_AD_REASON_AA_APP_FIM_WARNING = 209;    // AA app 警告注意
  DASMERROR_AD_REASON_CAMERA_FAILSAFE =
      210;  // FW、FN摄像头安全失效，FailSafe抑制
  DASMERROR_AD_REASON_PSP_SOFT_INHIBIT = 211;  // DMS/PSP相关故障
  DASMERROR_AD_REASON_NOP_LIDAR_FIM = 212;     // NOP状态下雷达fim故障

  // TakeOver Demand Inhibit reason
  DASMERROR_TD_REASON_DRIVER_DISTRACT_OR_DROWSE = 300;  // 驾驶员分心or疲劳
  DASMERROR_TD_REASON_PASSENGER_DOOR_UNLOCK = 301;  // 乘客车门未关且持续100ms
  DASMERROR_TD_REASON_SEAT_BELT_NOT_FASTENED = 302;  // 未系安全带
  DASMERROR_TD_REASON_VEHICLE_STABILITY_FUNC_RELATED =
      303;  // ABS/TCS/VDC/DTC/ARP等功能激活/不可用
  DASMERROR_TD_REASON_DRIVER_DOOR_UNLOCK = 304;  // 主驾驶室车门未关且持续100ms
  DASMERROR_TD_REASON_BRAKE_SYSTEM_RELATED = 305;  // Brake System 相关
  DASMERROR_TD_REASON_HOOD_OR_TRUNK_OPEN = 306;  // 引擎盖或后备箱状态打开>10s
  DASMERROR_TD_REASON_OVER_NAD_SET_MAX_SPEED =
      307;  // NAD状态下表显速度超过SetMaxSpeed 20kph
  DASMERROR_TD_REASON_DRIVER_DISTRACT_LONGONLY_MODE =
      308;  // LongOnly状态时驾驶员分心
  DASMERROR_TD_REASON_OVER_MAX_SPEED_CONTINUE =
      309;  // 表显速度超过最大速度且持续10s
  DASMERROR_TD_REASON_FCT_FIM_RELATED = 310;  // Fim信号置位
  DASMERROR_TD_REASON_DMS_HOD_STATUS_ERROR_CONTINUE =
      311;  // HOD驾驶员脱手检测传感器故障且持续10s
  DASMERROR_TD_REASON_DMS_HOD_FEEDBACK_TIMEOUT = 312;  // DMS的HOD实时反馈超时
  DASMERROR_TD_REASON_DRIVER_DISTRACT_WITH_THROTTLE =
      313;  // 驾驶员踩加速踏板时分心
  DASMERROR_TD_REASON_CDC_FAULT_RELATED = 314;  // CDC相关硬件故障
  DASMERROR_TD_REASON_FCT_FAILSAFE = 315;       // 雷达/摄像头failsafe
  DASMERROR_TD_REASON_CDP_ACTIVE = 316;         // CDP功能激活
  DASMERROR_TD_REASON_LIDAR_MODE_CHANGE = 317;  // 激光雷达异常
  DASMERROR_TD_REASON_SWC_FAULT = 318;          // SWC方向盘控制故障
  DASMERROR_TD_REASON_VLC_ACC_CAPACITY_LIMITED_CONTINUE =
      319;  // 纵向VLC加速能力受限，且持续10s
  DASMERROR_TD_REASON_VLC_DEC_CAPACITY_LIMITED_CONTINUE =
      320;  // 纵向VLC减速能力受限，且持续10s
  DASMERROR_TD_REASON_AA_APP_FIM_TAKEOVER = 321;  // AA app 警告接管
  DASMERROR_TD_REASON_FCT_FAILSAFE_CONTINUE = 322;  // 摄像头failsafe且持续10s
  DASMERROR_TD_REASON_PSP_FAULT_RELATED =
      323;  // PSP相关，如跳转失败、FIM信号、LLC异常等
  DASMERROR_TD_REASON_NOP_OR_URBAN_TO_PSP_FAILED = 324;  // NOP/Urban跳转PSP失败
  DASMERROR_TD_REASON_CRITICAL_APP_FAILURE = 325;        // 重要模块失效

  // EAS Request reason
  DASMERROR_EAS_REASON_DRIVER_DROWSE_EXTREMELY = 400;  // 驾驶员5级极其重度疲劳
  DASMERROR_EAS_REASON_DRIVER_DISTRACT_EXTREMELY = 401;  // 驾驶员3级重度分心
  DASMERROR_EAS_REASON_TD_CONTINUE_TO_EAS = 402;         // TD持续5s触发EAS
  DASMERROR_EAS_REASON_GLOBAL_LOCALIZATION_LOW_CONFIDENCE =
      403;                                  // global定位数据的置信度低
  DASMERROR_EAS_REASON_AA_APP_FAULT = 404;  // AA app 故障
  DASMERROR_EAS_REASON_EPS_FAULT = 405;     // EPS故障
  DASMERROR_EAS_REASON_NOP_REQUEST_PSP_FAILED = 406;  // NOP请求PSP功能失败
  DASMERROR_EAS_REASON_VLC_NOT_ACTIVE = 407;          // VLC无法激活
  DASMERROR_EAS_REASON_PSP_FIM_TO_EAS = 408;          // PSP异常，进入EAS

  // Hard Inhibit reason
  DASMERROR_HARD_INHIBIT_REASON_EBA_ACTIVE = 500;  // EBA紧急制动辅助系统激活
  DASMERROR_HARD_INHIBIT_REASON_BCU_CONTROL_NOT_AVAILABLE =
      501;  // BCU Control对ADC不可用
  DASMERROR_HARD_INHIBIT_REASON_HDC_ACTIVE =
      502;  // HDC陡坡缓降坡道辅助系统激活
  DASMERROR_HARD_INHIBIT_REASON_VCU_NOT_IN_DRIVE = 503;  // 当前车辆档位不在D档
  DASMERROR_HARD_INHIBIT_REASON_LONG_LOSS_COMM =
      504;  // 丢失EHY目标信息与车辆输入信息
  DASMERROR_HARD_INHIBIT_REASON_CRASH_DETECTED = 505;  // 检测到碰撞
  DASMERROR_HARD_INHIBIT_REASON_STANDSTILL_WITH_AD_TD =
      506;  // 车辆当前处于standstill，且存在AD、TD Inhibit
  DASMERROR_HARD_INHIBIT_REASON_FAM_REQUEST_HARD_INHIBIT =
      507;                                            // FAM请求Hard Ihibit
  DASMERROR_HARD_INHIBIT_REASON_NOP_CLOUD_OFF = 508;  // NOP状态下未连接到云端
  DASMERROR_HARD_INHIBIT_REASON_FCT_FAILSAFE_CONTINUE =
      509;  // FW/FN摄像头failsafe且持续10s
  DASMERROR_HARD_INHIBIT_REASON_PSP_HARD_INHIBIT =
      510;  // PSP相关，如PSP超速、PSP档位错误、VMC不可用等
  DASMERROR_HARD_INHIBIT_REASON_FCT_FIM_HRAD_INHIBIT = 511;  // FIM信号置位

  // driver override
  DASMERROR_LATTERAL_OVERRIDE = 1000;
  DASMERROR_BRAKE_APPLIED = 1001;

  // ADC App Fault
  DASMERROR_CONTROL_STATUS_FALSE = 2000;
  DASMERROR_CONTROL_LOSS_COMM = 2001;
  DASMERROR_PLANNER_STATUS_FALSE = 2002;

  // planner return code
  DASMERROR_PLANNER_ERRORCODE_FAILURE = 2100;
  DASMERROR_PLANNER_ERRORCODE_LOCAL_MAP_EMPTY = 2101;
  DASMERROR_PLANNER_ERRORCODE_GLOBAL_ROUTE_EMPTY = 2102;
  DASMERROR_PLANNER_ERRORCODE_LOCAL_ROUTER_FAILED = 2103;
  DASMERROR_PLANNER_ERRORCODE_REFERENCE_LINE_UPDATE_FAILED = 2104;
  DASMERROR_PLANNER_ERRORCODE_EGO_CAR_NOT_IN_LOCAL_MAP = 2105;
  DASMERROR_PLANNER_ERRORCODE_MOTION_PRE_CHECK_FAILED = 2106;
  DASMERROR_PLANNER_ERRORCODE_REF_LINE_GENERATOR_FAILED = 2107;
  DASMERROR_PLANNER_ERRORCODE_MOTION_SPEED_FALLBACK = 2108;

  // map manager debug
  // hdmap suppression reason
  DASMERROR_HDMAP_SUPPRESSION_REASON_NullCarState = 2200;
  DASMERROR_HDMAP_SUPPRESSION_REASON_LocalizationUnreliable = 2201;
  DASMERROR_HDMAP_SUPPRESSION_REASON_InvalidHDLocalRoadMap = 2202;
  DASMERROR_HDMAP_SUPPRESSION_REASON_NullPerceptionObjects = 2203;
  DASMERROR_HDMAP_SUPPRESSION_REASON_CheckResultFailed = 2204;
  DASMERROR_HDMAP_SUPPRESSION_REASON_EnforceLocalMapMode = 2205;
  DASMERROR_HDMAP_SUPPRESSION_REASON_NotNavigating = 2206;

  // lanemap suppression reason
  // highway
  DASMERROR_LANEMAP_SUPPRESSION_REASON_HW_NoHDLinkSegmentFind = 2300;
  DASMERROR_LANEMAP_SUPPRESSION_REASON_HW_CurrLaneConnectToSplit = 2301;
  DASMERROR_LANEMAP_SUPPRESSION_REASON_HW_CurrLaneConnectToMerge = 2302;
  DASMERROR_LANEMAP_SUPPRESSION_REASON_HW_DangerDistanceFromSplit = 2303;
  DASMERROR_LANEMAP_SUPPRESSION_REASON_HW_DangerDistanceFromMerge = 2304;
  DASMERROR_LANEMAP_SUPPRESSION_REASON_HW_GlobalRoutesToRamp = 2305;
  DASMERROR_LANEMAP_SUPPRESSION_REASON_HW_EnforceHDMode = 2306;
  DASMERROR_LANEMAP_SUPPRESSION_REASON_HW_InvalidWMConfidence = 2307;
  DASMERROR_LANEMAP_SUPPRESSION_REASON_HW_InvalidLaneLocalRoadMap = 2308;
  DASMERROR_LANEMAP_SUPPRESSION_REASON_HW_CheckLocalMapTimeOut = 2309;
  DASMERROR_LANEMAP_SUPPRESSION_REASON_HW_CheckDynamicEventFailed = 23010;
  DASMERROR_LANEMAP_SUPPRESSION_REASON_HW_RampInSdMap = 2311;
  DASMERROR_LANEMAP_SUPPRESSION_REASON_HW_InvalidHDLocalRoadMap = 2312;
  DASMERROR_LANEMAP_SUPPRESSION_REASON_HW_InvalidLaneId = 2313;
  // urban
  DASMERROR_LANEMAP_SUPPRESSION_REASON_UR_NotInODDArea = 2400;
  DASMERROR_LANEMAP_SUPPRESSION_REASON_UR_EnforceHDMode = 2401;
  DASMERROR_LANEMAP_SUPPRESSION_REASON_UR_InvalidWMConfidence = 2402;
  DASMERROR_LANEMAP_SUPPRESSION_REASON_UR_InvalidLaneLocalRoadMap = 2403;
  DASMERROR_LANEMAP_SUPPRESSION_REASON_UR_CheckLocalMapTimeOut = 2404;
  DASMERROR_LANEMAP_SUPPRESSION_REASON_UR_InvalidNaviMapInfo = 2405;

  // nop unavailable reason
  DASMERROR_NOP_UNAVAILABLE_REASON_MapModeUnavailable = 2406;
  DASMERROR_NOP_UNAVAILABLE_REASON_OddStatusUnavailable = 2407;
  DASMERROR_NOP_UNAVAILABLE_REASON_AllAreaButtonOnlyHighway = 2408;
  DASMERROR_NOP_UNAVAILABLE_REASON_None = 2409;

  // nop suppression reason
  DASMERROR_NOP_SUPPRESSION_REASON_FIM = 2500;
  DASMERROR_NOP_SUPPRESSION_REASON_AWBActv = 2501;
  DASMERROR_NOP_SUPPRESSION_REASON_AutoBrkgActv = 2502;
  DASMERROR_NOP_SUPPRESSION_REASON_ELKRunning = 2503;
  DASMERROR_NOP_SUPPRESSION_REASON_AEBPreWarnReq = 2504;
  DASMERROR_NOP_SUPPRESSION_REASON_OverSpeed = 2505;
  DASMERROR_NOP_SUPPRESSION_REASON_TrainNotCmpt = 2506;
  DASMERROR_NOP_SUPPRESSION_REASON_TrailerMode = 2507;
  DASMERROR_NOP_SUPPRESSION_REASON_EPSFault = 2508;
  DASMERROR_NOP_SUPPRESSION_REASON_NOPSup_FailSafe = 2509;
  DASMERROR_NOP_SUPPRESSION_REASON_NOPTopicFault = 2510;
  DASMERROR_NOP_SUPPRESSION_REASON_OverTDSpeed = 2511;
  DASMERROR_NOP_SUPPRESSION_REASON_RadFim = 2512;

  // psp activation prevention reason
  DASMERROR_PSP_ACTPREV_REASON_HzrdWarm = 2600;
  DASMERROR_PSP_ACTPREV_REASON_TrainNotCmpt = 2601;
  DASMERROR_PSP_ACTPREV_REASON_VMCNotFully = 2602;
  DASMERROR_PSP_ACTPREV_REASON_LgtErrTurnIndcn = 2603;
  DASMERROR_PSP_ACTPREV_REASON_AmbTemp = 2604;
  DASMERROR_PSP_ACTPREV_REASON_Maxspeed = 2605;
  DASMERROR_PSP_ACTPREV_REASON_SubAvail = 2606;
  DASMERROR_PSP_ACTPREV_REASON_OtherFunAct = 2607;
  DASMERROR_PSP_ACTPREV_REASON_CameraDataError = 2608;
  DASMERROR_PSP_ACTPREV_REASON_PSPStsNotAvail = 2609;
  DASMERROR_PSP_ACTPREV_REASON_SetDAPSPOff = 2610;
  DASMERROR_PSP_ACTPREV_REASON_PSPFim = 2611;
  DASMERROR_PSP_ACTPREV_REASON_GearNotDP = 2612;
  DASMERROR_PSP_ACTPREV_REASON_LatLoss = 2613;
  DASMERROR_PSP_ACTPREV_REASON_TurnIndctrOn = 2614;
  DASMERROR_PSP_ACTPREV_REASON_ALCLatCtrlOn = 2615;
  DASMERROR_PSP_ACTPREV_REASON_TrailerMode = 2616;
};

message DASMDebugInfo {
  optional DASMErrorCode error_code = 1 [default = DASMERROR_OK];
  optional string msg = 2;
}