syntax = "proto2";

option cc_enable_arenas = true;

package nio.ad.messages.task;

enum TaskType {
  NONE = 0;
  PSP_TO_LOC_BOX = 1;
  PSP_TO_QUEUE_AREA = 2;
  PSP_TO_PARKING_ZONE = 3;
  P2P_END_WITH_PARKING = 4;
  P2P_END_WITH_PARK_SEARCHING = 5;
  P2P_END_WITH_PULL_OVER = 6;
  P2P_END_WITH_NEARBY = 7;
  PN_NONE = 8;
  PN_TO_POI = 9;
}

enum TaskExecutationState {
  UNKNOWN = 0;
  SUCCESS = 1;
  PROCESSING = 2;
  FAIL = 3;  // TODO: add different reason
}

enum SchedulerLaneChangeEventState {
  EVENT_STATE_IDLE = 0;
  EVENT_STATE_LEFT_TRIGGER = 1;
  EVENT_STATE_RIGHT_TRIGGER = 2;
  EVENT_STATE_CANCEL_LEFT = 3;
  EVENT_STATE_CANCEL_RIGHT = 4;
}

enum LaneChangeTaskType {
  TASK_TYPE_HMI_REQ = 0;
  TASK_TYPE_ROUTING = 1;
  TASK_TYPE_OVERTAKE = 2;
  TASK_TYPE_PRIORITY = 3;
  TASK_TYPE_EMERGENCY = 4;
  TASK_TYPE_AVOID_MERGE_LANE = 5;
  TASK_TYPE_NUM = 6;
  TASK_TYPE_AVOID_BUS_LANE = 7;
}

enum HmiLaneChangeTaskError {
  TASK_ERROR_NONE = 0;
  TASK_ERROR_INTENTION_NOT_READY = 1;
  TASK_ERROR_SPEED_OUT_OF_RANGE = 2;
  TASK_ERROR_LANE_NOT_EXIST = 3;
  TASK_ERROR_LANE_NOT_DRIVABLE = 4;
  TASK_ERROR_LANE_BOUNDARY_FORBID = 5;
  TASK_ERROR_LC_SPACE_NOT_ENOUGH = 6;
  TASK_ERROR_NOT_INTERRUPT_LANE_CHANGING = 7;
  TASK_ERROR_ON_LANE_CHANGING = 8;
  TASK_ERROR_CANCELED_BY_HMI = 9;
  TASK_ERROR_CANCELED_BY_SAFETY = 10;
  TASK_ERROR_NOT_CANCEL_BY_OVER_CANCEL_POINT = 11;
  TASK_ERROR_APPROACH_OUT_OF_GLOBAL_ROUTE_ODD = 12;
  TASK_ERROR_LANE_DISTANCE_SHORT = 13;
  TASK_ERROR_NUM = 14;
  TASK_ERROR_RAMP_RISK_SCENARIO = 15;
  TASK_ERROR_SET_DA_ALCS = 16;
}

enum LaneChangeCoolingState {
  COOLING_STATE_WAIT_CONFIRM = 0;
  COOLING_STATE_WAIT_COOLING_TIME = 1;
  COOLING_STATE_DIRECT_RESPONSE = 2;
}

enum Scene {
  ROAD = 0;
  ROAD_TO_RAMP = 1;
  RAMP_TO_ROAD = 2;
  RAMP = 3;
}

enum Level {
  NORMAL = 0;
  HIGH = 1;
  MIDDLE = 2;
  LOW = 3;
}
