# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/avp/location_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.perf import sensor_ts_header_pb2 as common_dot_perf_dot_sensor__ts__header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/avp/location_info.proto',
  package='nio.ad.messages',
  syntax='proto2',
  serialized_options=b'\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x63ommon/avp/location_info.proto\x12\x0fnio.ad.messages\x1a\"common/perf/sensor_ts_header.proto\"\xc0\x03\n\x0cLocationInfo\x12\x18\n\x10timestamp_utc_ns\x18\x01 \x01(\x04\x12\x18\n\x10timestamp_ptp_ns\x18\x02 \x01(\x04\x12<\n\x08landmark\x18\x03 \x01(\x0e\x32*.nio.ad.messages.LocationInfo.LandmarkType\x12\x10\n\x08poi_uuid\x18\x04 \x01(\t\x12\x15\n\ttimestamp\x18\xf9\xff\xff\xff\x01 \x01(\x04\x12?\n\x12sensor_original_ts\x18\xfa\xff\xff\xff\x01 \x01(\x0b\x32\x1f.nio.ad.messages.SensorTSHeader\x12\x1a\n\x0epublish_ptp_ts\x18\xfb\xff\xff\xff\x01 \x01(\x04\x12\x18\n\x0cpublisher_id\x18\xfd\xff\xff\xff\x01 \x01(\t\x12\x13\n\x07\x63ounter\x18\xfe\xff\xff\xff\x01 \x01(\x04\x12\x16\n\npublish_ts\x18\xff\xff\xff\xff\x01 \x01(\x04\"q\n\x0cLandmarkType\x12\x0c\n\x08\x45NTRANCE\x10\x00\x12\x0f\n\x0b\x44\x45STINATION\x10\x01\x12\x08\n\x04\x45XIT\x10\x02\x12\x16\n\x12POWER_SWAP_STATION\x10\x03\x12\x14\n\x10NIO_SUPERCHARGER\x10\x04\x12\n\n\x06OTHERS\x10\x05\x42\x03\xf8\x01\x01'
  ,
  dependencies=[common_dot_perf_dot_sensor__ts__header__pb2.DESCRIPTOR,])



_LOCATIONINFO_LANDMARKTYPE = _descriptor.EnumDescriptor(
  name='LandmarkType',
  full_name='nio.ad.messages.LocationInfo.LandmarkType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ENTRANCE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DESTINATION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EXIT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='POWER_SWAP_STATION', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NIO_SUPERCHARGER', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OTHERS', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=423,
  serialized_end=536,
)
_sym_db.RegisterEnumDescriptor(_LOCATIONINFO_LANDMARKTYPE)


_LOCATIONINFO = _descriptor.Descriptor(
  name='LocationInfo',
  full_name='nio.ad.messages.LocationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp_utc_ns', full_name='nio.ad.messages.LocationInfo.timestamp_utc_ns', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp_ptp_ns', full_name='nio.ad.messages.LocationInfo.timestamp_ptp_ns', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='landmark', full_name='nio.ad.messages.LocationInfo.landmark', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='poi_uuid', full_name='nio.ad.messages.LocationInfo.poi_uuid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='nio.ad.messages.LocationInfo.timestamp', index=4,
      number=536870905, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_original_ts', full_name='nio.ad.messages.LocationInfo.sensor_original_ts', index=5,
      number=536870906, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='publish_ptp_ts', full_name='nio.ad.messages.LocationInfo.publish_ptp_ts', index=6,
      number=536870907, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='publisher_id', full_name='nio.ad.messages.LocationInfo.publisher_id', index=7,
      number=536870909, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='counter', full_name='nio.ad.messages.LocationInfo.counter', index=8,
      number=536870910, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='publish_ts', full_name='nio.ad.messages.LocationInfo.publish_ts', index=9,
      number=536870911, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOCATIONINFO_LANDMARKTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=536,
)

_LOCATIONINFO.fields_by_name['landmark'].enum_type = _LOCATIONINFO_LANDMARKTYPE
_LOCATIONINFO.fields_by_name['sensor_original_ts'].message_type = common_dot_perf_dot_sensor__ts__header__pb2._SENSORTSHEADER
_LOCATIONINFO_LANDMARKTYPE.containing_type = _LOCATIONINFO
DESCRIPTOR.message_types_by_name['LocationInfo'] = _LOCATIONINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocationInfo = _reflection.GeneratedProtocolMessageType('LocationInfo', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONINFO,
  '__module__' : 'common.avp.location_info_pb2'
  # @@protoc_insertion_point(class_scope:nio.ad.messages.LocationInfo)
  })
_sym_db.RegisterMessage(LocationInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
