// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/calibration/eol_imu_response.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_common_2fcalibration_2feol_5fimu_5fresponse_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_common_2fcalibration_2feol_5fimu_5fresponse_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3018000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3018001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "common/perf/sensor_ts_header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_common_2fcalibration_2feol_5fimu_5fresponse_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_common_2fcalibration_2feol_5fimu_5fresponse_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_common_2fcalibration_2feol_5fimu_5fresponse_2eproto;
namespace nio {
namespace ad {
namespace messages {
class EolImuResp;
struct EolImuRespDefaultTypeInternal;
extern EolImuRespDefaultTypeInternal _EolImuResp_default_instance_;
}  // namespace messages
}  // namespace ad
}  // namespace nio
PROTOBUF_NAMESPACE_OPEN
template<> ::nio::ad::messages::EolImuResp* Arena::CreateMaybeMessage<::nio::ad::messages::EolImuResp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace nio {
namespace ad {
namespace messages {

// ===================================================================

class EolImuResp final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nio.ad.messages.EolImuResp) */ {
 public:
  inline EolImuResp() : EolImuResp(nullptr) {}
  ~EolImuResp() override;
  explicit constexpr EolImuResp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EolImuResp(const EolImuResp& from);
  EolImuResp(EolImuResp&& from) noexcept
    : EolImuResp() {
    *this = ::std::move(from);
  }

  inline EolImuResp& operator=(const EolImuResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline EolImuResp& operator=(EolImuResp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EolImuResp& default_instance() {
    return *internal_default_instance();
  }
  static inline const EolImuResp* internal_default_instance() {
    return reinterpret_cast<const EolImuResp*>(
               &_EolImuResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EolImuResp& a, EolImuResp& b) {
    a.Swap(&b);
  }
  inline void Swap(EolImuResp* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EolImuResp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EolImuResp* New() const final {
    return new EolImuResp();
  }

  EolImuResp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EolImuResp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EolImuResp& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const EolImuResp& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EolImuResp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nio.ad.messages.EolImuResp";
  }
  protected:
  explicit EolImuResp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPublisherIdFieldNumber = 536870909,
    kSensorOriginalTsFieldNumber = 536870906,
    kCalStateFieldNumber = 1,
    kRsdImuBdyXFieldNumber = 2,
    kRsdImuBdyYFieldNumber = 3,
    kRsdImuBdyZFieldNumber = 4,
    kTimestampFieldNumber = 536870905,
    kPublishPtpTsFieldNumber = 536870907,
    kCounterFieldNumber = 536870910,
    kPublishTsFieldNumber = 536870911,
  };
  // optional string publisher_id = 536870909;
  bool has_publisher_id() const;
  private:
  bool _internal_has_publisher_id() const;
  public:
  void clear_publisher_id();
  const std::string& publisher_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_publisher_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_publisher_id();
  PROTOBUF_MUST_USE_RESULT std::string* release_publisher_id();
  void set_allocated_publisher_id(std::string* publisher_id);
  private:
  const std::string& _internal_publisher_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_publisher_id(const std::string& value);
  std::string* _internal_mutable_publisher_id();
  public:

  // optional .nio.ad.messages.SensorTSHeader sensor_original_ts = 536870906;
  bool has_sensor_original_ts() const;
  private:
  bool _internal_has_sensor_original_ts() const;
  public:
  void clear_sensor_original_ts();
  const ::nio::ad::messages::SensorTSHeader& sensor_original_ts() const;
  PROTOBUF_MUST_USE_RESULT ::nio::ad::messages::SensorTSHeader* release_sensor_original_ts();
  ::nio::ad::messages::SensorTSHeader* mutable_sensor_original_ts();
  void set_allocated_sensor_original_ts(::nio::ad::messages::SensorTSHeader* sensor_original_ts);
  private:
  const ::nio::ad::messages::SensorTSHeader& _internal_sensor_original_ts() const;
  ::nio::ad::messages::SensorTSHeader* _internal_mutable_sensor_original_ts();
  public:
  void unsafe_arena_set_allocated_sensor_original_ts(
      ::nio::ad::messages::SensorTSHeader* sensor_original_ts);
  ::nio::ad::messages::SensorTSHeader* unsafe_arena_release_sensor_original_ts();

  // optional uint32 cal_state = 1;
  bool has_cal_state() const;
  private:
  bool _internal_has_cal_state() const;
  public:
  void clear_cal_state();
  ::PROTOBUF_NAMESPACE_ID::uint32 cal_state() const;
  void set_cal_state(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_cal_state() const;
  void _internal_set_cal_state(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional float rsd_imu_bdy_x = 2;
  bool has_rsd_imu_bdy_x() const;
  private:
  bool _internal_has_rsd_imu_bdy_x() const;
  public:
  void clear_rsd_imu_bdy_x();
  float rsd_imu_bdy_x() const;
  void set_rsd_imu_bdy_x(float value);
  private:
  float _internal_rsd_imu_bdy_x() const;
  void _internal_set_rsd_imu_bdy_x(float value);
  public:

  // optional float rsd_imu_bdy_y = 3;
  bool has_rsd_imu_bdy_y() const;
  private:
  bool _internal_has_rsd_imu_bdy_y() const;
  public:
  void clear_rsd_imu_bdy_y();
  float rsd_imu_bdy_y() const;
  void set_rsd_imu_bdy_y(float value);
  private:
  float _internal_rsd_imu_bdy_y() const;
  void _internal_set_rsd_imu_bdy_y(float value);
  public:

  // optional float rsd_imu_bdy_z = 4;
  bool has_rsd_imu_bdy_z() const;
  private:
  bool _internal_has_rsd_imu_bdy_z() const;
  public:
  void clear_rsd_imu_bdy_z();
  float rsd_imu_bdy_z() const;
  void set_rsd_imu_bdy_z(float value);
  private:
  float _internal_rsd_imu_bdy_z() const;
  void _internal_set_rsd_imu_bdy_z(float value);
  public:

  // optional uint64 timestamp = 536870905;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 publish_ptp_ts = 536870907;
  bool has_publish_ptp_ts() const;
  private:
  bool _internal_has_publish_ptp_ts() const;
  public:
  void clear_publish_ptp_ts();
  ::PROTOBUF_NAMESPACE_ID::uint64 publish_ptp_ts() const;
  void set_publish_ptp_ts(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_publish_ptp_ts() const;
  void _internal_set_publish_ptp_ts(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 counter = 536870910;
  bool has_counter() const;
  private:
  bool _internal_has_counter() const;
  public:
  void clear_counter();
  ::PROTOBUF_NAMESPACE_ID::uint64 counter() const;
  void set_counter(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_counter() const;
  void _internal_set_counter(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 publish_ts = 536870911;
  bool has_publish_ts() const;
  private:
  bool _internal_has_publish_ts() const;
  public:
  void clear_publish_ts();
  ::PROTOBUF_NAMESPACE_ID::uint64 publish_ts() const;
  void set_publish_ts(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_publish_ts() const;
  void _internal_set_publish_ts(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:nio.ad.messages.EolImuResp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr publisher_id_;
  ::nio::ad::messages::SensorTSHeader* sensor_original_ts_;
  ::PROTOBUF_NAMESPACE_ID::uint32 cal_state_;
  float rsd_imu_bdy_x_;
  float rsd_imu_bdy_y_;
  float rsd_imu_bdy_z_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_;
  ::PROTOBUF_NAMESPACE_ID::uint64 publish_ptp_ts_;
  ::PROTOBUF_NAMESPACE_ID::uint64 counter_;
  ::PROTOBUF_NAMESPACE_ID::uint64 publish_ts_;
  friend struct ::TableStruct_common_2fcalibration_2feol_5fimu_5fresponse_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EolImuResp

// optional uint32 cal_state = 1;
inline bool EolImuResp::_internal_has_cal_state() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool EolImuResp::has_cal_state() const {
  return _internal_has_cal_state();
}
inline void EolImuResp::clear_cal_state() {
  cal_state_ = 0u;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 EolImuResp::_internal_cal_state() const {
  return cal_state_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 EolImuResp::cal_state() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.EolImuResp.cal_state)
  return _internal_cal_state();
}
inline void EolImuResp::_internal_set_cal_state(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000004u;
  cal_state_ = value;
}
inline void EolImuResp::set_cal_state(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_cal_state(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.EolImuResp.cal_state)
}

// optional float rsd_imu_bdy_x = 2;
inline bool EolImuResp::_internal_has_rsd_imu_bdy_x() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool EolImuResp::has_rsd_imu_bdy_x() const {
  return _internal_has_rsd_imu_bdy_x();
}
inline void EolImuResp::clear_rsd_imu_bdy_x() {
  rsd_imu_bdy_x_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline float EolImuResp::_internal_rsd_imu_bdy_x() const {
  return rsd_imu_bdy_x_;
}
inline float EolImuResp::rsd_imu_bdy_x() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.EolImuResp.rsd_imu_bdy_x)
  return _internal_rsd_imu_bdy_x();
}
inline void EolImuResp::_internal_set_rsd_imu_bdy_x(float value) {
  _has_bits_[0] |= 0x00000008u;
  rsd_imu_bdy_x_ = value;
}
inline void EolImuResp::set_rsd_imu_bdy_x(float value) {
  _internal_set_rsd_imu_bdy_x(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.EolImuResp.rsd_imu_bdy_x)
}

// optional float rsd_imu_bdy_y = 3;
inline bool EolImuResp::_internal_has_rsd_imu_bdy_y() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool EolImuResp::has_rsd_imu_bdy_y() const {
  return _internal_has_rsd_imu_bdy_y();
}
inline void EolImuResp::clear_rsd_imu_bdy_y() {
  rsd_imu_bdy_y_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline float EolImuResp::_internal_rsd_imu_bdy_y() const {
  return rsd_imu_bdy_y_;
}
inline float EolImuResp::rsd_imu_bdy_y() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.EolImuResp.rsd_imu_bdy_y)
  return _internal_rsd_imu_bdy_y();
}
inline void EolImuResp::_internal_set_rsd_imu_bdy_y(float value) {
  _has_bits_[0] |= 0x00000010u;
  rsd_imu_bdy_y_ = value;
}
inline void EolImuResp::set_rsd_imu_bdy_y(float value) {
  _internal_set_rsd_imu_bdy_y(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.EolImuResp.rsd_imu_bdy_y)
}

// optional float rsd_imu_bdy_z = 4;
inline bool EolImuResp::_internal_has_rsd_imu_bdy_z() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool EolImuResp::has_rsd_imu_bdy_z() const {
  return _internal_has_rsd_imu_bdy_z();
}
inline void EolImuResp::clear_rsd_imu_bdy_z() {
  rsd_imu_bdy_z_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline float EolImuResp::_internal_rsd_imu_bdy_z() const {
  return rsd_imu_bdy_z_;
}
inline float EolImuResp::rsd_imu_bdy_z() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.EolImuResp.rsd_imu_bdy_z)
  return _internal_rsd_imu_bdy_z();
}
inline void EolImuResp::_internal_set_rsd_imu_bdy_z(float value) {
  _has_bits_[0] |= 0x00000020u;
  rsd_imu_bdy_z_ = value;
}
inline void EolImuResp::set_rsd_imu_bdy_z(float value) {
  _internal_set_rsd_imu_bdy_z(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.EolImuResp.rsd_imu_bdy_z)
}

// optional uint64 timestamp = 536870905;
inline bool EolImuResp::_internal_has_timestamp() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool EolImuResp::has_timestamp() const {
  return _internal_has_timestamp();
}
inline void EolImuResp::clear_timestamp() {
  timestamp_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000040u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EolImuResp::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EolImuResp::timestamp() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.EolImuResp.timestamp)
  return _internal_timestamp();
}
inline void EolImuResp::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000040u;
  timestamp_ = value;
}
inline void EolImuResp::set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.EolImuResp.timestamp)
}

// optional .nio.ad.messages.SensorTSHeader sensor_original_ts = 536870906;
inline bool EolImuResp::_internal_has_sensor_original_ts() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || sensor_original_ts_ != nullptr);
  return value;
}
inline bool EolImuResp::has_sensor_original_ts() const {
  return _internal_has_sensor_original_ts();
}
inline const ::nio::ad::messages::SensorTSHeader& EolImuResp::_internal_sensor_original_ts() const {
  const ::nio::ad::messages::SensorTSHeader* p = sensor_original_ts_;
  return p != nullptr ? *p : reinterpret_cast<const ::nio::ad::messages::SensorTSHeader&>(
      ::nio::ad::messages::_SensorTSHeader_default_instance_);
}
inline const ::nio::ad::messages::SensorTSHeader& EolImuResp::sensor_original_ts() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.EolImuResp.sensor_original_ts)
  return _internal_sensor_original_ts();
}
inline void EolImuResp::unsafe_arena_set_allocated_sensor_original_ts(
    ::nio::ad::messages::SensorTSHeader* sensor_original_ts) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(sensor_original_ts_);
  }
  sensor_original_ts_ = sensor_original_ts;
  if (sensor_original_ts) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:nio.ad.messages.EolImuResp.sensor_original_ts)
}
inline ::nio::ad::messages::SensorTSHeader* EolImuResp::release_sensor_original_ts() {
  _has_bits_[0] &= ~0x00000002u;
  ::nio::ad::messages::SensorTSHeader* temp = sensor_original_ts_;
  sensor_original_ts_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::nio::ad::messages::SensorTSHeader* EolImuResp::unsafe_arena_release_sensor_original_ts() {
  // @@protoc_insertion_point(field_release:nio.ad.messages.EolImuResp.sensor_original_ts)
  _has_bits_[0] &= ~0x00000002u;
  ::nio::ad::messages::SensorTSHeader* temp = sensor_original_ts_;
  sensor_original_ts_ = nullptr;
  return temp;
}
inline ::nio::ad::messages::SensorTSHeader* EolImuResp::_internal_mutable_sensor_original_ts() {
  _has_bits_[0] |= 0x00000002u;
  if (sensor_original_ts_ == nullptr) {
    auto* p = CreateMaybeMessage<::nio::ad::messages::SensorTSHeader>(GetArenaForAllocation());
    sensor_original_ts_ = p;
  }
  return sensor_original_ts_;
}
inline ::nio::ad::messages::SensorTSHeader* EolImuResp::mutable_sensor_original_ts() {
  ::nio::ad::messages::SensorTSHeader* _msg = _internal_mutable_sensor_original_ts();
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.EolImuResp.sensor_original_ts)
  return _msg;
}
inline void EolImuResp::set_allocated_sensor_original_ts(::nio::ad::messages::SensorTSHeader* sensor_original_ts) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(sensor_original_ts_);
  }
  if (sensor_original_ts) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(sensor_original_ts));
    if (message_arena != submessage_arena) {
      sensor_original_ts = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, sensor_original_ts, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  sensor_original_ts_ = sensor_original_ts;
  // @@protoc_insertion_point(field_set_allocated:nio.ad.messages.EolImuResp.sensor_original_ts)
}

// optional uint64 publish_ptp_ts = 536870907;
inline bool EolImuResp::_internal_has_publish_ptp_ts() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool EolImuResp::has_publish_ptp_ts() const {
  return _internal_has_publish_ptp_ts();
}
inline void EolImuResp::clear_publish_ptp_ts() {
  publish_ptp_ts_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000080u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EolImuResp::_internal_publish_ptp_ts() const {
  return publish_ptp_ts_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EolImuResp::publish_ptp_ts() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.EolImuResp.publish_ptp_ts)
  return _internal_publish_ptp_ts();
}
inline void EolImuResp::_internal_set_publish_ptp_ts(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000080u;
  publish_ptp_ts_ = value;
}
inline void EolImuResp::set_publish_ptp_ts(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_publish_ptp_ts(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.EolImuResp.publish_ptp_ts)
}

// optional string publisher_id = 536870909;
inline bool EolImuResp::_internal_has_publisher_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool EolImuResp::has_publisher_id() const {
  return _internal_has_publisher_id();
}
inline void EolImuResp::clear_publisher_id() {
  publisher_id_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& EolImuResp::publisher_id() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.EolImuResp.publisher_id)
  return _internal_publisher_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void EolImuResp::set_publisher_id(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 publisher_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nio.ad.messages.EolImuResp.publisher_id)
}
inline std::string* EolImuResp::mutable_publisher_id() {
  std::string* _s = _internal_mutable_publisher_id();
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.EolImuResp.publisher_id)
  return _s;
}
inline const std::string& EolImuResp::_internal_publisher_id() const {
  return publisher_id_.Get();
}
inline void EolImuResp::_internal_set_publisher_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  publisher_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* EolImuResp::_internal_mutable_publisher_id() {
  _has_bits_[0] |= 0x00000001u;
  return publisher_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* EolImuResp::release_publisher_id() {
  // @@protoc_insertion_point(field_release:nio.ad.messages.EolImuResp.publisher_id)
  if (!_internal_has_publisher_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return publisher_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void EolImuResp::set_allocated_publisher_id(std::string* publisher_id) {
  if (publisher_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  publisher_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), publisher_id,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:nio.ad.messages.EolImuResp.publisher_id)
}

// optional uint64 counter = 536870910;
inline bool EolImuResp::_internal_has_counter() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool EolImuResp::has_counter() const {
  return _internal_has_counter();
}
inline void EolImuResp::clear_counter() {
  counter_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000100u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EolImuResp::_internal_counter() const {
  return counter_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EolImuResp::counter() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.EolImuResp.counter)
  return _internal_counter();
}
inline void EolImuResp::_internal_set_counter(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000100u;
  counter_ = value;
}
inline void EolImuResp::set_counter(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_counter(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.EolImuResp.counter)
}

// optional uint64 publish_ts = 536870911;
inline bool EolImuResp::_internal_has_publish_ts() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool EolImuResp::has_publish_ts() const {
  return _internal_has_publish_ts();
}
inline void EolImuResp::clear_publish_ts() {
  publish_ts_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000200u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EolImuResp::_internal_publish_ts() const {
  return publish_ts_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 EolImuResp::publish_ts() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.EolImuResp.publish_ts)
  return _internal_publish_ts();
}
inline void EolImuResp::_internal_set_publish_ts(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000200u;
  publish_ts_ = value;
}
inline void EolImuResp::set_publish_ts(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_publish_ts(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.EolImuResp.publish_ts)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace ad
}  // namespace nio

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_common_2fcalibration_2feol_5fimu_5fresponse_2eproto
