syntax = "proto2";

option cc_enable_arenas = true;

package nio.ad.messages;
import "common/perf/sensor_ts_header.proto";

message SimulationStateSync{
    optional uint32 DanadStsSet = 1;
    optional double TauGapSet = 2;
    optional double TgtSpdSet = 3;
    optional double Reserved_4 = 4;
    optional double Reserved_5 = 5; 
    optional double Reserved_6 = 6; 
    optional double Reserved_7 = 7; 
    optional double Reserved_8 = 8; 
    optional double Reserved_9 = 9; 
    optional double Reserved_10 = 10; 

    optional uint64 timestamp = 536870905; // ptp timestamp, nanosecond，used for data bundle readin 
    optional SensorTSHeader sensor_original_ts = 536870906;   // sensor original ts
    optional uint64 publish_ptp_ts = 536870907;     // publish ptp timestamp, uint in nanosec
	optional string publisher_id = 536870909; // uuid of the publisher
	optional uint64 counter = 536870910;         // message counter
	optional uint64 publish_ts = 536870911;    // publish utc timestamp; unit : nanosecond

}