// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/localization/lmm_transparent_info.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_common_2flocalization_2flmm_5ftransparent_5finfo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_common_2flocalization_2flmm_5ftransparent_5finfo_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3018000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3018001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_common_2flocalization_2flmm_5ftransparent_5finfo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_common_2flocalization_2flmm_5ftransparent_5finfo_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_common_2flocalization_2flmm_5ftransparent_5finfo_2eproto;
namespace nio {
namespace ad {
namespace messages {
class LMMTransparentInfo;
struct LMMTransparentInfoDefaultTypeInternal;
extern LMMTransparentInfoDefaultTypeInternal _LMMTransparentInfo_default_instance_;
}  // namespace messages
}  // namespace ad
}  // namespace nio
PROTOBUF_NAMESPACE_OPEN
template<> ::nio::ad::messages::LMMTransparentInfo* Arena::CreateMaybeMessage<::nio::ad::messages::LMMTransparentInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace nio {
namespace ad {
namespace messages {

// ===================================================================

class LMMTransparentInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nio.ad.messages.LMMTransparentInfo) */ {
 public:
  inline LMMTransparentInfo() : LMMTransparentInfo(nullptr) {}
  ~LMMTransparentInfo() override;
  explicit constexpr LMMTransparentInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LMMTransparentInfo(const LMMTransparentInfo& from);
  LMMTransparentInfo(LMMTransparentInfo&& from) noexcept
    : LMMTransparentInfo() {
    *this = ::std::move(from);
  }

  inline LMMTransparentInfo& operator=(const LMMTransparentInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline LMMTransparentInfo& operator=(LMMTransparentInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LMMTransparentInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const LMMTransparentInfo* internal_default_instance() {
    return reinterpret_cast<const LMMTransparentInfo*>(
               &_LMMTransparentInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LMMTransparentInfo& a, LMMTransparentInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(LMMTransparentInfo* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LMMTransparentInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LMMTransparentInfo* New() const final {
    return new LMMTransparentInfo();
  }

  LMMTransparentInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LMMTransparentInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LMMTransparentInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const LMMTransparentInfo& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LMMTransparentInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nio.ad.messages.LMMTransparentInfo";
  }
  protected:
  explicit LMMTransparentInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampUtcNsFieldNumber = 1,
    kTimestampPtpNsFieldNumber = 2,
    kCrossLayerProportionFieldNumber = 3,
    kGlobalFloorIdFieldNumber = 4,
  };
  // optional uint64 timestamp_utc_ns = 1;
  bool has_timestamp_utc_ns() const;
  private:
  bool _internal_has_timestamp_utc_ns() const;
  public:
  void clear_timestamp_utc_ns();
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_utc_ns() const;
  void set_timestamp_utc_ns(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timestamp_utc_ns() const;
  void _internal_set_timestamp_utc_ns(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 timestamp_ptp_ns = 2;
  bool has_timestamp_ptp_ns() const;
  private:
  bool _internal_has_timestamp_ptp_ns() const;
  public:
  void clear_timestamp_ptp_ns();
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_ptp_ns() const;
  void set_timestamp_ptp_ns(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timestamp_ptp_ns() const;
  void _internal_set_timestamp_ptp_ns(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional float cross_layer_proportion = 3;
  bool has_cross_layer_proportion() const;
  private:
  bool _internal_has_cross_layer_proportion() const;
  public:
  void clear_cross_layer_proportion();
  float cross_layer_proportion() const;
  void set_cross_layer_proportion(float value);
  private:
  float _internal_cross_layer_proportion() const;
  void _internal_set_cross_layer_proportion(float value);
  public:

  // optional int32 global_floor_id = 4;
  bool has_global_floor_id() const;
  private:
  bool _internal_has_global_floor_id() const;
  public:
  void clear_global_floor_id();
  ::PROTOBUF_NAMESPACE_ID::int32 global_floor_id() const;
  void set_global_floor_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_global_floor_id() const;
  void _internal_set_global_floor_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:nio.ad.messages.LMMTransparentInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_utc_ns_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_ptp_ns_;
  float cross_layer_proportion_;
  ::PROTOBUF_NAMESPACE_ID::int32 global_floor_id_;
  friend struct ::TableStruct_common_2flocalization_2flmm_5ftransparent_5finfo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LMMTransparentInfo

// optional uint64 timestamp_utc_ns = 1;
inline bool LMMTransparentInfo::_internal_has_timestamp_utc_ns() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool LMMTransparentInfo::has_timestamp_utc_ns() const {
  return _internal_has_timestamp_utc_ns();
}
inline void LMMTransparentInfo::clear_timestamp_utc_ns() {
  timestamp_utc_ns_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 LMMTransparentInfo::_internal_timestamp_utc_ns() const {
  return timestamp_utc_ns_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 LMMTransparentInfo::timestamp_utc_ns() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.LMMTransparentInfo.timestamp_utc_ns)
  return _internal_timestamp_utc_ns();
}
inline void LMMTransparentInfo::_internal_set_timestamp_utc_ns(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000001u;
  timestamp_utc_ns_ = value;
}
inline void LMMTransparentInfo::set_timestamp_utc_ns(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timestamp_utc_ns(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.LMMTransparentInfo.timestamp_utc_ns)
}

// optional uint64 timestamp_ptp_ns = 2;
inline bool LMMTransparentInfo::_internal_has_timestamp_ptp_ns() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool LMMTransparentInfo::has_timestamp_ptp_ns() const {
  return _internal_has_timestamp_ptp_ns();
}
inline void LMMTransparentInfo::clear_timestamp_ptp_ns() {
  timestamp_ptp_ns_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 LMMTransparentInfo::_internal_timestamp_ptp_ns() const {
  return timestamp_ptp_ns_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 LMMTransparentInfo::timestamp_ptp_ns() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.LMMTransparentInfo.timestamp_ptp_ns)
  return _internal_timestamp_ptp_ns();
}
inline void LMMTransparentInfo::_internal_set_timestamp_ptp_ns(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000002u;
  timestamp_ptp_ns_ = value;
}
inline void LMMTransparentInfo::set_timestamp_ptp_ns(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timestamp_ptp_ns(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.LMMTransparentInfo.timestamp_ptp_ns)
}

// optional float cross_layer_proportion = 3;
inline bool LMMTransparentInfo::_internal_has_cross_layer_proportion() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool LMMTransparentInfo::has_cross_layer_proportion() const {
  return _internal_has_cross_layer_proportion();
}
inline void LMMTransparentInfo::clear_cross_layer_proportion() {
  cross_layer_proportion_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline float LMMTransparentInfo::_internal_cross_layer_proportion() const {
  return cross_layer_proportion_;
}
inline float LMMTransparentInfo::cross_layer_proportion() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.LMMTransparentInfo.cross_layer_proportion)
  return _internal_cross_layer_proportion();
}
inline void LMMTransparentInfo::_internal_set_cross_layer_proportion(float value) {
  _has_bits_[0] |= 0x00000004u;
  cross_layer_proportion_ = value;
}
inline void LMMTransparentInfo::set_cross_layer_proportion(float value) {
  _internal_set_cross_layer_proportion(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.LMMTransparentInfo.cross_layer_proportion)
}

// optional int32 global_floor_id = 4;
inline bool LMMTransparentInfo::_internal_has_global_floor_id() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool LMMTransparentInfo::has_global_floor_id() const {
  return _internal_has_global_floor_id();
}
inline void LMMTransparentInfo::clear_global_floor_id() {
  global_floor_id_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LMMTransparentInfo::_internal_global_floor_id() const {
  return global_floor_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LMMTransparentInfo::global_floor_id() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.LMMTransparentInfo.global_floor_id)
  return _internal_global_floor_id();
}
inline void LMMTransparentInfo::_internal_set_global_floor_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  global_floor_id_ = value;
}
inline void LMMTransparentInfo::set_global_floor_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_global_floor_id(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.LMMTransparentInfo.global_floor_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace ad
}  // namespace nio

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_common_2flocalization_2flmm_5ftransparent_5finfo_2eproto
