// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/pnc/das_agent_request.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_common_2fpnc_2fdas_5fagent_5frequest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_common_2fpnc_2fdas_5fagent_5frequest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3018000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3018001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "common/pnc/geometry.pb.h"
#include "common/perf/sensor_ts_header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_common_2fpnc_2fdas_5fagent_5frequest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_common_2fpnc_2fdas_5fagent_5frequest_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_common_2fpnc_2fdas_5fagent_5frequest_2eproto;
namespace nio {
namespace ad {
namespace messages {
class Content;
struct ContentDefaultTypeInternal;
extern ContentDefaultTypeInternal _Content_default_instance_;
class DasAgentRequest;
struct DasAgentRequestDefaultTypeInternal;
extern DasAgentRequestDefaultTypeInternal _DasAgentRequest_default_instance_;
class Prompt;
struct PromptDefaultTypeInternal;
extern PromptDefaultTypeInternal _Prompt_default_instance_;
class PromptMessage;
struct PromptMessageDefaultTypeInternal;
extern PromptMessageDefaultTypeInternal _PromptMessage_default_instance_;
}  // namespace messages
}  // namespace ad
}  // namespace nio
PROTOBUF_NAMESPACE_OPEN
template<> ::nio::ad::messages::Content* Arena::CreateMaybeMessage<::nio::ad::messages::Content>(Arena*);
template<> ::nio::ad::messages::DasAgentRequest* Arena::CreateMaybeMessage<::nio::ad::messages::DasAgentRequest>(Arena*);
template<> ::nio::ad::messages::Prompt* Arena::CreateMaybeMessage<::nio::ad::messages::Prompt>(Arena*);
template<> ::nio::ad::messages::PromptMessage* Arena::CreateMaybeMessage<::nio::ad::messages::PromptMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace nio {
namespace ad {
namespace messages {

enum Content_Type : int {
  Content_Type_TEXT = 0,
  Content_Type_IMAGE_TIMESTAMP = 1,
  Content_Type_IMAGE_B64STRING = 2,
  Content_Type_IMAGE_URL = 3
};
bool Content_Type_IsValid(int value);
constexpr Content_Type Content_Type_Type_MIN = Content_Type_TEXT;
constexpr Content_Type Content_Type_Type_MAX = Content_Type_IMAGE_URL;
constexpr int Content_Type_Type_ARRAYSIZE = Content_Type_Type_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Content_Type_descriptor();
template<typename T>
inline const std::string& Content_Type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Content_Type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Content_Type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Content_Type_descriptor(), enum_t_value);
}
inline bool Content_Type_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Content_Type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Content_Type>(
    Content_Type_descriptor(), name, value);
}
enum PromptMessage_Role : int {
  PromptMessage_Role_USER = 0,
  PromptMessage_Role_SYSTEM = 1
};
bool PromptMessage_Role_IsValid(int value);
constexpr PromptMessage_Role PromptMessage_Role_Role_MIN = PromptMessage_Role_USER;
constexpr PromptMessage_Role PromptMessage_Role_Role_MAX = PromptMessage_Role_SYSTEM;
constexpr int PromptMessage_Role_Role_ARRAYSIZE = PromptMessage_Role_Role_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PromptMessage_Role_descriptor();
template<typename T>
inline const std::string& PromptMessage_Role_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PromptMessage_Role>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PromptMessage_Role_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PromptMessage_Role_descriptor(), enum_t_value);
}
inline bool PromptMessage_Role_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PromptMessage_Role* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PromptMessage_Role>(
    PromptMessage_Role_descriptor(), name, value);
}
enum Prompt_FunctionInfo : int {
  Prompt_FunctionInfo_DeadCar = 0,
  Prompt_FunctionInfo_ConstructionArea = 1
};
bool Prompt_FunctionInfo_IsValid(int value);
constexpr Prompt_FunctionInfo Prompt_FunctionInfo_FunctionInfo_MIN = Prompt_FunctionInfo_DeadCar;
constexpr Prompt_FunctionInfo Prompt_FunctionInfo_FunctionInfo_MAX = Prompt_FunctionInfo_ConstructionArea;
constexpr int Prompt_FunctionInfo_FunctionInfo_ARRAYSIZE = Prompt_FunctionInfo_FunctionInfo_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Prompt_FunctionInfo_descriptor();
template<typename T>
inline const std::string& Prompt_FunctionInfo_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Prompt_FunctionInfo>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Prompt_FunctionInfo_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Prompt_FunctionInfo_descriptor(), enum_t_value);
}
inline bool Prompt_FunctionInfo_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Prompt_FunctionInfo* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Prompt_FunctionInfo>(
    Prompt_FunctionInfo_descriptor(), name, value);
}
// ===================================================================

class Content final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nio.ad.messages.Content) */ {
 public:
  inline Content() : Content(nullptr) {}
  ~Content() override;
  explicit constexpr Content(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Content(const Content& from);
  Content(Content&& from) noexcept
    : Content() {
    *this = ::std::move(from);
  }

  inline Content& operator=(const Content& from) {
    CopyFrom(from);
    return *this;
  }
  inline Content& operator=(Content&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Content& default_instance() {
    return *internal_default_instance();
  }
  static inline const Content* internal_default_instance() {
    return reinterpret_cast<const Content*>(
               &_Content_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Content& a, Content& b) {
    a.Swap(&b);
  }
  inline void Swap(Content* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Content* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Content* New() const final {
    return new Content();
  }

  Content* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Content>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Content& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Content& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Content* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nio.ad.messages.Content";
  }
  protected:
  explicit Content(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Content_Type Type;
  static constexpr Type TEXT =
    Content_Type_TEXT;
  static constexpr Type IMAGE_TIMESTAMP =
    Content_Type_IMAGE_TIMESTAMP;
  static constexpr Type IMAGE_B64STRING =
    Content_Type_IMAGE_B64STRING;
  static constexpr Type IMAGE_URL =
    Content_Type_IMAGE_URL;
  static inline bool Type_IsValid(int value) {
    return Content_Type_IsValid(value);
  }
  static constexpr Type Type_MIN =
    Content_Type_Type_MIN;
  static constexpr Type Type_MAX =
    Content_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE =
    Content_Type_Type_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Type_descriptor() {
    return Content_Type_descriptor();
  }
  template<typename T>
  static inline const std::string& Type_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Type>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Type_Name.");
    return Content_Type_Name(enum_t_value);
  }
  static inline bool Type_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Type* value) {
    return Content_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kTextFieldNumber = 2,
    kImageUrlFieldNumber = 3,
    kImageB64StringFieldNumber = 4,
    kImageTimestampFieldNumber = 5,
    kTypeFieldNumber = 1,
  };
  // optional string text = 2;
  bool has_text() const;
  private:
  bool _internal_has_text() const;
  public:
  void clear_text();
  const std::string& text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_text();
  PROTOBUF_MUST_USE_RESULT std::string* release_text();
  void set_allocated_text(std::string* text);
  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(const std::string& value);
  std::string* _internal_mutable_text();
  public:

  // optional string image_url = 3;
  bool has_image_url() const;
  private:
  bool _internal_has_image_url() const;
  public:
  void clear_image_url();
  const std::string& image_url() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_image_url(ArgT0&& arg0, ArgT... args);
  std::string* mutable_image_url();
  PROTOBUF_MUST_USE_RESULT std::string* release_image_url();
  void set_allocated_image_url(std::string* image_url);
  private:
  const std::string& _internal_image_url() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_image_url(const std::string& value);
  std::string* _internal_mutable_image_url();
  public:

  // optional string image_b64string = 4;
  bool has_image_b64string() const;
  private:
  bool _internal_has_image_b64string() const;
  public:
  void clear_image_b64string();
  const std::string& image_b64string() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_image_b64string(ArgT0&& arg0, ArgT... args);
  std::string* mutable_image_b64string();
  PROTOBUF_MUST_USE_RESULT std::string* release_image_b64string();
  void set_allocated_image_b64string(std::string* image_b64string);
  private:
  const std::string& _internal_image_b64string() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_image_b64string(const std::string& value);
  std::string* _internal_mutable_image_b64string();
  public:

  // optional uint64 image_timestamp = 5;
  bool has_image_timestamp() const;
  private:
  bool _internal_has_image_timestamp() const;
  public:
  void clear_image_timestamp();
  ::PROTOBUF_NAMESPACE_ID::uint64 image_timestamp() const;
  void set_image_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_image_timestamp() const;
  void _internal_set_image_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional .nio.ad.messages.Content.Type type = 1;
  bool has_type() const;
  private:
  bool _internal_has_type() const;
  public:
  void clear_type();
  ::nio::ad::messages::Content_Type type() const;
  void set_type(::nio::ad::messages::Content_Type value);
  private:
  ::nio::ad::messages::Content_Type _internal_type() const;
  void _internal_set_type(::nio::ad::messages::Content_Type value);
  public:

  // @@protoc_insertion_point(class_scope:nio.ad.messages.Content)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr image_url_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr image_b64string_;
  ::PROTOBUF_NAMESPACE_ID::uint64 image_timestamp_;
  int type_;
  friend struct ::TableStruct_common_2fpnc_2fdas_5fagent_5frequest_2eproto;
};
// -------------------------------------------------------------------

class PromptMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nio.ad.messages.PromptMessage) */ {
 public:
  inline PromptMessage() : PromptMessage(nullptr) {}
  ~PromptMessage() override;
  explicit constexpr PromptMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PromptMessage(const PromptMessage& from);
  PromptMessage(PromptMessage&& from) noexcept
    : PromptMessage() {
    *this = ::std::move(from);
  }

  inline PromptMessage& operator=(const PromptMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline PromptMessage& operator=(PromptMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PromptMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const PromptMessage* internal_default_instance() {
    return reinterpret_cast<const PromptMessage*>(
               &_PromptMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PromptMessage& a, PromptMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(PromptMessage* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PromptMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PromptMessage* New() const final {
    return new PromptMessage();
  }

  PromptMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PromptMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PromptMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const PromptMessage& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PromptMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nio.ad.messages.PromptMessage";
  }
  protected:
  explicit PromptMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef PromptMessage_Role Role;
  static constexpr Role USER =
    PromptMessage_Role_USER;
  static constexpr Role SYSTEM =
    PromptMessage_Role_SYSTEM;
  static inline bool Role_IsValid(int value) {
    return PromptMessage_Role_IsValid(value);
  }
  static constexpr Role Role_MIN =
    PromptMessage_Role_Role_MIN;
  static constexpr Role Role_MAX =
    PromptMessage_Role_Role_MAX;
  static constexpr int Role_ARRAYSIZE =
    PromptMessage_Role_Role_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Role_descriptor() {
    return PromptMessage_Role_descriptor();
  }
  template<typename T>
  static inline const std::string& Role_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Role>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Role_Name.");
    return PromptMessage_Role_Name(enum_t_value);
  }
  static inline bool Role_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Role* value) {
    return PromptMessage_Role_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kContentsFieldNumber = 2,
    kRoleFieldNumber = 1,
  };
  // repeated .nio.ad.messages.Content contents = 2;
  int contents_size() const;
  private:
  int _internal_contents_size() const;
  public:
  void clear_contents();
  ::nio::ad::messages::Content* mutable_contents(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Content >*
      mutable_contents();
  private:
  const ::nio::ad::messages::Content& _internal_contents(int index) const;
  ::nio::ad::messages::Content* _internal_add_contents();
  public:
  const ::nio::ad::messages::Content& contents(int index) const;
  ::nio::ad::messages::Content* add_contents();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Content >&
      contents() const;

  // optional .nio.ad.messages.PromptMessage.Role role = 1;
  bool has_role() const;
  private:
  bool _internal_has_role() const;
  public:
  void clear_role();
  ::nio::ad::messages::PromptMessage_Role role() const;
  void set_role(::nio::ad::messages::PromptMessage_Role value);
  private:
  ::nio::ad::messages::PromptMessage_Role _internal_role() const;
  void _internal_set_role(::nio::ad::messages::PromptMessage_Role value);
  public:

  // @@protoc_insertion_point(class_scope:nio.ad.messages.PromptMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Content > contents_;
  int role_;
  friend struct ::TableStruct_common_2fpnc_2fdas_5fagent_5frequest_2eproto;
};
// -------------------------------------------------------------------

class Prompt final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nio.ad.messages.Prompt) */ {
 public:
  inline Prompt() : Prompt(nullptr) {}
  ~Prompt() override;
  explicit constexpr Prompt(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Prompt(const Prompt& from);
  Prompt(Prompt&& from) noexcept
    : Prompt() {
    *this = ::std::move(from);
  }

  inline Prompt& operator=(const Prompt& from) {
    CopyFrom(from);
    return *this;
  }
  inline Prompt& operator=(Prompt&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Prompt& default_instance() {
    return *internal_default_instance();
  }
  static inline const Prompt* internal_default_instance() {
    return reinterpret_cast<const Prompt*>(
               &_Prompt_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Prompt& a, Prompt& b) {
    a.Swap(&b);
  }
  inline void Swap(Prompt* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Prompt* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Prompt* New() const final {
    return new Prompt();
  }

  Prompt* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Prompt>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Prompt& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Prompt& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Prompt* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nio.ad.messages.Prompt";
  }
  protected:
  explicit Prompt(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Prompt_FunctionInfo FunctionInfo;
  static constexpr FunctionInfo DeadCar =
    Prompt_FunctionInfo_DeadCar;
  static constexpr FunctionInfo ConstructionArea =
    Prompt_FunctionInfo_ConstructionArea;
  static inline bool FunctionInfo_IsValid(int value) {
    return Prompt_FunctionInfo_IsValid(value);
  }
  static constexpr FunctionInfo FunctionInfo_MIN =
    Prompt_FunctionInfo_FunctionInfo_MIN;
  static constexpr FunctionInfo FunctionInfo_MAX =
    Prompt_FunctionInfo_FunctionInfo_MAX;
  static constexpr int FunctionInfo_ARRAYSIZE =
    Prompt_FunctionInfo_FunctionInfo_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  FunctionInfo_descriptor() {
    return Prompt_FunctionInfo_descriptor();
  }
  template<typename T>
  static inline const std::string& FunctionInfo_Name(T enum_t_value) {
    static_assert(::std::is_same<T, FunctionInfo>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function FunctionInfo_Name.");
    return Prompt_FunctionInfo_Name(enum_t_value);
  }
  static inline bool FunctionInfo_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      FunctionInfo* value) {
    return Prompt_FunctionInfo_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kPromptMessagesFieldNumber = 1,
    kFunctionInfoFieldNumber = 2,
  };
  // repeated .nio.ad.messages.PromptMessage prompt_messages = 1;
  int prompt_messages_size() const;
  private:
  int _internal_prompt_messages_size() const;
  public:
  void clear_prompt_messages();
  ::nio::ad::messages::PromptMessage* mutable_prompt_messages(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::PromptMessage >*
      mutable_prompt_messages();
  private:
  const ::nio::ad::messages::PromptMessage& _internal_prompt_messages(int index) const;
  ::nio::ad::messages::PromptMessage* _internal_add_prompt_messages();
  public:
  const ::nio::ad::messages::PromptMessage& prompt_messages(int index) const;
  ::nio::ad::messages::PromptMessage* add_prompt_messages();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::PromptMessage >&
      prompt_messages() const;

  // optional .nio.ad.messages.Prompt.FunctionInfo function_info = 2;
  bool has_function_info() const;
  private:
  bool _internal_has_function_info() const;
  public:
  void clear_function_info();
  ::nio::ad::messages::Prompt_FunctionInfo function_info() const;
  void set_function_info(::nio::ad::messages::Prompt_FunctionInfo value);
  private:
  ::nio::ad::messages::Prompt_FunctionInfo _internal_function_info() const;
  void _internal_set_function_info(::nio::ad::messages::Prompt_FunctionInfo value);
  public:

  // @@protoc_insertion_point(class_scope:nio.ad.messages.Prompt)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::PromptMessage > prompt_messages_;
  int function_info_;
  friend struct ::TableStruct_common_2fpnc_2fdas_5fagent_5frequest_2eproto;
};
// -------------------------------------------------------------------

class DasAgentRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nio.ad.messages.DasAgentRequest) */ {
 public:
  inline DasAgentRequest() : DasAgentRequest(nullptr) {}
  ~DasAgentRequest() override;
  explicit constexpr DasAgentRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DasAgentRequest(const DasAgentRequest& from);
  DasAgentRequest(DasAgentRequest&& from) noexcept
    : DasAgentRequest() {
    *this = ::std::move(from);
  }

  inline DasAgentRequest& operator=(const DasAgentRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DasAgentRequest& operator=(DasAgentRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DasAgentRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const DasAgentRequest* internal_default_instance() {
    return reinterpret_cast<const DasAgentRequest*>(
               &_DasAgentRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(DasAgentRequest& a, DasAgentRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(DasAgentRequest* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DasAgentRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DasAgentRequest* New() const final {
    return new DasAgentRequest();
  }

  DasAgentRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DasAgentRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DasAgentRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const DasAgentRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DasAgentRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nio.ad.messages.DasAgentRequest";
  }
  protected:
  explicit DasAgentRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPromptsFieldNumber = 1,
    kPublisherIdFieldNumber = 536870909,
    kSensorOriginalTsFieldNumber = 536870906,
    kRequestSeqFieldNumber = 2,
    kTimestampFieldNumber = 536870905,
    kPublishPtpTsFieldNumber = 536870907,
    kCounterFieldNumber = 536870910,
    kPublishTsFieldNumber = 536870911,
  };
  // repeated .nio.ad.messages.Prompt prompts = 1;
  int prompts_size() const;
  private:
  int _internal_prompts_size() const;
  public:
  void clear_prompts();
  ::nio::ad::messages::Prompt* mutable_prompts(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Prompt >*
      mutable_prompts();
  private:
  const ::nio::ad::messages::Prompt& _internal_prompts(int index) const;
  ::nio::ad::messages::Prompt* _internal_add_prompts();
  public:
  const ::nio::ad::messages::Prompt& prompts(int index) const;
  ::nio::ad::messages::Prompt* add_prompts();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Prompt >&
      prompts() const;

  // optional string publisher_id = 536870909;
  bool has_publisher_id() const;
  private:
  bool _internal_has_publisher_id() const;
  public:
  void clear_publisher_id();
  const std::string& publisher_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_publisher_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_publisher_id();
  PROTOBUF_MUST_USE_RESULT std::string* release_publisher_id();
  void set_allocated_publisher_id(std::string* publisher_id);
  private:
  const std::string& _internal_publisher_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_publisher_id(const std::string& value);
  std::string* _internal_mutable_publisher_id();
  public:

  // optional .nio.ad.messages.SensorTSHeader sensor_original_ts = 536870906;
  bool has_sensor_original_ts() const;
  private:
  bool _internal_has_sensor_original_ts() const;
  public:
  void clear_sensor_original_ts();
  const ::nio::ad::messages::SensorTSHeader& sensor_original_ts() const;
  PROTOBUF_MUST_USE_RESULT ::nio::ad::messages::SensorTSHeader* release_sensor_original_ts();
  ::nio::ad::messages::SensorTSHeader* mutable_sensor_original_ts();
  void set_allocated_sensor_original_ts(::nio::ad::messages::SensorTSHeader* sensor_original_ts);
  private:
  const ::nio::ad::messages::SensorTSHeader& _internal_sensor_original_ts() const;
  ::nio::ad::messages::SensorTSHeader* _internal_mutable_sensor_original_ts();
  public:
  void unsafe_arena_set_allocated_sensor_original_ts(
      ::nio::ad::messages::SensorTSHeader* sensor_original_ts);
  ::nio::ad::messages::SensorTSHeader* unsafe_arena_release_sensor_original_ts();

  // optional uint64 request_seq = 2;
  bool has_request_seq() const;
  private:
  bool _internal_has_request_seq() const;
  public:
  void clear_request_seq();
  ::PROTOBUF_NAMESPACE_ID::uint64 request_seq() const;
  void set_request_seq(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_request_seq() const;
  void _internal_set_request_seq(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 timestamp = 536870905;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 publish_ptp_ts = 536870907;
  bool has_publish_ptp_ts() const;
  private:
  bool _internal_has_publish_ptp_ts() const;
  public:
  void clear_publish_ptp_ts();
  ::PROTOBUF_NAMESPACE_ID::uint64 publish_ptp_ts() const;
  void set_publish_ptp_ts(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_publish_ptp_ts() const;
  void _internal_set_publish_ptp_ts(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 counter = 536870910;
  bool has_counter() const;
  private:
  bool _internal_has_counter() const;
  public:
  void clear_counter();
  ::PROTOBUF_NAMESPACE_ID::uint64 counter() const;
  void set_counter(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_counter() const;
  void _internal_set_counter(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 publish_ts = 536870911;
  bool has_publish_ts() const;
  private:
  bool _internal_has_publish_ts() const;
  public:
  void clear_publish_ts();
  ::PROTOBUF_NAMESPACE_ID::uint64 publish_ts() const;
  void set_publish_ts(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_publish_ts() const;
  void _internal_set_publish_ts(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:nio.ad.messages.DasAgentRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Prompt > prompts_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr publisher_id_;
  ::nio::ad::messages::SensorTSHeader* sensor_original_ts_;
  ::PROTOBUF_NAMESPACE_ID::uint64 request_seq_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_;
  ::PROTOBUF_NAMESPACE_ID::uint64 publish_ptp_ts_;
  ::PROTOBUF_NAMESPACE_ID::uint64 counter_;
  ::PROTOBUF_NAMESPACE_ID::uint64 publish_ts_;
  friend struct ::TableStruct_common_2fpnc_2fdas_5fagent_5frequest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Content

// optional .nio.ad.messages.Content.Type type = 1;
inline bool Content::_internal_has_type() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Content::has_type() const {
  return _internal_has_type();
}
inline void Content::clear_type() {
  type_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::nio::ad::messages::Content_Type Content::_internal_type() const {
  return static_cast< ::nio::ad::messages::Content_Type >(type_);
}
inline ::nio::ad::messages::Content_Type Content::type() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.Content.type)
  return _internal_type();
}
inline void Content::_internal_set_type(::nio::ad::messages::Content_Type value) {
  assert(::nio::ad::messages::Content_Type_IsValid(value));
  _has_bits_[0] |= 0x00000010u;
  type_ = value;
}
inline void Content::set_type(::nio::ad::messages::Content_Type value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.Content.type)
}

// optional string text = 2;
inline bool Content::_internal_has_text() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Content::has_text() const {
  return _internal_has_text();
}
inline void Content::clear_text() {
  text_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Content::text() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.Content.text)
  return _internal_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Content::set_text(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 text_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nio.ad.messages.Content.text)
}
inline std::string* Content::mutable_text() {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.Content.text)
  return _s;
}
inline const std::string& Content::_internal_text() const {
  return text_.Get();
}
inline void Content::_internal_set_text(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  text_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Content::_internal_mutable_text() {
  _has_bits_[0] |= 0x00000001u;
  return text_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Content::release_text() {
  // @@protoc_insertion_point(field_release:nio.ad.messages.Content.text)
  if (!_internal_has_text()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return text_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Content::set_allocated_text(std::string* text) {
  if (text != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  text_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), text,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:nio.ad.messages.Content.text)
}

// optional string image_url = 3;
inline bool Content::_internal_has_image_url() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Content::has_image_url() const {
  return _internal_has_image_url();
}
inline void Content::clear_image_url() {
  image_url_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Content::image_url() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.Content.image_url)
  return _internal_image_url();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Content::set_image_url(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 image_url_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nio.ad.messages.Content.image_url)
}
inline std::string* Content::mutable_image_url() {
  std::string* _s = _internal_mutable_image_url();
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.Content.image_url)
  return _s;
}
inline const std::string& Content::_internal_image_url() const {
  return image_url_.Get();
}
inline void Content::_internal_set_image_url(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  image_url_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Content::_internal_mutable_image_url() {
  _has_bits_[0] |= 0x00000002u;
  return image_url_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Content::release_image_url() {
  // @@protoc_insertion_point(field_release:nio.ad.messages.Content.image_url)
  if (!_internal_has_image_url()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return image_url_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Content::set_allocated_image_url(std::string* image_url) {
  if (image_url != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  image_url_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), image_url,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:nio.ad.messages.Content.image_url)
}

// optional string image_b64string = 4;
inline bool Content::_internal_has_image_b64string() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Content::has_image_b64string() const {
  return _internal_has_image_b64string();
}
inline void Content::clear_image_b64string() {
  image_b64string_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Content::image_b64string() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.Content.image_b64string)
  return _internal_image_b64string();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Content::set_image_b64string(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000004u;
 image_b64string_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nio.ad.messages.Content.image_b64string)
}
inline std::string* Content::mutable_image_b64string() {
  std::string* _s = _internal_mutable_image_b64string();
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.Content.image_b64string)
  return _s;
}
inline const std::string& Content::_internal_image_b64string() const {
  return image_b64string_.Get();
}
inline void Content::_internal_set_image_b64string(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  image_b64string_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Content::_internal_mutable_image_b64string() {
  _has_bits_[0] |= 0x00000004u;
  return image_b64string_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Content::release_image_b64string() {
  // @@protoc_insertion_point(field_release:nio.ad.messages.Content.image_b64string)
  if (!_internal_has_image_b64string()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return image_b64string_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Content::set_allocated_image_b64string(std::string* image_b64string) {
  if (image_b64string != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  image_b64string_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), image_b64string,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:nio.ad.messages.Content.image_b64string)
}

// optional uint64 image_timestamp = 5;
inline bool Content::_internal_has_image_timestamp() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Content::has_image_timestamp() const {
  return _internal_has_image_timestamp();
}
inline void Content::clear_image_timestamp() {
  image_timestamp_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Content::_internal_image_timestamp() const {
  return image_timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Content::image_timestamp() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.Content.image_timestamp)
  return _internal_image_timestamp();
}
inline void Content::_internal_set_image_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000008u;
  image_timestamp_ = value;
}
inline void Content::set_image_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_image_timestamp(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.Content.image_timestamp)
}

// -------------------------------------------------------------------

// PromptMessage

// optional .nio.ad.messages.PromptMessage.Role role = 1;
inline bool PromptMessage::_internal_has_role() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PromptMessage::has_role() const {
  return _internal_has_role();
}
inline void PromptMessage::clear_role() {
  role_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::nio::ad::messages::PromptMessage_Role PromptMessage::_internal_role() const {
  return static_cast< ::nio::ad::messages::PromptMessage_Role >(role_);
}
inline ::nio::ad::messages::PromptMessage_Role PromptMessage::role() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.PromptMessage.role)
  return _internal_role();
}
inline void PromptMessage::_internal_set_role(::nio::ad::messages::PromptMessage_Role value) {
  assert(::nio::ad::messages::PromptMessage_Role_IsValid(value));
  _has_bits_[0] |= 0x00000001u;
  role_ = value;
}
inline void PromptMessage::set_role(::nio::ad::messages::PromptMessage_Role value) {
  _internal_set_role(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.PromptMessage.role)
}

// repeated .nio.ad.messages.Content contents = 2;
inline int PromptMessage::_internal_contents_size() const {
  return contents_.size();
}
inline int PromptMessage::contents_size() const {
  return _internal_contents_size();
}
inline void PromptMessage::clear_contents() {
  contents_.Clear();
}
inline ::nio::ad::messages::Content* PromptMessage::mutable_contents(int index) {
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.PromptMessage.contents)
  return contents_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Content >*
PromptMessage::mutable_contents() {
  // @@protoc_insertion_point(field_mutable_list:nio.ad.messages.PromptMessage.contents)
  return &contents_;
}
inline const ::nio::ad::messages::Content& PromptMessage::_internal_contents(int index) const {
  return contents_.Get(index);
}
inline const ::nio::ad::messages::Content& PromptMessage::contents(int index) const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.PromptMessage.contents)
  return _internal_contents(index);
}
inline ::nio::ad::messages::Content* PromptMessage::_internal_add_contents() {
  return contents_.Add();
}
inline ::nio::ad::messages::Content* PromptMessage::add_contents() {
  ::nio::ad::messages::Content* _add = _internal_add_contents();
  // @@protoc_insertion_point(field_add:nio.ad.messages.PromptMessage.contents)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Content >&
PromptMessage::contents() const {
  // @@protoc_insertion_point(field_list:nio.ad.messages.PromptMessage.contents)
  return contents_;
}

// -------------------------------------------------------------------

// Prompt

// repeated .nio.ad.messages.PromptMessage prompt_messages = 1;
inline int Prompt::_internal_prompt_messages_size() const {
  return prompt_messages_.size();
}
inline int Prompt::prompt_messages_size() const {
  return _internal_prompt_messages_size();
}
inline void Prompt::clear_prompt_messages() {
  prompt_messages_.Clear();
}
inline ::nio::ad::messages::PromptMessage* Prompt::mutable_prompt_messages(int index) {
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.Prompt.prompt_messages)
  return prompt_messages_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::PromptMessage >*
Prompt::mutable_prompt_messages() {
  // @@protoc_insertion_point(field_mutable_list:nio.ad.messages.Prompt.prompt_messages)
  return &prompt_messages_;
}
inline const ::nio::ad::messages::PromptMessage& Prompt::_internal_prompt_messages(int index) const {
  return prompt_messages_.Get(index);
}
inline const ::nio::ad::messages::PromptMessage& Prompt::prompt_messages(int index) const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.Prompt.prompt_messages)
  return _internal_prompt_messages(index);
}
inline ::nio::ad::messages::PromptMessage* Prompt::_internal_add_prompt_messages() {
  return prompt_messages_.Add();
}
inline ::nio::ad::messages::PromptMessage* Prompt::add_prompt_messages() {
  ::nio::ad::messages::PromptMessage* _add = _internal_add_prompt_messages();
  // @@protoc_insertion_point(field_add:nio.ad.messages.Prompt.prompt_messages)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::PromptMessage >&
Prompt::prompt_messages() const {
  // @@protoc_insertion_point(field_list:nio.ad.messages.Prompt.prompt_messages)
  return prompt_messages_;
}

// optional .nio.ad.messages.Prompt.FunctionInfo function_info = 2;
inline bool Prompt::_internal_has_function_info() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Prompt::has_function_info() const {
  return _internal_has_function_info();
}
inline void Prompt::clear_function_info() {
  function_info_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::nio::ad::messages::Prompt_FunctionInfo Prompt::_internal_function_info() const {
  return static_cast< ::nio::ad::messages::Prompt_FunctionInfo >(function_info_);
}
inline ::nio::ad::messages::Prompt_FunctionInfo Prompt::function_info() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.Prompt.function_info)
  return _internal_function_info();
}
inline void Prompt::_internal_set_function_info(::nio::ad::messages::Prompt_FunctionInfo value) {
  assert(::nio::ad::messages::Prompt_FunctionInfo_IsValid(value));
  _has_bits_[0] |= 0x00000001u;
  function_info_ = value;
}
inline void Prompt::set_function_info(::nio::ad::messages::Prompt_FunctionInfo value) {
  _internal_set_function_info(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.Prompt.function_info)
}

// -------------------------------------------------------------------

// DasAgentRequest

// repeated .nio.ad.messages.Prompt prompts = 1;
inline int DasAgentRequest::_internal_prompts_size() const {
  return prompts_.size();
}
inline int DasAgentRequest::prompts_size() const {
  return _internal_prompts_size();
}
inline void DasAgentRequest::clear_prompts() {
  prompts_.Clear();
}
inline ::nio::ad::messages::Prompt* DasAgentRequest::mutable_prompts(int index) {
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.DasAgentRequest.prompts)
  return prompts_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Prompt >*
DasAgentRequest::mutable_prompts() {
  // @@protoc_insertion_point(field_mutable_list:nio.ad.messages.DasAgentRequest.prompts)
  return &prompts_;
}
inline const ::nio::ad::messages::Prompt& DasAgentRequest::_internal_prompts(int index) const {
  return prompts_.Get(index);
}
inline const ::nio::ad::messages::Prompt& DasAgentRequest::prompts(int index) const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.DasAgentRequest.prompts)
  return _internal_prompts(index);
}
inline ::nio::ad::messages::Prompt* DasAgentRequest::_internal_add_prompts() {
  return prompts_.Add();
}
inline ::nio::ad::messages::Prompt* DasAgentRequest::add_prompts() {
  ::nio::ad::messages::Prompt* _add = _internal_add_prompts();
  // @@protoc_insertion_point(field_add:nio.ad.messages.DasAgentRequest.prompts)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Prompt >&
DasAgentRequest::prompts() const {
  // @@protoc_insertion_point(field_list:nio.ad.messages.DasAgentRequest.prompts)
  return prompts_;
}

// optional uint64 request_seq = 2;
inline bool DasAgentRequest::_internal_has_request_seq() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool DasAgentRequest::has_request_seq() const {
  return _internal_has_request_seq();
}
inline void DasAgentRequest::clear_request_seq() {
  request_seq_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 DasAgentRequest::_internal_request_seq() const {
  return request_seq_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 DasAgentRequest::request_seq() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.DasAgentRequest.request_seq)
  return _internal_request_seq();
}
inline void DasAgentRequest::_internal_set_request_seq(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000004u;
  request_seq_ = value;
}
inline void DasAgentRequest::set_request_seq(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_request_seq(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.DasAgentRequest.request_seq)
}

// optional uint64 timestamp = 536870905;
inline bool DasAgentRequest::_internal_has_timestamp() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool DasAgentRequest::has_timestamp() const {
  return _internal_has_timestamp();
}
inline void DasAgentRequest::clear_timestamp() {
  timestamp_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 DasAgentRequest::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 DasAgentRequest::timestamp() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.DasAgentRequest.timestamp)
  return _internal_timestamp();
}
inline void DasAgentRequest::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000008u;
  timestamp_ = value;
}
inline void DasAgentRequest::set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.DasAgentRequest.timestamp)
}

// optional .nio.ad.messages.SensorTSHeader sensor_original_ts = 536870906;
inline bool DasAgentRequest::_internal_has_sensor_original_ts() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || sensor_original_ts_ != nullptr);
  return value;
}
inline bool DasAgentRequest::has_sensor_original_ts() const {
  return _internal_has_sensor_original_ts();
}
inline const ::nio::ad::messages::SensorTSHeader& DasAgentRequest::_internal_sensor_original_ts() const {
  const ::nio::ad::messages::SensorTSHeader* p = sensor_original_ts_;
  return p != nullptr ? *p : reinterpret_cast<const ::nio::ad::messages::SensorTSHeader&>(
      ::nio::ad::messages::_SensorTSHeader_default_instance_);
}
inline const ::nio::ad::messages::SensorTSHeader& DasAgentRequest::sensor_original_ts() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.DasAgentRequest.sensor_original_ts)
  return _internal_sensor_original_ts();
}
inline void DasAgentRequest::unsafe_arena_set_allocated_sensor_original_ts(
    ::nio::ad::messages::SensorTSHeader* sensor_original_ts) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(sensor_original_ts_);
  }
  sensor_original_ts_ = sensor_original_ts;
  if (sensor_original_ts) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:nio.ad.messages.DasAgentRequest.sensor_original_ts)
}
inline ::nio::ad::messages::SensorTSHeader* DasAgentRequest::release_sensor_original_ts() {
  _has_bits_[0] &= ~0x00000002u;
  ::nio::ad::messages::SensorTSHeader* temp = sensor_original_ts_;
  sensor_original_ts_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::nio::ad::messages::SensorTSHeader* DasAgentRequest::unsafe_arena_release_sensor_original_ts() {
  // @@protoc_insertion_point(field_release:nio.ad.messages.DasAgentRequest.sensor_original_ts)
  _has_bits_[0] &= ~0x00000002u;
  ::nio::ad::messages::SensorTSHeader* temp = sensor_original_ts_;
  sensor_original_ts_ = nullptr;
  return temp;
}
inline ::nio::ad::messages::SensorTSHeader* DasAgentRequest::_internal_mutable_sensor_original_ts() {
  _has_bits_[0] |= 0x00000002u;
  if (sensor_original_ts_ == nullptr) {
    auto* p = CreateMaybeMessage<::nio::ad::messages::SensorTSHeader>(GetArenaForAllocation());
    sensor_original_ts_ = p;
  }
  return sensor_original_ts_;
}
inline ::nio::ad::messages::SensorTSHeader* DasAgentRequest::mutable_sensor_original_ts() {
  ::nio::ad::messages::SensorTSHeader* _msg = _internal_mutable_sensor_original_ts();
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.DasAgentRequest.sensor_original_ts)
  return _msg;
}
inline void DasAgentRequest::set_allocated_sensor_original_ts(::nio::ad::messages::SensorTSHeader* sensor_original_ts) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(sensor_original_ts_);
  }
  if (sensor_original_ts) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(sensor_original_ts));
    if (message_arena != submessage_arena) {
      sensor_original_ts = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, sensor_original_ts, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  sensor_original_ts_ = sensor_original_ts;
  // @@protoc_insertion_point(field_set_allocated:nio.ad.messages.DasAgentRequest.sensor_original_ts)
}

// optional uint64 publish_ptp_ts = 536870907;
inline bool DasAgentRequest::_internal_has_publish_ptp_ts() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool DasAgentRequest::has_publish_ptp_ts() const {
  return _internal_has_publish_ptp_ts();
}
inline void DasAgentRequest::clear_publish_ptp_ts() {
  publish_ptp_ts_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 DasAgentRequest::_internal_publish_ptp_ts() const {
  return publish_ptp_ts_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 DasAgentRequest::publish_ptp_ts() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.DasAgentRequest.publish_ptp_ts)
  return _internal_publish_ptp_ts();
}
inline void DasAgentRequest::_internal_set_publish_ptp_ts(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000010u;
  publish_ptp_ts_ = value;
}
inline void DasAgentRequest::set_publish_ptp_ts(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_publish_ptp_ts(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.DasAgentRequest.publish_ptp_ts)
}

// optional string publisher_id = 536870909;
inline bool DasAgentRequest::_internal_has_publisher_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool DasAgentRequest::has_publisher_id() const {
  return _internal_has_publisher_id();
}
inline void DasAgentRequest::clear_publisher_id() {
  publisher_id_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& DasAgentRequest::publisher_id() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.DasAgentRequest.publisher_id)
  return _internal_publisher_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DasAgentRequest::set_publisher_id(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 publisher_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nio.ad.messages.DasAgentRequest.publisher_id)
}
inline std::string* DasAgentRequest::mutable_publisher_id() {
  std::string* _s = _internal_mutable_publisher_id();
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.DasAgentRequest.publisher_id)
  return _s;
}
inline const std::string& DasAgentRequest::_internal_publisher_id() const {
  return publisher_id_.Get();
}
inline void DasAgentRequest::_internal_set_publisher_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  publisher_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DasAgentRequest::_internal_mutable_publisher_id() {
  _has_bits_[0] |= 0x00000001u;
  return publisher_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DasAgentRequest::release_publisher_id() {
  // @@protoc_insertion_point(field_release:nio.ad.messages.DasAgentRequest.publisher_id)
  if (!_internal_has_publisher_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return publisher_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DasAgentRequest::set_allocated_publisher_id(std::string* publisher_id) {
  if (publisher_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  publisher_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), publisher_id,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:nio.ad.messages.DasAgentRequest.publisher_id)
}

// optional uint64 counter = 536870910;
inline bool DasAgentRequest::_internal_has_counter() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool DasAgentRequest::has_counter() const {
  return _internal_has_counter();
}
inline void DasAgentRequest::clear_counter() {
  counter_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 DasAgentRequest::_internal_counter() const {
  return counter_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 DasAgentRequest::counter() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.DasAgentRequest.counter)
  return _internal_counter();
}
inline void DasAgentRequest::_internal_set_counter(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000020u;
  counter_ = value;
}
inline void DasAgentRequest::set_counter(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_counter(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.DasAgentRequest.counter)
}

// optional uint64 publish_ts = 536870911;
inline bool DasAgentRequest::_internal_has_publish_ts() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool DasAgentRequest::has_publish_ts() const {
  return _internal_has_publish_ts();
}
inline void DasAgentRequest::clear_publish_ts() {
  publish_ts_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000040u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 DasAgentRequest::_internal_publish_ts() const {
  return publish_ts_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 DasAgentRequest::publish_ts() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.DasAgentRequest.publish_ts)
  return _internal_publish_ts();
}
inline void DasAgentRequest::_internal_set_publish_ts(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000040u;
  publish_ts_ = value;
}
inline void DasAgentRequest::set_publish_ts(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_publish_ts(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.DasAgentRequest.publish_ts)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace ad
}  // namespace nio

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::nio::ad::messages::Content_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::nio::ad::messages::Content_Type>() {
  return ::nio::ad::messages::Content_Type_descriptor();
}
template <> struct is_proto_enum< ::nio::ad::messages::PromptMessage_Role> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::nio::ad::messages::PromptMessage_Role>() {
  return ::nio::ad::messages::PromptMessage_Role_descriptor();
}
template <> struct is_proto_enum< ::nio::ad::messages::Prompt_FunctionInfo> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::nio::ad::messages::Prompt_FunctionInfo>() {
  return ::nio::ad::messages::Prompt_FunctionInfo_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_common_2fpnc_2fdas_5fagent_5frequest_2eproto
