# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/perception/e2e_waypoint.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.perf import sensor_ts_header_pb2 as common_dot_perf_dot_sensor__ts__header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/perception/e2e_waypoint.proto',
  package='nio.ad.messages',
  syntax='proto2',
  serialized_options=b'\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$common/perception/e2e_waypoint.proto\x12\x0fnio.ad.messages\x1a\"common/perf/sensor_ts_header.proto\"\xb8\x02\n\rEgoTrajectory\x12\x1a\n\x12\x45go_Waypoint_Count\x18\x01 \x01(\x05\x12\x30\n\rEgo_Waypoints\x18\x02 \x03(\x0b\x32\x19.nio.ad.messages.Waypoint\x12\"\n\x1a\x45go_Trajectory_Probability\x18\x03 \x01(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x12?\n\x12sensor_original_ts\x18\xfa\xff\xff\xff\x01 \x01(\x0b\x32\x1f.nio.ad.messages.SensorTSHeader\x12\x1a\n\x0epublish_ptp_ts\x18\xfb\xff\xff\xff\x01 \x01(\x04\x12\x18\n\x0cpublisher_id\x18\xfd\xff\xff\xff\x01 \x01(\t\x12\x13\n\x07\x63ounter\x18\xfe\xff\xff\xff\x01 \x01(\x04\x12\x16\n\npublish_ts\x18\xff\xff\xff\xff\x01 \x01(\x04\"^\n\x08Waypoint\x12\x19\n\x11\x45go_Long_Position\x18\x01 \x01(\x02\x12\x18\n\x10\x45go_Lat_Position\x18\x02 \x01(\x02\x12\x1d\n\x15\x45go_Vertical_Position\x18\x03 \x01(\x02\x42\x03\xf8\x01\x01'
  ,
  dependencies=[common_dot_perf_dot_sensor__ts__header__pb2.DESCRIPTOR,])




_EGOTRAJECTORY = _descriptor.Descriptor(
  name='EgoTrajectory',
  full_name='nio.ad.messages.EgoTrajectory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Ego_Waypoint_Count', full_name='nio.ad.messages.EgoTrajectory.Ego_Waypoint_Count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Ego_Waypoints', full_name='nio.ad.messages.EgoTrajectory.Ego_Waypoints', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Ego_Trajectory_Probability', full_name='nio.ad.messages.EgoTrajectory.Ego_Trajectory_Probability', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='nio.ad.messages.EgoTrajectory.timestamp', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_original_ts', full_name='nio.ad.messages.EgoTrajectory.sensor_original_ts', index=4,
      number=536870906, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='publish_ptp_ts', full_name='nio.ad.messages.EgoTrajectory.publish_ptp_ts', index=5,
      number=536870907, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='publisher_id', full_name='nio.ad.messages.EgoTrajectory.publisher_id', index=6,
      number=536870909, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='counter', full_name='nio.ad.messages.EgoTrajectory.counter', index=7,
      number=536870910, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='publish_ts', full_name='nio.ad.messages.EgoTrajectory.publish_ts', index=8,
      number=536870911, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=406,
)


_WAYPOINT = _descriptor.Descriptor(
  name='Waypoint',
  full_name='nio.ad.messages.Waypoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Ego_Long_Position', full_name='nio.ad.messages.Waypoint.Ego_Long_Position', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Ego_Lat_Position', full_name='nio.ad.messages.Waypoint.Ego_Lat_Position', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Ego_Vertical_Position', full_name='nio.ad.messages.Waypoint.Ego_Vertical_Position', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=502,
)

_EGOTRAJECTORY.fields_by_name['Ego_Waypoints'].message_type = _WAYPOINT
_EGOTRAJECTORY.fields_by_name['sensor_original_ts'].message_type = common_dot_perf_dot_sensor__ts__header__pb2._SENSORTSHEADER
DESCRIPTOR.message_types_by_name['EgoTrajectory'] = _EGOTRAJECTORY
DESCRIPTOR.message_types_by_name['Waypoint'] = _WAYPOINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EgoTrajectory = _reflection.GeneratedProtocolMessageType('EgoTrajectory', (_message.Message,), {
  'DESCRIPTOR' : _EGOTRAJECTORY,
  '__module__' : 'common.perception.e2e_waypoint_pb2'
  # @@protoc_insertion_point(class_scope:nio.ad.messages.EgoTrajectory)
  })
_sym_db.RegisterMessage(EgoTrajectory)

Waypoint = _reflection.GeneratedProtocolMessageType('Waypoint', (_message.Message,), {
  'DESCRIPTOR' : _WAYPOINT,
  '__module__' : 'common.perception.e2e_waypoint_pb2'
  # @@protoc_insertion_point(class_scope:nio.ad.messages.Waypoint)
  })
_sym_db.RegisterMessage(Waypoint)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
