syntax = "proto2";

option cc_enable_arenas = true;
package nio.ad.messages;
import "common/perf/sensor_ts_header.proto";

//[ADR-19631] parking new cru config
message ParkingParamConfig {

  optional bool super_rpa_in_enable           = 1; // super rpa func switch, default : false
  optional float speed_control_factor         = 2; //default : 1,  rpa func add value check [0.2, 2] is normal
  optional bool hero_button_sapa_enable       = 3; //Herobutton一键激活SAPA开关, default: TRUE, TRUE: 用户可以正常使用HeroButton激活SAPA, FALSE: 用户 无法使用HeroButton激活SAPA
  optional bool memory_available_setting      = 4; //存储记忆设置项, default: TRUE, TRUE: Available, FALSE: Not available
  optional uint32 trajectory_recording_reset_type = 5; //记忆轨迹腾挪偏差清除阈值, default: 3, 取值范围: 0~3
  optional uint32 obstacle_nudge_type         = 6; //全局绕行开关, default: 5, 取值范围: 0~5
  optional bool vru_nudge_type                = 7; //VRU绕行开关, default: TRUE, TRUE: 允许VRU绕行, FALSE: 不允许VRU绕行
  optional bool gear_change_nudge_type        = 8; //换挡绕行开关, default: TRUE, TRUE: 允许换挡绕行, FALSE: 不允许换挡绕行
  optional bool reverse_assist_enable         = 9; //一键返回功能开关, default: TRUE, TRUE: 用户可以正常使用一键返回功能, FALSE: 用户无法使用一键返回功能
  optional bool custom_parking_enable         = 10; //拖框车位功能开关, default: TRUE, TRUE: 用户可以正常使用随心泊功能, FALSE: 用户 无法使用随心停功能
  optional uint32 parking_trajectory_selection_mode = 11; //泊车轨迹筛选模式, default: 0, 取值范围0~2. 0: fusion mode, 1: rule only mode, 2: e2e only mode
  optional bool p2p_low_speed_enable          = 12; //p2p功能开关,  default: FALSE, TRUE: 用户可以P2P功能, FALSE: 用户 无法使用P2P功能
  optional bool vln_low_speed_enable          = 13; //vln功能开关, default: FALSE, TRUE: 用户可以VLN功能, FALSE: 用户 无法使用VLN功能

  optional uint64 timestamp = 536870905; // ptp timestamp, nanosecond，used for data bundle readin
  optional SensorTSHeader sensor_original_ts = 536870906;   // sensor original ts
  optional uint64 publish_ptp_ts   = 536870907;   //publish ptp timestamp, uint in nanosec
  optional string publisher_id     = 536870909;   // uuid of the publisher
  optional uint64 counter           = 536870910;  // message counter
  optional uint64 publish_ts      = 536870911;  // publish timestamp; unit : nanosecond

}