// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/cloud_config/adms_param_config.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_common_2fcloud_5fconfig_2fadms_5fparam_5fconfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_common_2fcloud_5fconfig_2fadms_5fparam_5fconfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3018000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3018001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "common/perf/sensor_ts_header.pb.h"
#include "common/cloud_config/adms_sensetime_config.pb.h"
#include "common/cloud_config/adms_operation_config.pb.h"
#include "common/cloud_config/adms_minieye_config.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_common_2fcloud_5fconfig_2fadms_5fparam_5fconfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_common_2fcloud_5fconfig_2fadms_5fparam_5fconfig_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_common_2fcloud_5fconfig_2fadms_5fparam_5fconfig_2eproto;
namespace nio {
namespace ad {
namespace messages {
class ADMSConfig;
struct ADMSConfigDefaultTypeInternal;
extern ADMSConfigDefaultTypeInternal _ADMSConfig_default_instance_;
}  // namespace messages
}  // namespace ad
}  // namespace nio
PROTOBUF_NAMESPACE_OPEN
template<> ::nio::ad::messages::ADMSConfig* Arena::CreateMaybeMessage<::nio::ad::messages::ADMSConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace nio {
namespace ad {
namespace messages {

// ===================================================================

class ADMSConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nio.ad.messages.ADMSConfig) */ {
 public:
  inline ADMSConfig() : ADMSConfig(nullptr) {}
  ~ADMSConfig() override;
  explicit constexpr ADMSConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ADMSConfig(const ADMSConfig& from);
  ADMSConfig(ADMSConfig&& from) noexcept
    : ADMSConfig() {
    *this = ::std::move(from);
  }

  inline ADMSConfig& operator=(const ADMSConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline ADMSConfig& operator=(ADMSConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ADMSConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const ADMSConfig* internal_default_instance() {
    return reinterpret_cast<const ADMSConfig*>(
               &_ADMSConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ADMSConfig& a, ADMSConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(ADMSConfig* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ADMSConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ADMSConfig* New() const final {
    return new ADMSConfig();
  }

  ADMSConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ADMSConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ADMSConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ADMSConfig& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ADMSConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nio.ad.messages.ADMSConfig";
  }
  protected:
  explicit ADMSConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPublisherIdFieldNumber = 536870909,
    kSensetimeConfigFieldNumber = 1,
    kMinieyeConfigFieldNumber = 3,
    kOperationConfigFieldNumber = 5,
    kSensorOriginalTsFieldNumber = 536870906,
    kSensetimeConfigUpdateFieldNumber = 2,
    kMinieyeConfigUpdateFieldNumber = 4,
    kOperationConfigUpdateFieldNumber = 6,
    kTimestampFieldNumber = 536870905,
    kPublishPtpTsFieldNumber = 536870907,
    kCounterFieldNumber = 536870910,
    kPublishTsFieldNumber = 536870911,
  };
  // optional string publisher_id = 536870909;
  bool has_publisher_id() const;
  private:
  bool _internal_has_publisher_id() const;
  public:
  void clear_publisher_id();
  const std::string& publisher_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_publisher_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_publisher_id();
  PROTOBUF_MUST_USE_RESULT std::string* release_publisher_id();
  void set_allocated_publisher_id(std::string* publisher_id);
  private:
  const std::string& _internal_publisher_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_publisher_id(const std::string& value);
  std::string* _internal_mutable_publisher_id();
  public:

  // optional .nio.ad.messages.ADMSSenseTimeConfig sensetime_config = 1;
  bool has_sensetime_config() const;
  private:
  bool _internal_has_sensetime_config() const;
  public:
  void clear_sensetime_config();
  const ::nio::ad::messages::ADMSSenseTimeConfig& sensetime_config() const;
  PROTOBUF_MUST_USE_RESULT ::nio::ad::messages::ADMSSenseTimeConfig* release_sensetime_config();
  ::nio::ad::messages::ADMSSenseTimeConfig* mutable_sensetime_config();
  void set_allocated_sensetime_config(::nio::ad::messages::ADMSSenseTimeConfig* sensetime_config);
  private:
  const ::nio::ad::messages::ADMSSenseTimeConfig& _internal_sensetime_config() const;
  ::nio::ad::messages::ADMSSenseTimeConfig* _internal_mutable_sensetime_config();
  public:
  void unsafe_arena_set_allocated_sensetime_config(
      ::nio::ad::messages::ADMSSenseTimeConfig* sensetime_config);
  ::nio::ad::messages::ADMSSenseTimeConfig* unsafe_arena_release_sensetime_config();

  // optional .nio.ad.messages.ADMSMinieyeConfig minieye_config = 3;
  bool has_minieye_config() const;
  private:
  bool _internal_has_minieye_config() const;
  public:
  void clear_minieye_config();
  const ::nio::ad::messages::ADMSMinieyeConfig& minieye_config() const;
  PROTOBUF_MUST_USE_RESULT ::nio::ad::messages::ADMSMinieyeConfig* release_minieye_config();
  ::nio::ad::messages::ADMSMinieyeConfig* mutable_minieye_config();
  void set_allocated_minieye_config(::nio::ad::messages::ADMSMinieyeConfig* minieye_config);
  private:
  const ::nio::ad::messages::ADMSMinieyeConfig& _internal_minieye_config() const;
  ::nio::ad::messages::ADMSMinieyeConfig* _internal_mutable_minieye_config();
  public:
  void unsafe_arena_set_allocated_minieye_config(
      ::nio::ad::messages::ADMSMinieyeConfig* minieye_config);
  ::nio::ad::messages::ADMSMinieyeConfig* unsafe_arena_release_minieye_config();

  // optional .nio.ad.messages.ADMSOperationConfig operation_config = 5;
  bool has_operation_config() const;
  private:
  bool _internal_has_operation_config() const;
  public:
  void clear_operation_config();
  const ::nio::ad::messages::ADMSOperationConfig& operation_config() const;
  PROTOBUF_MUST_USE_RESULT ::nio::ad::messages::ADMSOperationConfig* release_operation_config();
  ::nio::ad::messages::ADMSOperationConfig* mutable_operation_config();
  void set_allocated_operation_config(::nio::ad::messages::ADMSOperationConfig* operation_config);
  private:
  const ::nio::ad::messages::ADMSOperationConfig& _internal_operation_config() const;
  ::nio::ad::messages::ADMSOperationConfig* _internal_mutable_operation_config();
  public:
  void unsafe_arena_set_allocated_operation_config(
      ::nio::ad::messages::ADMSOperationConfig* operation_config);
  ::nio::ad::messages::ADMSOperationConfig* unsafe_arena_release_operation_config();

  // optional .nio.ad.messages.SensorTSHeader sensor_original_ts = 536870906;
  bool has_sensor_original_ts() const;
  private:
  bool _internal_has_sensor_original_ts() const;
  public:
  void clear_sensor_original_ts();
  const ::nio::ad::messages::SensorTSHeader& sensor_original_ts() const;
  PROTOBUF_MUST_USE_RESULT ::nio::ad::messages::SensorTSHeader* release_sensor_original_ts();
  ::nio::ad::messages::SensorTSHeader* mutable_sensor_original_ts();
  void set_allocated_sensor_original_ts(::nio::ad::messages::SensorTSHeader* sensor_original_ts);
  private:
  const ::nio::ad::messages::SensorTSHeader& _internal_sensor_original_ts() const;
  ::nio::ad::messages::SensorTSHeader* _internal_mutable_sensor_original_ts();
  public:
  void unsafe_arena_set_allocated_sensor_original_ts(
      ::nio::ad::messages::SensorTSHeader* sensor_original_ts);
  ::nio::ad::messages::SensorTSHeader* unsafe_arena_release_sensor_original_ts();

  // optional bool sensetime_config_update = 2;
  bool has_sensetime_config_update() const;
  private:
  bool _internal_has_sensetime_config_update() const;
  public:
  void clear_sensetime_config_update();
  bool sensetime_config_update() const;
  void set_sensetime_config_update(bool value);
  private:
  bool _internal_sensetime_config_update() const;
  void _internal_set_sensetime_config_update(bool value);
  public:

  // optional bool minieye_config_update = 4;
  bool has_minieye_config_update() const;
  private:
  bool _internal_has_minieye_config_update() const;
  public:
  void clear_minieye_config_update();
  bool minieye_config_update() const;
  void set_minieye_config_update(bool value);
  private:
  bool _internal_minieye_config_update() const;
  void _internal_set_minieye_config_update(bool value);
  public:

  // optional bool operation_config_update = 6;
  bool has_operation_config_update() const;
  private:
  bool _internal_has_operation_config_update() const;
  public:
  void clear_operation_config_update();
  bool operation_config_update() const;
  void set_operation_config_update(bool value);
  private:
  bool _internal_operation_config_update() const;
  void _internal_set_operation_config_update(bool value);
  public:

  // optional uint64 timestamp = 536870905;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 publish_ptp_ts = 536870907;
  bool has_publish_ptp_ts() const;
  private:
  bool _internal_has_publish_ptp_ts() const;
  public:
  void clear_publish_ptp_ts();
  ::PROTOBUF_NAMESPACE_ID::uint64 publish_ptp_ts() const;
  void set_publish_ptp_ts(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_publish_ptp_ts() const;
  void _internal_set_publish_ptp_ts(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 counter = 536870910;
  bool has_counter() const;
  private:
  bool _internal_has_counter() const;
  public:
  void clear_counter();
  ::PROTOBUF_NAMESPACE_ID::uint64 counter() const;
  void set_counter(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_counter() const;
  void _internal_set_counter(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 publish_ts = 536870911;
  bool has_publish_ts() const;
  private:
  bool _internal_has_publish_ts() const;
  public:
  void clear_publish_ts();
  ::PROTOBUF_NAMESPACE_ID::uint64 publish_ts() const;
  void set_publish_ts(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_publish_ts() const;
  void _internal_set_publish_ts(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:nio.ad.messages.ADMSConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr publisher_id_;
  ::nio::ad::messages::ADMSSenseTimeConfig* sensetime_config_;
  ::nio::ad::messages::ADMSMinieyeConfig* minieye_config_;
  ::nio::ad::messages::ADMSOperationConfig* operation_config_;
  ::nio::ad::messages::SensorTSHeader* sensor_original_ts_;
  bool sensetime_config_update_;
  bool minieye_config_update_;
  bool operation_config_update_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_;
  ::PROTOBUF_NAMESPACE_ID::uint64 publish_ptp_ts_;
  ::PROTOBUF_NAMESPACE_ID::uint64 counter_;
  ::PROTOBUF_NAMESPACE_ID::uint64 publish_ts_;
  friend struct ::TableStruct_common_2fcloud_5fconfig_2fadms_5fparam_5fconfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ADMSConfig

// optional .nio.ad.messages.ADMSSenseTimeConfig sensetime_config = 1;
inline bool ADMSConfig::_internal_has_sensetime_config() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || sensetime_config_ != nullptr);
  return value;
}
inline bool ADMSConfig::has_sensetime_config() const {
  return _internal_has_sensetime_config();
}
inline const ::nio::ad::messages::ADMSSenseTimeConfig& ADMSConfig::_internal_sensetime_config() const {
  const ::nio::ad::messages::ADMSSenseTimeConfig* p = sensetime_config_;
  return p != nullptr ? *p : reinterpret_cast<const ::nio::ad::messages::ADMSSenseTimeConfig&>(
      ::nio::ad::messages::_ADMSSenseTimeConfig_default_instance_);
}
inline const ::nio::ad::messages::ADMSSenseTimeConfig& ADMSConfig::sensetime_config() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.ADMSConfig.sensetime_config)
  return _internal_sensetime_config();
}
inline void ADMSConfig::unsafe_arena_set_allocated_sensetime_config(
    ::nio::ad::messages::ADMSSenseTimeConfig* sensetime_config) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(sensetime_config_);
  }
  sensetime_config_ = sensetime_config;
  if (sensetime_config) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:nio.ad.messages.ADMSConfig.sensetime_config)
}
inline ::nio::ad::messages::ADMSSenseTimeConfig* ADMSConfig::release_sensetime_config() {
  _has_bits_[0] &= ~0x00000002u;
  ::nio::ad::messages::ADMSSenseTimeConfig* temp = sensetime_config_;
  sensetime_config_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::nio::ad::messages::ADMSSenseTimeConfig* ADMSConfig::unsafe_arena_release_sensetime_config() {
  // @@protoc_insertion_point(field_release:nio.ad.messages.ADMSConfig.sensetime_config)
  _has_bits_[0] &= ~0x00000002u;
  ::nio::ad::messages::ADMSSenseTimeConfig* temp = sensetime_config_;
  sensetime_config_ = nullptr;
  return temp;
}
inline ::nio::ad::messages::ADMSSenseTimeConfig* ADMSConfig::_internal_mutable_sensetime_config() {
  _has_bits_[0] |= 0x00000002u;
  if (sensetime_config_ == nullptr) {
    auto* p = CreateMaybeMessage<::nio::ad::messages::ADMSSenseTimeConfig>(GetArenaForAllocation());
    sensetime_config_ = p;
  }
  return sensetime_config_;
}
inline ::nio::ad::messages::ADMSSenseTimeConfig* ADMSConfig::mutable_sensetime_config() {
  ::nio::ad::messages::ADMSSenseTimeConfig* _msg = _internal_mutable_sensetime_config();
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.ADMSConfig.sensetime_config)
  return _msg;
}
inline void ADMSConfig::set_allocated_sensetime_config(::nio::ad::messages::ADMSSenseTimeConfig* sensetime_config) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(sensetime_config_);
  }
  if (sensetime_config) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(sensetime_config));
    if (message_arena != submessage_arena) {
      sensetime_config = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, sensetime_config, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  sensetime_config_ = sensetime_config;
  // @@protoc_insertion_point(field_set_allocated:nio.ad.messages.ADMSConfig.sensetime_config)
}

// optional bool sensetime_config_update = 2;
inline bool ADMSConfig::_internal_has_sensetime_config_update() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool ADMSConfig::has_sensetime_config_update() const {
  return _internal_has_sensetime_config_update();
}
inline void ADMSConfig::clear_sensetime_config_update() {
  sensetime_config_update_ = false;
  _has_bits_[0] &= ~0x00000020u;
}
inline bool ADMSConfig::_internal_sensetime_config_update() const {
  return sensetime_config_update_;
}
inline bool ADMSConfig::sensetime_config_update() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.ADMSConfig.sensetime_config_update)
  return _internal_sensetime_config_update();
}
inline void ADMSConfig::_internal_set_sensetime_config_update(bool value) {
  _has_bits_[0] |= 0x00000020u;
  sensetime_config_update_ = value;
}
inline void ADMSConfig::set_sensetime_config_update(bool value) {
  _internal_set_sensetime_config_update(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.ADMSConfig.sensetime_config_update)
}

// optional .nio.ad.messages.ADMSMinieyeConfig minieye_config = 3;
inline bool ADMSConfig::_internal_has_minieye_config() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || minieye_config_ != nullptr);
  return value;
}
inline bool ADMSConfig::has_minieye_config() const {
  return _internal_has_minieye_config();
}
inline const ::nio::ad::messages::ADMSMinieyeConfig& ADMSConfig::_internal_minieye_config() const {
  const ::nio::ad::messages::ADMSMinieyeConfig* p = minieye_config_;
  return p != nullptr ? *p : reinterpret_cast<const ::nio::ad::messages::ADMSMinieyeConfig&>(
      ::nio::ad::messages::_ADMSMinieyeConfig_default_instance_);
}
inline const ::nio::ad::messages::ADMSMinieyeConfig& ADMSConfig::minieye_config() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.ADMSConfig.minieye_config)
  return _internal_minieye_config();
}
inline void ADMSConfig::unsafe_arena_set_allocated_minieye_config(
    ::nio::ad::messages::ADMSMinieyeConfig* minieye_config) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(minieye_config_);
  }
  minieye_config_ = minieye_config;
  if (minieye_config) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:nio.ad.messages.ADMSConfig.minieye_config)
}
inline ::nio::ad::messages::ADMSMinieyeConfig* ADMSConfig::release_minieye_config() {
  _has_bits_[0] &= ~0x00000004u;
  ::nio::ad::messages::ADMSMinieyeConfig* temp = minieye_config_;
  minieye_config_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::nio::ad::messages::ADMSMinieyeConfig* ADMSConfig::unsafe_arena_release_minieye_config() {
  // @@protoc_insertion_point(field_release:nio.ad.messages.ADMSConfig.minieye_config)
  _has_bits_[0] &= ~0x00000004u;
  ::nio::ad::messages::ADMSMinieyeConfig* temp = minieye_config_;
  minieye_config_ = nullptr;
  return temp;
}
inline ::nio::ad::messages::ADMSMinieyeConfig* ADMSConfig::_internal_mutable_minieye_config() {
  _has_bits_[0] |= 0x00000004u;
  if (minieye_config_ == nullptr) {
    auto* p = CreateMaybeMessage<::nio::ad::messages::ADMSMinieyeConfig>(GetArenaForAllocation());
    minieye_config_ = p;
  }
  return minieye_config_;
}
inline ::nio::ad::messages::ADMSMinieyeConfig* ADMSConfig::mutable_minieye_config() {
  ::nio::ad::messages::ADMSMinieyeConfig* _msg = _internal_mutable_minieye_config();
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.ADMSConfig.minieye_config)
  return _msg;
}
inline void ADMSConfig::set_allocated_minieye_config(::nio::ad::messages::ADMSMinieyeConfig* minieye_config) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(minieye_config_);
  }
  if (minieye_config) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(minieye_config));
    if (message_arena != submessage_arena) {
      minieye_config = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, minieye_config, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  minieye_config_ = minieye_config;
  // @@protoc_insertion_point(field_set_allocated:nio.ad.messages.ADMSConfig.minieye_config)
}

// optional bool minieye_config_update = 4;
inline bool ADMSConfig::_internal_has_minieye_config_update() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool ADMSConfig::has_minieye_config_update() const {
  return _internal_has_minieye_config_update();
}
inline void ADMSConfig::clear_minieye_config_update() {
  minieye_config_update_ = false;
  _has_bits_[0] &= ~0x00000040u;
}
inline bool ADMSConfig::_internal_minieye_config_update() const {
  return minieye_config_update_;
}
inline bool ADMSConfig::minieye_config_update() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.ADMSConfig.minieye_config_update)
  return _internal_minieye_config_update();
}
inline void ADMSConfig::_internal_set_minieye_config_update(bool value) {
  _has_bits_[0] |= 0x00000040u;
  minieye_config_update_ = value;
}
inline void ADMSConfig::set_minieye_config_update(bool value) {
  _internal_set_minieye_config_update(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.ADMSConfig.minieye_config_update)
}

// optional .nio.ad.messages.ADMSOperationConfig operation_config = 5;
inline bool ADMSConfig::_internal_has_operation_config() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || operation_config_ != nullptr);
  return value;
}
inline bool ADMSConfig::has_operation_config() const {
  return _internal_has_operation_config();
}
inline const ::nio::ad::messages::ADMSOperationConfig& ADMSConfig::_internal_operation_config() const {
  const ::nio::ad::messages::ADMSOperationConfig* p = operation_config_;
  return p != nullptr ? *p : reinterpret_cast<const ::nio::ad::messages::ADMSOperationConfig&>(
      ::nio::ad::messages::_ADMSOperationConfig_default_instance_);
}
inline const ::nio::ad::messages::ADMSOperationConfig& ADMSConfig::operation_config() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.ADMSConfig.operation_config)
  return _internal_operation_config();
}
inline void ADMSConfig::unsafe_arena_set_allocated_operation_config(
    ::nio::ad::messages::ADMSOperationConfig* operation_config) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(operation_config_);
  }
  operation_config_ = operation_config;
  if (operation_config) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:nio.ad.messages.ADMSConfig.operation_config)
}
inline ::nio::ad::messages::ADMSOperationConfig* ADMSConfig::release_operation_config() {
  _has_bits_[0] &= ~0x00000008u;
  ::nio::ad::messages::ADMSOperationConfig* temp = operation_config_;
  operation_config_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::nio::ad::messages::ADMSOperationConfig* ADMSConfig::unsafe_arena_release_operation_config() {
  // @@protoc_insertion_point(field_release:nio.ad.messages.ADMSConfig.operation_config)
  _has_bits_[0] &= ~0x00000008u;
  ::nio::ad::messages::ADMSOperationConfig* temp = operation_config_;
  operation_config_ = nullptr;
  return temp;
}
inline ::nio::ad::messages::ADMSOperationConfig* ADMSConfig::_internal_mutable_operation_config() {
  _has_bits_[0] |= 0x00000008u;
  if (operation_config_ == nullptr) {
    auto* p = CreateMaybeMessage<::nio::ad::messages::ADMSOperationConfig>(GetArenaForAllocation());
    operation_config_ = p;
  }
  return operation_config_;
}
inline ::nio::ad::messages::ADMSOperationConfig* ADMSConfig::mutable_operation_config() {
  ::nio::ad::messages::ADMSOperationConfig* _msg = _internal_mutable_operation_config();
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.ADMSConfig.operation_config)
  return _msg;
}
inline void ADMSConfig::set_allocated_operation_config(::nio::ad::messages::ADMSOperationConfig* operation_config) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(operation_config_);
  }
  if (operation_config) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(operation_config));
    if (message_arena != submessage_arena) {
      operation_config = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, operation_config, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  operation_config_ = operation_config;
  // @@protoc_insertion_point(field_set_allocated:nio.ad.messages.ADMSConfig.operation_config)
}

// optional bool operation_config_update = 6;
inline bool ADMSConfig::_internal_has_operation_config_update() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool ADMSConfig::has_operation_config_update() const {
  return _internal_has_operation_config_update();
}
inline void ADMSConfig::clear_operation_config_update() {
  operation_config_update_ = false;
  _has_bits_[0] &= ~0x00000080u;
}
inline bool ADMSConfig::_internal_operation_config_update() const {
  return operation_config_update_;
}
inline bool ADMSConfig::operation_config_update() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.ADMSConfig.operation_config_update)
  return _internal_operation_config_update();
}
inline void ADMSConfig::_internal_set_operation_config_update(bool value) {
  _has_bits_[0] |= 0x00000080u;
  operation_config_update_ = value;
}
inline void ADMSConfig::set_operation_config_update(bool value) {
  _internal_set_operation_config_update(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.ADMSConfig.operation_config_update)
}

// optional uint64 timestamp = 536870905;
inline bool ADMSConfig::_internal_has_timestamp() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool ADMSConfig::has_timestamp() const {
  return _internal_has_timestamp();
}
inline void ADMSConfig::clear_timestamp() {
  timestamp_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000100u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ADMSConfig::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ADMSConfig::timestamp() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.ADMSConfig.timestamp)
  return _internal_timestamp();
}
inline void ADMSConfig::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000100u;
  timestamp_ = value;
}
inline void ADMSConfig::set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.ADMSConfig.timestamp)
}

// optional .nio.ad.messages.SensorTSHeader sensor_original_ts = 536870906;
inline bool ADMSConfig::_internal_has_sensor_original_ts() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || sensor_original_ts_ != nullptr);
  return value;
}
inline bool ADMSConfig::has_sensor_original_ts() const {
  return _internal_has_sensor_original_ts();
}
inline const ::nio::ad::messages::SensorTSHeader& ADMSConfig::_internal_sensor_original_ts() const {
  const ::nio::ad::messages::SensorTSHeader* p = sensor_original_ts_;
  return p != nullptr ? *p : reinterpret_cast<const ::nio::ad::messages::SensorTSHeader&>(
      ::nio::ad::messages::_SensorTSHeader_default_instance_);
}
inline const ::nio::ad::messages::SensorTSHeader& ADMSConfig::sensor_original_ts() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.ADMSConfig.sensor_original_ts)
  return _internal_sensor_original_ts();
}
inline void ADMSConfig::unsafe_arena_set_allocated_sensor_original_ts(
    ::nio::ad::messages::SensorTSHeader* sensor_original_ts) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(sensor_original_ts_);
  }
  sensor_original_ts_ = sensor_original_ts;
  if (sensor_original_ts) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:nio.ad.messages.ADMSConfig.sensor_original_ts)
}
inline ::nio::ad::messages::SensorTSHeader* ADMSConfig::release_sensor_original_ts() {
  _has_bits_[0] &= ~0x00000010u;
  ::nio::ad::messages::SensorTSHeader* temp = sensor_original_ts_;
  sensor_original_ts_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::nio::ad::messages::SensorTSHeader* ADMSConfig::unsafe_arena_release_sensor_original_ts() {
  // @@protoc_insertion_point(field_release:nio.ad.messages.ADMSConfig.sensor_original_ts)
  _has_bits_[0] &= ~0x00000010u;
  ::nio::ad::messages::SensorTSHeader* temp = sensor_original_ts_;
  sensor_original_ts_ = nullptr;
  return temp;
}
inline ::nio::ad::messages::SensorTSHeader* ADMSConfig::_internal_mutable_sensor_original_ts() {
  _has_bits_[0] |= 0x00000010u;
  if (sensor_original_ts_ == nullptr) {
    auto* p = CreateMaybeMessage<::nio::ad::messages::SensorTSHeader>(GetArenaForAllocation());
    sensor_original_ts_ = p;
  }
  return sensor_original_ts_;
}
inline ::nio::ad::messages::SensorTSHeader* ADMSConfig::mutable_sensor_original_ts() {
  ::nio::ad::messages::SensorTSHeader* _msg = _internal_mutable_sensor_original_ts();
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.ADMSConfig.sensor_original_ts)
  return _msg;
}
inline void ADMSConfig::set_allocated_sensor_original_ts(::nio::ad::messages::SensorTSHeader* sensor_original_ts) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(sensor_original_ts_);
  }
  if (sensor_original_ts) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(sensor_original_ts));
    if (message_arena != submessage_arena) {
      sensor_original_ts = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, sensor_original_ts, submessage_arena);
    }
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  sensor_original_ts_ = sensor_original_ts;
  // @@protoc_insertion_point(field_set_allocated:nio.ad.messages.ADMSConfig.sensor_original_ts)
}

// optional uint64 publish_ptp_ts = 536870907;
inline bool ADMSConfig::_internal_has_publish_ptp_ts() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool ADMSConfig::has_publish_ptp_ts() const {
  return _internal_has_publish_ptp_ts();
}
inline void ADMSConfig::clear_publish_ptp_ts() {
  publish_ptp_ts_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000200u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ADMSConfig::_internal_publish_ptp_ts() const {
  return publish_ptp_ts_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ADMSConfig::publish_ptp_ts() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.ADMSConfig.publish_ptp_ts)
  return _internal_publish_ptp_ts();
}
inline void ADMSConfig::_internal_set_publish_ptp_ts(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000200u;
  publish_ptp_ts_ = value;
}
inline void ADMSConfig::set_publish_ptp_ts(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_publish_ptp_ts(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.ADMSConfig.publish_ptp_ts)
}

// optional string publisher_id = 536870909;
inline bool ADMSConfig::_internal_has_publisher_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ADMSConfig::has_publisher_id() const {
  return _internal_has_publisher_id();
}
inline void ADMSConfig::clear_publisher_id() {
  publisher_id_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ADMSConfig::publisher_id() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.ADMSConfig.publisher_id)
  return _internal_publisher_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ADMSConfig::set_publisher_id(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 publisher_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nio.ad.messages.ADMSConfig.publisher_id)
}
inline std::string* ADMSConfig::mutable_publisher_id() {
  std::string* _s = _internal_mutable_publisher_id();
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.ADMSConfig.publisher_id)
  return _s;
}
inline const std::string& ADMSConfig::_internal_publisher_id() const {
  return publisher_id_.Get();
}
inline void ADMSConfig::_internal_set_publisher_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  publisher_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ADMSConfig::_internal_mutable_publisher_id() {
  _has_bits_[0] |= 0x00000001u;
  return publisher_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ADMSConfig::release_publisher_id() {
  // @@protoc_insertion_point(field_release:nio.ad.messages.ADMSConfig.publisher_id)
  if (!_internal_has_publisher_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return publisher_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ADMSConfig::set_allocated_publisher_id(std::string* publisher_id) {
  if (publisher_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  publisher_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), publisher_id,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:nio.ad.messages.ADMSConfig.publisher_id)
}

// optional uint64 counter = 536870910;
inline bool ADMSConfig::_internal_has_counter() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool ADMSConfig::has_counter() const {
  return _internal_has_counter();
}
inline void ADMSConfig::clear_counter() {
  counter_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000400u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ADMSConfig::_internal_counter() const {
  return counter_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ADMSConfig::counter() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.ADMSConfig.counter)
  return _internal_counter();
}
inline void ADMSConfig::_internal_set_counter(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000400u;
  counter_ = value;
}
inline void ADMSConfig::set_counter(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_counter(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.ADMSConfig.counter)
}

// optional uint64 publish_ts = 536870911;
inline bool ADMSConfig::_internal_has_publish_ts() const {
  bool value = (_has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline bool ADMSConfig::has_publish_ts() const {
  return _internal_has_publish_ts();
}
inline void ADMSConfig::clear_publish_ts() {
  publish_ts_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000800u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ADMSConfig::_internal_publish_ts() const {
  return publish_ts_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ADMSConfig::publish_ts() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.ADMSConfig.publish_ts)
  return _internal_publish_ts();
}
inline void ADMSConfig::_internal_set_publish_ts(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000800u;
  publish_ts_ = value;
}
inline void ADMSConfig::set_publish_ts(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_publish_ts(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.ADMSConfig.publish_ts)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace ad
}  // namespace nio

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_common_2fcloud_5fconfig_2fadms_5fparam_5fconfig_2eproto
