syntax = "proto2";

option cc_enable_arenas = true;
package nio.ad.messages.debug;
// import "common/perf/sensor_ts_header.proto";

message DLBEVDDebugMeas{

	optional uint32 HA_sTgtPassed_mp = 1 ;
	optional uint32 HA_sTgtInFS_mp = 2 ;
	optional float HA_sTgtLonPos_mp = 3 ;
	optional float HA_cutLTgtLonPos_mp = 4 ;
	optional float HA_cutRTgtLonPos_mp = 5 ;
	optional float HA_cutLTgtCrossLineDist_mp = 6 ;
	optional float HA_cutLTgtCrossLineHeadRad_mp = 7 ;
	optional float HA_cutRTgtCrossLineDist_mp = 8 ;
	optional float HA_cutRTgtCrossLineHeadRad_mp = 9 ;
	optional bool HA_cutTgtDstCheckSts_mp = 10 ;
	optional bool HA_cutTgtFSConfirmSts_mp = 11 ;
	optional float HA_cutTgtHeadRad_mp = 12 ;
	optional bool HA_cutTgtIsCutInSts_mp = 13 ;
	optional uint32 HA_cutTgtLineInFSNum_mp = 14 ;
	optional bool HA_cutTgtLineLowConf_mp = 15 ;
	optional uint32 HA_cutTgtMECategory_mp = 16 ;
	optional float HA_tsiTgtLonPos_mp = 17 ;
	optional float HA_ocTgtLonPos_mp = 18 ;
	optional float HA_farTgtLonPos_mp = 19 ;
	optional bool HA_flgConstructionObs_mp = 20 ;
	optional float HA_mSharpCurv_mp = 21 ;
	optional float HA_vCurvSpdLmt_mp = 22 ;
	optional float HA_dst2ActCurv_mp = 23 ;
	optional float HA_lEdgInteDst_mp = 24 ;
	optional float HA_confLineL_mp = 25 ;
	optional float HA_confLineR_mp = 26 ;
	optional float HA_lLaneWidthInit_mp = 27 ;
	optional uint32 HA_numConstructionCone_mp = 28 ;
	optional uint32 HA_numConstructionObs_mp = 29 ;
	optional float HA_lLaneWidthAim_mp = 30 ;
	optional float HA_tiRainOffTime_mp = 31 ;
	optional float HA_tiFogOffTime_mp = 32 ;
	optional float HA_tiLowSunOffTime_mp = 33 ;
	optional uint32 HA_stTgt_mp = 34 ;
	optional uint32 HA_stLane_mp = 35 ;
	optional uint32 HA_stArea_mp = 36 ;
	optional uint32 HA_stWeather_mp = 37 ;
	optional uint32 HA_infoIcon_mp = 38 ;
	optional uint32 HA_infoText_mp = 39 ;
	optional uint32 HA_infoSound_mp = 40 ;
	optional uint32 EVD_flgRecordEvent_mp = 41 ;
	optional uint32 EVD_stEDRType_mp = 42 ;
	optional uint32 EVD_bDecision_mp = 43 ;
	optional uint32 EVD_stChangeDir_mp = 44 ;
	optional uint32 EVD_stPathDir_mp = 45 ;
	optional uint32 EVD_stPathType_mp = 46 ;
	optional uint32 EVD_stLeadingDir_mp = 47 ;
	optional uint32 EVD_flgSpdValid_mp = 48 ;
	optional uint32 EVD_vSpd_mp = 49 ;
	optional uint32 EVD_flgDistanceValid_mp = 50 ;
	optional float EVD_dstDistance_mp = 51 ;
	optional uint32 EVD_flgDeadlineValid_mp = 52 ;
	optional float EVD_tiDeadline_mp = 53 ;
	optional uint32 EVD_stDecisionSrc_mp = 54 ;
	optional int32 EVD_stSpecGPType_mp = 55 ;
	optional int32 EVD_dstSpecGPLen_mp = 56 ;
	optional uint32 EVD_xSpecGPLaneLinkType_mp = 57 ;
	optional uint32 EVD_xSpecGPBranchTurn_mp = 58 ;
	optional uint32 EVD_stLocType_mp = 59 ;
	optional int32 EVD_numGPNum_mp = 60 ;
	optional int32 EVD_stGP0Type_mp = 61 ;
	optional int32 EVD_dstGP0Len_mp = 62 ;
	optional uint32 EVD_xLaneChangeReason_mp = 63 ;
	optional uint32 EVD_xInnerTAKEOVERInfo_mp = 64 ;
	optional uint32 EVD_xOutputTAKEOVERInfo_mp = 65 ;
	optional uint32 EVD_stDMstatus_mp = 66 ;
	optional uint32 EVD_stCTRLstatus_mp = 67 ;
	optional uint32 EVD_stLaneChangeReq_mp = 68 ;
	optional uint32 EVD_stLPPstatus_mp = 69 ;
	optional int32 EVD_dstLeadingDist_mp = 70 ;
	optional int32 EVD_numCurrLaneNum_mp = 71 ;
	optional int32 EVD_numCurrLaneIdx_mp = 72 ;
	optional int32 EVD_numCheckedCurrLaneIdx_mp = 73 ;
	optional int32 EVD_cntAheadCurvHoldFrames_mp = 74 ;
	optional uint32 EVD_vTar1Spd_mp = 75 ;
	optional float EVD_dstTar1Distance_mp = 76 ;
	optional uint32 EVD_flgTar1Valid_mp = 77 ;
	optional uint32 EVD_stTar1Type_mp = 78 ;
	optional uint32 EVD_vTar2Spd_mp = 79 ;
	optional float EVD_dstTar2Distance_mp = 80 ;
	optional uint32 EVD_flgTar2Valid_mp = 81 ;
	optional uint32 EVD_stTar2Type_mp = 82 ;
	optional uint32 EVD_vTar3Spd_mp = 83 ;
	optional float EVD_dstTar3Distance_mp = 84 ;
	optional uint32 EVD_flgTar3Valid_mp = 85 ;
	optional uint32 EVD_stTar3Type_mp = 86 ;
	optional uint32 EVD_stSLCSatisfied_mp = 87 ;
	optional float EVD_xSLCPredST_mp = 88 ;
	optional float EVD_xSLCPredLE_mp = 89 ;
	optional float EVD_xSLCPredRI_mp = 90 ;
	optional uint32 EVD_xSLCDirCnt_mp = 91 ;
	optional uint32 EVD_stSLCPredDirPrev_mp = 92 ;
	optional int32 EVD_cntCoolDownAfterSLC_mp = 93 ;
	optional int32 EVD_cntCoolDownAfterSlCandNAVI_mp = 94 ;
	optional int32 EVD_cntCoolDownAfterDriverCancel_mp = 95 ;
	optional int32 EVD_cntCoolDownAfterNOPNewlyActived_mp = 96 ;
	optional int32 EVD_cntCoolDownLaneChangeReq_mp = 97 ;
	optional int32 EVD_cntCoolDownAfterDriverTurn_mp = 98 ;
	optional int32 EVD_cntCoolDownAfterCrossLM_mp = 99 ;
	optional int32 EVD_stTurnIndcrSt_mp = 100 ;
	optional int32 EVD_stLeTurnLghtSt_mp = 101 ;
	optional int32 EVD_stRiTurnLghtSt_mp = 102 ;
	optional int32 EVD_stTurnIndcrComplicateSt_mp = 103 ;
	optional int32 EVD_stLeTurnLghtComplicateSt_mp = 104 ;
	optional int32 EVD_stRiTurnLghtComplicateSt_mp = 105 ;
	optional int32 EVD_cntTurnIndcrLghtCntr_mp = 106 ;
	optional int32 EVD_stLCMonitorFlg_mp = 107 ;
	optional int32 EVD_cntLCMonitorCnt_mp = 108 ;
	optional uint32 EVD_xRAMP2HW_mp = 109 ;
	optional uint32 EVD_xHW2RAMP_mp = 110 ;
	optional uint32 EVD_xLANECHANGE1_mp = 111 ;
	optional uint32 EVD_xLANECHANGE2_mp = 112 ;
	optional uint32 EVD_xLANECHANGE3_mp = 113 ;
	optional uint32 EVD_xLANECHANGE4_mp = 114 ;
	optional uint32 EVD_xLANECHANGE5_mp = 115 ;
	optional uint32 EVD_xPATHSELECT_mp = 116 ;
	optional uint32 EVD_xLEADING_mp = 117 ;
	optional uint32 EVD_xPILOT2SPEC1_mp = 118 ;
	optional uint32 EVD_xPILOT2SPEC2_mp = 119 ;
	optional uint32 EVD_xPILOT2SPEC3_mp = 120 ;
	optional uint32 EVD_xPILOT_mp = 121 ;
	optional float EVD_xSpare01_mp = 122 ;
	optional float EVD_xSpare02_mp = 123 ;
	optional float EVD_xSpare03_mp = 124 ;
	optional uint32 EVD_flgTargetCondition_mp = 125 ;
	optional int32 EVD_RP_numEnblLaneIdx_min_mp = 126 ;
	optional int32 EVD_RP_numEnblLaneIdx_max_mp = 127 ;
	optional int32 EVD_RP_numSgstLaneIdx_min_mp = 128 ;
	optional int32 EVD_RP_numSgstLaneIdx_max_mp = 129 ;
	optional int32 EVD_LA_cntLaneAdjustCntr_mp = 130 ;
	optional uint32 EVD_xPreferTurn_mp = 131 ;
	optional int32 EVD_GFP_dstStart_mp = 132 ;
	optional int32 EVD_GFP_dstEnd_mp = 133 ;
	optional uint32 EVD_GFP_flgValid_mp = 134 ;
	optional uint32 EVD_GFP_xClassification_mp = 135 ;
	optional int32 EVD_GFP_dstDistance_mp = 136 ;
	optional uint32 EVD_GFP_xType_mp = 137 ;
	optional int32 EVD_xSucceedLaneID_mp = 138 ;
	optional int32 EVD_xSucceedDir_mp = 139 ;
	optional uint32 EVD_stFrntWiper_mp = 140 ;
	optional uint32 EVD_stRainFall_mp = 141 ;
	optional uint32 EVD_stLeftLaneDecel_mp = 142 ;
	optional uint32 EVD_stRightLaneDecel_mp = 143 ;
	optional uint32 EVD_out_bDecision_mp = 144 ;
	optional uint32 EVD_out_stChangeDir_mp = 145 ;
	optional uint32 EVD_out_xLaneChangeReason_mp = 146 ;
	optional uint32 EVD_out_stPathDir_mp = 147 ;
	optional uint32 EVD_out_stRampDir_mp = 148 ;
	optional float EVD_out_dstDst2Leading_mp = 149 ;
	optional uint32 EVD_out_stLeadingDir_mp = 150 ;
	optional uint32 EVD_out_xTAKEOVERInfo_mp = 151 ;
	optional uint32 EVD_out_flgSpdValid_mp = 152 ;
	optional uint32 EVD_out_vSpd_mp = 153 ;
	optional uint32 EVD_out_flgDistanceValid_mp = 154 ;
	optional float EVD_out_dstDistance_mp = 155 ;
	optional uint32 EVD_out_flgDeadlineValid_mp = 156 ;
	optional float EVD_out_tiDeadline_mp = 157 ;
	optional uint32 EVD_out_vCurrSpd_mp = 158 ;
	optional float EVD_out_dstCurrDist_mp = 159 ;
	optional uint32 EVD_out_flgCurrValid_mp = 160 ;
	optional uint32 EVD_out_stCurrSrc_mp = 161 ;
	optional uint32 EVD_out_vCurrRegulation_mp = 162 ;
	optional uint32 EVD_out_vTar1Spd_mp = 163 ;
	optional float EVD_out_dstTar1Dist_mp = 164 ;
	optional uint32 EVD_out_flgTar1Valid_mp = 165 ;
	optional uint32 EVD_out_stTar1Src_mp = 166 ;
	optional uint32 EVD_out_vTar1Regulation_mp = 167 ;
	optional uint32 EVD_out_vTar2Spd_mp = 168 ;
	optional float EVD_out_dstTar2Dist_mp = 169 ;
	optional uint32 EVD_out_flgTar2Valid_mp = 170 ;
	optional uint32 EVD_out_stTar2Src_mp = 171 ;
	optional uint32 EVD_out_vTar2Regulation_mp = 172 ;
	optional uint32 EVD_out_vTar3Spd_mp = 173 ;
	optional float EVD_out_dstTar3Dist_mp = 174 ;
	optional uint32 EVD_out_flgTar3Valid_mp = 175 ;
	optional uint32 EVD_out_stTar3Src_mp = 176 ;
	optional uint32 EVD_out_vTar3Regulation_mp = 177 ;
	optional uint32 EVD_out_flgGFPValid_mp = 178 ;
	optional uint32 EVD_out_xGFPClassification_mp = 179 ;
	optional float EVD_out_dstGFPDistance_mp = 180 ;
	optional uint32 EVD_out_xGFPType_mp = 181 ;
	optional uint32 EVD_out_stEgoSts2Curve_mp = 182 ;
	optional uint32 EVD_out_flgCurrSpdLmtSuppressed_mp = 183 ;
	optional int32 EVD_record_stOverTakeTmpSt_mp = 184 ;
	optional int32 EVD_record_xOverTakeTgt1ID_mp = 185 ;
	optional int32 EVD_record_cntOverTakeTmp_mp = 186 ;
	optional int32 EVD_record_cntNoOTbyBadLoc_mp = 187 ;
	optional int32 EVD_record_cntNoOTbyDriverCancelCD_mp = 188 ;
	optional int32 EVD_record_cntNoOTbySLCCD_mp = 189 ;
	optional int32 EVD_record_cntNoOTbyNOPCD_mp = 190 ;
	optional int32 EVD_record_cntNoOTbyHardRain_mp = 191 ;
	optional int32 EVD_record_cntNoOTbyOutwardRoad_mp = 192 ;
	optional int32 EVD_record_cntNoOTbyConeArea_mp = 193 ;
	optional int32 EVD_record_cntNoOTbyOppositeToSgt_mp = 194 ;
	optional int32 EVD_record_cntNoOTbySlowSideFormerTgt_mp = 195 ;
	optional int32 EVD_record_cntNoOTbyUnPassingBranch_mp = 196 ;
	optional int32 EVD_record_cntNoOTbyOnlyLeftTwo_mp = 197 ;
	optional int32 SA_vTgtSpd_mp = 198 ;
	optional uint32 SA_stValid_mp = 199 ;
	optional uint32 SA_xSrcName_mp = 200 ;
	optional uint32 TSR_flgByPassCancelSign_mp = 201 ;
	optional uint32 TSR_flgByPassSpdSign_mp = 202 ;
	optional float TSR_lSelectedTSLatDist_mp = 203 ;
	optional float TSR_lSelectedTSLongDist_mp = 204 ;
	optional uint32 TSR_stEgoLocSts_mp = 205 ;
	optional uint32 TSR_stIsExitSignTSIdx_mp = 206 ;
	optional uint32 TSR_stNotInCurrRoadTSIdx_mp = 207 ;
	optional int32 TSR_stSelectedTSID_mp = 208 ;
	optional int32 TSR_stSelectedTSName_mp = 209 ;
	optional int32 TSR_stSelectedTSSupName_mp = 210 ;
	optional uint32 TSR_stSelectedTSFilterType_mp = 211 ;
	optional uint32 TSR_stSelectedTSRelevancy_mp = 212 ;
	optional int32 TSR_stCurrTSID_mp = 213 ;
	optional uint32 TSR_stSpdLmtUnit2iACC_mp = 214 ;
	optional int32 TSR_vSpdLmtValue2iACC0_mp = 215 ;
	optional uint32 TSR_numSpdLmtId2iACC0_mp = 216 ;
	optional uint32 TSR_stSpdLmtSrc2iACC0_mp = 217 ;
	optional uint32 TSR_stSpdLmtConf2iACC0_mp = 218 ;
	optional uint32 TSR_stSupSignTyp2iACC0_mp = 219 ;
	optional uint32 TSR_stSupSignAttr2iACC0_mp = 220 ;
	optional int32 TSR_dstSpdLmtDst2iACC0_mp = 221 ;
	optional int32 TSR_vSpdLmtValue2iACC1_mp = 222 ;
	optional uint32 TSR_numSpdLmtId2iACC1_mp = 223 ;
	optional uint32 TSR_stSpdLmtSrc2iACC1_mp = 224 ;
	optional uint32 TSR_stSpdLmtConf2iACC1_mp = 225 ;
	optional uint32 TSR_stSupSignTyp2iACC1_mp = 226 ;
	optional uint32 TSR_stSupSignAttr2iACC1_mp = 227 ;
	optional int32 TSR_dstSpdLmtDst2iACC1_mp = 228 ;
	optional int32 TSR_vSpdLmtValue2iACC2_mp = 229 ;
	optional uint32 TSR_numSpdLmtId2iACC2_mp = 230 ;
	optional uint32 TSR_stSpdLmtSrc2iACC2_mp = 231 ;
	optional uint32 TSR_stSpdLmtConf2iACC2_mp = 232 ;
	optional uint32 TSR_stSupSignTyp2iACC2_mp = 233 ;
	optional uint32 TSR_stSupSignAttr2iACC2_mp = 234 ;
	optional int32 TSR_dstSpdLmtDst2iACC2_mp = 235 ;
	optional int32 TSR_vSpdLmtValue2iACC3_mp = 236 ;
	optional uint32 TSR_numSpdLmtId2iACC3_mp = 237 ;
	optional uint32 TSR_stSpdLmtSrc2iACC3_mp = 238 ;
	optional uint32 TSR_stSpdLmtConf2iACC3_mp = 239 ;
	optional uint32 TSR_stSupSignTyp2iACC3_mp = 240 ;
	optional uint32 TSR_stSupSignAttr2iACC3_mp = 241 ;
	optional int32 TSR_dstSpdLmtDst2iACC3_mp = 242 ;
	optional uint32 TSR_stTrackedTSNum_mp = 243 ;
	optional uint32 TSR_stSelectedTSNum_mp = 244 ;
	optional float TSR_dstDisplacement_mp = 245 ;
	optional uint32 TSR_stWeatherSts_mp = 246 ;
	optional int32 TSR_vByPassSpdSignValue_mp = 247 ;
	optional uint32 TSR_stIsValidHDMap_mp = 248 ;
	optional uint32 TSR_stIsValidADASMap_mp = 249 ;
	optional uint32 TSR_stIsValidTSR_mp = 250 ;
	optional uint32 TSR_stIsValidRMESpdLoc_mp = 251 ;
	optional int32 TSR_vSpdLmtPt0Value_mp = 252 ;
	optional int32 TSR_dstSpdLmtPt0Dist_mp = 253 ;
	optional uint32 TSR_stSpdLmtPt0Src_mp = 254 ;
	optional uint32 TSR_stSpdLmtPt0Typ_mp = 255 ;
	optional uint32 TSR_stSpdLmtPt0RoadClass_mp = 256 ;
	optional uint32 TSR_stSpdLmtPt0RoadForm_mp = 257 ;
	optional uint32 TSR_stSpdLmtPt0GPTyp_mp = 258 ;
	optional int32 TSR_vSpdLmtPt0BaseSpd_mp = 259 ;
	optional int32 TSR_stSpdLmtPt0OriId_mp = 260 ;
	optional uint32 TSR_stSpdLmtPt0SpdId_mp = 261 ;
	optional int32 TSR_vSpdLmtPt1Value_mp = 262 ;
	optional int32 TSR_dstSpdLmtPt1Dist_mp = 263 ;
	optional uint32 TSR_stSpdLmtPt1Src_mp = 264 ;
	optional uint32 TSR_stSpdLmtPt1Typ_mp = 265 ;
	optional uint32 TSR_stSpdLmtPt1RoadClass_mp = 266 ;
	optional uint32 TSR_stSpdLmtPt1RoadForm_mp = 267 ;
	optional uint32 TSR_stSpdLmtPt1GPTyp_mp = 268 ;
	optional int32 TSR_vSpdLmtPt1BaseSpd_mp = 269 ;
	optional int32 TSR_stSpdLmtPt1OriId_mp = 270 ;
	optional uint32 TSR_stSpdLmtPt1SpdId_mp = 271 ;
	optional int32 TSR_vSpdLmtPt2Value_mp = 272 ;
	optional int32 TSR_dstSpdLmtPt2Dist_mp = 273 ;
	optional uint32 TSR_stSpdLmtPt2Src_mp = 274 ;
	optional uint32 TSR_stSpdLmtPt2Typ_mp = 275 ;
	optional uint32 TSR_stSpdLmtPt2RoadClass_mp = 276 ;
	optional uint32 TSR_stSpdLmtPt2RoadForm_mp = 277 ;
	optional uint32 TSR_stSpdLmtPt2GPTyp_mp = 278 ;
	optional int32 TSR_vSpdLmtPt2BaseSpd_mp = 279 ;
	optional int32 TSR_stSpdLmtPt2OriId_mp = 280 ;
	optional uint32 TSR_stSpdLmtPt2SpdId_mp = 281 ;
	optional int32 TSR_vSpdLmtPt3Value_mp = 282 ;
	optional int32 TSR_dstSpdLmtPt3Dist_mp = 283 ;
	optional uint32 TSR_stSpdLmtPt3Src_mp = 284 ;
	optional uint32 TSR_stSpdLmtPt3Typ_mp = 285 ;
	optional uint32 TSR_stSpdLmtPt3RoadClass_mp = 286 ;
	optional uint32 TSR_stSpdLmtPt3RoadForm_mp = 287 ;
	optional uint32 TSR_stSpdLmtPt3GPTyp_mp = 288 ;
	optional int32 TSR_vSpdLmtPt3BaseSpd_mp = 289 ;
	optional int32 TSR_stSpdLmtPt3OriId_mp = 290 ;
	optional uint32 TSR_stSpdLmtPt3SpdId_mp = 291 ;
	optional bool TSR_stIsValidSpd_mp = 292 ;
	optional bool TSR_stIsValidLoc_mp = 293 ;
	optional int32 TSR_vNaviRaisedSpd_mp = 294 ;
	optional int32 TSR_stNaviRaisedMarkedGpId_mp = 295 ;
	optional uint32 SA_CA_flgCAValid_mp = 296 ;
	optional float SA_CA_vCASpdLimit_mp = 297 ;
	optional float SA_CA_vSpdLmtByCurvature_mp = 298 ;
	optional float SA_CA_xCurvaturePred_mp = 299 ;
	optional uint32 SA_FS_flgFSValid_mp = 300 ;
	optional int32 SA_FS_vFSSpdLimit_mp = 301 ;
	optional float SA_FS_arFSArea_mp = 302 ;
	optional float SA_FS_arFSAreaFiltered_mp = 303 ;
	optional float SA_FS_tiFSHoldTime_mp = 304 ;
	optional uint32 SA_RA_flgRAVlid_mp = 305 ;
	optional float SA_RA_vRASpdLimit_mp = 306 ;
	optional float SA_RA_RoadArea_mp = 307 ;
	optional float SA_RA_RoadAreaWarn_mp = 308 ;
	optional float SA_FUS_vSpdByDst_mp = 309 ;
	optional float SA_FUS_dstTgt1_mp = 310 ;
	optional float SA_FUS_vSpdLimit_mp = 311 ;
	optional float SA_TF_vAvgCarSpdLeft_mp = 312 ;
	optional float SA_TF_vAvgTruckSpdLeft_mp = 313 ;
	optional float SA_TF_vAvgCarSpdRight_mp = 314 ;
	optional float SA_TF_vAvgTruckSpdRight_mp = 315 ;
	optional float SA_TF_vSpdLimit_mp = 316 ;
	optional uint32 SA_CO_flgConeObjectValid_mp = 317 ;
	optional int32 SA_CO_dstConeObjectDist_mp = 318 ;
	optional int32 SA_CO_vConeObjectSpd_mp = 319 ;
	optional bool SA_MAPCURV_flgIterConverg_mp = 320 ;
	optional int32 SA_MAPCURV_cntrIterTimes_mp = 321 ;
	optional int32 SA_MAPCURV_vFirstCurvLmt_mp = 322 ;
	optional bool SA_MAPCURV_flgValid_mp = 323 ;
	optional int32 SA_MAPCURV_vSpdLimit_mp = 324 ;
	optional uint32 LPP_stLeadModeStatus_mp = 325 ;
	optional uint32 LPP_stIsLaneChangeInLeadMode_mp = 326 ;
	optional uint32 LPP_stIsInLeadMode_mp = 327 ;
	optional float LPP_pctLeadTrajConf_mp = 328 ;
	optional float LPP_lLeadModeLatTargetWidth_mp = 329 ;
	optional float LPP_tiLeadElapsed_mp = 330 ;
	optional float LPP_tiLeadPeriod_mp = 331 ;
	optional float LPP_lLeadModeLonTargetDistance_mp = 332 ;
	optional uint32 LPP_flgTargetCondition_mp = 333 ;
	optional float LPP_xLaneMarkDebounce_mp = 334 ;
	optional float LPP_lC0ByT_mp = 335 ;
	optional float LPP_xLeadModeSmoothCnt_mp = 336 ;
	optional float LPP_tiTTPToCheckRampType_mp = 337 ;
	optional uint32 LPP_lDist2StartPoint_mp = 338 ;
	optional float LPP_lEgoCurrentLatPos_mp = 339 ;
	optional float LPP_lLaneWidthAtEndInSplit_mp = 340 ;
	optional float LPP_xPlannerChangeSmoothCnt_mp = 341 ;
	optional uint32 LPP_stPlannerSrc_mp = 342 ;
	optional float EHY_tiElapsEHY_mp = 343 ;
	optional float EHY_tiElapsSensor_mp = 344 ;
	optional float EHY_tiElapsCameraME_mp = 345 ;
	optional float EHY_tiElapsRadar_mp = 346 ;
	optional float EHY_tiElapsEGO_mp = 347 ;
	optional float EHY_tiElapsHypoWorld_mp = 348 ;
	optional float EHY_tiElapsRoad_mp = 349 ;
	optional float EHY_tiElapsObject_mp = 350 ;
	optional float EHY_tiElapsRadAsso_mp = 351 ;
	optional float EHY_tiElapsVisAsso_mp = 352 ;
	optional float EHY_tiElapsFusion_mp = 353 ;
	optional float EHY_tiElapsSilica_mp = 354 ;
	optional float EHY_tiElapsSilica1_mp = 355 ;
	optional float EHY_tiElapsSilica2_mp = 356 ;
	optional float EHY_tiElapsSilica3_mp = 357 ;
	optional float EHY_tiElapsSilica4_mp = 358 ;
	optional float EHY_tiElapsSilica5_mp = 359 ;
	optional float EHY_tiElapsSilica6_mp = 360 ;
	optional float EHY_tiElapsSilica7_mp = 361 ;
	optional float EHY_tiElapsSignalOut_mp = 362 ;
	optional float EHY_tiElapsUSS_mp = 363 ;
	optional float EHY_tiElapsFSP_mp = 364 ;
	optional float EHY_tiElapsChassis_mp = 365 ;
	optional float EHY_tiElapsHDMap_mp = 366 ;
	optional float EHY_tiElapsMapTrajStart_mp = 367 ;
	optional float EHY_tiElapsMapTraj_mp = 368 ;
	optional float EHY_tiElapsLeadPlanner_mp = 369 ;
	optional float EHY_tiElapsRMFusionStart_mp = 370 ;
	optional float EHY_tiElapsRMFusionHDLMCreated_mp = 371 ;
	optional float EHY_tiElapsRMFusionCoarseMatch_mp = 372 ;
	optional float EHY_tiElapsRMFusionDelicateMatch_mp = 373 ;
	optional float EHY_tiElapsRMFusion_mp = 374 ;
	optional float EHY_tiElapsRMFusionICPStart_mp = 375 ;
	optional float EHY_tiElapsRMFusionICPSVD_mp = 376 ;
	optional float EHY_tiElapsRMFusionICPAlgebra_mp = 377 ;
	optional float EHY_tiElapsRMEAdjustRoleStart_mp = 378 ;
	optional float EHY_tiElapsRMEAdjustRoleEnd_mp = 379 ;
	optional float EHY_tiElapsRMEAssignLanesStart_mp = 380 ;
	optional float EHY_tiElapsRMEAssignLanesEnd_mp = 381 ;
	optional float EHY_tiElapsRMEUpdateCentralLineStart_mp = 382 ;
	optional float EHY_tiElapsRMEUpdateCentralLineEnd_mp = 383 ;
	optional float EHY_tiElapsRMObjTraj_mp = 384 ;
	optional uint32 EHY_stWarn_mp = 385 ;
	optional uint32 EAEB_FCWSuppressReason_mp = 386 ;
	optional uint32 EAEB_PreFillSuppressReason_mp = 387 ;
	optional uint32 EAEB_SoftBrkSuppressReason_mp = 388 ;
	optional uint32 EAEB_HardBrkSuppressReason_mp = 389 ;
	optional uint32 EAEB_VruFCWSuppressReason_mp = 390 ;
	optional uint32 EAEB_VruPreFillSuppressReason_mp = 391 ;
	optional uint32 EAEB_VruSoftBrkSuppressReason_mp = 392 ;
	optional uint32 EAEB_VruHardBrkSuppressReason_mp = 393 ;
	optional float EAEB_MinObjTTC_mp = 394 ;
	optional float EAEB_FCWTTCThrds_mp = 395 ;
	optional float EAEB_PreFillTTCThrds_mp = 396 ;
	optional float EAEB_SoftBrkTTCThrds_mp = 397 ;
	optional float EAEB_HardBrkTTCThrds_mp = 398 ;
	optional float EAEB_VruFCWTTCThrds_mp = 399 ;
	optional float EAEB_VruPreFillTTCThrds_mp = 400 ;
	optional float EAEB_VruSoftBrkTTCThrds_mp = 401 ;
	optional float EAEB_VruHardBrkTTCThrds_mp = 402 ;
	optional uint32 EAEB_AlertOutput_mp = 403 ;
	optional uint32 EHY_flgShadowAEBActive_mp = 404 ;
	optional uint32 EHY_flgShadowAEBPreActive_mp = 405 ;
	optional uint32 TF_flgLeftLaneAverageSpdIsLowEachFrame_mp = 406 ;
	optional uint32 TF_flgLeftLaneAverageSpdIsLowDebounced_mp = 407 ;
	optional float TF_LeftLaneAverageSpd_mp = 408 ;
	optional uint32 TF_flgLeftLaneVehGapIsSmallEachFram_mp = 409 ;
	optional uint32 TF_flgLeftLaneVehGapIsSmallDebounced_mp = 410 ;
	optional uint32 TF_LeftLaneAccDecStatusEachFrame_mp = 411 ;
	optional uint32 TF_LeftLaneAccDecStatusDebounced_mp = 412 ;
	optional uint32 TF_flgRightLaneAverageSpdIsLowEachFrame_mp = 413 ;
	optional uint32 TF_flgRightLaneAverageSpdIsLowDebounced_mp = 414 ;
	optional float TF_RightLaneAverageSpd_mp = 415 ;
	optional uint32 TF_flgRightLaneVehGapIsSmallEachFram_mp = 416 ;
	optional uint32 TF_flgRightLaneVehGapIsSmallDebounced_mp = 417 ;
	optional uint32 TF_RightLaneAccDecStatusEachFrame_mp = 418 ;
	optional uint32 TF_RightLaneAccDecStatusDebounced_mp = 419 ;
	optional float TF_flgStoppedVehConf_mp = 420 ;
	optional float TF_flgStoppedVehDst_mp = 421 ;
	optional float TF_tiStoppedVehTTC_mp = 422 ;
	optional uint32 MAP_Traj_stPlanSt_mp = 423 ;
	optional uint32 MAP_Traj_stPlanSrc_mp = 424 ;
	optional uint32 LPP_LP_stStatus_mp = 425 ;
	optional float LPP_LP_xTrajC0_mp = 426 ;
	optional float LPP_LP_xTrajC1_mp = 427 ;
	optional float LPP_LP_xTrajC2_mp = 428 ;
	optional float LPP_LP_xTrajC3_mp = 429 ;
	optional float LPP_LP_xTrajC4_mp = 430 ;
	optional float LPP_LP_xTrajC5_mp = 431 ;
	optional float LPP_LP_lEnd_mp = 432 ;
	optional float LPP_LP_dstSplit2Branch_mp = 433 ;
	optional float LPP_LP_dstZeroPtX_mp = 434 ;
	optional float LPP_LP_dstZeroPtY_mp = 435 ;
	optional uint32 LPP_LP_nIterTimes_mp = 436 ;
	optional float LPP_LP_Cost_mp = 437 ;
	optional uint32 LPP_LP_nCostListSize_mp = 438 ;
	optional bool LPP_LP_flgMapValid_mp = 439 ;
	optional bool LPP_LP_flgHppValid_mp = 440 ;
	optional bool LPP_FS_flgShadowOn_mp = 441 ;
	optional float LPP_FS_tiShadowOnTimer_mp = 442 ;
	optional float LPP_FS_dstTrajC0Differ_mp = 443 ;
	optional float LPP_FS_dstTrajDyDiffer_mp = 444 ;
	optional float LPP_FS_xShadowTrajC0_mp = 445 ;
	optional float LPP_FS_xShadowTrajC1_mp = 446 ;
	optional float LPP_FS_xShadowTrajC2_mp = 447 ;
	optional bool LPP_FS_flgFSWorkNoLaneChg_mp = 448 ;
	optional float EHY_tiElapsInputAdpt_mp = 449 ;
	optional float EHY_tiElapsOutputAdpt_mp = 450 ;
	optional float EHY_tiElapsObjectUpdateCal_mp = 451 ;
	optional float EHY_tiElapsObjectChkMatchPair_mp = 452 ;
	optional float EHY_tiElapsObjectTimUpdate_mp = 453 ;
	optional float EHY_tiElapsSilicaTSILanePre_mp = 454 ;
	optional float EHY_tiElapsSilicaLaneChgMonitor_mp = 455 ;
	optional float EHY_tiElapsSilicaTSI_mp = 456 ;
	optional float EHY_tiElapsSilicaTSE_mp = 457 ;
	optional float EHY_tiElapsSilicaObjLocAdpt_mp = 458 ;
	optional float EHY_tiElapsSilicaSGA_mp = 459 ;
	optional float EHY_tiElapsSilicaTSR_mp = 460 ;
	optional float EHY_tiElapsSilicaSA_mp = 461 ;
	optional float EHY_tiElapsSilicaTF_mp = 462 ;
	optional float EHY_tiElapsSilicaEVD_mp = 463 ;
	optional float EHY_tiElapsSilicaLPP_mp = 464 ;
	optional float EHY_tiElapsSilicaHA_mp = 465 ;
	optional float EHY_tiElapsSilicaEDR_mp = 466 ;
	optional float EHY_tiElapsRMUpdateLMRE_mp = 467 ;
	optional float EHY_tiElapsRMJudgConstArea_mp = 468 ;
	optional float EHY_tiElapsRMFSRoadEdge_mp = 469 ;
	optional float EHY_tiElapsRMLMPreprocess_mp = 470 ;
	optional float EHY_tiElapsRMLMTrack_mp = 471 ;
	optional float EHY_tiElapsRMLMPostprocess_mp = 472 ;
	optional float EHY_tiElapsRMChckLaneChg_mp = 473 ;
	optional float EHY_tiElapsRMAdjustLMRole_mp = 474 ;
	optional float EHY_tiElapsRMUpdateCLMOut_mp = 475 ;
	optional float EHY_tiElapsRMAssignLanes_mp = 476 ;
	optional float EHY_tiElapsRMUpdateLaneCentralLine_mp = 477 ;
	optional float EHY_CPULoad_mp = 478 ;
	optional uint64 EHY_tiEHYStart_mp = 479 ;
	optional uint64 EHY_tiEHYEnd_mp = 480 ;
	optional float EHY_tiElapsObjLMRel_mp = 481 ;
	optional float EHY_tiElapsObjLMRelInputAdpt_mp = 482 ;
	optional float EHY_tiElapsObjLMRelObjAssociation_mp = 483 ;
	optional float EHY_tiElapsObjLMRelLMAssociation_mp = 484 ;
	optional float EHY_tiElapsObjLMRelCalRel_mp = 485 ;
	optional float EHY_tiElapsObjLMRelLMMod_mp = 486 ;
	optional uint32 TSR_stSASVisionFailsafe_mp = 487 ;
	optional uint32 TSR_stSASFault_mp = 488 ;
	optional uint32 TSR_stSASGnssLoc_mp = 489 ;
	optional uint32 TSR_stSASSalesRegion_mp = 490 ;
	optional uint32 TSR_stSASSalesCountry_mp = 491 ;
	optional uint32 TSR_stSASReserve1_mp = 492 ;
	optional uint32 TSR_stSASReserve2_mp = 493 ;
	optional uint32 Lidar_tiElapsUpdatePts_mp = 494 ;
	optional uint32 Lidar_tiElapsEdgeEst_mp = 495 ;
	optional uint32 Lidar_tiElapsGroundRM_mp = 496 ;
	optional uint32 Lidar_stReserve1_mp = 9994 ;
	optional uint32 Lidar_stReserve2_mp = 9995 ;
	optional uint32 Lidar_stReserve3_mp = 9996 ;
	optional uint32 Lidar_stReserve4_mp = 9997 ;
	optional uint32 Lidar_stReserve5_mp = 9998 ;
	optional uint32 Lidar_stReserve6_mp = 9999 ;

    optional uint64 timestamp = 536870905; // ptp timestamp, nanosecond，used for data bundle readin 
	// optional SensorTSHeader sensor_original_ts = 536870906;   // sensor original ts
	optional uint64 publish_ptp_ts = 536870907; // publish ptp timestamp, uint in nanosec
	optional string publisher_id = 536870909; // uuid of the publisher
	optional uint64 counter = 536870910; // message counter
	optional uint64 publish_ts = 536870911;    // publish timestamp; unit : nanosecond
}
