syntax = "proto2";

option cc_enable_arenas = true;
package nio.ad.messages.debug;
// import "common/perf/sensor_ts_header.proto";

message DLBRMEDebugMeas{

	optional uint32 LM_LVLM_stQl_mp = 1 ;
	optional float LM_LVLM_xC0_mp = 2 ;
	optional float LM_LVLM_xC1_mp = 3 ;
	optional float LM_LVLM_xC2_mp = 4 ;
	optional float LM_LVLM_xC3_mp = 5 ;
	optional float LM_LVLM_lStart_mp = 6 ;
	optional float LM_LVLM_lEnd_mp = 7 ;
	optional float LM_LVLM_lCtrlPtLonPos_mp = 8 ;
	optional float LM_LVLM_lCtrlPtLatPos_mp = 9 ;
	optional uint32 LM_RLM_stLeQl_mp = 10 ;
	optional float LM_RLM_xLeC0_mp = 11 ;
	optional float LM_RLM_xLeC1_mp = 12 ;
	optional float LM_RLM_xLeC2_mp = 13 ;
	optional float LM_RLM_xLeC3_mp = 14 ;
	optional float LM_RLM_lLeStart_mp = 15 ;
	optional float LM_RLM_lLeEnd_mp = 16 ;
	optional float LM_RLM_pctLeConfidence_mp = 17 ;
	optional uint32 LM_RLM_stRiQl_mp = 18 ;
	optional float LM_RLM_xRiC0_mp = 19 ;
	optional float LM_RLM_xRiC1_mp = 20 ;
	optional float LM_RLM_xRiC2_mp = 21 ;
	optional float LM_RLM_xRiC3_mp = 22 ;
	optional float LM_RLM_lRiStart_mp = 23 ;
	optional float LM_RLM_lRiEnd_mp = 24 ;
	optional float LM_RLM_pctRiConfidence_mp = 25 ;
	optional uint32 LM_PP_stQl_mp = 26 ;
	optional float LM_PP_pctConfidence_mp = 27 ;
	optional float LM_PP_xC0_mp = 28 ;
	optional float LM_PP_xC1_mp = 29 ;
	optional float LM_PP_xC2_mp = 30 ;
	optional float LM_PP_xC3_mp = 31 ;
	optional float LM_PP_lStart_mp = 32 ;
	optional float LM_PP_lEnd_mp = 33 ;
	optional float LM_PP_lLonCtrlPt_mp = 34 ;
	optional float LM_PP_lLatCtrlPt_mp = 35 ;
	optional uint32 LM_TPP_stQl_mp = 36 ;
	optional float LM_TPP_pctConfidence_mp = 37 ;
	optional float LM_TPP_xC0_mp = 38 ;
	optional float LM_TPP_xC1_mp = 39 ;
	optional float LM_TPP_xC2_mp = 40 ;
	optional float LM_TPP_xC3_mp = 41 ;
	optional float LM_TPP_lStart_mp = 42 ;
	optional float LM_TPP_lEnd_mp = 43 ;
	optional float LM_TPP_lLonCtrlPt_mp = 44 ;
	optional float LM_TPP_lLatCtrlPt_mp = 45 ;
	optional uint32 LM_stLMStatus_mp = 46 ;
	optional int32 LM_numEgoLaneLoc_mp = 47 ;
	optional uint32 LM_numEgoLaneLocIdx_mp = 48 ;
	optional uint32 OBSOLETE_LM_stEgoGPSStatus_mp = 49 ;
	optional float OBSOLETE_LM_locEgoGPSLongitude_mp = 50 ;
	optional float OBSOLETE_LM_locEgoGPSLatitude_mp = 51 ;
	optional float OBSOLETE_LM_locEgoGPSAltitude_mp = 52 ;
	optional float LM_phiEgoLaneLoc_mp = 53 ;
	optional float OBSOLETE_LM_vEgoGPSSpeed_mp = 54 ;
	optional uint32 LM_numRoadLaneNumber_mp = 55 ;
	optional uint32 LM_stRoadCondition_mp = 56 ;
	optional uint32 LM_stRoadEdge0_Quality_mp = 57 ;
	optional float LM_xRoadEdge0_C0_mp = 58 ;
	optional float LM_xRoadEdge0_C1_mp = 59 ;
	optional float LM_xRoadEdge0_C2_mp = 60 ;
	optional float LM_xRoadEdge0_C3_mp = 61 ;
	optional float LM_lRoadEdge0_RangeStart_mp = 62 ;
	optional float LM_lRoadEdge0_RangeEnd_mp = 63 ;
	optional uint32 LM_stRoadEdge0_Color_mp = 64 ;
	optional uint32 LM_stRoadEdge0_Type_mp = 65 ;
	optional float LM_lRoadEdge0_MarkWidth_mp = 66 ;
	optional uint32 LM_stRoadEdge0_Src_mp = 67 ;
	optional uint32 LM_stRoadEdge1_Quality_mp = 68 ;
	optional float LM_xRoadEdge1_C0_mp = 69 ;
	optional float LM_xRoadEdge1_C1_mp = 70 ;
	optional float LM_xRoadEdge1_C2_mp = 71 ;
	optional float LM_xRoadEdge1_C3_mp = 72 ;
	optional float LM_lRoadEdge1_RangeStart_mp = 73 ;
	optional float LM_lRoadEdge1_RangeEnd_mp = 74 ;
	optional uint32 LM_stRoadEdge1_Color_mp = 75 ;
	optional uint32 LM_stRoadEdge1_Type_mp = 76 ;
	optional float LM_lRoadEdge1_MarkWidth_mp = 77 ;
	optional uint32 LM_stRoadEdge1_Src_mp = 78 ;
	optional uint32 LM_stRoad_Lane0_LaneStatus_mp = 79 ;
	optional float LM_stRoad_Lane0_pctConfidence_mp = 80 ;
	optional uint32 LM_numRoad_Lane0_LaneId_mp = 81 ;
	optional float LM_IRoad_Lane0_LaneWidth_mp = 82 ;
	optional uint32 LM_stRoad_Lane0_LaneDrvDir_mp = 83 ;
	optional uint32 LM_vRoad_Lane0_MinSpdLmt_mp = 84 ;
	optional uint32 LM_vRoad_Lane0_MaxSpdLmt_mp = 85 ;
	optional float LM_stRoad_Lane0_LaneLen_mp = 86 ;
	optional uint32 LM_stRoad_Lane0_LineCross_mp = 87 ;
	optional uint32 LM_stRoad_Lane0_LaneMark0_Quality_mp = 88 ;
	optional float LM_xRoad_Lane0_LaneMark0_C0_mp = 89 ;
	optional float LM_xRoad_Lane0_LaneMark0_C1_mp = 90 ;
	optional float LM_xRoad_Lane0_LaneMark0_C2_mp = 91 ;
	optional float LM_xRoad_Lane0_LaneMark0_C3_mp = 92 ;
	optional float LM_lRoad_Lane0_LaneMark0_RangeStart_mp = 93 ;
	optional float LM_lRoad_Lane0_LaneMark0_RangeEnd_mp = 94 ;
	optional uint32 LM_stRoad_Lane0_LaneMark0_Color_mp = 95 ;
	optional uint32 LM_stRoad_Lane0_LaneMark0_Type_mp = 96 ;
	optional float LM_lRoad_Lane0_LaneMark0_MarkWidth_mp = 97 ;
	optional uint32 LM_stRoad_Lane0_LaneMark0_Src_mp = 98 ;
	optional uint32 LM_stRoad_Lane0_LaneMark1_Quality_mp = 99 ;
	optional float LM_xRoad_Lane0_LaneMark1_C0_mp = 100 ;
	optional float LM_xRoad_Lane0_LaneMark1_C1_mp = 101 ;
	optional float LM_xRoad_Lane0_LaneMark1_C2_mp = 102 ;
	optional float LM_xRoad_Lane0_LaneMark1_C3_mp = 103 ;
	optional float LM_lRoad_Lane0_LaneMark1_RangeStart_mp = 104 ;
	optional float LM_lRoad_Lane0_LaneMark1_RangeEnd_mp = 105 ;
	optional uint32 LM_stRoad_Lane0_LaneMark1_Color_mp = 106 ;
	optional uint32 LM_stRoad_Lane0_LaneMark1_Type_mp = 107 ;
	optional float LM_lRoad_Lane0_LaneMark1_MarkWidth_mp = 108 ;
	optional uint32 LM_stRoad_Lane0_LaneMark1_Src_mp = 109 ;
	optional uint32 LM_stRoad_Lane0_CentralLine_Quality_mp = 110 ;
	optional float LM_xRoad_Lane0_CentralLine_C0_mp = 111 ;
	optional float LM_xRoad_Lane0_CentralLine_C1_mp = 112 ;
	optional float LM_xRoad_Lane0_CentralLine_C2_mp = 113 ;
	optional float LM_xRoad_Lane0_CentralLine_C3_mp = 114 ;
	optional float LM_lRoad_Lane0_CentralLine_RangeStart_mp = 115 ;
	optional float LM_lRoad_Lane0_CentralLine_RangeEnd_mp = 116 ;
	optional uint32 LM_stRoad_Lane0_CentralLine_Color_mp = 117 ;
	optional uint32 LM_stRoad_Lane0_CentralLine_Type_mp = 118 ;
	optional float LM_lRoad_Lane0_CentralLine_MarkWidth_mp = 119 ;
	optional uint32 LM_stRoad_Lane0_CentralLine_Src_mp = 120 ;
	optional uint32 LM_stRoad_Lane1_LaneStatus_mp = 121 ;
	optional float LM_stRoad_Lane1_pctConfidence_mp = 122 ;
	optional uint32 LM_numRoad_Lane1_LaneId_mp = 123 ;
	optional float LM_IRoad_Lane1_LaneWidth_mp = 124 ;
	optional uint32 LM_stRoad_Lane1_LaneDrvDir_mp = 125 ;
	optional uint32 LM_vRoad_Lane1_MinSpdLmt_mp = 126 ;
	optional uint32 LM_vRoad_Lane1_MaxSpdLmt_mp = 127 ;
	optional float LM_stRoad_Lane1_LaneLen_mp = 128 ;
	optional uint32 LM_stRoad_Lane1_LineCross_mp = 129 ;
	optional uint32 LM_stRoad_Lane1_LaneMark0_Quality_mp = 130 ;
	optional float LM_xRoad_Lane1_LaneMark0_C0_mp = 131 ;
	optional float LM_xRoad_Lane1_LaneMark0_C1_mp = 132 ;
	optional float LM_xRoad_Lane1_LaneMark0_C2_mp = 133 ;
	optional float LM_xRoad_Lane1_LaneMark0_C3_mp = 134 ;
	optional float LM_lRoad_Lane1_LaneMark0_RangeStart_mp = 135 ;
	optional float LM_lRoad_Lane1_LaneMark0_RangeEnd_mp = 136 ;
	optional uint32 LM_stRoad_Lane1_LaneMark0_Color_mp = 137 ;
	optional uint32 LM_stRoad_Lane1_LaneMark0_Type_mp = 138 ;
	optional float LM_lRoad_Lane1_LaneMark0_MarkWidth_mp = 139 ;
	optional uint32 LM_stRoad_Lane1_LaneMark0_Src_mp = 140 ;
	optional uint32 LM_stRoad_Lane1_LaneMark1_Quality_mp = 141 ;
	optional float LM_xRoad_Lane1_LaneMark1_C0_mp = 142 ;
	optional float LM_xRoad_Lane1_LaneMark1_C1_mp = 143 ;
	optional float LM_xRoad_Lane1_LaneMark1_C2_mp = 144 ;
	optional float LM_xRoad_Lane1_LaneMark1_C3_mp = 145 ;
	optional float LM_lRoad_Lane1_LaneMark1_RangeStart_mp = 146 ;
	optional float LM_lRoad_Lane1_LaneMark1_RangeEnd_mp = 147 ;
	optional uint32 LM_stRoad_Lane1_LaneMark1_Color_mp = 148 ;
	optional uint32 LM_stRoad_Lane1_LaneMark1_Type_mp = 149 ;
	optional float LM_lRoad_Lane1_LaneMark1_MarkWidth_mp = 150 ;
	optional uint32 LM_stRoad_Lane1_LaneMark1_Src_mp = 151 ;
	optional uint32 LM_stRoad_Lane1_CentralLine_Quality_mp = 152 ;
	optional float LM_xRoad_Lane1_CentralLine_C0_mp = 153 ;
	optional float LM_xRoad_Lane1_CentralLine_C1_mp = 154 ;
	optional float LM_xRoad_Lane1_CentralLine_C2_mp = 155 ;
	optional float LM_xRoad_Lane1_CentralLine_C3_mp = 156 ;
	optional float LM_lRoad_Lane1_CentralLine_RangeStart_mp = 157 ;
	optional float LM_lRoad_Lane1_CentralLine_RangeEnd_mp = 158 ;
	optional uint32 LM_stRoad_Lane1_CentralLine_Color_mp = 159 ;
	optional uint32 LM_stRoad_Lane1_CentralLine_Type_mp = 160 ;
	optional float LM_lRoad_Lane1_CentralLine_MarkWidth_mp = 161 ;
	optional uint32 LM_stRoad_Lane1_CentralLine_Src_mp = 162 ;
	optional uint32 LM_stRoad_Lane2_LaneStatus_mp = 163 ;
	optional float LM_stRoad_Lane2_pctConfidence_mp = 164 ;
	optional uint32 LM_numRoad_Lane2_LaneId_mp = 165 ;
	optional float LM_IRoad_Lane2_LaneWidth_mp = 166 ;
	optional uint32 LM_stRoad_Lane2_LaneDrvDir_mp = 167 ;
	optional uint32 LM_vRoad_Lane2_MinSpdLmt_mp = 168 ;
	optional uint32 LM_vRoad_Lane2_MaxSpdLmt_mp = 169 ;
	optional float LM_stRoad_Lane2_LaneLen_mp = 170 ;
	optional uint32 LM_stRoad_Lane2_LineCross_mp = 171 ;
	optional uint32 LM_stRoad_Lane2_LaneMark0_Quality_mp = 172 ;
	optional float LM_xRoad_Lane2_LaneMark0_C0_mp = 173 ;
	optional float LM_xRoad_Lane2_LaneMark0_C1_mp = 174 ;
	optional float LM_xRoad_Lane2_LaneMark0_C2_mp = 175 ;
	optional float LM_xRoad_Lane2_LaneMark0_C3_mp = 176 ;
	optional float LM_lRoad_Lane2_LaneMark0_RangeStart_mp = 177 ;
	optional float LM_lRoad_Lane2_LaneMark0_RangeEnd_mp = 178 ;
	optional uint32 LM_stRoad_Lane2_LaneMark0_Color_mp = 179 ;
	optional uint32 LM_stRoad_Lane2_LaneMark0_Type_mp = 180 ;
	optional float LM_lRoad_Lane2_LaneMark0_MarkWidth_mp = 181 ;
	optional uint32 LM_stRoad_Lane2_LaneMark0_Src_mp = 182 ;
	optional uint32 LM_stRoad_Lane2_CentralLine_Quality_mp = 183 ;
	optional float LM_xRoad_Lane2_CentralLine_C0_mp = 184 ;
	optional float LM_xRoad_Lane2_CentralLine_C1_mp = 185 ;
	optional float LM_xRoad_Lane2_CentralLine_C2_mp = 186 ;
	optional float LM_xRoad_Lane2_CentralLine_C3_mp = 187 ;
	optional float LM_lRoad_Lane2_CentralLine_RangeStart_mp = 188 ;
	optional float LM_lRoad_Lane2_CentralLine_RangeEnd_mp = 189 ;
	optional uint32 LM_stRoad_Lane2_CentralLine_Color_mp = 190 ;
	optional uint32 LM_stRoad_Lane2_CentralLine_Type_mp = 191 ;
	optional float LM_lRoad_Lane2_CentralLine_MarkWidth_mp = 192 ;
	optional uint32 LM_stRoad_Lane2_CentralLine_Src_mp = 193 ;
	optional uint32 LM_stRoad_Lane2_LaneMark1_Quality_mp = 194 ;
	optional float LM_xRoad_Lane2_LaneMark1_C0_mp = 195 ;
	optional float LM_xRoad_Lane2_LaneMark1_C1_mp = 196 ;
	optional float LM_xRoad_Lane2_LaneMark1_C2_mp = 197 ;
	optional float LM_xRoad_Lane2_LaneMark1_C3_mp = 198 ;
	optional float LM_lRoad_Lane2_LaneMark1_RangeStart_mp = 199 ;
	optional float LM_lRoad_Lane2_LaneMark1_RangeEnd_mp = 200 ;
	optional uint32 LM_stRoad_Lane2_LaneMark1_Color_mp = 201 ;
	optional uint32 LM_stRoad_Lane2_LaneMark1_Type_mp = 202 ;
	optional float LM_lRoad_Lane2_LaneMark1_MarkWidth_mp = 203 ;
	optional uint32 LM_stRoad_Lane2_LaneMark1_Src_mp = 204 ;
	optional uint32 LM_stRoad_Lane3_LaneStatus_mp = 205 ;
	optional float LM_stRoad_Lane3_pctConfidence_mp = 206 ;
	optional uint32 LM_numRoad_Lane3_LaneId_mp = 207 ;
	optional float LM_IRoad_Lane3_LaneWidth_mp = 208 ;
	optional uint32 LM_stRoad_Lane3_LaneDrvDir_mp = 209 ;
	optional uint32 LM_vRoad_Lane3_MinSpdLmt_mp = 210 ;
	optional uint32 LM_vRoad_Lane3_MaxSpdLmt_mp = 211 ;
	optional float LM_stRoad_Lane3_LaneLen_mp = 212 ;
	optional uint32 LM_stRoad_Lane3_LineCross_mp = 213 ;
	optional uint32 LM_stRoad_Lane3_LaneMark0_Quality_mp = 214 ;
	optional float LM_xRoad_Lane3_LaneMark0_C0_mp = 215 ;
	optional float LM_xRoad_Lane3_LaneMark0_C1_mp = 216 ;
	optional float LM_xRoad_Lane3_LaneMark0_C2_mp = 217 ;
	optional float LM_xRoad_Lane3_LaneMark0_C3_mp = 218 ;
	optional float LM_lRoad_Lane3_LaneMark0_RangeStart_mp = 219 ;
	optional float LM_lRoad_Lane3_LaneMark0_RangeEnd_mp = 220 ;
	optional uint32 LM_stRoad_Lane3_LaneMark0_Color_mp = 221 ;
	optional uint32 LM_stRoad_Lane3_LaneMark0_Type_mp = 222 ;
	optional float LM_lRoad_Lane3_LaneMark0_MarkWidth_mp = 223 ;
	optional uint32 LM_stRoad_Lane3_LaneMark0_Src_mp = 224 ;
	optional uint32 LM_stRoad_Lane3_CentralLine_Quality_mp = 225 ;
	optional float LM_xRoad_Lane3_CentralLine_C0_mp = 226 ;
	optional float LM_xRoad_Lane3_CentralLine_C1_mp = 227 ;
	optional float LM_xRoad_Lane3_CentralLine_C2_mp = 228 ;
	optional float LM_xRoad_Lane3_CentralLine_C3_mp = 229 ;
	optional float LM_lRoad_Lane3_CentralLine_RangeStart_mp = 230 ;
	optional float LM_lRoad_Lane3_CentralLine_RangeEnd_mp = 231 ;
	optional uint32 LM_stRoad_Lane3_CentralLine_Color_mp = 232 ;
	optional uint32 LM_stRoad_Lane3_CentralLine_Type_mp = 233 ;
	optional float LM_lRoad_Lane3_CentralLine_MarkWidth_mp = 234 ;
	optional uint32 LM_stRoad_Lane3_CentralLine_Src_mp = 235 ;
	optional uint32 LM_stRoad_Lane3_LaneMark1_Quality_mp = 236 ;
	optional float LM_xRoad_Lane3_LaneMark1_C0_mp = 237 ;
	optional float LM_xRoad_Lane3_LaneMark1_C1_mp = 238 ;
	optional float LM_xRoad_Lane3_LaneMark1_C2_mp = 239 ;
	optional float LM_xRoad_Lane3_LaneMark1_C3_mp = 240 ;
	optional float LM_lRoad_Lane3_LaneMark1_RangeStart_mp = 241 ;
	optional float LM_lRoad_Lane3_LaneMark1_RangeEnd_mp = 242 ;
	optional uint32 LM_stRoad_Lane3_LaneMark1_Color_mp = 243 ;
	optional uint32 LM_stRoad_Lane3_LaneMark1_Type_mp = 244 ;
	optional float LM_lRoad_Lane3_LaneMark1_MarkWidth_mp = 245 ;
	optional uint32 LM_stRoad_Lane3_LaneMark1_Src_mp = 246 ;
	optional uint32 LM_stRoad_Lane4_LaneStatus_mp = 247 ;
	optional float LM_stRoad_Lane4_pctConfidence_mp = 248 ;
	optional uint32 LM_numRoad_Lane4_LaneId_mp = 249 ;
	optional float LM_IRoad_Lane4_LaneWidth_mp = 250 ;
	optional uint32 LM_stRoad_Lane4_LaneDrvDir_mp = 251 ;
	optional uint32 LM_vRoad_Lane4_MinSpdLmt_mp = 252 ;
	optional uint32 LM_vRoad_Lane4_MaxSpdLmt_mp = 253 ;
	optional float LM_stRoad_Lane4_LaneLen_mp = 254 ;
	optional uint32 LM_stRoad_Lane4_LineCross_mp = 255 ;
	optional uint32 LM_stRoad_Lane4_LaneMark0_Quality_mp = 256 ;
	optional float LM_xRoad_Lane4_LaneMark0_C0_mp = 257 ;
	optional float LM_xRoad_Lane4_LaneMark0_C1_mp = 258 ;
	optional float LM_xRoad_Lane4_LaneMark0_C2_mp = 259 ;
	optional float LM_xRoad_Lane4_LaneMark0_C3_mp = 260 ;
	optional float LM_lRoad_Lane4_LaneMark0_RangeStart_mp = 261 ;
	optional float LM_lRoad_Lane4_LaneMark0_RangeEnd_mp = 262 ;
	optional uint32 LM_stRoad_Lane4_LaneMark0_Color_mp = 263 ;
	optional uint32 LM_stRoad_Lane4_LaneMark0_Type_mp = 264 ;
	optional float LM_lRoad_Lane4_LaneMark0_MarkWidth_mp = 265 ;
	optional uint32 LM_stRoad_Lane4_LaneMark0_Src_mp = 266 ;
	optional uint32 LM_stRoad_Lane4_CentralLine_Quality_mp = 267 ;
	optional float LM_xRoad_Lane4_CentralLine_C0_mp = 268 ;
	optional float LM_xRoad_Lane4_CentralLine_C1_mp = 269 ;
	optional float LM_xRoad_Lane4_CentralLine_C2_mp = 270 ;
	optional float LM_xRoad_Lane4_CentralLine_C3_mp = 271 ;
	optional float LM_lRoad_Lane4_CentralLine_RangeStart_mp = 272 ;
	optional float LM_lRoad_Lane4_CentralLine_RangeEnd_mp = 273 ;
	optional uint32 LM_stRoad_Lane4_CentralLine_Color_mp = 274 ;
	optional uint32 LM_stRoad_Lane4_CentralLine_Type_mp = 275 ;
	optional float LM_lRoad_Lane4_CentralLine_MarkWidth_mp = 276 ;
	optional uint32 LM_stRoad_Lane4_CentralLine_Src_mp = 277 ;
	optional uint32 LM_stRoad_Lane4_LaneMark1_Quality_mp = 278 ;
	optional float LM_xRoad_Lane4_LaneMark1_C0_mp = 279 ;
	optional float LM_xRoad_Lane4_LaneMark1_C1_mp = 280 ;
	optional float LM_xRoad_Lane4_LaneMark1_C2_mp = 281 ;
	optional float LM_xRoad_Lane4_LaneMark1_C3_mp = 282 ;
	optional float LM_lRoad_Lane4_LaneMark1_RangeStart_mp = 283 ;
	optional float LM_lRoad_Lane4_LaneMark1_RangeEnd_mp = 284 ;
	optional uint32 LM_stRoad_Lane4_LaneMark1_Color_mp = 285 ;
	optional uint32 LM_stRoad_Lane4_LaneMark1_Type_mp = 286 ;
	optional float LM_lRoad_Lane4_LaneMark1_MarkWidth_mp = 287 ;
	optional uint32 LM_stRoad_Lane4_LaneMark1_Src_mp = 288 ;
	optional uint32 LM_stRoad_Lane5_LaneStatus_mp = 289 ;
	optional float LM_stRoad_Lane5_pctConfidence_mp = 290 ;
	optional uint32 LM_numRoad_Lane5_LaneId_mp = 291 ;
	optional float LM_IRoad_Lane5_LaneWidth_mp = 292 ;
	optional uint32 LM_stRoad_Lane5_LaneDrvDir_mp = 293 ;
	optional uint32 LM_vRoad_Lane5_MinSpdLmt_mp = 294 ;
	optional uint32 LM_vRoad_Lane5_MaxSpdLmt_mp = 295 ;
	optional float LM_stRoad_Lane5_LaneLen_mp = 296 ;
	optional uint32 LM_stRoad_Lane5_LineCross_mp = 297 ;
	optional uint32 LM_stRoad_Lane5_LaneMark0_Quality_mp = 298 ;
	optional float LM_xRoad_Lane5_LaneMark0_C0_mp = 299 ;
	optional float LM_xRoad_Lane5_LaneMark0_C1_mp = 300 ;
	optional float LM_xRoad_Lane5_LaneMark0_C2_mp = 301 ;
	optional float LM_xRoad_Lane5_LaneMark0_C3_mp = 302 ;
	optional float LM_lRoad_Lane5_LaneMark0_RangeStart_mp = 303 ;
	optional float LM_lRoad_Lane5_LaneMark0_RangeEnd_mp = 304 ;
	optional uint32 LM_stRoad_Lane5_LaneMark0_Color_mp = 305 ;
	optional uint32 LM_stRoad_Lane5_LaneMark0_Type_mp = 306 ;
	optional float LM_lRoad_Lane5_LaneMark0_MarkWidth_mp = 307 ;
	optional uint32 LM_stRoad_Lane5_LaneMark0_Src_mp = 308 ;
	optional uint32 LM_stRoad_Lane5_CentralLine_Quality_mp = 309 ;
	optional float LM_xRoad_Lane5_CentralLine_C0_mp = 310 ;
	optional float LM_xRoad_Lane5_CentralLine_C1_mp = 311 ;
	optional float LM_xRoad_Lane5_CentralLine_C2_mp = 312 ;
	optional float LM_xRoad_Lane5_CentralLine_C3_mp = 313 ;
	optional float LM_lRoad_Lane5_CentralLine_RangeStart_mp = 314 ;
	optional float LM_lRoad_Lane5_CentralLine_RangeEnd_mp = 315 ;
	optional uint32 LM_stRoad_Lane5_CentralLine_Color_mp = 316 ;
	optional uint32 LM_stRoad_Lane5_CentralLine_Type_mp = 317 ;
	optional float LM_lRoad_Lane5_CentralLine_MarkWidth_mp = 318 ;
	optional uint32 LM_stRoad_Lane5_CentralLine_Src_mp = 319 ;
	optional uint32 LM_stRoad_Lane5_LaneMark1_Quality_mp = 320 ;
	optional float LM_xRoad_Lane5_LaneMark1_C0_mp = 321 ;
	optional float LM_xRoad_Lane5_LaneMark1_C1_mp = 322 ;
	optional float LM_xRoad_Lane5_LaneMark1_C2_mp = 323 ;
	optional float LM_xRoad_Lane5_LaneMark1_C3_mp = 324 ;
	optional float LM_lRoad_Lane5_LaneMark1_RangeStart_mp = 325 ;
	optional float LM_lRoad_Lane5_LaneMark1_RangeEnd_mp = 326 ;
	optional uint32 LM_stRoad_Lane5_LaneMark1_Color_mp = 327 ;
	optional uint32 LM_stRoad_Lane5_LaneMark1_Type_mp = 328 ;
	optional float LM_lRoad_Lane5_LaneMark1_MarkWidth_mp = 329 ;
	optional uint32 LM_stRoad_Lane5_LaneMark1_Src_mp = 330 ;
	optional uint32 LM_stRoad_Lane6_LaneStatus_mp = 331 ;
	optional float LM_stRoad_Lane6_pctConfidence_mp = 332 ;
	optional uint32 LM_numRoad_Lane6_LaneId_mp = 333 ;
	optional float LM_IRoad_Lane6_LaneWidth_mp = 334 ;
	optional uint32 LM_stRoad_Lane6_LaneDrvDir_mp = 335 ;
	optional uint32 LM_vRoad_Lane6_MinSpdLmt_mp = 336 ;
	optional uint32 LM_vRoad_Lane6_MaxSpdLmt_mp = 337 ;
	optional float LM_stRoad_Lane6_LaneLen_mp = 338 ;
	optional uint32 LM_stRoad_Lane6_LineCross_mp = 339 ;
	optional uint32 LM_stRoad_Lane6_LaneMark0_Quality_mp = 340 ;
	optional float LM_xRoad_Lane6_LaneMark0_C0_mp = 341 ;
	optional float LM_xRoad_Lane6_LaneMark0_C1_mp = 342 ;
	optional float LM_xRoad_Lane6_LaneMark0_C2_mp = 343 ;
	optional float LM_xRoad_Lane6_LaneMark0_C3_mp = 344 ;
	optional float LM_lRoad_Lane6_LaneMark0_RangeStart_mp = 345 ;
	optional float LM_lRoad_Lane6_LaneMark0_RangeEnd_mp = 346 ;
	optional uint32 LM_stRoad_Lane6_LaneMark0_Color_mp = 347 ;
	optional uint32 LM_stRoad_Lane6_LaneMark0_Type_mp = 348 ;
	optional float LM_lRoad_Lane6_LaneMark0_MarkWidth_mp = 349 ;
	optional uint32 LM_stRoad_Lane6_LaneMark0_Src_mp = 350 ;
	optional uint32 LM_stRoad_Lane6_CentralLine_Quality_mp = 351 ;
	optional float LM_xRoad_Lane6_CentralLine_C0_mp = 352 ;
	optional float LM_xRoad_Lane6_CentralLine_C1_mp = 353 ;
	optional float LM_xRoad_Lane6_CentralLine_C2_mp = 354 ;
	optional float LM_xRoad_Lane6_CentralLine_C3_mp = 355 ;
	optional float LM_lRoad_Lane6_CentralLine_RangeStart_mp = 356 ;
	optional float LM_lRoad_Lane6_CentralLine_RangeEnd_mp = 357 ;
	optional uint32 LM_stRoad_Lane6_CentralLine_Color_mp = 358 ;
	optional uint32 LM_stRoad_Lane6_CentralLine_Type_mp = 359 ;
	optional float LM_lRoad_Lane6_CentralLine_MarkWidth_mp = 360 ;
	optional uint32 LM_stRoad_Lane6_CentralLine_Src_mp = 361 ;
	optional uint32 LM_stRoad_Lane6_LaneMark1_Quality_mp = 362 ;
	optional float LM_xRoad_Lane6_LaneMark1_C0_mp = 363 ;
	optional float LM_xRoad_Lane6_LaneMark1_C1_mp = 364 ;
	optional float LM_xRoad_Lane6_LaneMark1_C2_mp = 365 ;
	optional float LM_xRoad_Lane6_LaneMark1_C3_mp = 366 ;
	optional float LM_lRoad_Lane6_LaneMark1_RangeStart_mp = 367 ;
	optional float LM_lRoad_Lane6_LaneMark1_RangeEnd_mp = 368 ;
	optional uint32 LM_stRoad_Lane6_LaneMark1_Color_mp = 369 ;
	optional uint32 LM_stRoad_Lane6_LaneMark1_Type_mp = 370 ;
	optional float LM_lRoad_Lane6_LaneMark1_MarkWidth_mp = 371 ;
	optional uint32 LM_stRoad_Lane6_LaneMark1_Src_mp = 372 ;
	optional uint32 LM_stRoad_Lane7_LaneStatus_mp = 373 ;
	optional float LM_stRoad_Lane7_pctConfidence_mp = 374 ;
	optional uint32 LM_numRoad_Lane7_LaneId_mp = 375 ;
	optional float LM_IRoad_Lane7_LaneWidth_mp = 376 ;
	optional uint32 LM_stRoad_Lane7_LaneDrvDir_mp = 377 ;
	optional uint32 LM_vRoad_Lane7_MinSpdLmt_mp = 378 ;
	optional uint32 LM_vRoad_Lane7_MaxSpdLmt_mp = 379 ;
	optional float LM_stRoad_Lane7_LaneLen_mp = 380 ;
	optional uint32 LM_stRoad_Lane7_LineCross_mp = 381 ;
	optional uint32 LM_stRoad_Lane7_LaneMark0_Quality_mp = 382 ;
	optional float LM_xRoad_Lane7_LaneMark0_C0_mp = 383 ;
	optional float LM_xRoad_Lane7_LaneMark0_C1_mp = 384 ;
	optional float LM_xRoad_Lane7_LaneMark0_C2_mp = 385 ;
	optional float LM_xRoad_Lane7_LaneMark0_C3_mp = 386 ;
	optional float LM_lRoad_Lane7_LaneMark0_RangeStart_mp = 387 ;
	optional float LM_lRoad_Lane7_LaneMark0_RangeEnd_mp = 388 ;
	optional uint32 LM_stRoad_Lane7_LaneMark0_Color_mp = 389 ;
	optional uint32 LM_stRoad_Lane7_LaneMark0_Type_mp = 390 ;
	optional float LM_lRoad_Lane7_LaneMark0_MarkWidth_mp = 391 ;
	optional uint32 LM_stRoad_Lane7_LaneMark0_Src_mp = 392 ;
	optional uint32 LM_stRoad_Lane7_CentralLine_Quality_mp = 393 ;
	optional float LM_xRoad_Lane7_CentralLine_C0_mp = 394 ;
	optional float LM_xRoad_Lane7_CentralLine_C1_mp = 395 ;
	optional float LM_xRoad_Lane7_CentralLine_C2_mp = 396 ;
	optional float LM_xRoad_Lane7_CentralLine_C3_mp = 397 ;
	optional float LM_lRoad_Lane7_CentralLine_RangeStart_mp = 398 ;
	optional float LM_lRoad_Lane7_CentralLine_RangeEnd_mp = 399 ;
	optional uint32 LM_stRoad_Lane7_CentralLine_Color_mp = 400 ;
	optional uint32 LM_stRoad_Lane7_CentralLine_Type_mp = 401 ;
	optional float LM_lRoad_Lane7_CentralLine_MarkWidth_mp = 402 ;
	optional uint32 LM_stRoad_Lane7_CentralLine_Src_mp = 403 ;
	optional uint32 LM_stRoad_Lane7_LaneMark1_Quality_mp = 404 ;
	optional float LM_xRoad_Lane7_LaneMark1_C0_mp = 405 ;
	optional float LM_xRoad_Lane7_LaneMark1_C1_mp = 406 ;
	optional float LM_xRoad_Lane7_LaneMark1_C2_mp = 407 ;
	optional float LM_xRoad_Lane7_LaneMark1_C3_mp = 408 ;
	optional float LM_lRoad_Lane7_LaneMark1_RangeStart_mp = 409 ;
	optional float LM_lRoad_Lane7_LaneMark1_RangeEnd_mp = 410 ;
	optional uint32 LM_stRoad_Lane7_LaneMark1_Color_mp = 411 ;
	optional uint32 LM_stRoad_Lane7_LaneMark1_Type_mp = 412 ;
	optional float LM_lRoad_Lane7_LaneMark1_MarkWidth_mp = 413 ;
	optional uint32 LM_stRoad_Lane7_LaneMark1_Src_mp = 414 ;
	optional uint32 LM_stRoadType_mp = 415 ;
	optional uint32 LM_numRoadDynLaneNumber_mp = 416 ;
	optional uint32 LM_stRoadDynCondition_mp = 417 ;
	optional uint32 LM_stRoadDynEdge0_Quality_mp = 418 ;
	optional float LM_xRoadDynEdge0_C0_mp = 419 ;
	optional float LM_xRoadDynEdge0_C1_mp = 420 ;
	optional float LM_xRoadDynEdge0_C2_mp = 421 ;
	optional float LM_xRoadDynEdge0_C3_mp = 422 ;
	optional float LM_lRoadDynEdge0_RangeStart_mp = 423 ;
	optional float LM_lRoadDynEdge0_RangeEnd_mp = 424 ;
	optional uint32 LM_stRoadDynEdge0_Color_mp = 425 ;
	optional uint32 LM_stRoadDynEdge0_Type_mp = 426 ;
	optional float LM_lRoadDynEdge0_MarkWidth_mp = 427 ;
	optional uint32 LM_stRoadDynEdge0_Src_mp = 428 ;
	optional uint32 LM_stRoadDynEdge1_Quality_mp = 429 ;
	optional float LM_xRoadDynEdge1_C0_mp = 430 ;
	optional float LM_xRoadDynEdge1_C1_mp = 431 ;
	optional float LM_xRoadDynEdge1_C2_mp = 432 ;
	optional float LM_xRoadDynEdge1_C3_mp = 433 ;
	optional float LM_lRoadDynEdge1_RangeStart_mp = 434 ;
	optional float LM_lRoadDynEdge1_RangeEnd_mp = 435 ;
	optional uint32 LM_stRoadDynEdge1_Color_mp = 436 ;
	optional uint32 LM_stRoadDynEdge1_Type_mp = 437 ;
	optional float LM_lRoadDynEdge1_MarkWidth_mp = 438 ;
	optional uint32 LM_stRoadDynEdge1_Src_mp = 439 ;
	optional uint32 LM_stRoadDyn_Lane0_LaneStatus_mp = 440 ;
	optional float LM_stRoadDyn_Lane0_pctConfidence_mp = 441 ;
	optional uint32 LM_numRoadDyn_Lane0_LaneId_mp = 442 ;
	optional float LM_IRoadDyn_Lane0_LaneWidth_mp = 443 ;
	optional uint32 LM_stRoadDyn_Lane0_LaneDrvDir_mp = 444 ;
	optional uint32 LM_vRoadDyn_Lane0_MinSpdLmt_mp = 445 ;
	optional uint32 LM_vRoadDyn_Lane0_MaxSpdLmt_mp = 446 ;
	optional float LM_stRoadDyn_Lane0_LaneLen_mp = 447 ;
	optional uint32 LM_stRoadDyn_Lane0_LineCross_mp = 448 ;
	optional uint32 LM_stRoadDyn_Lane0_LaneMark0_Quality_mp = 449 ;
	optional float LM_xRoadDyn_Lane0_LaneMark0_C0_mp = 450 ;
	optional float LM_xRoadDyn_Lane0_LaneMark0_C1_mp = 451 ;
	optional float LM_xRoadDyn_Lane0_LaneMark0_C2_mp = 452 ;
	optional float LM_xRoadDyn_Lane0_LaneMark0_C3_mp = 453 ;
	optional float LM_lRoadDyn_Lane0_LaneMark0_RangeStart_mp = 454 ;
	optional float LM_lRoadDyn_Lane0_LaneMark0_RangeEnd_mp = 455 ;
	optional uint32 LM_stRoadDyn_Lane0_LaneMark0_Color_mp = 456 ;
	optional uint32 LM_stRoadDyn_Lane0_LaneMark0_Type_mp = 457 ;
	optional float LM_lRoadDyn_Lane0_LaneMark0_MarkWidth_mp = 458 ;
	optional uint32 LM_stRoadDyn_Lane0_LaneMark0_Src_mp = 459 ;
	optional uint32 LM_stRoadDyn_Lane0_LaneMark1_Quality_mp = 460 ;
	optional float LM_xRoadDyn_Lane0_LaneMark1_C0_mp = 461 ;
	optional float LM_xRoadDyn_Lane0_LaneMark1_C1_mp = 462 ;
	optional float LM_xRoadDyn_Lane0_LaneMark1_C2_mp = 463 ;
	optional float LM_xRoadDyn_Lane0_LaneMark1_C3_mp = 464 ;
	optional float LM_lRoadDyn_Lane0_LaneMark1_RangeStart_mp = 465 ;
	optional float LM_lRoadDyn_Lane0_LaneMark1_RangeEnd_mp = 466 ;
	optional uint32 LM_stRoadDyn_Lane0_LaneMark1_Color_mp = 467 ;
	optional uint32 LM_stRoadDyn_Lane0_LaneMark1_Type_mp = 468 ;
	optional float LM_lRoadDyn_Lane0_LaneMark1_MarkWidth_mp = 469 ;
	optional uint32 LM_stRoadDyn_Lane0_LaneMark1_Src_mp = 470 ;
	optional uint32 LM_stRoadDyn_Lane0_CentralLine_Quality_mp = 471 ;
	optional float LM_xRoadDyn_Lane0_CentralLine_C0_mp = 472 ;
	optional float LM_xRoadDyn_Lane0_CentralLine_C1_mp = 473 ;
	optional float LM_xRoadDyn_Lane0_CentralLine_C2_mp = 474 ;
	optional float LM_xRoadDyn_Lane0_CentralLine_C3_mp = 475 ;
	optional float LM_lRoadDyn_Lane0_CentralLine_RangeStart_mp = 476 ;
	optional float LM_lRoadDyn_Lane0_CentralLine_RangeEnd_mp = 477 ;
	optional uint32 LM_stRoadDyn_Lane0_CentralLine_Color_mp = 478 ;
	optional uint32 LM_stRoadDyn_Lane0_CentralLine_Type_mp = 479 ;
	optional float LM_lRoadDyn_Lane0_CentralLine_MarkWidth_mp = 480 ;
	optional uint32 LM_stRoadDyn_Lane0_CentralLine_Src_mp = 481 ;
	optional uint32 LM_stRoadDyn_Lane1_LaneStatus_mp = 482 ;
	optional float LM_stRoadDyn_Lane1_pctConfidence_mp = 483 ;
	optional uint32 LM_numRoadDyn_Lane1_LaneId_mp = 484 ;
	optional float LM_IRoadDyn_Lane1_LaneWidth_mp = 485 ;
	optional uint32 LM_stRoadDyn_Lane1_LaneDrvDir_mp = 486 ;
	optional uint32 LM_vRoadDyn_Lane1_MinSpdLmt_mp = 487 ;
	optional uint32 LM_vRoadDyn_Lane1_MaxSpdLmt_mp = 488 ;
	optional float LM_stRoadDyn_Lane1_LaneLen_mp = 489 ;
	optional uint32 LM_stRoadDyn_Lane1_LineCross_mp = 490 ;
	optional uint32 LM_stRoadDyn_Lane1_LaneMark0_Quality_mp = 491 ;
	optional float LM_xRoadDyn_Lane1_LaneMark0_C0_mp = 492 ;
	optional float LM_xRoadDyn_Lane1_LaneMark0_C1_mp = 493 ;
	optional float LM_xRoadDyn_Lane1_LaneMark0_C2_mp = 494 ;
	optional float LM_xRoadDyn_Lane1_LaneMark0_C3_mp = 495 ;
	optional float LM_lRoadDyn_Lane1_LaneMark0_RangeStart_mp = 496 ;
	optional float LM_lRoadDyn_Lane1_LaneMark0_RangeEnd_mp = 497 ;
	optional uint32 LM_stRoadDyn_Lane1_LaneMark0_Color_mp = 498 ;
	optional uint32 LM_stRoadDyn_Lane1_LaneMark0_Type_mp = 499 ;
	optional float LM_lRoadDyn_Lane1_LaneMark0_MarkWidth_mp = 500 ;
	optional uint32 LM_stRoadDyn_Lane1_LaneMark0_Src_mp = 501 ;
	optional uint32 LM_stRoadDyn_Lane1_LaneMark1_Quality_mp = 502 ;
	optional float LM_xRoadDyn_Lane1_LaneMark1_C0_mp = 503 ;
	optional float LM_xRoadDyn_Lane1_LaneMark1_C1_mp = 504 ;
	optional float LM_xRoadDyn_Lane1_LaneMark1_C2_mp = 505 ;
	optional float LM_xRoadDyn_Lane1_LaneMark1_C3_mp = 506 ;
	optional float LM_lRoadDyn_Lane1_LaneMark1_RangeStart_mp = 507 ;
	optional float LM_lRoadDyn_Lane1_LaneMark1_RangeEnd_mp = 508 ;
	optional uint32 LM_stRoadDyn_Lane1_LaneMark1_Color_mp = 509 ;
	optional uint32 LM_stRoadDyn_Lane1_LaneMark1_Type_mp = 510 ;
	optional float LM_lRoadDyn_Lane1_LaneMark1_MarkWidth_mp = 511 ;
	optional uint32 LM_stRoadDyn_Lane1_LaneMark1_Src_mp = 512 ;
	optional uint32 LM_stRoadDyn_Lane1_CentralLine_Quality_mp = 513 ;
	optional float LM_xRoadDyn_Lane1_CentralLine_C0_mp = 514 ;
	optional float LM_xRoadDyn_Lane1_CentralLine_C1_mp = 515 ;
	optional float LM_xRoadDyn_Lane1_CentralLine_C2_mp = 516 ;
	optional float LM_xRoadDyn_Lane1_CentralLine_C3_mp = 517 ;
	optional float LM_lRoadDyn_Lane1_CentralLine_RangeStart_mp = 518 ;
	optional float LM_lRoadDyn_Lane1_CentralLine_RangeEnd_mp = 519 ;
	optional uint32 LM_stRoadDyn_Lane1_CentralLine_Color_mp = 520 ;
	optional uint32 LM_stRoadDyn_Lane1_CentralLine_Type_mp = 521 ;
	optional float LM_lRoadDyn_Lane1_CentralLine_MarkWidth_mp = 522 ;
	optional uint32 LM_stRoadDyn_Lane1_CentralLine_Src_mp = 523 ;
	optional uint32 LM_stRoadDyn_Lane2_LaneStatus_mp = 524 ;
	optional float LM_stRoadDyn_Lane2_pctConfidence_mp = 525 ;
	optional uint32 LM_numRoadDyn_Lane2_LaneId_mp = 526 ;
	optional float LM_IRoadDyn_Lane2_LaneWidth_mp = 527 ;
	optional uint32 LM_stRoadDyn_Lane2_LaneDrvDir_mp = 528 ;
	optional uint32 LM_vRoadDyn_Lane2_MinSpdLmt_mp = 529 ;
	optional uint32 LM_vRoadDyn_Lane2_MaxSpdLmt_mp = 530 ;
	optional float LM_stRoadDyn_Lane2_LaneLen_mp = 531 ;
	optional uint32 LM_stRoadDyn_Lane2_LineCross_mp = 532 ;
	optional uint32 LM_stRoadDyn_Lane2_LaneMark0_Quality_mp = 533 ;
	optional float LM_xRoadDyn_Lane2_LaneMark0_C0_mp = 534 ;
	optional float LM_xRoadDyn_Lane2_LaneMark0_C1_mp = 535 ;
	optional float LM_xRoadDyn_Lane2_LaneMark0_C2_mp = 536 ;
	optional float LM_xRoadDyn_Lane2_LaneMark0_C3_mp = 537 ;
	optional float LM_lRoadDyn_Lane2_LaneMark0_RangeStart_mp = 538 ;
	optional float LM_lRoadDyn_Lane2_LaneMark0_RangeEnd_mp = 539 ;
	optional uint32 LM_stRoadDyn_Lane2_LaneMark0_Color_mp = 540 ;
	optional uint32 LM_stRoadDyn_Lane2_LaneMark0_Type_mp = 541 ;
	optional float LM_lRoadDyn_Lane2_LaneMark0_MarkWidth_mp = 542 ;
	optional uint32 LM_stRoadDyn_Lane2_LaneMark0_Src_mp = 543 ;
	optional uint32 LM_stRoadDyn_Lane2_CentralLine_Quality_mp = 544 ;
	optional float LM_xRoadDyn_Lane2_CentralLine_C0_mp = 545 ;
	optional float LM_xRoadDyn_Lane2_CentralLine_C1_mp = 546 ;
	optional float LM_xRoadDyn_Lane2_CentralLine_C2_mp = 547 ;
	optional float LM_xRoadDyn_Lane2_CentralLine_C3_mp = 548 ;
	optional float LM_lRoadDyn_Lane2_CentralLine_RangeStart_mp = 549 ;
	optional float LM_lRoadDyn_Lane2_CentralLine_RangeEnd_mp = 550 ;
	optional uint32 LM_stRoadDyn_Lane2_CentralLine_Color_mp = 551 ;
	optional uint32 LM_stRoadDyn_Lane2_CentralLine_Type_mp = 552 ;
	optional float LM_lRoadDyn_Lane2_CentralLine_MarkWidth_mp = 553 ;
	optional uint32 LM_stRoadDyn_Lane2_CentralLine_Src_mp = 554 ;
	optional uint32 LM_stRoadDyn_Lane2_LaneMark1_Quality_mp = 555 ;
	optional float LM_xRoadDyn_Lane2_LaneMark1_C0_mp = 556 ;
	optional float LM_xRoadDyn_Lane2_LaneMark1_C1_mp = 557 ;
	optional float LM_xRoadDyn_Lane2_LaneMark1_C2_mp = 558 ;
	optional float LM_xRoadDyn_Lane2_LaneMark1_C3_mp = 559 ;
	optional float LM_lRoadDyn_Lane2_LaneMark1_RangeStart_mp = 560 ;
	optional float LM_lRoadDyn_Lane2_LaneMark1_RangeEnd_mp = 561 ;
	optional uint32 LM_stRoadDyn_Lane2_LaneMark1_Color_mp = 562 ;
	optional uint32 LM_stRoadDyn_Lane2_LaneMark1_Type_mp = 563 ;
	optional float LM_lRoadDyn_Lane2_LaneMark1_MarkWidth_mp = 564 ;
	optional uint32 LM_stRoadDyn_Lane2_LaneMark1_Src_mp = 565 ;
	optional uint32 LM_stRoadDyn_Lane3_LaneStatus_mp = 566 ;
	optional float LM_stRoadDyn_Lane3_pctConfidence_mp = 567 ;
	optional uint32 LM_numRoadDyn_Lane3_LaneId_mp = 568 ;
	optional float LM_IRoadDyn_Lane3_LaneWidth_mp = 569 ;
	optional uint32 LM_stRoadDyn_Lane3_LaneDrvDir_mp = 570 ;
	optional uint32 LM_vRoadDyn_Lane3_MinSpdLmt_mp = 571 ;
	optional uint32 LM_vRoadDyn_Lane3_MaxSpdLmt_mp = 572 ;
	optional float LM_stRoadDyn_Lane3_LaneLen_mp = 573 ;
	optional uint32 LM_stRoadDyn_Lane3_LineCross_mp = 574 ;
	optional uint32 LM_stRoadDyn_Lane3_LaneMark0_Quality_mp = 575 ;
	optional float LM_xRoadDyn_Lane3_LaneMark0_C0_mp = 576 ;
	optional float LM_xRoadDyn_Lane3_LaneMark0_C1_mp = 577 ;
	optional float LM_xRoadDyn_Lane3_LaneMark0_C2_mp = 578 ;
	optional float LM_xRoadDyn_Lane3_LaneMark0_C3_mp = 579 ;
	optional float LM_lRoadDyn_Lane3_LaneMark0_RangeStart_mp = 580 ;
	optional float LM_lRoadDyn_Lane3_LaneMark0_RangeEnd_mp = 581 ;
	optional uint32 LM_stRoadDyn_Lane3_LaneMark0_Color_mp = 582 ;
	optional uint32 LM_stRoadDyn_Lane3_LaneMark0_Type_mp = 583 ;
	optional float LM_lRoadDyn_Lane3_LaneMark0_MarkWidth_mp = 584 ;
	optional uint32 LM_stRoadDyn_Lane3_LaneMark0_Src_mp = 585 ;
	optional uint32 LM_stRoadDyn_Lane3_CentralLine_Quality_mp = 586 ;
	optional float LM_xRoadDyn_Lane3_CentralLine_C0_mp = 587 ;
	optional float LM_xRoadDyn_Lane3_CentralLine_C1_mp = 588 ;
	optional float LM_xRoadDyn_Lane3_CentralLine_C2_mp = 589 ;
	optional float LM_xRoadDyn_Lane3_CentralLine_C3_mp = 590 ;
	optional float LM_lRoadDyn_Lane3_CentralLine_RangeStart_mp = 591 ;
	optional float LM_lRoadDyn_Lane3_CentralLine_RangeEnd_mp = 592 ;
	optional uint32 LM_stRoadDyn_Lane3_CentralLine_Color_mp = 593 ;
	optional uint32 LM_stRoadDyn_Lane3_CentralLine_Type_mp = 594 ;
	optional float LM_lRoadDyn_Lane3_CentralLine_MarkWidth_mp = 595 ;
	optional uint32 LM_stRoadDyn_Lane3_CentralLine_Src_mp = 596 ;
	optional uint32 LM_stRoadDyn_Lane3_LaneMark1_Quality_mp = 597 ;
	optional float LM_xRoadDyn_Lane3_LaneMark1_C0_mp = 598 ;
	optional float LM_xRoadDyn_Lane3_LaneMark1_C1_mp = 599 ;
	optional float LM_xRoadDyn_Lane3_LaneMark1_C2_mp = 600 ;
	optional float LM_xRoadDyn_Lane3_LaneMark1_C3_mp = 601 ;
	optional float LM_lRoadDyn_Lane3_LaneMark1_RangeStart_mp = 602 ;
	optional float LM_lRoadDyn_Lane3_LaneMark1_RangeEnd_mp = 603 ;
	optional uint32 LM_stRoadDyn_Lane3_LaneMark1_Color_mp = 604 ;
	optional uint32 LM_stRoadDyn_Lane3_LaneMark1_Type_mp = 605 ;
	optional float LM_lRoadDyn_Lane3_LaneMark1_MarkWidth_mp = 606 ;
	optional uint32 LM_stRoadDyn_Lane3_LaneMark1_Src_mp = 607 ;
	optional uint32 LM_stRoadDyn_Lane4_LaneStatus_mp = 608 ;
	optional float LM_stRoadDyn_Lane4_pctConfidence_mp = 609 ;
	optional uint32 LM_numRoadDyn_Lane4_LaneId_mp = 610 ;
	optional float LM_IRoadDyn_Lane4_LaneWidth_mp = 611 ;
	optional uint32 LM_stRoadDyn_Lane4_LaneDrvDir_mp = 612 ;
	optional uint32 LM_vRoadDyn_Lane4_MinSpdLmt_mp = 613 ;
	optional uint32 LM_vRoadDyn_Lane4_MaxSpdLmt_mp = 614 ;
	optional float LM_stRoadDyn_Lane4_LaneLen_mp = 615 ;
	optional uint32 LM_stRoadDyn_Lane4_LineCross_mp = 616 ;
	optional uint32 LM_stRoadDyn_Lane4_LaneMark0_Quality_mp = 617 ;
	optional float LM_xRoadDyn_Lane4_LaneMark0_C0_mp = 618 ;
	optional float LM_xRoadDyn_Lane4_LaneMark0_C1_mp = 619 ;
	optional float LM_xRoadDyn_Lane4_LaneMark0_C2_mp = 620 ;
	optional float LM_xRoadDyn_Lane4_LaneMark0_C3_mp = 621 ;
	optional float LM_lRoadDyn_Lane4_LaneMark0_RangeStart_mp = 622 ;
	optional float LM_lRoadDyn_Lane4_LaneMark0_RangeEnd_mp = 623 ;
	optional uint32 LM_stRoadDyn_Lane4_LaneMark0_Color_mp = 624 ;
	optional uint32 LM_stRoadDyn_Lane4_LaneMark0_Type_mp = 625 ;
	optional float LM_lRoadDyn_Lane4_LaneMark0_MarkWidth_mp = 626 ;
	optional uint32 LM_stRoadDyn_Lane4_LaneMark0_Src_mp = 627 ;
	optional uint32 LM_stRoadDyn_Lane4_CentralLine_Quality_mp = 628 ;
	optional float LM_xRoadDyn_Lane4_CentralLine_C0_mp = 629 ;
	optional float LM_xRoadDyn_Lane4_CentralLine_C1_mp = 630 ;
	optional float LM_xRoadDyn_Lane4_CentralLine_C2_mp = 631 ;
	optional float LM_xRoadDyn_Lane4_CentralLine_C3_mp = 632 ;
	optional float LM_lRoadDyn_Lane4_CentralLine_RangeStart_mp = 633 ;
	optional float LM_lRoadDyn_Lane4_CentralLine_RangeEnd_mp = 634 ;
	optional uint32 LM_stRoadDyn_Lane4_CentralLine_Color_mp = 635 ;
	optional uint32 LM_stRoadDyn_Lane4_CentralLine_Type_mp = 636 ;
	optional float LM_lRoadDyn_Lane4_CentralLine_MarkWidth_mp = 637 ;
	optional uint32 LM_stRoadDyn_Lane4_CentralLine_Src_mp = 638 ;
	optional uint32 LM_stRoadDyn_Lane4_LaneMark1_Quality_mp = 639 ;
	optional float LM_xRoadDyn_Lane4_LaneMark1_C0_mp = 640 ;
	optional float LM_xRoadDyn_Lane4_LaneMark1_C1_mp = 641 ;
	optional float LM_xRoadDyn_Lane4_LaneMark1_C2_mp = 642 ;
	optional float LM_xRoadDyn_Lane4_LaneMark1_C3_mp = 643 ;
	optional float LM_lRoadDyn_Lane4_LaneMark1_RangeStart_mp = 644 ;
	optional float LM_lRoadDyn_Lane4_LaneMark1_RangeEnd_mp = 645 ;
	optional uint32 LM_stRoadDyn_Lane4_LaneMark1_Color_mp = 646 ;
	optional uint32 LM_stRoadDyn_Lane4_LaneMark1_Type_mp = 647 ;
	optional float LM_lRoadDyn_Lane4_LaneMark1_MarkWidth_mp = 648 ;
	optional uint32 LM_stRoadDyn_Lane4_LaneMark1_Src_mp = 649 ;
	optional uint32 LM_stRoadDyn_Lane5_LaneStatus_mp = 650 ;
	optional float LM_stRoadDyn_Lane5_pctConfidence_mp = 651 ;
	optional uint32 LM_numRoadDyn_Lane5_LaneId_mp = 652 ;
	optional float LM_IRoadDyn_Lane5_LaneWidth_mp = 653 ;
	optional uint32 LM_stRoadDyn_Lane5_LaneDrvDir_mp = 654 ;
	optional uint32 LM_vRoadDyn_Lane5_MinSpdLmt_mp = 655 ;
	optional uint32 LM_vRoadDyn_Lane5_MaxSpdLmt_mp = 656 ;
	optional float LM_stRoadDyn_Lane5_LaneLen_mp = 657 ;
	optional uint32 LM_stRoadDyn_Lane5_LineCross_mp = 658 ;
	optional uint32 LM_stRoadDyn_Lane5_LaneMark0_Quality_mp = 659 ;
	optional float LM_xRoadDyn_Lane5_LaneMark0_C0_mp = 660 ;
	optional float LM_xRoadDyn_Lane5_LaneMark0_C1_mp = 661 ;
	optional float LM_xRoadDyn_Lane5_LaneMark0_C2_mp = 662 ;
	optional float LM_xRoadDyn_Lane5_LaneMark0_C3_mp = 663 ;
	optional float LM_lRoadDyn_Lane5_LaneMark0_RangeStart_mp = 664 ;
	optional float LM_lRoadDyn_Lane5_LaneMark0_RangeEnd_mp = 665 ;
	optional uint32 LM_stRoadDyn_Lane5_LaneMark0_Color_mp = 666 ;
	optional uint32 LM_stRoadDyn_Lane5_LaneMark0_Type_mp = 667 ;
	optional float LM_lRoadDyn_Lane5_LaneMark0_MarkWidth_mp = 668 ;
	optional uint32 LM_stRoadDyn_Lane5_LaneMark0_Src_mp = 669 ;
	optional uint32 LM_stRoadDyn_Lane5_CentralLine_Quality_mp = 670 ;
	optional float LM_xRoadDyn_Lane5_CentralLine_C0_mp = 671 ;
	optional float LM_xRoadDyn_Lane5_CentralLine_C1_mp = 672 ;
	optional float LM_xRoadDyn_Lane5_CentralLine_C2_mp = 673 ;
	optional float LM_xRoadDyn_Lane5_CentralLine_C3_mp = 674 ;
	optional float LM_lRoadDyn_Lane5_CentralLine_RangeStart_mp = 675 ;
	optional float LM_lRoadDyn_Lane5_CentralLine_RangeEnd_mp = 676 ;
	optional uint32 LM_stRoadDyn_Lane5_CentralLine_Color_mp = 677 ;
	optional uint32 LM_stRoadDyn_Lane5_CentralLine_Type_mp = 678 ;
	optional float LM_lRoadDyn_Lane5_CentralLine_MarkWidth_mp = 679 ;
	optional uint32 LM_stRoadDyn_Lane5_CentralLine_Src_mp = 680 ;
	optional uint32 LM_stRoadDyn_Lane5_LaneMark1_Quality_mp = 681 ;
	optional float LM_xRoadDyn_Lane5_LaneMark1_C0_mp = 682 ;
	optional float LM_xRoadDyn_Lane5_LaneMark1_C1_mp = 683 ;
	optional float LM_xRoadDyn_Lane5_LaneMark1_C2_mp = 684 ;
	optional float LM_xRoadDyn_Lane5_LaneMark1_C3_mp = 685 ;
	optional float LM_lRoadDyn_Lane5_LaneMark1_RangeStart_mp = 686 ;
	optional float LM_lRoadDyn_Lane5_LaneMark1_RangeEnd_mp = 687 ;
	optional uint32 LM_stRoadDyn_Lane5_LaneMark1_Color_mp = 688 ;
	optional uint32 LM_stRoadDyn_Lane5_LaneMark1_Type_mp = 689 ;
	optional float LM_lRoadDyn_Lane5_LaneMark1_MarkWidth_mp = 690 ;
	optional uint32 LM_stRoadDyn_Lane5_LaneMark1_Src_mp = 691 ;
	optional uint32 LM_stRoadDyn_Lane6_LaneStatus_mp = 692 ;
	optional float LM_stRoadDyn_Lane6_pctConfidence_mp = 693 ;
	optional uint32 LM_numRoadDyn_Lane6_LaneId_mp = 694 ;
	optional float LM_IRoadDyn_Lane6_LaneWidth_mp = 695 ;
	optional uint32 LM_stRoadDyn_Lane6_LaneDrvDir_mp = 696 ;
	optional uint32 LM_vRoadDyn_Lane6_MinSpdLmt_mp = 697 ;
	optional uint32 LM_vRoadDyn_Lane6_MaxSpdLmt_mp = 698 ;
	optional float LM_stRoadDyn_Lane6_LaneLen_mp = 699 ;
	optional uint32 LM_stRoadDyn_Lane6_LineCross_mp = 700 ;
	optional uint32 LM_stRoadDyn_Lane6_LaneMark0_Quality_mp = 701 ;
	optional float LM_xRoadDyn_Lane6_LaneMark0_C0_mp = 702 ;
	optional float LM_xRoadDyn_Lane6_LaneMark0_C1_mp = 703 ;
	optional float LM_xRoadDyn_Lane6_LaneMark0_C2_mp = 704 ;
	optional float LM_xRoadDyn_Lane6_LaneMark0_C3_mp = 705 ;
	optional float LM_lRoadDyn_Lane6_LaneMark0_RangeStart_mp = 706 ;
	optional float LM_lRoadDyn_Lane6_LaneMark0_RangeEnd_mp = 707 ;
	optional uint32 LM_stRoadDyn_Lane6_LaneMark0_Color_mp = 708 ;
	optional uint32 LM_stRoadDyn_Lane6_LaneMark0_Type_mp = 709 ;
	optional float LM_lRoadDyn_Lane6_LaneMark0_MarkWidth_mp = 710 ;
	optional uint32 LM_stRoadDyn_Lane6_LaneMark0_Src_mp = 711 ;
	optional uint32 LM_stRoadDyn_Lane6_CentralLine_Quality_mp = 712 ;
	optional float LM_xRoadDyn_Lane6_CentralLine_C0_mp = 713 ;
	optional float LM_xRoadDyn_Lane6_CentralLine_C1_mp = 714 ;
	optional float LM_xRoadDyn_Lane6_CentralLine_C2_mp = 715 ;
	optional float LM_xRoadDyn_Lane6_CentralLine_C3_mp = 716 ;
	optional float LM_lRoadDyn_Lane6_CentralLine_RangeStart_mp = 717 ;
	optional float LM_lRoadDyn_Lane6_CentralLine_RangeEnd_mp = 718 ;
	optional uint32 LM_stRoadDyn_Lane6_CentralLine_Color_mp = 719 ;
	optional uint32 LM_stRoadDyn_Lane6_CentralLine_Type_mp = 720 ;
	optional float LM_lRoadDyn_Lane6_CentralLine_MarkWidth_mp = 721 ;
	optional uint32 LM_stRoadDyn_Lane6_CentralLine_Src_mp = 722 ;
	optional uint32 LM_stRoadDyn_Lane6_LaneMark1_Quality_mp = 723 ;
	optional float LM_xRoadDyn_Lane6_LaneMark1_C0_mp = 724 ;
	optional float LM_xRoadDyn_Lane6_LaneMark1_C1_mp = 725 ;
	optional float LM_xRoadDyn_Lane6_LaneMark1_C2_mp = 726 ;
	optional float LM_xRoadDyn_Lane6_LaneMark1_C3_mp = 727 ;
	optional float LM_lRoadDyn_Lane6_LaneMark1_RangeStart_mp = 728 ;
	optional float LM_lRoadDyn_Lane6_LaneMark1_RangeEnd_mp = 729 ;
	optional uint32 LM_stRoadDyn_Lane6_LaneMark1_Color_mp = 730 ;
	optional uint32 LM_stRoadDyn_Lane6_LaneMark1_Type_mp = 731 ;
	optional float LM_lRoadDyn_Lane6_LaneMark1_MarkWidth_mp = 732 ;
	optional uint32 LM_stRoadDyn_Lane6_LaneMark1_Src_mp = 733 ;
	optional uint32 LM_stRoadDyn_Lane7_LaneStatus_mp = 734 ;
	optional float LM_stRoadDyn_Lane7_pctConfidence_mp = 735 ;
	optional uint32 LM_numRoadDyn_Lane7_LaneId_mp = 736 ;
	optional float LM_IRoadDyn_Lane7_LaneWidth_mp = 737 ;
	optional uint32 LM_stRoadDyn_Lane7_LaneDrvDir_mp = 738 ;
	optional uint32 LM_vRoadDyn_Lane7_MinSpdLmt_mp = 739 ;
	optional uint32 LM_vRoadDyn_Lane7_MaxSpdLmt_mp = 740 ;
	optional float LM_stRoadDyn_Lane7_LaneLen_mp = 741 ;
	optional uint32 LM_stRoadDyn_Lane7_LineCross_mp = 742 ;
	optional uint32 LM_stRoadDyn_Lane7_LaneMark0_Quality_mp = 743 ;
	optional float LM_xRoadDyn_Lane7_LaneMark0_C0_mp = 744 ;
	optional float LM_xRoadDyn_Lane7_LaneMark0_C1_mp = 745 ;
	optional float LM_xRoadDyn_Lane7_LaneMark0_C2_mp = 746 ;
	optional float LM_xRoadDyn_Lane7_LaneMark0_C3_mp = 747 ;
	optional float LM_lRoadDyn_Lane7_LaneMark0_RangeStart_mp = 748 ;
	optional float LM_lRoadDyn_Lane7_LaneMark0_RangeEnd_mp = 749 ;
	optional uint32 LM_stRoadDyn_Lane7_LaneMark0_Color_mp = 750 ;
	optional uint32 LM_stRoadDyn_Lane7_LaneMark0_Type_mp = 751 ;
	optional float LM_lRoadDyn_Lane7_LaneMark0_MarkWidth_mp = 752 ;
	optional uint32 LM_stRoadDyn_Lane7_LaneMark0_Src_mp = 753 ;
	optional uint32 LM_stRoadDyn_Lane7_CentralLine_Quality_mp = 754 ;
	optional float LM_xRoadDyn_Lane7_CentralLine_C0_mp = 755 ;
	optional float LM_xRoadDyn_Lane7_CentralLine_C1_mp = 756 ;
	optional float LM_xRoadDyn_Lane7_CentralLine_C2_mp = 757 ;
	optional float LM_xRoadDyn_Lane7_CentralLine_C3_mp = 758 ;
	optional float LM_lRoadDyn_Lane7_CentralLine_RangeStart_mp = 759 ;
	optional float LM_lRoadDyn_Lane7_CentralLine_RangeEnd_mp = 760 ;
	optional uint32 LM_stRoadDyn_Lane7_CentralLine_Color_mp = 761 ;
	optional uint32 LM_stRoadDyn_Lane7_CentralLine_Type_mp = 762 ;
	optional float LM_lRoadDyn_Lane7_CentralLine_MarkWidth_mp = 763 ;
	optional uint32 LM_stRoadDyn_Lane7_CentralLine_Src_mp = 764 ;
	optional uint32 LM_stRoadDyn_Lane7_LaneMark1_Quality_mp = 765 ;
	optional float LM_xRoadDyn_Lane7_LaneMark1_C0_mp = 766 ;
	optional float LM_xRoadDyn_Lane7_LaneMark1_C1_mp = 767 ;
	optional float LM_xRoadDyn_Lane7_LaneMark1_C2_mp = 768 ;
	optional float LM_xRoadDyn_Lane7_LaneMark1_C3_mp = 769 ;
	optional float LM_lRoadDyn_Lane7_LaneMark1_RangeStart_mp = 770 ;
	optional float LM_lRoadDyn_Lane7_LaneMark1_RangeEnd_mp = 771 ;
	optional uint32 LM_stRoadDyn_Lane7_LaneMark1_Color_mp = 772 ;
	optional uint32 LM_stRoadDyn_Lane7_LaneMark1_Type_mp = 773 ;
	optional float LM_lRoadDyn_Lane7_LaneMark1_MarkWidth_mp = 774 ;
	optional uint32 LM_stRoadDyn_Lane7_LaneMark1_Src_mp = 775 ;
	optional uint32 LM_stRoadDynType_mp = 776 ;
	optional uint32 LM_stPathPlanTrajLane_Quality_mp = 777 ;
	optional float LM_xPathPlanTrajLane_C0_mp = 778 ;
	optional float LM_xPathPlanTrajLane_C1_mp = 779 ;
	optional float LM_xPathPlanTrajLane_C2_mp = 780 ;
	optional float LM_xPathPlanTrajLane_C3_mp = 781 ;
	optional float LM_lPathPlanTrajLane_RangeStart_mp = 782 ;
	optional float LM_lPathPlanTrajLane_RangeEnd_mp = 783 ;
	optional uint32 LM_stPathPlanTrajLane_Color_mp = 784 ;
	optional uint32 LM_stPathPlanTrajLane_Type_mp = 785 ;
	optional float LM_lPathPlanTrajLane_MarkWidth_mp = 786 ;
	optional uint32 LM_stPathPlanTrajLane_Src_mp = 787 ;
	optional float LM_lPathPlanLatCtrlPt_mp = 788 ;
	optional float LM_lPathPlanLonCtrlPt_mp = 789 ;
	optional uint32 LM_stEgoTrajLane_Quality_mp = 790 ;
	optional float LM_xEgoTrajLane_C0_mp = 791 ;
	optional float LM_xEgoTrajLane_C1_mp = 792 ;
	optional float LM_xEgoTrajLane_C2_mp = 793 ;
	optional float LM_xEgoTrajLane_C3_mp = 794 ;
	optional float LM_lEgoTrajLane_RangeStart_mp = 795 ;
	optional float LM_lEgoTrajLane_RangeEnd_mp = 796 ;
	optional uint32 LM_stEgoTrajLane_Color_mp = 797 ;
	optional uint32 LM_stEgoTrajLane_Type_mp = 798 ;
	optional float LM_lEgoTrajLane_MarkWidth_mp = 799 ;
	optional uint32 LM_stEgoTrajLane_Src_mp = 800 ;
	optional float LM_lEgoTrajLatCtrlPt_mp = 801 ;
	optional float LM_lEgoTrajLonCtrlPt_mp = 802 ;
	optional uint32 LM_stLastQuitReason_mp = 803 ;
	optional float LM_pctLeLaneMarkConf_mp = 804 ;
	optional float LM_pctRiLaneMarkConf_mp = 805 ;
	optional float LM_pctLVLMConf_mp = 806 ;
	optional float LM_pctLeRLMConf_mp = 807 ;
	optional float LM_pctRiRLMConf_mp = 808 ;
	optional uint32 LM_cntFilterLevel_mp = 809 ;
	optional float LM_degHeadDiff_mp = 810 ;
	optional uint32 LM_LVLM_cntTgtIdx_mp = 811 ;
	optional uint32 LM_CLM_Mode_mp = 812 ;
	optional float LM_LVLM_lMaxFollowDist_mp = 813 ;
	optional int32 LM_idxUnexpectedLane_mp = 814 ;
	optional uint32 LM_flgPickLaneMarkByTF_mp = 815 ;
	optional int32 LM_idxBaseLaneMarkIdx_mp = 816 ;
	optional float LM_degLeRiHeadDiff_mp = 817 ;
	optional float LM_degLeRiHeadThrd_mp = 818 ;
	optional uint32 LM_LVLM_stQuitReason_mp = 819 ;
	optional uint32 LM_bQRFWFaultMask_mp = 820 ;
	optional uint32 LM_bQREQFailMask_mp = 821 ;
	optional uint32 LM_bQRLMThresholdMask_mp = 822 ;
	optional uint32 LM_bWarningFWFaultMask_mp = 823 ;
	optional uint32 LM_bWarningEQFailMask_mp = 824 ;
	optional uint32 LM_bWarningLMThresholdMask_mp = 825 ;
	optional float LM_stPathPlanTrajLane_Conf_mp = 826 ;
	optional float LM_LMAS_vOffsetAll_mp = 827 ;
	optional float LM_LMAS_vOffsetMark_mp = 828 ;
	optional float LM_LMAS_vDownFilterMark_mp = 829 ;
	optional float LM_LMAS_vObs3Rank_mp = 830 ;
	optional float LM_LMAS_vObs3RankFilter_mp = 831 ;
	optional float LM_LMAS_vOffsetObs3_mp = 832 ;
	optional float LM_LMAS_vOffsetObs3Mark_mp = 833 ;
	optional float LM_LMAS_vObs5Rank_mp = 834 ;
	optional float LM_LMAS_vObs5RankFilter_mp = 835 ;
	optional float LM_LMAS_vOffsetObs5_mp = 836 ;
	optional float LM_LMAS_vOffsetObs5Mark_mp = 837 ;
	optional float LM_LMAS_vObs9Rank_mp = 838 ;
	optional float LM_LMAS_vObs9RankFilter_mp = 839 ;
	optional float LM_LMAS_vOffsetObs9_mp = 840 ;
	optional float LM_LMAS_vOffsetObs9Mark_mp = 841 ;
	optional float LM_LMAS_vObs10Rank_mp = 842 ;
	optional float LM_LMAS_vObs10RankFilter_mp = 843 ;
	optional float LM_LMAS_vOffsetObs10_mp = 844 ;
	optional float LM_LMAS_vOffsetObs10Mark_mp = 845 ;
	optional float LM_LMAS_vObs19Rank_mp = 846 ;
	optional float LM_LMAS_vObs19RankFilter_mp = 847 ;
	optional float LM_LMAS_vOffsetObs19_mp = 848 ;
	optional float LM_LMAS_vOffsetObs19Mark_mp = 849 ;
	optional float LM_LMAS_vObs21Rank_mp = 850 ;
	optional float LM_LMAS_vObs21RankFilter_mp = 851 ;
	optional float LM_LMAS_vOffsetObs21_mp = 852 ;
	optional float LM_LMAS_vOffsetObs21Mark_mp = 853 ;
	optional uint32 LME_STL_stValid_mp = 854 ;
	optional float LME_STL_lWidth_mp = 855 ;
	optional float LME_STL_lLonPos_mp = 856 ;
	optional float LME_STL_lLength_mp = 857 ;
	optional uint32 RME_numLaneMarkIdNumber_mp = 858 ;
	optional uint32 RME_numLaneIdNumber_mp = 859 ;
	optional uint32 RME_numLaneMarkNumberInMap_mp = 860 ;
	optional uint32 RME_numLaneNumberInMap_mp = 861 ;
	optional int32 RME_numLaneTopologySize_mp = 862 ;
	optional int32 RME_idCurrentLaneId_mp = 863 ;
	optional float RME_LeLMSumSlop_mp = 864 ;
	optional float RME_NxLeLMSumSlop_mp = 865 ;
	optional float RME_RiLMSumSlop_mp = 866 ;
	optional float RME_NxRiLMSumSlop_mp = 867 ;
	optional uint32 RME_flgIsLMShrinked_mp = 868 ;
	optional uint32 RME_flgIsCurrLaneShrinked_mp = 869 ;
	optional uint32 RME_flgIsNxLaneShrinked_mp = 870 ;
	optional uint32 LPP_stQl_mp = 871 ;
	optional float LPP_pctConfidence_mp = 872 ;
	optional float LPP_xC0_mp = 873 ;
	optional float LPP_xC1_mp = 874 ;
	optional float LPP_xC2_mp = 875 ;
	optional float LPP_xC3_mp = 876 ;
	optional float LPP_lStart_mp = 877 ;
	optional float LPP_lEnd_mp = 878 ;
	optional float LPP_lLonCtrlPt_mp = 879 ;
	optional float LPP_lLatCtrlPt_mp = 880 ;
	optional uint32 RM_flgIsIntersection_mp = 881 ;
	optional uint32 LPP_stLeadPattern_mp = 882 ;
	optional uint32 LPP_stRampType_mp = 883 ;
	optional uint32 LPP_flgTarLaneIdValid_mp = 884 ;
	optional int32 LPP_lDecelLaneLen_mp = 885 ;
	optional int32 LPP_lDecelLaneSpdLimit_mp = 886 ;
	optional float LPP_lTTPOnDecelLane_mp = 887 ;
	optional float LPP_lLaneChangeTTPThrh_mp = 888 ;
	optional uint32 LPP_numValidLaneNum_mp = 889 ;
	optional int32 LPP_idxTarLaneIndex_mp = 890 ;
	optional float LPP_stHostRiLMDiffX_mp = 891 ;
	optional float LPP_stHostRiLMDiffY_mp = 892 ;
	optional float LPP_stHostRiLMSlope_mp = 893 ;
	optional float LPP_stHostRiLMDiffStart_mp = 894 ;
	optional float LPP_stHostRiLMStart_mp = 895 ;
	optional uint32 LPP_stUseLMToCheckDiffDir_mp = 896 ;
	optional float LPP_lLMCheckCnt_mp = 897 ;
	optional float LPP_lLMCheckCntThrd_mp = 898 ;
	optional float LPP_lAdjacentLaneWidth_mp = 899 ;
	optional uint32 LPP_stAdjacentLaneBranch_mp = 900 ;
	optional float LPP_tiSmoothTimerCnt_mp = 901 ;
	optional float LPP_tiSmoothTimerCntLimit_mp = 902 ;
	optional uint32 LPP_stNextLane0Type_mp = 903 ;
	optional float LPP_lDistSplit2Rmap_mp = 904 ;
	optional float LPP_lDistSplit2gp_mp = 905 ;
	optional uint32 LPP_stLeadPeridMode_mp = 906 ;
	optional uint32 LPP_stLeadPlannerDir_mp = 907 ;
	optional uint32 LPP_flgRightLaneVldandAllowC_mp = 908 ;
	optional uint32 LPP_flgLeftLaneVldandAllowC_mp = 909 ;
	optional uint32 LPP_flgRightLaneValid_mp = 910 ;
	optional uint32 LPP_flgLeftLaneValid_mp = 911 ;
	optional uint32 LPP_flgRightLaneAllowC_mp = 912 ;
	optional uint32 LPP_flgLeftLaneAllowC_mp = 913 ;
	optional uint32 LPP_flgTargetEnalbe_mp = 914 ;
	optional uint32 LPP_flgRightLaneReady_mp = 915 ;
	optional uint32 LPP_flgLeftLaneReady_mp = 916 ;
	optional uint32 LPP_flgBeginRightLeadInit_mp = 917 ;
	optional uint32 LPP_flgBeginLeftLeadInit_mp = 918 ;
	optional float LPP_tiLeadActualPeriod_mp = 919 ;
	optional float LPP_ltTrajRealTimeLaneWidth_mp = 920 ;
	optional uint32 LPP_stTrajGetC1Mode_mp = 921 ;
	optional uint32 LPP_flgTrajC1IsNon_mp = 922 ;
	optional float LPP_lC1ByTime_mp = 923 ;
	optional float LPP_lEgoLaneC1_mp = 924 ;
	optional float LPP_lC2ByTime_mp = 925 ;
	optional float LPP_lEgoLaneC2_mp = 926 ;
	optional uint32 LPP_stEgoParallWithNextLaneMark_mp = 927 ;
	optional uint32 LPP_stP2LaneMarkFollowSrc_mp = 928 ;
	optional uint32 LPP_flgP2LaneMarkAllowC_mp = 929 ;
	optional uint32 Lpp_stP2lLaneMarkScene_mp = 930 ;
	optional uint32 Lpp_flgP2lLaneMarkIsExist_mp = 931 ;
	optional uint32 Lpp_stEVDPathDirCmd_mp = 932 ;
	optional uint32 Lpp_stWorkingPathDir_mp = 933 ;
	optional float Lpp_stWorkingPathDirLatchTimer_mp = 934 ;
	optional int32 Lpp_cntLaneChangeCntInLeadMode_mp = 935 ;
	optional uint32 Lpp_stLeadModeFailReason_mp = 936 ;
	optional float LPP_tiLeadTime_mp = 937 ;
	optional uint32 LPP_stStatus_mp = 938 ;
	optional uint32 RM_flgStopLineValid_mp = 939 ;
	optional float RM_lStopLineWidth_mp = 940 ;
	optional float RM_lStopLineLen_mp = 941 ;
	optional float RM_lStopLineDistance_mp = 942 ;
	optional uint32 RM_Fusion_flgCoarseMatchAva_mp = 943 ;
	optional int32 RM_Fusion_numICPiterTime_mp = 944 ;
	optional float RM_Fusion_dstICPresLoss_mp = 945 ;
	optional int32 RM_Fusion_numMapMarkNum_mp = 946 ;
	optional int32 RM_Fusion_numMELMNum_mp = 947 ;
	optional int32 RM_Fusion_numCoarseMatchNum_mp = 948 ;
	optional uint32 RM_Fusion_stCoarseST_mp = 949 ;
	optional float RM_Fusion_angSingleICPAngle_mp = 950 ;
	optional float RM_Fusion_dstSingleICPX_mp = 951 ;
	optional float RM_Fusion_dstSingleICPY_mp = 952 ;
	optional float RM_Fusion_angICPAngle_mp = 953 ;
	optional float RM_Fusion_dstICPX_mp = 954 ;
	optional float RM_Fusion_dstICPY_mp = 955 ;
	optional float RM_Fusion_lICPedMELMLength_mp = 956 ;
	optional float RM_Fusion_lMatchedMELMLength_mp = 957 ;
	optional float RM_Fusion_lTotalMELMLength_mp = 958 ;
	optional uint32 RM_Road_flgHasCLMHostLM_mp = 959 ;
	optional uint32 RM_Road_flgHasUpdatedLanes_mp = 960 ;

    optional uint64 timestamp = 536870905; // ptp timestamp, nanosecond，used for data bundle readin 
	// optional SensorTSHeader sensor_original_ts = 536870906;   // sensor original ts
	optional uint64 publish_ptp_ts = 536870907; // publish ptp timestamp, uint in nanosec
	optional string publisher_id = 536870909; // uuid of the publisher
	optional uint64 counter = 536870910; // message counter
	optional uint64 publish_ts = 536870911;    // publish timestamp; unit : nanosecond
}
