syntax = "proto2";

option cc_enable_arenas = true;
package nio.ad.messages.debug;
// import "common/perf/sensor_ts_header.proto";

message DLBTSIDebugMeas{

	optional uint32 TSI_stOTStatus_mp = 1 ;
	optional uint32 TSI_numSTgt1ObjIndex_mp = 2 ;
	optional float TSI_lSTgt1LonPos_mp = 3 ;
	optional float TSI_vSTgt1LonVel_mp = 4 ;
	optional float TSI_aSTgt1LonAcc_mp = 5 ;
	optional uint32 TSI_stSTgt1Status_mp = 6 ;
	optional uint32 TSI_flgSTgt1Valid_mp = 7 ;
	optional uint32 TSI_stSTgt1Type_mp = 8 ;
	optional uint32 TSI_numSTgt2ObjIndex_mp = 9 ;
	optional float TSI_lSTgt2LonPos_mp = 10 ;
	optional float TSI_vSTgt2LonVel_mp = 11 ;
	optional float TSI_aSTgt2LonAcc_mp = 12 ;
	optional uint32 TSI_stSTgt2Status_mp = 13 ;
	optional uint32 TSI_flgSTgt2Valid_mp = 14 ;
	optional uint32 TSI_stSTgt2Type_mp = 15 ;
	optional float TSI_dphiYawrateDiff_mp = 16 ;
	optional float TSI_tYawrateFiltT_mp = 17 ;
	optional float TSI_dphiYawrateOfs_mp = 18 ;
	optional float TSI_dphiYawrateRaw_mp = 19 ;
	optional float TSI_dphiYawrateFiltered_mp = 20 ;
	optional uint32 TSI_OTStatus_mp = 21 ;
	optional uint32 TSI_OTLmtLaneDir_mp = 22 ;
	optional uint32 TSI_useLaneC2_mp = 23 ;
	optional uint32 TSI_useVisionCIPV_mp = 24 ;
	optional uint32 TSI_numVisionCIPVID_mp = 25 ;
	optional float TSI_degCIPVHd2Lane_mp = 26 ;
	optional uint32 TSI_CTA_bufTgt_idxObjFL1_mp = 27 ;
	optional uint32 TSI_CTA_bufTgt_idxObjFL2_mp = 28 ;
	optional uint32 TSI_CTA_bufTgt_idxObjFR1_mp = 29 ;
	optional uint32 TSI_CTA_bufTgt_idxObjFR2_mp = 30 ;
	optional uint32 TSI_CTA_bufTgt_idxObjRL1_mp = 31 ;
	optional uint32 TSI_CTA_bufTgt_idxObjRL2_mp = 32 ;
	optional uint32 TSI_CTA_bufTgt_idxObjRR1_mp = 33 ;
	optional uint32 TSI_CTA_bufTgt_idxObjRR2_mp = 34 ;
	optional uint32 TSI_CTA_bufTgt_validFL_mp = 35 ;
	optional uint32 TSI_CTA_bufTgt_validFR_mp = 36 ;
	optional uint32 TSI_CTA_bufTgt_validRL_mp = 37 ;
	optional uint32 TSI_CTA_bufTgt_validRR_mp = 38 ;
	optional uint32 TSI_CTA_bufTgt_cntFL1_mp = 39 ;
	optional uint32 TSI_CTA_bufTgt_cntFL2_mp = 40 ;
	optional uint32 TSI_CTA_bufTgt_cntFR1_mp = 41 ;
	optional uint32 TSI_CTA_bufTgt_cntFR2_mp = 42 ;
	optional uint32 TSI_CTA_bufTgt_cntRL1_mp = 43 ;
	optional uint32 TSI_CTA_bufTgt_cntRL2_mp = 44 ;
	optional uint32 TSI_CTA_bufTgt_cntRR1_mp = 45 ;
	optional uint32 TSI_CTA_bufTgt_cntRR2_mp = 46 ;
	optional uint32 TSI_CTA_bufTgt_iSelectedFL_mp = 47 ;
	optional uint32 TSI_CTA_bufTgt_iSelectedFR_mp = 48 ;
	optional uint32 TSI_CTA_bufTgt_iSelectedRL_mp = 49 ;
	optional uint32 TSI_CTA_bufTgt_iSelectedRR_mp = 50 ;
	optional float TSI_degYawRate_Cur1_mp = 51 ;
	optional float TSI_degYawRate_Cur2_mp = 52 ;
	optional float TSI_degYawRate_Cur3_mp = 53 ;
	optional float TSI_degYawRate_Cur4_mp = 54 ;
	optional float TSI_stYawRateLowPassFlt_Yaxis1_mp = 55 ;
	optional float TSI_stYawRateLowPassFlt_Yaxis2_mp = 56 ;
	optional float TSI_stYawRateLowPassFlt_Yaxis3_mp = 57 ;
	optional float TSI_stYawRateLowPassFlt_Yaxis4_mp = 58 ;
	optional float TSI_dstFnlGrab_dstLon_x1_mp = 59 ;
	optional float TSI_dstFnlGrab_dstLon_x2_mp = 60 ;
	optional float TSI_dstFnlGrab_dstLon_x3_mp = 61 ;
	optional float TSI_dstFnlGrab_dstLon_x4_mp = 62 ;
	optional float TSI_dstFnlGrab_v1_mp = 63 ;
	optional float TSI_dstFnlGrab_v2_mp = 64 ;
	optional float TSI_dstFnlGrab_v3_mp = 65 ;
	optional float TSI_dstFnlGrab_v4_mp = 66 ;
	optional float TSI_dstFnlRelease_dstLon_x1_mp = 67 ;
	optional float TSI_dstFnlRelease_dstLon_x2_mp = 68 ;
	optional float TSI_dstFnlRelease_dstLon_x3_mp = 69 ;
	optional float TSI_dstFnlRelease_dstLon_x4_mp = 70 ;
	optional float TSI_dstFnlRelease_v1_mp = 71 ;
	optional float TSI_dstFnlRelease_v2_mp = 72 ;
	optional float TSI_dstFnlRelease_v3_mp = 73 ;
	optional float TSI_dstFnlRelease_v4_mp = 74 ;
	optional float TSI_numTgtGrbDelay_v1_mp = 75 ;
	optional float TSI_numTgtGrbDelay_v2_mp = 76 ;
	optional float TSI_numTgtGrbDelay_v3_mp = 77 ;
	optional float TSI_numTgtGrbDelay_v4_mp = 78 ;
	optional float TSI_numTgtRlsDelay_v1_mp = 79 ;
	optional float TSI_numTgtRlsDelay_v2_mp = 80 ;
	optional float TSI_numTgtRlsDelay_v3_mp = 81 ;
	optional float TSI_numTgtRlsDelay_v4_mp = 82 ;
	optional float TSI_numTgt1RlsAddDelay_v1_mp = 83 ;
	optional float TSI_numTgt1RlsAddDelay_v2_mp = 84 ;
	optional float TSI_numTgt1RlsAddDelay_v3_mp = 85 ;
	optional float TSI_numTgt1RlsAddDelay_v4_mp = 86 ;
	optional uint32 TSI_numOTCntLmt_C_mp = 87 ;
	optional uint32 TSI_numProbeTgt1Index_C_mp = 88 ;
	optional uint32 TSI_numProbeTgt2Index_C_mp = 89 ;
	optional float TSI_dtiYawRateFilterdT_C_mp = 90 ;
	optional float TSI_dstMaxLanDst_C_mp = 91 ;
	optional float TSI_dstMinLanDst_C_mp = 92 ;
	optional float TSI_lLaneWidthDft_C_mp = 93 ;
	optional float TSI_phiThrStrngAgLanChg_C_mp = 94 ;
	optional float TSI_dphiThrYawRateLanChg_C_mp = 95 ;
	optional float TSI_vThrEVSpdPthSrcHi_C_mp = 96 ;
	optional float TSI_vThrEVSpdPthSrcLo_C_mp = 97 ;
	optional float TSI_dstFnlOfsStatic_C_mp = 98 ;
	optional float TSI_dphiMaxStraightLanYaw_C_mp = 99 ;
	optional float TSI_lMinLanLenCurv_C_mp = 100 ;
	optional float TSI_lMinLanLenStraight_C_mp = 101 ;
	optional float TSI_dphiThrYawrateDiffAlongLine_C_mp = 102 ;
	optional float TSI_rThrLanC1AlongLine_C_mp = 103 ;
	optional float TSI_dphiThrYawrateDiffAdjust_C_mp = 104 ;
	optional float TSI_dstOfsetC0StartAdjust_C_mp = 105 ;
	optional float TSI_dstOfsetC0EndAdjust_C_mp = 106 ;
	optional float TSI_phiThrC1StartAdjust_C_mp = 107 ;
	optional float TSI_phiThrC1EndAdjust_C_mp = 108 ;
	optional float TSI_dstMinLanDstRid_C_mp = 109 ;
	optional float TSI_rStaticTgtSwtDly_v1_mp = 110 ;
	optional float TSI_rStaticTgtSwtDly_v2_mp = 111 ;
	optional float TSI_rStaticTgtSwtDly_v3_mp = 112 ;
	optional float TSI_rStaticTgtSwtDly_v4_mp = 113 ;
	optional float TSI_rByYawrateTgtSwtDly_v1_mp = 114 ;
	optional float TSI_rByYawrateTgtSwtDly_v2_mp = 115 ;
	optional float TSI_rByYawrateTgtSwtDly_v3_mp = 116 ;
	optional float TSI_rByYawrateTgtSwtDly_v4_mp = 117 ;
	optional uint32 TSI_stInputAccMode_mp = 118 ;
	optional float TSI_lSTgt1LatPos_mp = 119 ;
	optional float TSI_vSTgt1LatVel_mp = 120 ;
	optional float TSI_aSTgt1LatAcc_mp = 121 ;
	optional float TSI_lSTgt2LatPos_mp = 122 ;
	optional float TSI_vSTgt2LatVel_mp = 123 ;
	optional float TSI_aSTgt2LatAcc_mp = 124 ;
	optional uint32 TSI_numSTgt3ObjIndex_mp = 125 ;
	optional float TSI_lSTgt3LonPos_mp = 126 ;
	optional float TSI_vSTgt3LonVel_mp = 127 ;
	optional float TSI_aSTgt3LonAcc_mp = 128 ;
	optional uint32 TSI_stSTgt3Status_mp = 129 ;
	optional uint32 TSI_flgSTgt3Valid_mp = 130 ;
	optional uint32 TSI_stSTgt3Type_mp = 131 ;
	optional float TSI_lSTgt3LatPos_mp = 132 ;
	optional float TSI_vSTgt3LatVel_mp = 133 ;
	optional float TSI_aSTgt3LatAcc_mp = 134 ;
	optional uint32 TSI_numSTgt4ObjIndex_mp = 135 ;
	optional float TSI_lSTgt4LonPos_mp = 136 ;
	optional float TSI_vSTgt4LonVel_mp = 137 ;
	optional float TSI_aSTgt4LonAcc_mp = 138 ;
	optional uint32 TSI_stSTgt4Status_mp = 139 ;
	optional uint32 TSI_flgSTgt4Valid_mp = 140 ;
	optional uint32 TSI_stSTgt4Type_mp = 141 ;
	optional float TSI_lSTgt4LatPos_mp = 142 ;
	optional float TSI_vSTgt4LatVel_mp = 143 ;
	optional float TSI_aSTgt4LatAcc_mp = 144 ;
	optional uint32 TSI_numSTgt5ObjIndex_mp = 145 ;
	optional float TSI_lSTgt5LonPos_mp = 146 ;
	optional float TSI_vSTgt5LonVel_mp = 147 ;
	optional float TSI_aSTgt5LonAcc_mp = 148 ;
	optional uint32 TSI_stSTgt5Status_mp = 149 ;
	optional uint32 TSI_flgSTgt5Valid_mp = 150 ;
	optional uint32 TSI_stSTgt5Type_mp = 151 ;
	optional float TSI_lSTgt5LatPos_mp = 152 ;
	optional float TSI_vSTgt5LatVel_mp = 153 ;
	optional float TSI_aSTgt5LatAcc_mp = 154 ;
	optional uint32 TSI_numSTgt6ObjIndex_mp = 155 ;
	optional float TSI_lSTgt6LonPos_mp = 156 ;
	optional float TSI_vSTgt6LonVel_mp = 157 ;
	optional float TSI_aSTgt6LonAcc_mp = 158 ;
	optional uint32 TSI_stSTgt6Status_mp = 159 ;
	optional uint32 TSI_flgSTgt6Valid_mp = 160 ;
	optional uint32 TSI_stSTgt6Type_mp = 161 ;
	optional float TSI_lSTgt6LatPos_mp = 162 ;
	optional float TSI_vSTgt6LatVel_mp = 163 ;
	optional float TSI_aSTgt6LatAcc_mp = 164 ;
	optional uint32 OBF_stStatus_mp = 165 ;
	optional float LCP_Tgt3_probLaneChangeOrigin_mp = 166 ;
	optional float LCP_Tgt3_probLaneChangeProcessed_mp = 167 ;
	optional float LCP_Tgt5_probLaneChangeOrigin_mp = 168 ;
	optional float LCP_Tgt5_probLaneChangeProcessed_mp = 169 ;
	optional float TSI_vSTgt1LonVelCCS_mp = 170 ;
	optional float TSI_vSTgt2LonVelCCS_mp = 171 ;
	optional float TSI_vSTgt3LonVelCCS_mp = 172 ;
	optional float TSI_vSTgt4LonVelCCS_mp = 173 ;
	optional float TSI_vSTgt5LonVelCCS_mp = 174 ;
	optional float TSI_vSTgt6LonVelCCS_mp = 175 ;
	optional float TSI_vSTgt1LatVelCCS_mp = 176 ;
	optional float TSI_vSTgt2LatVelCCS_mp = 177 ;
	optional float TSI_vSTgt3LatVelCCS_mp = 178 ;
	optional float TSI_vSTgt4LatVelCCS_mp = 179 ;
	optional float TSI_vSTgt5LatVelCCS_mp = 180 ;
	optional float TSI_vSTgt6LatVelCCS_mp = 181 ;
	optional float TSI_probTgt3LaneChangeSVM_mp = 182 ;
	optional float TSI_probTgt4LaneChangeSVM_mp = 183 ;
	optional float TSI_probTgt5LaneChangeSVM_mp = 184 ;
	optional float TSI_probTgt6LaneChangeSVM_mp = 185 ;
	optional float TSI_probTgt1LaneChangeSVM_mp = 186 ;
	optional uint32 TSI_flgTSI1IsDangerous_mp = 187 ;
	optional uint32 TSE_flgTgt1Valid_mp = 188 ;
	optional uint32 TSE_flgTgt2Valid_mp = 189 ;
	optional uint32 TSE_flgTgt3Valid_mp = 190 ;
	optional uint32 TSE_flgTgt4Valid_mp = 191 ;
	optional uint32 TSE_xTgt1Index_mp = 192 ;
	optional uint32 TSE_xTgt2Index_mp = 193 ;
	optional uint32 TSE_xTgt3Index_mp = 194 ;
	optional uint32 TSE_xTgt4Index_mp = 195 ;
	optional uint32 TSE_flgTgt1FilterByMoveOut_mp = 196 ;
	optional uint32 TSE_flgTgt2FilterByMoveOut_mp = 197 ;
	optional uint32 LCP_Tgt3_numLaneChangeCounter_mp = 198 ;
	optional uint32 LCP_Tgt5_numLaneChangeCounter_mp = 199 ;
	optional uint32 OBF_1_Lane_Index_mp = 200 ;
	optional uint32 OBF_2_Lane_Index_mp = 201 ;
	optional uint32 OBF_3_Lane_Index_mp = 202 ;
	optional uint32 OBF_4_Lane_Index_mp = 203 ;
	optional uint32 OBF_5_Lane_Index_mp = 204 ;
	optional uint32 OBF_6_Lane_Index_mp = 205 ;
	optional uint32 OBF_7_Lane_Index_mp = 206 ;
	optional uint32 OBF_8_Lane_Index_mp = 207 ;
	optional uint32 OBF_9_Lane_Index_mp = 208 ;
	optional uint32 OBF_10_Lane_Index_mp = 209 ;
	optional uint32 OBF_11_Lane_Index_mp = 210 ;
	optional uint32 OBF_12_Lane_Index_mp = 211 ;
	optional uint32 OBF_13_Lane_Index_mp = 212 ;
	optional uint32 OBF_14_Lane_Index_mp = 213 ;
	optional uint32 OBF_15_Lane_Index_mp = 214 ;
	optional uint32 OBF_16_Lane_Index_mp = 215 ;
	optional uint32 OBF_17_Lane_Index_mp = 216 ;
	optional uint32 OBF_18_Lane_Index_mp = 217 ;
	optional uint32 OBF_19_Lane_Index_mp = 218 ;
	optional uint32 OBF_20_Lane_Index_mp = 219 ;
	optional uint32 OBF_21_Lane_Index_mp = 220 ;
	optional uint32 OBF_22_Lane_Index_mp = 221 ;
	optional uint32 OBF_23_Lane_Index_mp = 222 ;
	optional uint32 OBF_24_Lane_Index_mp = 223 ;
	optional uint32 OBF_25_Lane_Index_mp = 224 ;
	optional uint32 OBF_26_Lane_Index_mp = 225 ;
	optional uint32 OBF_27_Lane_Index_mp = 226 ;
	optional uint32 OBF_28_Lane_Index_mp = 227 ;
	optional uint32 OBF_29_Lane_Index_mp = 228 ;
	optional uint32 OBF_30_Lane_Index_mp = 229 ;
	optional uint32 OBF_31_Lane_Index_mp = 230 ;
	optional uint32 OBF_32_Lane_Index_mp = 231 ;
	optional uint32 OBF_33_Lane_Index_mp = 232 ;
	optional uint32 OBF_34_Lane_Index_mp = 233 ;
	optional uint32 OBF_35_Lane_Index_mp = 234 ;
	optional uint32 OBF_36_Lane_Index_mp = 235 ;
	optional uint32 OBF_37_Lane_Index_mp = 236 ;
	optional uint32 OBF_38_Lane_Index_mp = 237 ;
	optional uint32 OBF_39_Lane_Index_mp = 238 ;
	optional uint32 OBF_40_Lane_Index_mp = 239 ;
	optional uint32 OBF_41_Lane_Index_mp = 240 ;
	optional uint32 OBF_42_Lane_Index_mp = 241 ;
	optional uint32 OBF_43_Lane_Index_mp = 242 ;
	optional uint32 OBF_44_Lane_Index_mp = 243 ;
	optional uint32 OBF_45_Lane_Index_mp = 244 ;
	optional uint32 OBF_46_Lane_Index_mp = 245 ;
	optional uint32 OBF_47_Lane_Index_mp = 246 ;
	optional uint32 OBF_48_Lane_Index_mp = 247 ;
	optional uint32 OBF_49_Lane_Index_mp = 248 ;
	optional uint32 OBF_50_Lane_Index_mp = 249 ;
	optional uint32 OBF_51_Lane_Index_mp = 250 ;
	optional uint32 OBF_52_Lane_Index_mp = 251 ;
	optional uint32 OBF_53_Lane_Index_mp = 252 ;
	optional uint32 OBF_54_Lane_Index_mp = 253 ;
	optional uint32 OBF_55_Lane_Index_mp = 254 ;
	optional uint32 OBF_56_Lane_Index_mp = 255 ;
	optional uint32 OBF_57_Lane_Index_mp = 256 ;
	optional uint32 OBF_58_Lane_Index_mp = 257 ;
	optional uint32 OBF_59_Lane_Index_mp = 258 ;
	optional uint32 OBF_60_Lane_Index_mp = 259 ;
	optional uint32 OBF_61_Lane_Index_mp = 260 ;
	optional uint32 OBF_62_Lane_Index_mp = 261 ;
	optional uint32 OBF_63_Lane_Index_mp = 262 ;
	optional uint32 OBF_64_Lane_Index_mp = 263 ;
	optional uint32 OBF_65_Lane_Index_mp = 264 ;
	optional uint32 OBF_66_Lane_Index_mp = 265 ;
	optional uint32 OBF_67_Lane_Index_mp = 266 ;
	optional uint32 OBF_68_Lane_Index_mp = 267 ;
	optional uint32 OBF_69_Lane_Index_mp = 268 ;
	optional uint32 OBF_70_Lane_Index_mp = 269 ;
	optional uint32 OBF_71_Lane_Index_mp = 270 ;
	optional uint32 OBF_72_Lane_Index_mp = 271 ;
	optional uint32 OBF_73_Lane_Index_mp = 272 ;
	optional uint32 OBF_74_Lane_Index_mp = 273 ;
	optional uint32 OBF_75_Lane_Index_mp = 274 ;
	optional uint32 OBF_76_Lane_Index_mp = 275 ;
	optional uint32 OBF_77_Lane_Index_mp = 276 ;
	optional uint32 OBF_78_Lane_Index_mp = 277 ;
	optional uint32 OBF_79_Lane_Index_mp = 278 ;
	optional uint32 OBF_80_Lane_Index_mp = 279 ;
	optional uint32 OBF_81_Lane_Index_mp = 280 ;
	optional uint32 OBF_82_Lane_Index_mp = 281 ;
	optional uint32 OBF_83_Lane_Index_mp = 282 ;
	optional uint32 OBF_84_Lane_Index_mp = 283 ;
	optional uint32 OBF_85_Lane_Index_mp = 284 ;
	optional uint32 OBF_86_Lane_Index_mp = 285 ;
	optional uint32 OBF_87_Lane_Index_mp = 286 ;
	optional uint32 OBF_88_Lane_Index_mp = 287 ;
	optional uint32 OBF_89_Lane_Index_mp = 288 ;
	optional uint32 OBF_90_Lane_Index_mp = 289 ;
	optional uint32 OBF_91_Lane_Index_mp = 290 ;
	optional uint32 OBF_92_Lane_Index_mp = 291 ;
	optional uint32 OBF_93_Lane_Index_mp = 292 ;
	optional uint32 OBF_94_Lane_Index_mp = 293 ;
	optional uint32 OBF_95_Lane_Index_mp = 294 ;
	optional uint32 OBF_96_Lane_Index_mp = 295 ;
	optional uint32 OBF_97_Lane_Index_mp = 296 ;
	optional uint32 OBF_98_Lane_Index_mp = 297 ;
	optional uint32 OBF_99_Lane_Index_mp = 298 ;
	optional uint32 OBF_100_Lane_Index_mp = 299 ;
	optional uint32 OBF_101_Lane_Index_mp = 300 ;
	optional uint32 OBF_102_Lane_Index_mp = 301 ;
	optional uint32 OBF_103_Lane_Index_mp = 302 ;
	optional uint32 OBF_104_Lane_Index_mp = 303 ;
	optional uint32 OBF_105_Lane_Index_mp = 304 ;
	optional uint32 OBF_106_Lane_Index_mp = 305 ;
	optional uint32 OBF_107_Lane_Index_mp = 306 ;
	optional uint32 OBF_108_Lane_Index_mp = 307 ;
	optional uint32 OBF_109_Lane_Index_mp = 308 ;
	optional uint32 OBF_110_Lane_Index_mp = 309 ;
	optional uint32 OBF_111_Lane_Index_mp = 310 ;
	optional uint32 OBF_112_Lane_Index_mp = 311 ;
	optional uint32 OBF_113_Lane_Index_mp = 312 ;
	optional uint32 OBF_114_Lane_Index_mp = 313 ;
	optional uint32 OBF_115_Lane_Index_mp = 314 ;
	optional uint32 OBF_116_Lane_Index_mp = 315 ;
	optional uint32 OBF_117_Lane_Index_mp = 316 ;
	optional uint32 OBF_118_Lane_Index_mp = 317 ;
	optional uint32 OBF_119_Lane_Index_mp = 318 ;
	optional uint32 OBF_120_Lane_Index_mp = 319 ;
	optional uint32 OBF_121_Lane_Index_mp = 320 ;
	optional uint32 OBF_122_Lane_Index_mp = 321 ;
	optional uint32 OBF_123_Lane_Index_mp = 322 ;
	optional uint32 OBF_124_Lane_Index_mp = 323 ;
	optional uint32 OBF_125_Lane_Index_mp = 324 ;
	optional uint32 OBF_126_Lane_Index_mp = 325 ;
	optional uint32 OBF_127_Lane_Index_mp = 326 ;
	optional uint32 OBF_128_Lane_Index_mp = 327 ;
	optional uint32 OBF_idxSelectedByBlinkerIndex1_mp = 328 ;
	optional uint32 OBF_idxSelectedByBlinkerIndex2_mp = 329 ;
	optional uint32 OBF_idxSelectedByLaneChangePredIndex_mp = 330 ;
	optional uint32 OBF_idxSelectedByLaneChangePredAheadFrame_mp = 331 ;
	optional uint32 OBF_idxSelectedByBlinkerAheadFrame_mp = 332 ;
	optional float OBF_proSelectedByLaneChangePredProbability3To1_mp = 333 ;
	optional float OBF_proSelectedByLaneChangePredProbability5To1_mp = 334 ;
	optional float OBF_proSelectedBySVM3To1_mp = 335 ;
	optional float OBF_proSelectedBySVM5To1_mp = 336 ;
	optional uint32 SGA_cntUSSFSPAlertDebounceCnt_mp = 337 ;
	optional uint32 SGA_flgAlertUSS_mp = 338 ;
	optional uint32 SGA_flgAlertRadarFC_mp = 339 ;
	optional uint32 SGA_flgAlertRadarFL_mp = 340 ;
	optional uint32 SGA_flgAlertRadarFR_mp = 341 ;
	optional uint32 SGA_flgAlertME_mp = 342 ;
	optional uint32 SGA_flgAlertActive_mp = 343 ;
	optional uint32 SGA_flgAlertFSPSceneValid_mp = 344 ;
	optional uint32 SGA_flgAlertUSSSceneValid_mp = 345 ;
	optional uint32 SGA_flgAlertSceneValid_mp = 346 ;
	optional uint32 SGA_stAlertSt_mp = 347 ;
	optional uint32 SGA_indexAlertRadarFCIndex_mp = 348 ;
	optional uint32 SGA_indexAlertRadarFLIndex_mp = 349 ;
	optional uint32 SGA_indexAlertRadarFRIndex_mp = 350 ;
	optional uint32 SGA_indexAlertMEIndex_mp = 351 ;
	optional uint32 SGA_indexAlertUSSIndex_mp = 352 ;
	optional bool SGA_flgRecordEvent_mp = 353 ;
	optional float SGA_UssObjPosX_mp = 354 ;
	optional float SGA_UssObjPosY_mp = 355 ;
	optional float SGA_UssObjProb_mp = 356 ;
	optional uint32 SGA_UssObjType_mp = 357 ;
	optional float SGA_UssPosYMinThreshold_mp = 358 ;
	optional float SGA_UssPosYMaxThreshold_mp = 359 ;
	optional float SGA_FLRadarObjPosX_mp = 360 ;
	optional float SGA_FLRadarObjPosY_mp = 361 ;
	optional float SGA_FLRadarObjVX_mp = 362 ;
	optional float SGA_FLRadarObjVY_mp = 363 ;
	optional uint32 SGA_FLRadarObjValidStatus_mp = 364 ;
	optional float SGA_FRRadarObjPosX_mp = 365 ;
	optional float SGA_FRRadarObjPosY_mp = 366 ;
	optional float SGA_FRRadarObjVX_mp = 367 ;
	optional float SGA_FRRadarObjVY_mp = 368 ;
	optional uint32 SGA_FRRadarObjValidStatus_mp = 369 ;
	optional float SGA_FCRadarObjPosX_mp = 370 ;
	optional float SGA_FCRadarObjPosY_mp = 371 ;
	optional float SGA_FCRadarObjVX_mp = 372 ;
	optional float SGA_FCRadarObjVY_mp = 373 ;
	optional uint32 SGA_FCRadarObjValidStatus_mp = 374 ;
	optional float SGA_MEObjPosX_mp = 375 ;
	optional float SGA_MEObjPosY_mp = 376 ;
	optional uint32 SGA_MEObjType_mp = 377 ;
	optional float SGA_MEObjExistProb_mp = 378 ;
	optional uint32 SGA_MEObjValidStatus_mp = 379 ;
	optional uint32 SGA_SvcFrntObstacleStsReason_mp = 380 ;
	optional uint32 TSI_FlgHostLaneSuperWide_mp = 381 ;

    optional uint64 timestamp = 536870905; // ptp timestamp, nanosecond，used for data bundle readin 
	// optional SensorTSHeader sensor_original_ts = 536870906;   // sensor original ts
	optional uint64 publish_ptp_ts = 536870907; // publish ptp timestamp, uint in nanosec
	optional string publisher_id = 536870909; // uuid of the publisher
	optional uint64 counter = 536870910; // message counter
	optional uint64 publish_ts = 536870911;    // publish timestamp; unit : nanosecond
}
