syntax = "proto2";

option cc_enable_arenas = true;
package nio.ad.messages.debug;
// import "common/perf/sensor_ts_header.proto";

message DLBOBFDebugMeas{

	optional float OBF_errorCamCal_mp = 1 ;
	optional uint32 OBF_nDistr1CamCal_mp = 2 ;
	optional uint32 OBF_nDistr2CamCal_mp = 3 ;
	optional uint32 OBF_nDistr3CamCal_mp = 4 ;
	optional uint32 OBF_nDistr4CamCal_mp = 5 ;
	optional int32 Rdr_cntVldFrameCntInVyStats_mp = 6 ;
	optional int32 Rdr_cntObjCnt0CntInVyStats_mp = 7 ;
	optional int32 Rdr_cntObjCnt1CntInVyStats_mp = 8 ;
	optional int32 Rdr_cntObjCnt2CntInVyStats_mp = 9 ;
	optional int32 Rdr_cntObjCnt3CntInVyStats_mp = 10 ;
	optional float Rdr_vAvgVy0InVyStats_mp = 11 ;
	optional float Rdr_vAvgVy1InVyStats_mp = 12 ;
	optional float Rdr_vAvgVy2InVyStats_mp = 13 ;
	optional float Rdr_vAvgVy3InVyStats_mp = 14 ;
	optional float Rdr_dstAvgFront_mp = 15 ;
	optional float Rdr_dstAvgRear_mp = 16 ;
	optional int32 Rdr_cntRadarStGridFrameCnt_mp = 17 ;
	optional int32 Rdr_cntRadarStGridCntFL0_mp = 18 ;
	optional int32 Rdr_cntRadarStGridCntFL2_mp = 19 ;
	optional int32 Rdr_cntRadarStGridCntFL4_mp = 20 ;
	optional int32 Rdr_cntRadarStGridCntFL6_mp = 21 ;
	optional int32 Rdr_cntRadarStGridCntFL16_mp = 22 ;
	optional int32 Rdr_cntRadarStGridCntFL18_mp = 23 ;
	optional int32 Rdr_cntRadarStGridCntFL20_mp = 24 ;
	optional int32 Rdr_cntRadarStGridCntFL22_mp = 25 ;
	optional int32 Rdr_cntRadarStGridCntFL32_mp = 26 ;
	optional int32 Rdr_cntRadarStGridCntFL34_mp = 27 ;
	optional int32 Rdr_cntRadarStGridCntFL36_mp = 28 ;
	optional int32 Rdr_cntRadarStGridCntFL38_mp = 29 ;
	optional int32 Rdr_cntRadarStGridCntFL48_mp = 30 ;
	optional int32 Rdr_cntRadarStGridCntFL50_mp = 31 ;
	optional int32 Rdr_cntRadarStGridCntFL52_mp = 32 ;
	optional int32 Rdr_cntRadarStGridCntFL54_mp = 33 ;
	optional int32 Rdr_cntRadarStGridCntFR0_mp = 34 ;
	optional int32 Rdr_cntRadarStGridCntFR2_mp = 35 ;
	optional int32 Rdr_cntRadarStGridCntFR4_mp = 36 ;
	optional int32 Rdr_cntRadarStGridCntFR6_mp = 37 ;
	optional int32 Rdr_cntRadarStGridCntFR16_mp = 38 ;
	optional int32 Rdr_cntRadarStGridCntFR18_mp = 39 ;
	optional int32 Rdr_cntRadarStGridCntFR20_mp = 40 ;
	optional int32 Rdr_cntRadarStGridCntFR22_mp = 41 ;
	optional int32 Rdr_cntRadarStGridCntFR32_mp = 42 ;
	optional int32 Rdr_cntRadarStGridCntFR34_mp = 43 ;
	optional int32 Rdr_cntRadarStGridCntFR36_mp = 44 ;
	optional int32 Rdr_cntRadarStGridCntFR38_mp = 45 ;
	optional int32 Rdr_cntRadarStGridCntFR48_mp = 46 ;
	optional int32 Rdr_cntRadarStGridCntFR50_mp = 47 ;
	optional int32 Rdr_cntRadarStGridCntFR52_mp = 48 ;
	optional int32 Rdr_cntRadarStGridCntFR54_mp = 49 ;
	optional int32 Rdr_cntRadarStGridCntRL0_mp = 50 ;
	optional int32 Rdr_cntRadarStGridCntRL2_mp = 51 ;
	optional int32 Rdr_cntRadarStGridCntRL4_mp = 52 ;
	optional int32 Rdr_cntRadarStGridCntRL6_mp = 53 ;
	optional int32 Rdr_cntRadarStGridCntRL16_mp = 54 ;
	optional int32 Rdr_cntRadarStGridCntRL18_mp = 55 ;
	optional int32 Rdr_cntRadarStGridCntRL20_mp = 56 ;
	optional int32 Rdr_cntRadarStGridCntRL22_mp = 57 ;
	optional int32 Rdr_cntRadarStGridCntRL32_mp = 58 ;
	optional int32 Rdr_cntRadarStGridCntRL34_mp = 59 ;
	optional int32 Rdr_cntRadarStGridCntRL36_mp = 60 ;
	optional int32 Rdr_cntRadarStGridCntRL38_mp = 61 ;
	optional int32 Rdr_cntRadarStGridCntRL48_mp = 62 ;
	optional int32 Rdr_cntRadarStGridCntRL50_mp = 63 ;
	optional int32 Rdr_cntRadarStGridCntRL52_mp = 64 ;
	optional int32 Rdr_cntRadarStGridCntRL54_mp = 65 ;
	optional int32 Rdr_cntRadarStGridCntRR0_mp = 66 ;
	optional int32 Rdr_cntRadarStGridCntRR2_mp = 67 ;
	optional int32 Rdr_cntRadarStGridCntRR4_mp = 68 ;
	optional int32 Rdr_cntRadarStGridCntRR6_mp = 69 ;
	optional int32 Rdr_cntRadarStGridCntRR16_mp = 70 ;
	optional int32 Rdr_cntRadarStGridCntRR18_mp = 71 ;
	optional int32 Rdr_cntRadarStGridCntRR20_mp = 72 ;
	optional int32 Rdr_cntRadarStGridCntRR22_mp = 73 ;
	optional int32 Rdr_cntRadarStGridCntRR32_mp = 74 ;
	optional int32 Rdr_cntRadarStGridCntRR34_mp = 75 ;
	optional int32 Rdr_cntRadarStGridCntRR36_mp = 76 ;
	optional int32 Rdr_cntRadarStGridCntRR38_mp = 77 ;
	optional int32 Rdr_cntRadarStGridCntRR48_mp = 78 ;
	optional int32 Rdr_cntRadarStGridCntRR50_mp = 79 ;
	optional int32 Rdr_cntRadarStGridCntRR52_mp = 80 ;
	optional int32 Rdr_cntRadarStGridCntRR54_mp = 81 ;
	optional bool Rdr_flgParamIsValid_mp = 82 ;
	optional int32 Rdr_numObjMatchActiveF_mp = 83 ;
	optional int32 Rdr_numObjMatchActiveR_mp = 84 ;
	optional float Rdr_dstObjMatchThrdF_mp = 85 ;
	optional float Rdr_dstObjMatchThrdR_mp = 86 ;
	optional float Rdr_rObjMatchLossThrdF_mp = 87 ;
	optional float Rdr_rObjMatchLossThrdR_mp = 88 ;
	optional int32 Rdr_frameObjCntActive_mp = 89 ;
	optional float Rdr_numObjCntThrdF_mp = 90 ;
	optional float Rdr_numObjCntThrdR_mp = 91 ;
	optional int32 Rdr_numGridCntThrdF_mp = 92 ;
	optional int32 Rdr_numGridCntThrdR_mp = 93 ;
	optional float Rdr_rObjCntRatioThrdR_mp = 94 ;
	optional float Rdr_rObjCntRatioThrdF_mp = 95 ;
	optional bool OBF_stRearObjDet_mp = 96 ;
	optional float OBF_dstRearObjDetX_mp = 97 ;
	optional float OBF_dstRearObjDetY_mp = 98 ;

    optional uint64 timestamp = 536870905; // ptp timestamp, nanosecond，used for data bundle readin 
	// optional SensorTSHeader sensor_original_ts = 536870906;   // sensor original ts
	optional uint64 publish_ptp_ts = 536870907; // publish ptp timestamp, uint in nanosec
	optional string publisher_id = 536870909; // uuid of the publisher
	optional uint64 counter = 536870910; // message counter
	optional uint64 publish_ts = 536870911;    // publish timestamp; unit : nanosecond
}
