syntax = "proto2";

option cc_enable_arenas = true;
package nio.ad.messages;
import "common/perf/sensor_ts_header.proto";

import "common/perception/perception_objects.proto";
import "common/perception/radar_object.proto";
import "common/perception/radar_object_side.proto";
import "common/perception/vision_road_detection.proto";
import "common/perception/vision_failsafe.proto";
import "common/perception/vision_feature_flag.proto";
import "common/perception/free_space.proto";
import "common/perception/vision_traffic_light.proto";
import "common/perception/vision_traffic_sign.proto";
import "common/perception/vision_vehicle_light.proto";
import "common/vehicle_in/vehicle_10ms.proto";
import "common/vehicle_in/vehicle_50ms.proto";
import "common/map_engine/sd_map.proto";
import "np/apps/fct_out.proto";
import "common/platform/mcu_proxy/vehicle/vehicle_info.proto";
import "common/perception/od_output.proto";
import "common/perception/road_perception_2d.proto";

message EHYSINTopicTime{
  optional uint64 received_topic_publish_ts = 1;
  optional uint64 received_topic_counter = 2; 
}

message EHYSINOutputs{
  optional ObjectsDetection vision_objects =1;
  optional RadarSensor radar_info =2;
  optional RoadDetection vision_road =3;
  optional FailSafeDetection vision_failsafe =4;
  optional Features vision_feature =5;
  optional FreeSpaceDetection vision_fsp =6;
  optional TrafficLightDetection vision_traffic_light =7;
  optional TrafficSignDetection vision_traffic_sign =8;
  optional VehicleLightDetection vision_vehicle_light =9;
  optional VEH10ms vehicle_10ms =10;
  optional VEH50ms vehicle_50ms =11;
  optional SdMap sd_map =12;
  optional FctOut fct_out =13;
  optional VehicleInfo vehicle_config =14;

  optional EHYSINTopicTime radar_info_topic =15;
  optional EHYSINTopicTime vision_objects_topic =16;
  optional EHYSINTopicTime vision_road_topic =17;
  optional EHYSINTopicTime vision_failsafe_topic =18;
  optional EHYSINTopicTime vision_feature_topic =19;
  optional EHYSINTopicTime vision_fsp_topic =20;
  optional EHYSINTopicTime vision_traffic_light_topic =21;
  optional EHYSINTopicTime vision_traffic_sign_topic =22;
  optional EHYSINTopicTime vision_vehicle_light_topic =23;
  optional EHYSINTopicTime vehicle_10ms_topic =24;
  optional EHYSINTopicTime vehicle_50ms_topic =25;
  optional EHYSINTopicTime vehicle_fctout_topic =26;
  optional EHYSINTopicTime sd_map_topic =27;
  optional EHYSINTopicTime lidar_read_ts =28;
  optional EHYSINTopicTime vehicle_config_topic =29;
  optional EHYSINTopicTime dead_reckoning_latest_ts =30;

  optional ODOutputPb od_output =31;
  optional EHYSINTopicTime od_output_topic =32;
  optional LaneList lanelist =33;
  optional EHYSINTopicTime lanelist_topic =34;
  optional EHYSINTopicTime radar_side_feature_topic =35;
  optional EHYSINTopicTime nop_functionstatus_topic =36;

  optional uint64 ehy_input_timestamp =37;//uint in nanosec

  optional RadarSensorSide side_radar_info = 38;
  optional EHYSINTopicTime radar_side_info_topic =39;

  optional EHYSINTopicTime side_feature_topic = 40;
  optional BEVLane bevlane =41;
  optional EHYSINTopicTime bevlane_topic =42;
  optional EHYSINTopicTime lk_ts1 = 43;
  optional EHYSINTopicTime lk_ts2 = 44;

  repeated EHYSINTopicTime logged_ts = 45;
  optional EHYSINTopicTime obf_output_topic = 46;

  optional uint64 timestamp = 536870905; // ptp timestamp, nanosecond，used for data bundle readin  
  optional SensorTSHeader sensor_original_ts = 536870906;   // sensor original ts
  optional uint64 publish_ptp_ts = 536870907; // publish ptp timestamp, uint in nanosec
  optional string publisher_id = 536870909;   // uuid of the publisher
  optional uint64 counter = 536870910;        // message counter
  optional uint64 publish_ts = 536870911;     // publish utc timestamp; unit : nanosecond
}


