syntax = "proto2";

option cc_enable_arenas = true;
package nio.ad.messages;

import "common/cfgclient/cfg_info.proto";
import "common/perf/sensor_ts_header.proto";

//receive request signal from app

message CfgFileRequest {    
    optional CfgModule module           = 1;  //module name
    optional SubFunc func               = 2;  //module sub func 
    
    optional uint64 timestamp = 536870905; // ptp timestamp, nanosecond，used for data bundle readin
    optional SensorTSHeader sensor_original_ts = 536870906;   // sensor original ts
    optional uint64 publish_ptp_ts   = 536870907;   //publish ptp timestamp, uint in nanosec
    optional string publisher_id     = 536870909;   // uuid of the publisher
    optional uint64 counter           = 536870910;  // message counter
    optional uint64 publish_ts      = 536870911;  // publish timestamp; unit : nanosecond
}