// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: np/apps/road_model_outputs.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_np_2fapps_2froad_5fmodel_5foutputs_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_np_2fapps_2froad_5fmodel_5foutputs_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3018000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3018001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "common/perf/sensor_ts_header.pb.h"
#include "np/apps/ehy_obf_outputs.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_np_2fapps_2froad_5fmodel_5foutputs_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_np_2fapps_2froad_5fmodel_5foutputs_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_np_2fapps_2froad_5fmodel_5foutputs_2eproto;
namespace nio {
namespace ad {
namespace messages {
class LineInfo;
struct LineInfoDefaultTypeInternal;
extern LineInfoDefaultTypeInternal _LineInfo_default_instance_;
class ObjectInfo;
struct ObjectInfoDefaultTypeInternal;
extern ObjectInfoDefaultTypeInternal _ObjectInfo_default_instance_;
class RoadModelOutputs;
struct RoadModelOutputsDefaultTypeInternal;
extern RoadModelOutputsDefaultTypeInternal _RoadModelOutputs_default_instance_;
}  // namespace messages
}  // namespace ad
}  // namespace nio
PROTOBUF_NAMESPACE_OPEN
template<> ::nio::ad::messages::LineInfo* Arena::CreateMaybeMessage<::nio::ad::messages::LineInfo>(Arena*);
template<> ::nio::ad::messages::ObjectInfo* Arena::CreateMaybeMessage<::nio::ad::messages::ObjectInfo>(Arena*);
template<> ::nio::ad::messages::RoadModelOutputs* Arena::CreateMaybeMessage<::nio::ad::messages::RoadModelOutputs>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace nio {
namespace ad {
namespace messages {

enum LineInfo_Role : int {
  LineInfo_Role_LDRole_Unknown = 0,
  LineInfo_Role_LDRole_Host_Left = 1,
  LineInfo_Role_LDRole_Host_Right = 2,
  LineInfo_Role_LDRole_Adjacent_Left_Left = 3,
  LineInfo_Role_LDRole_Adjacent_Left_Right = 4,
  LineInfo_Role_LDRole_Adjacent_Right_Left = 5,
  LineInfo_Role_LDRole_Adjacent_Right_Right = 6
};
bool LineInfo_Role_IsValid(int value);
constexpr LineInfo_Role LineInfo_Role_Role_MIN = LineInfo_Role_LDRole_Unknown;
constexpr LineInfo_Role LineInfo_Role_Role_MAX = LineInfo_Role_LDRole_Adjacent_Right_Right;
constexpr int LineInfo_Role_Role_ARRAYSIZE = LineInfo_Role_Role_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LineInfo_Role_descriptor();
template<typename T>
inline const std::string& LineInfo_Role_Name(T enum_t_value) {
  static_assert(::std::is_same<T, LineInfo_Role>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function LineInfo_Role_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    LineInfo_Role_descriptor(), enum_t_value);
}
inline bool LineInfo_Role_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LineInfo_Role* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LineInfo_Role>(
    LineInfo_Role_descriptor(), name, value);
}
// ===================================================================

class LineInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nio.ad.messages.LineInfo) */ {
 public:
  inline LineInfo() : LineInfo(nullptr) {}
  ~LineInfo() override;
  explicit constexpr LineInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LineInfo(const LineInfo& from);
  LineInfo(LineInfo&& from) noexcept
    : LineInfo() {
    *this = ::std::move(from);
  }

  inline LineInfo& operator=(const LineInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline LineInfo& operator=(LineInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LineInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const LineInfo* internal_default_instance() {
    return reinterpret_cast<const LineInfo*>(
               &_LineInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LineInfo& a, LineInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(LineInfo* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LineInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LineInfo* New() const final {
    return new LineInfo();
  }

  LineInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LineInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LineInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const LineInfo& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LineInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nio.ad.messages.LineInfo";
  }
  protected:
  explicit LineInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef LineInfo_Role Role;
  static constexpr Role LDRole_Unknown =
    LineInfo_Role_LDRole_Unknown;
  static constexpr Role LDRole_Host_Left =
    LineInfo_Role_LDRole_Host_Left;
  static constexpr Role LDRole_Host_Right =
    LineInfo_Role_LDRole_Host_Right;
  static constexpr Role LDRole_Adjacent_Left_Left =
    LineInfo_Role_LDRole_Adjacent_Left_Left;
  static constexpr Role LDRole_Adjacent_Left_Right =
    LineInfo_Role_LDRole_Adjacent_Left_Right;
  static constexpr Role LDRole_Adjacent_Right_Left =
    LineInfo_Role_LDRole_Adjacent_Right_Left;
  static constexpr Role LDRole_Adjacent_Right_Right =
    LineInfo_Role_LDRole_Adjacent_Right_Right;
  static inline bool Role_IsValid(int value) {
    return LineInfo_Role_IsValid(value);
  }
  static constexpr Role Role_MIN =
    LineInfo_Role_Role_MIN;
  static constexpr Role Role_MAX =
    LineInfo_Role_Role_MAX;
  static constexpr int Role_ARRAYSIZE =
    LineInfo_Role_Role_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Role_descriptor() {
    return LineInfo_Role_descriptor();
  }
  template<typename T>
  static inline const std::string& Role_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Role>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Role_Name.");
    return LineInfo_Role_Name(enum_t_value);
  }
  static inline bool Role_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Role* value) {
    return LineInfo_Role_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kPointsFieldNumber = 10,
    kRoleFieldNumber = 1,
    kIdFieldNumber = 2,
    kOriTrackIdFieldNumber = 3,
    kC0FieldNumber = 4,
    kC1FieldNumber = 5,
    kC2FieldNumber = 6,
    kC3FieldNumber = 7,
    kStartFieldNumber = 8,
    kEndFieldNumber = 9,
  };
  // repeated .nio.ad.messages.Point3D points = 10;
  int points_size() const;
  private:
  int _internal_points_size() const;
  public:
  void clear_points();
  ::nio::ad::messages::Point3D* mutable_points(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Point3D >*
      mutable_points();
  private:
  const ::nio::ad::messages::Point3D& _internal_points(int index) const;
  ::nio::ad::messages::Point3D* _internal_add_points();
  public:
  const ::nio::ad::messages::Point3D& points(int index) const;
  ::nio::ad::messages::Point3D* add_points();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Point3D >&
      points() const;

  // optional .nio.ad.messages.LineInfo.Role role = 1;
  bool has_role() const;
  private:
  bool _internal_has_role() const;
  public:
  void clear_role();
  ::nio::ad::messages::LineInfo_Role role() const;
  void set_role(::nio::ad::messages::LineInfo_Role value);
  private:
  ::nio::ad::messages::LineInfo_Role _internal_role() const;
  void _internal_set_role(::nio::ad::messages::LineInfo_Role value);
  public:

  // optional uint32 id = 2;
  bool has_id() const;
  private:
  bool _internal_has_id() const;
  public:
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 ori_track_id = 3;
  bool has_ori_track_id() const;
  private:
  bool _internal_has_ori_track_id() const;
  public:
  void clear_ori_track_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 ori_track_id() const;
  void set_ori_track_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_ori_track_id() const;
  void _internal_set_ori_track_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional float c0 = 4;
  bool has_c0() const;
  private:
  bool _internal_has_c0() const;
  public:
  void clear_c0();
  float c0() const;
  void set_c0(float value);
  private:
  float _internal_c0() const;
  void _internal_set_c0(float value);
  public:

  // optional float c1 = 5;
  bool has_c1() const;
  private:
  bool _internal_has_c1() const;
  public:
  void clear_c1();
  float c1() const;
  void set_c1(float value);
  private:
  float _internal_c1() const;
  void _internal_set_c1(float value);
  public:

  // optional float c2 = 6;
  bool has_c2() const;
  private:
  bool _internal_has_c2() const;
  public:
  void clear_c2();
  float c2() const;
  void set_c2(float value);
  private:
  float _internal_c2() const;
  void _internal_set_c2(float value);
  public:

  // optional float c3 = 7;
  bool has_c3() const;
  private:
  bool _internal_has_c3() const;
  public:
  void clear_c3();
  float c3() const;
  void set_c3(float value);
  private:
  float _internal_c3() const;
  void _internal_set_c3(float value);
  public:

  // optional float start = 8;
  bool has_start() const;
  private:
  bool _internal_has_start() const;
  public:
  void clear_start();
  float start() const;
  void set_start(float value);
  private:
  float _internal_start() const;
  void _internal_set_start(float value);
  public:

  // optional float end = 9;
  bool has_end() const;
  private:
  bool _internal_has_end() const;
  public:
  void clear_end();
  float end() const;
  void set_end(float value);
  private:
  float _internal_end() const;
  void _internal_set_end(float value);
  public:

  // @@protoc_insertion_point(class_scope:nio.ad.messages.LineInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Point3D > points_;
  int role_;
  ::PROTOBUF_NAMESPACE_ID::uint32 id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 ori_track_id_;
  float c0_;
  float c1_;
  float c2_;
  float c3_;
  float start_;
  float end_;
  friend struct ::TableStruct_np_2fapps_2froad_5fmodel_5foutputs_2eproto;
};
// -------------------------------------------------------------------

class ObjectInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nio.ad.messages.ObjectInfo) */ {
 public:
  inline ObjectInfo() : ObjectInfo(nullptr) {}
  ~ObjectInfo() override;
  explicit constexpr ObjectInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ObjectInfo(const ObjectInfo& from);
  ObjectInfo(ObjectInfo&& from) noexcept
    : ObjectInfo() {
    *this = ::std::move(from);
  }

  inline ObjectInfo& operator=(const ObjectInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObjectInfo& operator=(ObjectInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ObjectInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ObjectInfo* internal_default_instance() {
    return reinterpret_cast<const ObjectInfo*>(
               &_ObjectInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ObjectInfo& a, ObjectInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ObjectInfo* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObjectInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ObjectInfo* New() const final {
    return new ObjectInfo();
  }

  ObjectInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ObjectInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ObjectInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ObjectInfo& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObjectInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nio.ad.messages.ObjectInfo";
  }
  protected:
  explicit ObjectInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPointsFieldNumber = 3,
    kIdFieldNumber = 1,
    kOriTrackIdFieldNumber = 2,
  };
  // repeated .nio.ad.messages.Point3D points = 3;
  int points_size() const;
  private:
  int _internal_points_size() const;
  public:
  void clear_points();
  ::nio::ad::messages::Point3D* mutable_points(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Point3D >*
      mutable_points();
  private:
  const ::nio::ad::messages::Point3D& _internal_points(int index) const;
  ::nio::ad::messages::Point3D* _internal_add_points();
  public:
  const ::nio::ad::messages::Point3D& points(int index) const;
  ::nio::ad::messages::Point3D* add_points();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Point3D >&
      points() const;

  // optional uint32 id = 1;
  bool has_id() const;
  private:
  bool _internal_has_id() const;
  public:
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 ori_track_id = 2;
  bool has_ori_track_id() const;
  private:
  bool _internal_has_ori_track_id() const;
  public:
  void clear_ori_track_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 ori_track_id() const;
  void set_ori_track_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_ori_track_id() const;
  void _internal_set_ori_track_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:nio.ad.messages.ObjectInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Point3D > points_;
  ::PROTOBUF_NAMESPACE_ID::uint32 id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 ori_track_id_;
  friend struct ::TableStruct_np_2fapps_2froad_5fmodel_5foutputs_2eproto;
};
// -------------------------------------------------------------------

class RoadModelOutputs final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nio.ad.messages.RoadModelOutputs) */ {
 public:
  inline RoadModelOutputs() : RoadModelOutputs(nullptr) {}
  ~RoadModelOutputs() override;
  explicit constexpr RoadModelOutputs(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoadModelOutputs(const RoadModelOutputs& from);
  RoadModelOutputs(RoadModelOutputs&& from) noexcept
    : RoadModelOutputs() {
    *this = ::std::move(from);
  }

  inline RoadModelOutputs& operator=(const RoadModelOutputs& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoadModelOutputs& operator=(RoadModelOutputs&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoadModelOutputs& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoadModelOutputs* internal_default_instance() {
    return reinterpret_cast<const RoadModelOutputs*>(
               &_RoadModelOutputs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RoadModelOutputs& a, RoadModelOutputs& b) {
    a.Swap(&b);
  }
  inline void Swap(RoadModelOutputs* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoadModelOutputs* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RoadModelOutputs* New() const final {
    return new RoadModelOutputs();
  }

  RoadModelOutputs* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RoadModelOutputs>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoadModelOutputs& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const RoadModelOutputs& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoadModelOutputs* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nio.ad.messages.RoadModelOutputs";
  }
  protected:
  explicit RoadModelOutputs(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLineInfosFieldNumber = 2,
    kObjectInfosFieldNumber = 3,
    kPublisherIdFieldNumber = 536870909,
    kSensorOriginalTsFieldNumber = 536870906,
    kTimestampFieldNumber = 1,
    kPublishPtpTsFieldNumber = 536870907,
    kCounterFieldNumber = 536870910,
    kPublishTsFieldNumber = 536870911,
  };
  // repeated .nio.ad.messages.LineInfo LineInfos = 2;
  int lineinfos_size() const;
  private:
  int _internal_lineinfos_size() const;
  public:
  void clear_lineinfos();
  ::nio::ad::messages::LineInfo* mutable_lineinfos(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::LineInfo >*
      mutable_lineinfos();
  private:
  const ::nio::ad::messages::LineInfo& _internal_lineinfos(int index) const;
  ::nio::ad::messages::LineInfo* _internal_add_lineinfos();
  public:
  const ::nio::ad::messages::LineInfo& lineinfos(int index) const;
  ::nio::ad::messages::LineInfo* add_lineinfos();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::LineInfo >&
      lineinfos() const;

  // repeated .nio.ad.messages.ObjectInfo ObjectInfos = 3;
  int objectinfos_size() const;
  private:
  int _internal_objectinfos_size() const;
  public:
  void clear_objectinfos();
  ::nio::ad::messages::ObjectInfo* mutable_objectinfos(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::ObjectInfo >*
      mutable_objectinfos();
  private:
  const ::nio::ad::messages::ObjectInfo& _internal_objectinfos(int index) const;
  ::nio::ad::messages::ObjectInfo* _internal_add_objectinfos();
  public:
  const ::nio::ad::messages::ObjectInfo& objectinfos(int index) const;
  ::nio::ad::messages::ObjectInfo* add_objectinfos();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::ObjectInfo >&
      objectinfos() const;

  // optional string publisher_id = 536870909;
  bool has_publisher_id() const;
  private:
  bool _internal_has_publisher_id() const;
  public:
  void clear_publisher_id();
  const std::string& publisher_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_publisher_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_publisher_id();
  PROTOBUF_MUST_USE_RESULT std::string* release_publisher_id();
  void set_allocated_publisher_id(std::string* publisher_id);
  private:
  const std::string& _internal_publisher_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_publisher_id(const std::string& value);
  std::string* _internal_mutable_publisher_id();
  public:

  // optional .nio.ad.messages.SensorTSHeader sensor_original_ts = 536870906;
  bool has_sensor_original_ts() const;
  private:
  bool _internal_has_sensor_original_ts() const;
  public:
  void clear_sensor_original_ts();
  const ::nio::ad::messages::SensorTSHeader& sensor_original_ts() const;
  PROTOBUF_MUST_USE_RESULT ::nio::ad::messages::SensorTSHeader* release_sensor_original_ts();
  ::nio::ad::messages::SensorTSHeader* mutable_sensor_original_ts();
  void set_allocated_sensor_original_ts(::nio::ad::messages::SensorTSHeader* sensor_original_ts);
  private:
  const ::nio::ad::messages::SensorTSHeader& _internal_sensor_original_ts() const;
  ::nio::ad::messages::SensorTSHeader* _internal_mutable_sensor_original_ts();
  public:
  void unsafe_arena_set_allocated_sensor_original_ts(
      ::nio::ad::messages::SensorTSHeader* sensor_original_ts);
  ::nio::ad::messages::SensorTSHeader* unsafe_arena_release_sensor_original_ts();

  // optional uint64 timestamp = 1;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 publish_ptp_ts = 536870907;
  bool has_publish_ptp_ts() const;
  private:
  bool _internal_has_publish_ptp_ts() const;
  public:
  void clear_publish_ptp_ts();
  ::PROTOBUF_NAMESPACE_ID::uint64 publish_ptp_ts() const;
  void set_publish_ptp_ts(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_publish_ptp_ts() const;
  void _internal_set_publish_ptp_ts(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 counter = 536870910;
  bool has_counter() const;
  private:
  bool _internal_has_counter() const;
  public:
  void clear_counter();
  ::PROTOBUF_NAMESPACE_ID::uint64 counter() const;
  void set_counter(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_counter() const;
  void _internal_set_counter(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 publish_ts = 536870911;
  bool has_publish_ts() const;
  private:
  bool _internal_has_publish_ts() const;
  public:
  void clear_publish_ts();
  ::PROTOBUF_NAMESPACE_ID::uint64 publish_ts() const;
  void set_publish_ts(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_publish_ts() const;
  void _internal_set_publish_ts(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:nio.ad.messages.RoadModelOutputs)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::LineInfo > lineinfos_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::ObjectInfo > objectinfos_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr publisher_id_;
  ::nio::ad::messages::SensorTSHeader* sensor_original_ts_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_;
  ::PROTOBUF_NAMESPACE_ID::uint64 publish_ptp_ts_;
  ::PROTOBUF_NAMESPACE_ID::uint64 counter_;
  ::PROTOBUF_NAMESPACE_ID::uint64 publish_ts_;
  friend struct ::TableStruct_np_2fapps_2froad_5fmodel_5foutputs_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LineInfo

// optional .nio.ad.messages.LineInfo.Role role = 1;
inline bool LineInfo::_internal_has_role() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool LineInfo::has_role() const {
  return _internal_has_role();
}
inline void LineInfo::clear_role() {
  role_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::nio::ad::messages::LineInfo_Role LineInfo::_internal_role() const {
  return static_cast< ::nio::ad::messages::LineInfo_Role >(role_);
}
inline ::nio::ad::messages::LineInfo_Role LineInfo::role() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.LineInfo.role)
  return _internal_role();
}
inline void LineInfo::_internal_set_role(::nio::ad::messages::LineInfo_Role value) {
  assert(::nio::ad::messages::LineInfo_Role_IsValid(value));
  _has_bits_[0] |= 0x00000001u;
  role_ = value;
}
inline void LineInfo::set_role(::nio::ad::messages::LineInfo_Role value) {
  _internal_set_role(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.LineInfo.role)
}

// optional uint32 id = 2;
inline bool LineInfo::_internal_has_id() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool LineInfo::has_id() const {
  return _internal_has_id();
}
inline void LineInfo::clear_id() {
  id_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 LineInfo::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 LineInfo::id() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.LineInfo.id)
  return _internal_id();
}
inline void LineInfo::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000002u;
  id_ = value;
}
inline void LineInfo::set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.LineInfo.id)
}

// optional uint32 ori_track_id = 3;
inline bool LineInfo::_internal_has_ori_track_id() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool LineInfo::has_ori_track_id() const {
  return _internal_has_ori_track_id();
}
inline void LineInfo::clear_ori_track_id() {
  ori_track_id_ = 0u;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 LineInfo::_internal_ori_track_id() const {
  return ori_track_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 LineInfo::ori_track_id() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.LineInfo.ori_track_id)
  return _internal_ori_track_id();
}
inline void LineInfo::_internal_set_ori_track_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000004u;
  ori_track_id_ = value;
}
inline void LineInfo::set_ori_track_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_ori_track_id(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.LineInfo.ori_track_id)
}

// optional float c0 = 4;
inline bool LineInfo::_internal_has_c0() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool LineInfo::has_c0() const {
  return _internal_has_c0();
}
inline void LineInfo::clear_c0() {
  c0_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline float LineInfo::_internal_c0() const {
  return c0_;
}
inline float LineInfo::c0() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.LineInfo.c0)
  return _internal_c0();
}
inline void LineInfo::_internal_set_c0(float value) {
  _has_bits_[0] |= 0x00000008u;
  c0_ = value;
}
inline void LineInfo::set_c0(float value) {
  _internal_set_c0(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.LineInfo.c0)
}

// optional float c1 = 5;
inline bool LineInfo::_internal_has_c1() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool LineInfo::has_c1() const {
  return _internal_has_c1();
}
inline void LineInfo::clear_c1() {
  c1_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline float LineInfo::_internal_c1() const {
  return c1_;
}
inline float LineInfo::c1() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.LineInfo.c1)
  return _internal_c1();
}
inline void LineInfo::_internal_set_c1(float value) {
  _has_bits_[0] |= 0x00000010u;
  c1_ = value;
}
inline void LineInfo::set_c1(float value) {
  _internal_set_c1(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.LineInfo.c1)
}

// optional float c2 = 6;
inline bool LineInfo::_internal_has_c2() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool LineInfo::has_c2() const {
  return _internal_has_c2();
}
inline void LineInfo::clear_c2() {
  c2_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline float LineInfo::_internal_c2() const {
  return c2_;
}
inline float LineInfo::c2() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.LineInfo.c2)
  return _internal_c2();
}
inline void LineInfo::_internal_set_c2(float value) {
  _has_bits_[0] |= 0x00000020u;
  c2_ = value;
}
inline void LineInfo::set_c2(float value) {
  _internal_set_c2(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.LineInfo.c2)
}

// optional float c3 = 7;
inline bool LineInfo::_internal_has_c3() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool LineInfo::has_c3() const {
  return _internal_has_c3();
}
inline void LineInfo::clear_c3() {
  c3_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline float LineInfo::_internal_c3() const {
  return c3_;
}
inline float LineInfo::c3() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.LineInfo.c3)
  return _internal_c3();
}
inline void LineInfo::_internal_set_c3(float value) {
  _has_bits_[0] |= 0x00000040u;
  c3_ = value;
}
inline void LineInfo::set_c3(float value) {
  _internal_set_c3(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.LineInfo.c3)
}

// optional float start = 8;
inline bool LineInfo::_internal_has_start() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool LineInfo::has_start() const {
  return _internal_has_start();
}
inline void LineInfo::clear_start() {
  start_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline float LineInfo::_internal_start() const {
  return start_;
}
inline float LineInfo::start() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.LineInfo.start)
  return _internal_start();
}
inline void LineInfo::_internal_set_start(float value) {
  _has_bits_[0] |= 0x00000080u;
  start_ = value;
}
inline void LineInfo::set_start(float value) {
  _internal_set_start(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.LineInfo.start)
}

// optional float end = 9;
inline bool LineInfo::_internal_has_end() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool LineInfo::has_end() const {
  return _internal_has_end();
}
inline void LineInfo::clear_end() {
  end_ = 0;
  _has_bits_[0] &= ~0x00000100u;
}
inline float LineInfo::_internal_end() const {
  return end_;
}
inline float LineInfo::end() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.LineInfo.end)
  return _internal_end();
}
inline void LineInfo::_internal_set_end(float value) {
  _has_bits_[0] |= 0x00000100u;
  end_ = value;
}
inline void LineInfo::set_end(float value) {
  _internal_set_end(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.LineInfo.end)
}

// repeated .nio.ad.messages.Point3D points = 10;
inline int LineInfo::_internal_points_size() const {
  return points_.size();
}
inline int LineInfo::points_size() const {
  return _internal_points_size();
}
inline ::nio::ad::messages::Point3D* LineInfo::mutable_points(int index) {
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.LineInfo.points)
  return points_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Point3D >*
LineInfo::mutable_points() {
  // @@protoc_insertion_point(field_mutable_list:nio.ad.messages.LineInfo.points)
  return &points_;
}
inline const ::nio::ad::messages::Point3D& LineInfo::_internal_points(int index) const {
  return points_.Get(index);
}
inline const ::nio::ad::messages::Point3D& LineInfo::points(int index) const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.LineInfo.points)
  return _internal_points(index);
}
inline ::nio::ad::messages::Point3D* LineInfo::_internal_add_points() {
  return points_.Add();
}
inline ::nio::ad::messages::Point3D* LineInfo::add_points() {
  ::nio::ad::messages::Point3D* _add = _internal_add_points();
  // @@protoc_insertion_point(field_add:nio.ad.messages.LineInfo.points)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Point3D >&
LineInfo::points() const {
  // @@protoc_insertion_point(field_list:nio.ad.messages.LineInfo.points)
  return points_;
}

// -------------------------------------------------------------------

// ObjectInfo

// optional uint32 id = 1;
inline bool ObjectInfo::_internal_has_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ObjectInfo::has_id() const {
  return _internal_has_id();
}
inline void ObjectInfo::clear_id() {
  id_ = 0u;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ObjectInfo::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ObjectInfo::id() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.ObjectInfo.id)
  return _internal_id();
}
inline void ObjectInfo::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000001u;
  id_ = value;
}
inline void ObjectInfo::set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.ObjectInfo.id)
}

// optional uint32 ori_track_id = 2;
inline bool ObjectInfo::_internal_has_ori_track_id() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool ObjectInfo::has_ori_track_id() const {
  return _internal_has_ori_track_id();
}
inline void ObjectInfo::clear_ori_track_id() {
  ori_track_id_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ObjectInfo::_internal_ori_track_id() const {
  return ori_track_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ObjectInfo::ori_track_id() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.ObjectInfo.ori_track_id)
  return _internal_ori_track_id();
}
inline void ObjectInfo::_internal_set_ori_track_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000002u;
  ori_track_id_ = value;
}
inline void ObjectInfo::set_ori_track_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_ori_track_id(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.ObjectInfo.ori_track_id)
}

// repeated .nio.ad.messages.Point3D points = 3;
inline int ObjectInfo::_internal_points_size() const {
  return points_.size();
}
inline int ObjectInfo::points_size() const {
  return _internal_points_size();
}
inline ::nio::ad::messages::Point3D* ObjectInfo::mutable_points(int index) {
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.ObjectInfo.points)
  return points_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Point3D >*
ObjectInfo::mutable_points() {
  // @@protoc_insertion_point(field_mutable_list:nio.ad.messages.ObjectInfo.points)
  return &points_;
}
inline const ::nio::ad::messages::Point3D& ObjectInfo::_internal_points(int index) const {
  return points_.Get(index);
}
inline const ::nio::ad::messages::Point3D& ObjectInfo::points(int index) const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.ObjectInfo.points)
  return _internal_points(index);
}
inline ::nio::ad::messages::Point3D* ObjectInfo::_internal_add_points() {
  return points_.Add();
}
inline ::nio::ad::messages::Point3D* ObjectInfo::add_points() {
  ::nio::ad::messages::Point3D* _add = _internal_add_points();
  // @@protoc_insertion_point(field_add:nio.ad.messages.ObjectInfo.points)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::Point3D >&
ObjectInfo::points() const {
  // @@protoc_insertion_point(field_list:nio.ad.messages.ObjectInfo.points)
  return points_;
}

// -------------------------------------------------------------------

// RoadModelOutputs

// optional uint64 timestamp = 1;
inline bool RoadModelOutputs::_internal_has_timestamp() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool RoadModelOutputs::has_timestamp() const {
  return _internal_has_timestamp();
}
inline void RoadModelOutputs::clear_timestamp() {
  timestamp_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 RoadModelOutputs::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 RoadModelOutputs::timestamp() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.RoadModelOutputs.timestamp)
  return _internal_timestamp();
}
inline void RoadModelOutputs::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000004u;
  timestamp_ = value;
}
inline void RoadModelOutputs::set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.RoadModelOutputs.timestamp)
}

// repeated .nio.ad.messages.LineInfo LineInfos = 2;
inline int RoadModelOutputs::_internal_lineinfos_size() const {
  return lineinfos_.size();
}
inline int RoadModelOutputs::lineinfos_size() const {
  return _internal_lineinfos_size();
}
inline void RoadModelOutputs::clear_lineinfos() {
  lineinfos_.Clear();
}
inline ::nio::ad::messages::LineInfo* RoadModelOutputs::mutable_lineinfos(int index) {
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.RoadModelOutputs.LineInfos)
  return lineinfos_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::LineInfo >*
RoadModelOutputs::mutable_lineinfos() {
  // @@protoc_insertion_point(field_mutable_list:nio.ad.messages.RoadModelOutputs.LineInfos)
  return &lineinfos_;
}
inline const ::nio::ad::messages::LineInfo& RoadModelOutputs::_internal_lineinfos(int index) const {
  return lineinfos_.Get(index);
}
inline const ::nio::ad::messages::LineInfo& RoadModelOutputs::lineinfos(int index) const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.RoadModelOutputs.LineInfos)
  return _internal_lineinfos(index);
}
inline ::nio::ad::messages::LineInfo* RoadModelOutputs::_internal_add_lineinfos() {
  return lineinfos_.Add();
}
inline ::nio::ad::messages::LineInfo* RoadModelOutputs::add_lineinfos() {
  ::nio::ad::messages::LineInfo* _add = _internal_add_lineinfos();
  // @@protoc_insertion_point(field_add:nio.ad.messages.RoadModelOutputs.LineInfos)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::LineInfo >&
RoadModelOutputs::lineinfos() const {
  // @@protoc_insertion_point(field_list:nio.ad.messages.RoadModelOutputs.LineInfos)
  return lineinfos_;
}

// repeated .nio.ad.messages.ObjectInfo ObjectInfos = 3;
inline int RoadModelOutputs::_internal_objectinfos_size() const {
  return objectinfos_.size();
}
inline int RoadModelOutputs::objectinfos_size() const {
  return _internal_objectinfos_size();
}
inline void RoadModelOutputs::clear_objectinfos() {
  objectinfos_.Clear();
}
inline ::nio::ad::messages::ObjectInfo* RoadModelOutputs::mutable_objectinfos(int index) {
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.RoadModelOutputs.ObjectInfos)
  return objectinfos_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::ObjectInfo >*
RoadModelOutputs::mutable_objectinfos() {
  // @@protoc_insertion_point(field_mutable_list:nio.ad.messages.RoadModelOutputs.ObjectInfos)
  return &objectinfos_;
}
inline const ::nio::ad::messages::ObjectInfo& RoadModelOutputs::_internal_objectinfos(int index) const {
  return objectinfos_.Get(index);
}
inline const ::nio::ad::messages::ObjectInfo& RoadModelOutputs::objectinfos(int index) const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.RoadModelOutputs.ObjectInfos)
  return _internal_objectinfos(index);
}
inline ::nio::ad::messages::ObjectInfo* RoadModelOutputs::_internal_add_objectinfos() {
  return objectinfos_.Add();
}
inline ::nio::ad::messages::ObjectInfo* RoadModelOutputs::add_objectinfos() {
  ::nio::ad::messages::ObjectInfo* _add = _internal_add_objectinfos();
  // @@protoc_insertion_point(field_add:nio.ad.messages.RoadModelOutputs.ObjectInfos)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::nio::ad::messages::ObjectInfo >&
RoadModelOutputs::objectinfos() const {
  // @@protoc_insertion_point(field_list:nio.ad.messages.RoadModelOutputs.ObjectInfos)
  return objectinfos_;
}

// optional .nio.ad.messages.SensorTSHeader sensor_original_ts = 536870906;
inline bool RoadModelOutputs::_internal_has_sensor_original_ts() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || sensor_original_ts_ != nullptr);
  return value;
}
inline bool RoadModelOutputs::has_sensor_original_ts() const {
  return _internal_has_sensor_original_ts();
}
inline const ::nio::ad::messages::SensorTSHeader& RoadModelOutputs::_internal_sensor_original_ts() const {
  const ::nio::ad::messages::SensorTSHeader* p = sensor_original_ts_;
  return p != nullptr ? *p : reinterpret_cast<const ::nio::ad::messages::SensorTSHeader&>(
      ::nio::ad::messages::_SensorTSHeader_default_instance_);
}
inline const ::nio::ad::messages::SensorTSHeader& RoadModelOutputs::sensor_original_ts() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.RoadModelOutputs.sensor_original_ts)
  return _internal_sensor_original_ts();
}
inline void RoadModelOutputs::unsafe_arena_set_allocated_sensor_original_ts(
    ::nio::ad::messages::SensorTSHeader* sensor_original_ts) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(sensor_original_ts_);
  }
  sensor_original_ts_ = sensor_original_ts;
  if (sensor_original_ts) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:nio.ad.messages.RoadModelOutputs.sensor_original_ts)
}
inline ::nio::ad::messages::SensorTSHeader* RoadModelOutputs::release_sensor_original_ts() {
  _has_bits_[0] &= ~0x00000002u;
  ::nio::ad::messages::SensorTSHeader* temp = sensor_original_ts_;
  sensor_original_ts_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::nio::ad::messages::SensorTSHeader* RoadModelOutputs::unsafe_arena_release_sensor_original_ts() {
  // @@protoc_insertion_point(field_release:nio.ad.messages.RoadModelOutputs.sensor_original_ts)
  _has_bits_[0] &= ~0x00000002u;
  ::nio::ad::messages::SensorTSHeader* temp = sensor_original_ts_;
  sensor_original_ts_ = nullptr;
  return temp;
}
inline ::nio::ad::messages::SensorTSHeader* RoadModelOutputs::_internal_mutable_sensor_original_ts() {
  _has_bits_[0] |= 0x00000002u;
  if (sensor_original_ts_ == nullptr) {
    auto* p = CreateMaybeMessage<::nio::ad::messages::SensorTSHeader>(GetArenaForAllocation());
    sensor_original_ts_ = p;
  }
  return sensor_original_ts_;
}
inline ::nio::ad::messages::SensorTSHeader* RoadModelOutputs::mutable_sensor_original_ts() {
  ::nio::ad::messages::SensorTSHeader* _msg = _internal_mutable_sensor_original_ts();
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.RoadModelOutputs.sensor_original_ts)
  return _msg;
}
inline void RoadModelOutputs::set_allocated_sensor_original_ts(::nio::ad::messages::SensorTSHeader* sensor_original_ts) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(sensor_original_ts_);
  }
  if (sensor_original_ts) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(sensor_original_ts));
    if (message_arena != submessage_arena) {
      sensor_original_ts = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, sensor_original_ts, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  sensor_original_ts_ = sensor_original_ts;
  // @@protoc_insertion_point(field_set_allocated:nio.ad.messages.RoadModelOutputs.sensor_original_ts)
}

// optional uint64 publish_ptp_ts = 536870907;
inline bool RoadModelOutputs::_internal_has_publish_ptp_ts() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool RoadModelOutputs::has_publish_ptp_ts() const {
  return _internal_has_publish_ptp_ts();
}
inline void RoadModelOutputs::clear_publish_ptp_ts() {
  publish_ptp_ts_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 RoadModelOutputs::_internal_publish_ptp_ts() const {
  return publish_ptp_ts_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 RoadModelOutputs::publish_ptp_ts() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.RoadModelOutputs.publish_ptp_ts)
  return _internal_publish_ptp_ts();
}
inline void RoadModelOutputs::_internal_set_publish_ptp_ts(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000008u;
  publish_ptp_ts_ = value;
}
inline void RoadModelOutputs::set_publish_ptp_ts(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_publish_ptp_ts(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.RoadModelOutputs.publish_ptp_ts)
}

// optional string publisher_id = 536870909;
inline bool RoadModelOutputs::_internal_has_publisher_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RoadModelOutputs::has_publisher_id() const {
  return _internal_has_publisher_id();
}
inline void RoadModelOutputs::clear_publisher_id() {
  publisher_id_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RoadModelOutputs::publisher_id() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.RoadModelOutputs.publisher_id)
  return _internal_publisher_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RoadModelOutputs::set_publisher_id(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 publisher_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:nio.ad.messages.RoadModelOutputs.publisher_id)
}
inline std::string* RoadModelOutputs::mutable_publisher_id() {
  std::string* _s = _internal_mutable_publisher_id();
  // @@protoc_insertion_point(field_mutable:nio.ad.messages.RoadModelOutputs.publisher_id)
  return _s;
}
inline const std::string& RoadModelOutputs::_internal_publisher_id() const {
  return publisher_id_.Get();
}
inline void RoadModelOutputs::_internal_set_publisher_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  publisher_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* RoadModelOutputs::_internal_mutable_publisher_id() {
  _has_bits_[0] |= 0x00000001u;
  return publisher_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* RoadModelOutputs::release_publisher_id() {
  // @@protoc_insertion_point(field_release:nio.ad.messages.RoadModelOutputs.publisher_id)
  if (!_internal_has_publisher_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return publisher_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void RoadModelOutputs::set_allocated_publisher_id(std::string* publisher_id) {
  if (publisher_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  publisher_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), publisher_id,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:nio.ad.messages.RoadModelOutputs.publisher_id)
}

// optional uint64 counter = 536870910;
inline bool RoadModelOutputs::_internal_has_counter() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool RoadModelOutputs::has_counter() const {
  return _internal_has_counter();
}
inline void RoadModelOutputs::clear_counter() {
  counter_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 RoadModelOutputs::_internal_counter() const {
  return counter_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 RoadModelOutputs::counter() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.RoadModelOutputs.counter)
  return _internal_counter();
}
inline void RoadModelOutputs::_internal_set_counter(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000010u;
  counter_ = value;
}
inline void RoadModelOutputs::set_counter(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_counter(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.RoadModelOutputs.counter)
}

// optional uint64 publish_ts = 536870911;
inline bool RoadModelOutputs::_internal_has_publish_ts() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool RoadModelOutputs::has_publish_ts() const {
  return _internal_has_publish_ts();
}
inline void RoadModelOutputs::clear_publish_ts() {
  publish_ts_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 RoadModelOutputs::_internal_publish_ts() const {
  return publish_ts_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 RoadModelOutputs::publish_ts() const {
  // @@protoc_insertion_point(field_get:nio.ad.messages.RoadModelOutputs.publish_ts)
  return _internal_publish_ts();
}
inline void RoadModelOutputs::_internal_set_publish_ts(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000020u;
  publish_ts_ = value;
}
inline void RoadModelOutputs::set_publish_ts(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_publish_ts(value);
  // @@protoc_insertion_point(field_set:nio.ad.messages.RoadModelOutputs.publish_ts)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace ad
}  // namespace nio

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::nio::ad::messages::LineInfo_Role> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::nio::ad::messages::LineInfo_Role>() {
  return ::nio::ad::messages::LineInfo_Role_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_np_2fapps_2froad_5fmodel_5foutputs_2eproto
