# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/pnc/map_projection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/pnc/map_projection.proto',
  package='nio.ad.messages',
  syntax='proto2',
  serialized_options=b'\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1f\x63ommon/pnc/map_projection.proto\x12\x0fnio.ad.messages\"U\n\rMapProjection\x12\x15\n\rlongitude_deg\x18\x01 \x01(\x01\x12\x14\n\x0clatitude_deg\x18\x02 \x01(\x01\x12\x17\n\x0cscale_factor\x18\x03 \x01(\x01:\x01\x31\x42\x03\xf8\x01\x01'
)




_MAPPROJECTION = _descriptor.Descriptor(
  name='MapProjection',
  full_name='nio.ad.messages.MapProjection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='longitude_deg', full_name='nio.ad.messages.MapProjection.longitude_deg', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude_deg', full_name='nio.ad.messages.MapProjection.latitude_deg', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scale_factor', full_name='nio.ad.messages.MapProjection.scale_factor', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=137,
)

DESCRIPTOR.message_types_by_name['MapProjection'] = _MAPPROJECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MapProjection = _reflection.GeneratedProtocolMessageType('MapProjection', (_message.Message,), {
  'DESCRIPTOR' : _MAPPROJECTION,
  '__module__' : 'common.pnc.map_projection_pb2'
  # @@protoc_insertion_point(class_scope:nio.ad.messages.MapProjection)
  })
_sym_db.RegisterMessage(MapProjection)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
