syntax = "proto2";

option cc_enable_arenas = true;
package nio.ad.messages;
import "common/perf/sensor_ts_header.proto";

import "common/sensors/camera_data.proto";

message CameraCompressData {
    optional Header       header           = 1;
    optional uint64       sys_time_us      = 2; /*用于各传感器消息时间同步的时间戳*/
    optional int32        height           = 3; /*分辨率 row*/
    optional int32        width            = 4; /*分辨率 clomn*/
    optional int32        channel          = 5;
    optional bytes        data             = 6;
    optional ColorSpace   color_space      = 7;
    optional CompressType compress_type    = 8;
    optional int32        yuvStride        = 9; /*YUV row size (bytes)*/
    optional uint64       timestamp_ptp_ns = 10;

    optional uint64 timestamp = 536870905; // ptp timestamp, nanosecond，used for data bundle readin 
    optional SensorTSHeader sensor_original_ts = 536870906;   // sensor original ts
    optional uint64       publish_ptp_ts   = 536870907; // publish ptp timestamp, uint in nanosec
    optional string       publisher_id     = 536870909; // uuid of the publisher
    optional uint64       counter          = 536870910; // message counter
    optional uint64       publish_ts       = 536870911; // publish timestamp; unit : nanosecond
}
