syntax = "proto2";

option cc_enable_arenas = true;
package nio.ad.messages;
import "common/perf/sensor_ts_header.proto";

import "np/apps/ehy_obf_outputs.proto";
import "common/dms/dms_drive_assist.proto";
import "common/perception/multisource_object.proto";
import "common/vehicle_out/ads_drv_if.proto";
import "common/vehicle_in/str_sys.proto";
import "common/vehicle_in/veh_enum_type.proto";

message DssadElementV2 {
    message DssadBasic {
        enum EventCode {
            INVALID         = 0;
            ADS_ACTIVE      = 1;    // ADS激活
            ADS_QUIT        = 2;    // ADS退出
            INTERVENE_REQ   = 3;    // 发出介入请求
            RISK_STRATEGY   = 4;    // 启动最小风险策略
            ADS_SERIOUS_FAILURE = 5;   // ads严重失效
            VEH_SERIOUS_FAILURE = 6;   // vehicle严重失效
            CRASH_DETECTED = 7;     // 碰撞
            CRASH_RISK = 8;         // 有碰撞风险
            DRIVER_REQ = 9;         // 驾驶员操作ADS激活/退出  
    
            DANADSt_NOP_ACTIVE       = 0x10;    // NOP Active
            DANADSt_NAD_ENGAGED      = 0x11;    // PSP Active
            DANADSt_NAD_ACTIVE       = 0x12;    // NAD Active
            DANADSt_NAD_ENGAGED_BEAT = 0x13;    // Risk Mitigation Procedure
            DANADSt_QUIT             = 0x20;    // off state
        }
        enum ContEventCode {
            CRASH_DETECTED_CONT = 7;
            CRASH_RISK_CONT = 8;
            LOCK_CONT      = 9;
        }
    
        optional string vin                  = 1;             
        optional string hw_version           = 2;         // 实现自动驾驶数据记录系统功能的硬件版本号    
        optional string serial_num           = 3;         // 实现自动驾驶数据记录系统功能的序列号   
        optional string ads_software_version = 4; 
        optional string dssad_version        = 5;           
        optional EventCode event_code        = 6;  // 事件类型编码
    
        optional uint32 year    = 7;
        optional uint32 month   = 8;
        optional uint32 day     = 9;
        optional uint32 hour    = 10;
        optional uint32 minute  = 11;
        optional uint32 second  = 12;
    
        optional double longitude    = 13;  // 经度
        optional double latitude     = 14;  // 纬度
        optional uint32 odometer     = 15;  // 累计行驶里程
        optional ContEventCode  period_event_cont = 16;     
         
        optional uint32 event_cont_time_year          = 17;           
        optional uint32 event_cont_time_month         = 18;           
        optional uint32 event_cont_time_day           = 19;           
        optional uint32 event_cont_time_hour          = 20;          
        optional uint32 event_cont_time_minute        = 21;         
        optional uint32 event_cont_time_second        = 22;  
    
        optional bool integrity      = 23;  // 事件记录完整标志
    }
    
    message VehicleStatus {
        optional float speed              = 1;  // 车辆速度
        optional float lateral_accelerate = 2;  // 车辆横向加速度
        optional float axial_accelerate   = 3;  // 车辆纵向加速度
        optional float yaw_velocity       = 4;  // 车辆横摆角速度
        optional float roll_velocity      = 5;  // 车辆侧倾角速度
        optional double course_angle      = 6;  // 航向角

        // +自定义
        optional NpIfInfo.DANADStType_e   DANADSts  = 20;
        // 辅助驾驶状态 common/vehicle_out/ads.DrvrIF.NpDrvIF.DANADSts 
        optional bool  CrashDetd     = 21;
        // 碰撞检测状态 common/vehicle_in/vehicle_50ms.VehBody.CrashDetd
        optional bool ABSActv        = 22;
        // ABS common/vehicle_in/vehicle_10ms.BrkSys.BrkFunSt.ABSActv
        optional bool DTCActv       = 23;     
        // DTC  common/vehicle_in/vehicle_10ms.BrkSys.BrkFunSt.DTCActv
        optional bool VDCActv       = 24; 
        // VDC common/vehicle_in/vehicle_10ms.BrkSys.BrkFunSt.VDCActv
        optional bool TCSActv       = 25; 
        // TCS common/vehicle_in/vehicle_10ms.BrkSys.BrkFunSt.TCSActv
        message SBWStatus { // common/vehicle_in/vehicle_10ms.StrSys
            optional float  EpsTargetAngSAE = 1;
            optional uint32 EpsTargetAngSts = 2;
            optional uint32 StfAssiMod      = 3;
            optional uint32 EpsAssiMod      = 4;
            optional float  VehSpdStr       = 5;
            optional uint32 VehSpdStrSts    = 6;
            optional StrAgFailStsType_e StrAgFailSts = 7;
            optional float  StrWhlAgSAE         = 8;
            optional QfZeroAsVld_e PnnAgVld     = 9;
            optional float  PnnAgSAE            = 10;
            optional QfZeroAsVld_e TorsBarTqVld = 11;
            optional float  TorsBarTqSAE        = 12;
        }
        optional SBWStatus SBW_status = 26; // @linescope: NT3  // SBW
    }
    
    message ADASStatus {
        optional float lateral_accelerate    = 1;   // ADS请求的横向加速度
        optional float steering_wheel_angle  = 2;   // ADS请求的方向盘转向角
        optional float turning_curvature     = 3;   // ADS请求的转向曲率
        optional float front_wheel_angle     = 4;   // ADS请求的前轮转角
        optional float pinion_steering_angle = 5;   // ADS请求的转向小齿轮转向角
    
        optional float steering_wheel_torque     = 6;   // ADS请求的方向盘转向力矩
        optional float steering_wheel_angle_rate = 7;   // ADS请求的方向盘转向角速率
        optional uint32 gear_request             = 8;   // ADS请求的挡位
        optional uint32 speed_request            = 9;   // ADS请求的车速
        optional float acceleration_request      = 10;  // ADS请求的纵向加速度
    
        optional float accelerator_pedal_ration = 11;  // ADS请求的油门踏板开度比例
        optional float brake_pedal_ration       = 12;  // ADS请求的刹车踏板开度比例
        optional uint32 drive_torque_request    = 13;  // ADS请求的驱动转矩
        optional uint32 rotary_speed_request    = 14;  // ADS请求的驱动转速
        optional uint32 wheel_torque_request    = 15;  // ADS请求的轮端扭矩
    
        optional uint32 adaptive_lighting_status = 16;  // ADS请求的自适应照明系统状态
        optional uint32 low_beam_status          = 17;  // ADS请求的近灯光状态
        optional uint32 high_beam_status         = 18;  // ADS请求的远光灯状态
        optional uint32 hazard_light             = 19;  // ADS请求的危险警告信号状态
        optional uint32 turn_left_light          = 20;  // ADS请求的左转向信号灯状态
        optional uint32 turn_right_light         = 21;  // ADS请求的右转向灯状态
        optional uint32 wiper_request            = 22;  // ADS请求的车辆雨刮状态
    }
    
    message EnvironmentInfo {
        message relative_velocity {
            optional uint32 id = 1;
            optional float vx = 2;  // km/h
            optional float vy = 3;
            optional float vz = 4;
        }
        repeated FusObject fuse_objects  = 1; // not used
        repeated DynObject dynamic_obj   = 2; // MultisourceObjects->dynamic_obj
        repeated StaticObject static_obj = 3; // MultisourceObjects->static_obj
        repeated relative_velocity dynamic_prop = 4;
        repeated relative_velocity static_prop  = 5;
    }
    
    message DriverStatus {
        optional uint32 driver_capability   = 1;    // 驾驶员接管能力
        optional uint32 seat_belt_status    = 2;    // 驾驶员是否系安全带
        optional uint32 seat_occupy_status  = 3;    // 驾驶员是否在驾驶位置
        optional float accr_pedal_position  = 4;    // 加速踏板开度
        optional float brake_pedal_position = 5;    // 刹车踏板开度
        optional uint32 brake_pedal_status  = 6;    // 刹车踏板状态
        optional float steering_wheel_angle = 7;    // 转向盘角度（如有转向盘）
        optional float torsion_bar_torque   = 8;    // 转向扭矩
        optional DMSDriverInLoopSt driver_inloop_status = 9;
    }
    
    optional DssadBasic basic_info        = 1;
    optional VehicleStatus vehicle_status = 2;
    optional ADASStatus adas_status       = 3;
    optional EnvironmentInfo env_info     = 4;
    optional DriverStatus driver_status   = 5;

    repeated string       camera_files    = 6;   // camera file path

    optional uint64 timestamp = 536870905; // ptp timestamp, nanosecond，used for data bundle readin
    optional SensorTSHeader sensor_original_ts = 536870906;   // sensor original ts
    optional uint64 publish_ptp_ts   = 536870907;   //publish ptp timestamp, uint in nanosec
    optional string publisher_id     = 536870909;   // uuid of the publisher
    optional uint64 counter          = 536870910;   // message counter
    optional uint64 publish_ts       = 536870911;   // publish timestamp; unit : nanosecond
}

