syntax = "proto2";

option cc_enable_arenas = true;
package nio.ad.messages;

//module
enum SsmControlModule {
    DEFAULT_SSM_RESERVED        = 0;
    SCAP_MODE                   = 1;    //Swarm Compute Acceleration Provider mode
}

enum SsmControlCmd {
    INVALID_CMD                 = 0;    
    NORMAL_ENTER                = 1;    //SSM->MODULE
    NORMAL_EXIT                 = 2;    //SSM->MODULE
    HB_TIMEOUT_EXIT             = 3;    //SSM->MODULE
    CLIENT_EXIT                 = 4;    //MODULE->SSM
}

enum SsmControlResult {
    DEFAULT_RESULT_RESERVED     = 0;
    EXECUTING                   = 1;
    SUCCESS                     = 2;
    FAIL_FOR_CMD_GENERAL_ERROR  = 3;
}


enum SsmMachineState {
    SSM_NONE                    = 0;
    SSM_PASSIVE                 = 1;
    SSM_STANDBY                 = 2;
    SSM_ACTIVE                  = 3;
    SSM_FAILURE                 = 4;
}
