syntax = "proto2";

option cc_enable_arenas = true;

package nio.ad.messages;
import "common/perf/sensor_ts_header.proto";
import "common/dms/dms_result.proto";
import "common/dms/dms_can.proto";
import "common/dms/dms_eas.proto";
import "common/dms/dms_drive_assist.proto";
import "common/dms/adms.proto";
import "common/dms/adms_risk_score.proto";
import "common/dms/dms_feature.proto";
import "common/dms/dms_base.proto";
import "common/dms/dms_dlb_enum.proto";

message DGB_DMS_DrowsinessResult {
  optional DMS_DrowsinessResult.DMS_DrowsinessLevel level = 1;
  optional bool is_valid = 2;
  optional DMS_INVALID_TYPE invalid_type = 4;
}

message DGB_DMS_DistractionResult {
  optional DMS_DistractionResult.DMS_DistractionLevel level = 1;
  optional bool is_valid = 3;
  optional DMS_INVALID_TYPE invalid_type = 6;
}

message DGB_DMS_EyeStatusResult {
  optional DMS_EyeStatusResult.DMS_EyeStatus left_eye = 1;
  optional DMSVector left_eye_gaze_vector = 4;
  optional DMSPosition3f left_eye_position = 5;
  optional DMS_EyeStatusResult.DMS_EyeStatus right_eye = 6;
  optional DMSVector right_eye_gaze_vector = 9;
  optional DMSPosition3f right_eye_position = 10;
  optional DMS_INVALID_TYPE left_eye_invalid_type = 11;
  optional DMS_INVALID_TYPE right_eye_invalid_type = 12;
}

message DGB_DMS_GazeAoiResult {
  optional DMS_GazeAoiResult.DMS_GazeAoi gaze_aoi = 1;
  optional bool is_valid = 2;
  optional DMS_INVALID_TYPE invalid_type = 3;
}

message DGB_DMS_HeadResult {
  optional DMSPosition3f head_position = 1;
  optional DMSPose head_pose = 2;
}

message DGB_DMS_PhoneActionResult {
  optional DMS_PhoneActionResult.DMS_PhoneAction phone_action = 1;
  optional float confidence = 2;
}

message DGB_DMS_FaceResult {
  optional bool is_valid = 1;
  repeated DMSPoint2f landmarks = 2;
  optional uint32 landmark_number = 3;
  optional int32 top_left_x = 4;     // top-left x
  optional int32 bottom_right_x = 5; // bottom-right x
  optional int32 top_left_y = 6;     // top-left y
  optional int32 bottom_right_y = 7; // bottom-right y
  optional DMS_INVALID_TYPE invalid_type = 8;
}

message DGB_DMS_ImageQuality {
  optional float image_variance = 1; // variance of image pixels
  optional float overexpo_ratio = 2; // over exposure pixels percantage
}

// for NT3
message DGB_DMS_AeRoiResult { optional bool is_valid = 1; }

message DGB_DMS_Result {
  optional DGB_DMS_DrowsinessResult drowsiness_result = 1;
  optional DGB_DMS_DistractionResult distraction_result = 2;
  optional DGB_DMS_EyeStatusResult eye_status_result = 3; // 0:left 1:right
  optional DGB_DMS_GazeAoiResult gaze_aoi_result = 4;
  optional DGB_DMS_HeadResult head_result = 5;
  optional DGB_DMS_PhoneActionResult phone_result = 6;
  optional DGB_DMS_FaceResult face_result = 13;
  optional DMS_Status system_status = 15;
  optional DGB_DMS_DistractionResult moment_distraction_result = 17;
  optional DGB_DMS_GazeAoiResult cur_gaze_aoi_result = 18;
  optional DMS_DistZone dist_zone = 19;
  optional DGB_DMS_DistractionResult distraction_long_result = 20;
  optional DGB_DMS_ImageQuality img_quality = 21;

  // @begin segscope: NT3
  optional DGB_DMS_GazeAoiResult dms_ae_roi_result = 23;
  optional DMS_Status sdk_status = 24;
  optional bool sdk_reset_by_dist = 25;
  optional bool sdk_reset_by_drow = 26;
  optional uint64 dist_alert_suppression = 27;
  optional uint64 drow_alert_suppression = 28;
  optional DGB_DMS_DrowsinessResult post_da_drows_res = 29;
  optional DGB_DMS_DrowsinessResult post_md_drows_res = 30;
  // @end segscope: NT3

  optional DGB_DMS_DrowsinessResult fast_drowsiness_result = 31;

  optional uint64 dms_self_check = 102;
}

message DGB_DMS_CAN {
  optional DrowsinessLevel_ADC03 drowsiness_lvl = 1;
  optional DrowsinessSts_ADC03 drowsiness_sts = 2;
  optional DistractionLevel_ADC03 distraction_lvl = 3;
  optional DistractionSts_ADC03 distraction_sts = 4;
  optional DistractionLevel_short_ADC03 distraction_lvl_short = 5;
  optional DistractionSts_short_ADC03 distraction_sts_short = 6;
  optional SmartDrvYrsDetSts smart_drv_yrs_det_sts = 7;
  optional DMStelltaleLevel dms_telltale_level = 8;
}

message DGB_DMS_EAS {
  optional bool Drowsiness_EAS_Trigger = 1;
  optional bool Distraction_EAS_Trigger = 2;
}

message DGB_DMS_DA {
  optional DMSDistractionSts_DA distraction_sts = 1;
  optional DMSDistractionLevel_DA distraction_level = 2;
  optional DMSDrowsinessSts_DA drowsiness_sts = 3;
  optional DMSDrowsinessLevel_DA drowsiness_level = 4;
  optional DMSDistractionSts_DA_Short distraction_sts_short = 5;
  optional DMSDistractionLevel_DA_Short distraction_level_short = 6;
  optional DMSSensitivityChgReq_DA ldw_sensitivity_req = 7;
  optional DMSSensitivityChgReq_DA fcw_sensitivity_req = 8;
  optional DMSSensitivityChgReq_DA lka_sensitivity_req = 9;
  optional DMSSensitivityChgReq_DA elk_sensitivity_req = 10;
  optional DMSDistractionSts_DA_Moment distraction_sts_moment = 11;
  optional DMSDistractionLevel_DA_Moment distraction_level_moment = 12;
  optional DMSDriverInLoopSt driver_in_loop_status = 13;
  optional uint64 dms_status = 99;
}

message DGB_ADMS {
  reserved 25, 26;
  optional DMSSteeringTorqueReq steering_torque_req = 2;
  optional float driver_in_loop_conf = 13; // 1 as inloop, 0 as not inloop, normally output in [0,1]
  optional uint32 ADMS_WTIs = 16;
  optional uint32 driver_attn_alert =
      18; // diifer by target class and relative position
  repeated ADMSESDObject adms_esd_objects = 21;
  optional DMSRiskSceneWarning distraction_warning = 23;
  optional DMSRiskSceneWarning phone_call_warning = 24; // @linescope: NT3
  message ADMSESDObject {
    optional uint32 esd_adms_obj_id = 1; // id in multisrc object
    enum ADMSESDObjFunc {
      ADMSESDObjFunc_Normal = 0; // no display require
      ADMSESDObjFunc_Red = 1;    // highlight object in red
    }
    optional ADMSESDObjFunc esd_adms_obj_func = 2;
    enum ADMSESDObjType {
      ADMSESDObjType_None = 0;
      ADMSESDObjType_DynamicObj = 1;
      ADMSESDObjType_StaticObj = 2;
    }
    optional ADMSESDObjType esd_adms_obj_type = 3;
    optional uint32 related_ADMS_WTI = 4; // internal msg, no need by ESD module
  }
}

message DGB_ADMSRiskScore {

  optional uint64 high_risk_scene = 6;
  optional uint32 risk_scene_ttc = 7;
  optional uint64 adms_subfunction_mask = 8;
  optional uint64 high_risk_scene_mask = 9;
  optional uint64 risk_scene_warn_mask = 10;
  optional uint64 driver_attn_status = 11;
  optional uint64 attn_alert_obj_id = 12;
  repeated DriverAttnObj driver_attn_obj = 16;
  optional DriverGaze driver_gaze = 18;
  optional uint64 adms_self_check = 98;
  optional uint64 adms_status = 99;

  message DriverAttnObj {
    optional uint32 obj_id = 1;
    optional uint32 obj_sts = 2;
  }

  message DriverGaze {
    optional float headpos_x = 1; // [m] in veh coord
    optional float headpos_y = 2;
    optional float headpos_z = 3;
    optional float yaw = 4;               // rad in veh coord
    optional float pitch = 5;             // rad in veh coord
    optional float yaw_range = 6;         // rad, single side, focus range
    optional float yaw_edge_range = 7;    // rad, single side
    optional float pitch_range = 8;       // rad
    optional float pitch_edge_range = 9;  // rad
    optional float headpose_yaw_min = 10; // yaw min thrd for look frnt
    optional float headpose_yaw_max = 11; // yaw max thrd for look frnt
  }
}
message DGB_DMS_DLB {
  optional DMS_DrowsinessLevel_DLB drowsiness_lvl = 1;
  optional DMS_DistractionLevel_DLB distraction_lvl = 2;
}

message DGB_DMS_DA_DLB {
  optional DMS_DrowsinessLevel_DA_DLB drowsiness_lvl = 1;
  optional DMS_DistractionLevel_DA_DLB distraction_lvl = 2;
}
message ADMSDgbInfo {
  optional DGB_DMS_Result dms_result = 1;
  optional DGB_DMS_CAN dms_can = 2;
  optional DGB_DMS_EAS dms_eas = 3;
  optional DGB_DMS_DA dms_drive_assist = 4;
  optional DGB_ADMS adms = 5;
  optional DGB_ADMSRiskScore adms_risk_score = 6;
  optional DGB_DMS_DLB dgb_dms_dlb = 7;
  optional DGB_DMS_DA_DLB dgb_dms_da_dlb = 8;

  optional uint64 timestamp = 536870905; // ptp timestamp, nanosecond，used for data bundle readin 
  optional SensorTSHeader sensor_original_ts = 536870906; // sensor original ts
  optional uint64 publish_ptp_ts =
      536870907; // publish ptp timestamp unit : nanosecond
  optional string publisher_id = 536870909; // uuid of the publisher
  optional uint64 counter = 536870910;      // message counter
  optional uint64 publish_ts =
      536870911; // publish timestamp; unit : nanosecond
}